### ISSUE TITLE
unknown object in stream: 15 (PgpKey.parseAndNormalizeKeyRings)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1153]
### Where? 
Settings -> Keys -> Import private key

### Need to look at

```
Caused by: java.io.IOException: unknown object in stream: 15
        at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source:58)
        at com.flowcrypt.email.example.file.PgpKey.parseAndNormalizeKeyRings(PgpKey.kt:181)
```
### Full stack
```
[SUMMARY]
java.io.IOException: unknown object in stream: 15
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.jetpack.viewmodel.PrivateKeysViewModel$parseKeys$1.invokeSuspend(PrivateKeysViewModel.kt:256)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:342)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.flowcrypt.email.jetpack.viewmodel.PrivateKeysViewModel.parseKeys(PrivateKeysViewModel.kt:221)
        at com.flowcrypt.email.ui.activity.base.BaseImportKeyActivity.onClick(BaseImportKeyActivity.kt:191)
        at com.flowcrypt.email.ui.activity.ImportPrivateKeyActivity.onClick(ImportPrivateKeyActivity.kt:105)
        at android.view.View.performClick(View.java:8178)
        at android.widget.TextView.performClick(TextView.java:16104)
        at android.view.View.performClickInternal(View.java:8147)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30233)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8429)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.io.IOException: unknown object in stream: 15
        at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source:58)
        at com.flowcrypt.email.example.file.PgpKey.parseAndNormalizeKeyRings(PgpKey.kt:181)
        at com.flowcrypt.email.example.file.PgpKey.parseKeys(PgpKey.kt:101)
        at com.flowcrypt.email.example.file.PgpKey.parseKeysC(PgpKey.kt:128)
        at com.flowcrypt.email.jetpack.viewmodel.PrivateKeysViewModel$parseKeys$1.invokeSuspend(PrivateKeysViewModel.kt:253)
        ... 25 more
java.io.IOException: unknown object in stream: 15
        at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source:58)
        at com.flowcrypt.email.example.file.PgpKey.parseAndNormalizeKeyRings(PgpKey.kt:181)
        at com.flowcrypt.email.example.file.PgpKey.parseKeys(PgpKey.kt:101)
        at com.flowcrypt.email.example.file.PgpKey.parseKeysC(PgpKey.kt:128)
        at com.flowcrypt.email.jetpack.viewmodel.PrivateKeysViewModel$parseKeys$1.invokeSuspend(PrivateKeysViewModel.kt:253)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:342)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
        at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
        at com.flowcrypt.email.jetpack.viewmodel.PrivateKeysViewModel.parseKeys(PrivateKeysViewModel.kt:221)
        at com.flowcrypt.email.ui.activity.base.BaseImportKeyActivity.onClick(BaseImportKeyActivity.kt:191)
        at com.flowcrypt.email.ui.activity.ImportPrivateKeyActivity.onClick(ImportPrivateKeyActivity.kt:105)
        at android.view.View.performClick(View.java:8178)
        at android.widget.TextView.performClick(TextView.java:16104)
        at android.view.View.performClickInternal(View.java:8147)
        at android.view.View.access$3700(View.java:888)
        at android.view.View$PerformClick.run(View.java:30233)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8429)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by IvanPizhenko** [comment]
@DenBond7 Please attach here a private key file which causes this.

**Comment by IvanPizhenko** [comment]
Generally - BouncyCastle doesn't support everything that openpgp.js supports, moreover, openpgp.js may just silently ignore things that it doesn't understand, meaning that it still create packet, but with some "generic" content. So we may need to extend BouncyCastle parser to handle something that it doesn't understand or at least let it ignore such things.

**Comment by DenBond7** [comment]
> @DenBond7 Please attach here a private key file which causes this.

unfortunately, I can't do that. It's a report from the ACRA bugs. Some user has encountered this issue. There is no more additional info.

**Comment by IvanPizhenko** [comment]
ok, I will try to find out what stands for the packet type 15 and will think how we can handle it.

**Comment by DenBond7** [comment]
@IvanPizhenko I will be adding `ACRA` label for such an issue. So you will always know that there is no additional info.

**Comment by IvanPizhenko** [comment]
@DenBond7 yes, it would be nice to have such label, thank you!

**Comment by IvanPizhenko** [comment]
According to [this page](https://www.iana.org/assignments/pgp-parameters/pgp-parameters.xhtml)

15-16 | Unknown
-- | --

**Comment by tomholub** [comment]
Both are valid approaches (but the second one is more work considering that it's an unknown / ignorable packet). I'd do the following: OpenPGP.js test cases may contain a key with unknown type. If not, then SequoiaPGP may have one. There has to be a key somewhere that we could test it. I'd try finding that key and testing with it.

@rrrooommmaaa - let us know if you have any other recommendation

**Comment by DenBond7** [comment]
@IvanPizhenko 
>Another option, since this is really not valid packet type, at least according to present standard, import such key should be just failed and customer to see an error message. If then customer would himself report this and provide sample key, we can work out a better solution.

When this issue happens a user sees a hint with the message `unknown object in stream: 15`. So he can right us for help. As I understand that is not a regular case. So only some users can be affected.

**Comment by rrrooommmaaa** [comment]
> @rrrooommmaaa - let us know if you have any other recommendation

So is there really a packet 15 in the stream? This guy https://github.com/bcgit/bc-java/issues/740 complained that this strange error happened to him when the code tries to skip some data. His comment was:
```
/*
  * The PGPObjectFactory expects us to read all data bytes immediately,
  * otherwise expect an error such as "unknown object in stream".
  */
final byte[] cleartext;
if (PGPLiteralData.class.isInstance(obj)) {
    InputStream plain = PGPLiteralData.class.cast(obj).getDataStream();
    cleartext = // ...consume "plain" here...
    obj = df.nextObject();
} else {
    throw new PGPException(
            "Unexpected GPG encrypted data object type: "
                    + obj.getClass().getSimpleName());
}
```

It may be applicable to our situation to
```
      while (true) {
        val obj = objectFactory.nextObject() ?: break
        if (obj is PGPKeyRing) {
          keys.add(obj)
        } else {
            ... consume properly?
        }
      }
 ```

**Comment by IvanPizhenko** [comment]
good catch. will look into that.

**Comment by DenBond7** [comment]
@IvanPizhenko 
> provide sample key, we can work out a better solution.

I think this issue relates to importing binary keys. I have a similar error when I'm trying to import one test binary key.
Please look at the example key.
[privkey.txt](https://github.com/FlowCrypt/flowcrypt-android/files/6294417/privkey.txt)

```
java.io.IOException: unknown object in stream: 47
1618208966.686 14405-14405/com.flowcrypt.email.debug W/System.err:     at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source:58)
```

**Comment by DenBond7** [comment]
@IvanPizhenko Please pause your work on this issue. It seems I found a bug on the Android side. After migration to use Kotlin instead of Node.js for the key parsing I've left almost the whole code as-is. There I was opening an input stream, converting it to a string, and sending it to Node.js. But this converting causes a problem in the current realization. After dropping the converting and use an input stream as an original source I can parse binary keys. I think #309 should resolve this issue.

**Comment by IvanPizhenko** [comment]
reassigning to you then
