### ISSUE TITLE
StringIndexOutOfBoundsException: length=49; index=50(MsgBlockParser.detectBlockNext)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1154]
### Where? 
CreateMessageFragment -> fetch and update info about contacts

### Need to look at

```
Caused by: java.lang.StringIndexOutOfBoundsException: length=49; index=50
        at java.lang.String.substring(String.java:1971)
        at com.flowcrypt.email.example.file.MsgBlockParser.detectBlockNext(MsgBlockParser.kt:37)
```
### Full stack

```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
java.lang.StringIndexOutOfBoundsException: length=49; index=50


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.jetpack.viewmodel.ContactsViewModel$fetchAndUpdateInfoAboutContacts$1.invokeSuspend(ContactsViewModel.kt:171)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6558)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
Caused by: java.lang.StringIndexOutOfBoundsException: length=49; index=50
        at java.lang.String.substring(String.java:1971)
        at com.flowcrypt.email.example.file.MsgBlockParser.detectBlockNext(MsgBlockParser.kt:37)
        at com.flowcrypt.email.example.file.MsgBlockParser.detectBlocks(MsgBlockParser.kt:24)
        at com.flowcrypt.email.example.file.PgpMsg.detectBlockType(PgpMsg.kt:45)
        at com.flowcrypt.email.example.file.PgpKey.parseKeys(PgpKey.kt:87)
        at com.flowcrypt.email.example.file.PgpKey.parseKeysC(PgpKey.kt:128)
        at com.flowcrypt.email.example.file.PgpKey.parseKeysC$default(PgpKey.kt:127)
        at com.flowcrypt.email.jetpack.viewmodel.ContactsViewModel$getPgpContactInfoFromServer$2.invokeSuspend(ContactsViewModel.kt:305)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Builders.common.kt:214)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
java.lang.StringIndexOutOfBoundsException: length=49; index=50
        at java.lang.String.substring(String.java:1971)
        at com.flowcrypt.email.example.file.MsgBlockParser.detectBlockNext(MsgBlockParser.kt:37)
        at com.flowcrypt.email.example.file.MsgBlockParser.detectBlocks(MsgBlockParser.kt:24)
        at com.flowcrypt.email.example.file.PgpMsg.detectBlockType(PgpMsg.kt:45)
        at com.flowcrypt.email.example.file.PgpKey.parseKeys(PgpKey.kt:87)
        at com.flowcrypt.email.example.file.PgpKey.parseKeysC(PgpKey.kt:128)
        at com.flowcrypt.email.example.file.PgpKey.parseKeysC$default(PgpKey.kt:127)
        at com.flowcrypt.email.jetpack.viewmodel.ContactsViewModel$getPgpContactInfoFromServer$2.invokeSuspend(ContactsViewModel.kt:305)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Builders.common.kt:214)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by IvanPizhenko** [comment]
@DenBond7 can you please provide any sample data which causes this?

**Comment by DenBond7** [comment]
@IvanPizhenko For future issues. As I've described [here](https://github.com/FlowCrypt/flowcrypt-android/issues/1153) there is no more additional info. That's only bug reports from the [ACRA](https://github.com/ACRA/acra).

Unfortunately, we can just analyze what we receive (`stacktrace` ). :(

**Comment by IvanPizhenko** [comment]
ok, I will try, maybe we miss some check for string length and we just can add it.
