### ISSUE TITLE
NPE in PgpKey.encryptKey()

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1157]
### Where? 
The key encryption

### Need to look at

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.bouncycastle.bcpg.BCPGKey org.bouncycastle.openpgp.PGPPrivateKey.getPrivateKeyDataPacket()' on a null object reference
        at org.bouncycastle.openpgp.PGPSecretKey.buildSecretKeyPacket(Unknown Source:6)
        at org.bouncycastle.openpgp.PGPSecretKey.<init>(Unknown Source:5)
```
### Full stack
```
[SUMMARY]
java.lang.NullPointerException: Attempt to invoke virtual method 'org.bouncycastle.bcpg.BCPGKey org.bouncycastle.openpgp.PGPPrivateKey.getPrivateKeyDataPacket()' on a null object reference
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.kt:60)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.bouncycastle.bcpg.BCPGKey org.bouncycastle.openpgp.PGPPrivateKey.getPrivateKeyDataPacket()' on a null object reference
        at org.bouncycastle.openpgp.PGPSecretKey.buildSecretKeyPacket(Unknown Source:6)
        at org.bouncycastle.openpgp.PGPSecretKey.<init>(Unknown Source:5)
        at org.example.file.modification.secretkeyring.SecretKeyRingEditor.lockPrivateKey(SecretKeyRingEditor.java:703)
        at org.example.file.modification.secretkeyring.SecretKeyRingEditor.changePassphrase(SecretKeyRingEditor.java:675)
        at org.example.file.modification.secretkeyring.SecretKeyRingEditor.access$300(SecretKeyRingEditor.java:71)
        at org.example.file.modification.secretkeyring.SecretKeyRingEditor$WithPassphraseImpl.toNewPassphrase(SecretKeyRingEditor.java:647)
        at com.flowcrypt.email.example.file.PgpKey.encryptKey(PgpKey.kt:38)
        at com.flowcrypt.email.example.file.PgpKey.encryptKey(PgpKey.kt:31)
        at com.flowcrypt.email.service.actionqueue.actions.EncryptPrivateKeysIfNeededAction.run(EncryptPrivateKeysIfNeededAction.kt:71)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.kt:54)
        ... 7 more
java.lang.NullPointerException: Attempt to invoke virtual method 'org.bouncycastle.bcpg.BCPGKey org.bouncycastle.openpgp.PGPPrivateKey.getPrivateKeyDataPacket()' on a null object reference
        at org.bouncycastle.openpgp.PGPSecretKey.buildSecretKeyPacket(Unknown Source:6)
        at org.bouncycastle.openpgp.PGPSecretKey.<init>(Unknown Source:5)
        at org.example.file.modification.secretkeyring.SecretKeyRingEditor.lockPrivateKey(SecretKeyRingEditor.java:703)
        at org.example.file.modification.secretkeyring.SecretKeyRingEditor.changePassphrase(SecretKeyRingEditor.java:675)
        at org.example.file.modification.secretkeyring.SecretKeyRingEditor.access$300(SecretKeyRingEditor.java:71)
        at org.example.file.modification.secretkeyring.SecretKeyRingEditor$WithPassphraseImpl.toNewPassphrase(SecretKeyRingEditor.java:647)
        at com.flowcrypt.email.example.file.PgpKey.encryptKey(PgpKey.kt:38)
        at com.flowcrypt.email.example.file.PgpKey.encryptKey(PgpKey.kt:31)
        at com.flowcrypt.email.service.actionqueue.actions.EncryptPrivateKeysIfNeededAction.run(EncryptPrivateKeysIfNeededAction.kt:71)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.kt:54)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by IvanPizhenko** [comment]
I've looked at stacktrace and I can see a strange thing - pgpainless package name replaced with "org.example.file.". It doesn't seem to be correct.

**Comment by DenBond7** [comment]
@IvanPizhenko We are trying to remove file names from the ACRA reports. You can find more details here #678 #651
