### ISSUE TITLE
crash - missing drawable icon

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#117]
```
[STACK_TRACE]
java.lang.NoClassDefFoundError: android/graphics/drawable/Icon
        at java.lang.Class.getDeclaredMethods(Native Method)
        at java.lang.Class.getDeclaredMethods(Class.java:656)
        at android.view.ViewDebug.getExportedPropertyMethods(ViewDebug.java:960)
        at android.view.ViewDebug.exportMethods(ViewDebug.java:1047)
        at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:997)
        at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:983)
        at android.view.ViewDebug.dumpView(ViewDebug.java:900)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:870)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dump(ViewDebug.java:793)
        at android.view.ViewDebug.dispatchCommand(ViewDebug.java:416)
        at android.view.ViewRootImpl$W.executeCommand(ViewRootImpl.java:6258)
        at android.view.IWindow$Stub.onTransact(IWindow.java:65)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.Icon" on path: DexPathList[[zip file "/data/app/com.flowcrypt.email-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flowcrypt.email-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        ... 19 more
java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.Icon" on path: DexPathList[[zip file "/data/app/com.flowcrypt.email-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flowcrypt.email-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at java.lang.Class.getDeclaredMethods(Native Method)
        at java.lang.Class.getDeclaredMethods(Class.java:656)
        at android.view.ViewDebug.getExportedPropertyMethods(ViewDebug.java:960)
        at android.view.ViewDebug.exportMethods(ViewDebug.java:1047)
        at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:997)
        at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:983)
        at android.view.ViewDebug.dumpView(ViewDebug.java:900)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:870)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dump(ViewDebug.java:793)
        at android.view.ViewDebug.dispatchCommand(ViewDebug.java:416)
        at android.view.ViewRootImpl$W.executeCommand(ViewRootImpl.java:6258)
        at android.view.IWindow$Stub.onTransact(IWindow.java:65)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)



[LOGCAT]
10-10 16:10:02.350 D/dalvikvm( 4431): VFY: replacing opcode 0x6f at 0x0008
10-10 16:10:02.350 I/dalvikvm( 4431): Could not find method android.widget.TextView.setAutoSizeTextTypeUniformWithConfiguration, referenced from method android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeUniformWithConfiguration
10-10 16:10:02.350 W/dalvikvm( 4431): VFY: unable to resolve virtual method 12968: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithConfiguration (IIII)V
10-10 16:10:02.350 D/dalvikvm( 4431): VFY: replacing opcode 0x6f at 0x0006
10-10 16:10:02.350 I/dalvikvm( 4431): Could not find method android.widget.TextView.setAutoSizeTextTypeUniformWithPresetSizes, referenced from method android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeUniformWithPresetSizes
10-10 16:10:02.350 W/dalvikvm( 4431): VFY: unable to resolve virtual method 12969: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithPresetSizes ([II)V
10-10 16:10:02.350 D/dalvikvm( 4431): VFY: replacing opcode 0x6f at 0x0006
10-10 16:10:02.350 I/dalvikvm( 4431): Could not find method android.widget.TextView.setAutoSizeTextTypeWithDefaults, referenced from method android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeWithDefaults
10-10 16:10:02.350 W/dalvikvm( 4431): VFY: unable to resolve virtual method 12970: Landroid/widget/TextView;.setAutoSizeTextTypeWithDefaults (I)V
10-10 16:10:02.350 D/dalvikvm( 4431): VFY: replacing opcode 0x6f at 0x0006
10-10 16:10:02.910 I/dalvikvm( 4431): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zzo.zzy
10-10 16:10:02.920 W/dalvikvm( 4431): VFY: unable to resolve virtual method 576: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
10-10 16:10:02.920 D/dalvikvm( 4431): VFY: replacing opcode 0x6e at 0x0012
10-10 16:10:03.220 D/dalvikvm( 4431): GC_CONCURRENT freed 231K, 10% free 2896K/3208K, paused 61ms+16ms, total 290ms
10-10 16:10:05.990 W/GooglePlayServicesUtil( 4431): Google Play services out of date.  Requires 11020000 but found 8489030
10-10 16:10:06.030 I/dalvikvm( 4431): Could not find method android.content.res.Resources.getColor, referenced from method com.flowcrypt.email.util.UIUtil.getColor
10-10 16:10:06.030 W/dalvikvm( 4431): VFY: unable to resolve virtual method 612: Landroid/content/res/Resources;.getColor (ILandroid/content/res/Resources$Theme;)I
10-10 16:10:06.030 D/dalvikvm( 4431): VFY: replacing opcode 0x6e at 0x000e
10-10 16:10:06.040 I/dalvikvm( 4431): Could not find method android.text.Html.fromHtml, referenced from method com.flowcrypt.email.util.UIUtil.setHtmlTextToTextView
10-10 16:10:06.040 W/dalvikvm( 4431): VFY: unable to resolve static method 11587: Landroid/text/Html;.fromHtml (Ljava/lang/String;I)Landroid/text/Spanned;
10-10 16:10:06.040 D/dalvikvm( 4431): VFY: replacing opcode 0x71 at 0x000f
10-10 16:10:06.210 I/Choreographer( 4431): Skipped 34 frames!  The application may be doing too much work on its main thread.
10-10 16:10:06.950 I/Choreographer( 4431): Skipped 168 frames!  The application may be doing too much work on its main thread.
10-10 16:10:07.090 D/gralloc_goldfish( 4431): Emulator without GPU emulation detected.
10-10 16:10:07.590 D/dalvikvm( 4431): GC_CONCURRENT freed 200K, 9% free 3091K/3376K, paused 9ms+10ms, total 133ms
10-10 16:10:07.890 I/Choreographer( 4431): Skipped 36 frames!  The application may be doing too much work on its main thread.
10-10 16:10:08.490 I/Choreographer( 4431): Skipped 402 frames!  The application may be doing too much work on its main thread.
10-10 16:10:09.450 I/Choreographer( 4431): Skipped 36 frames!  The application may be doing too much work on its main thread.
10-10 16:10:50.230 D/dalvikvm( 4431): GC_CONCURRENT freed 254K, 10% free 3261K/3600K, paused 7ms+18ms, total 159ms
10-10 16:10:51.570 D/dalvikvm( 4431): GC_CONCURRENT freed 350K, 12% free 3315K/3748K, paused 9ms+8ms, total 138ms
10-10 16:10:52.770 D/dalvikvm( 4431): GC_CONCURRENT freed 374K, 12% free 3361K/3804K, paused 9ms+15ms, total 233ms
10-10 16:10:53.730 D/dalvikvm( 4431): GC_CONCURRENT freed 425K, 14% free 3394K/3904K, paused 18ms+14ms, total 143ms
10-10 16:10:54.350 D/dalvikvm( 4431): GC_CONCURRENT freed 372K, 12% free 3449K/3904K, paused 17ms+8ms, total 107ms
10-10 16:10:54.970 D/dalvikvm( 4431): GC_CONCURRENT freed 426K, 13% free 3448K/3956K, paused 6ms+14ms, total 118ms
10-10 16:10:55.600 D/dalvikvm( 4431): GC_CONCURRENT freed 416K, 13% free 3458K/3956K, paused 13ms+27ms, total 123ms
10-10 16:10:56.460 D/dalvikvm( 4431): GC_CONCURRENT freed 529K, 16% free 3386K/3992K, paused 7ms+17ms, total 175ms
10-10 16:10:57.080 D/dalvikvm( 4431): GC_CONCURRENT freed 433K, 16% free 3372K/3992K, paused 6ms+14ms, total 120ms
10-10 16:10:57.730 D/dalvikvm( 4431): GC_CONCURRENT freed 403K, 16% free 3386K/3992K, paused 16ms+12ms, total 106ms
10-10 16:10:58.410 D/dalvikvm( 4431): GC_CONCURRENT freed 427K, 16% free 3376K/3992K, paused 7ms+17ms, total 89ms
10-10 16:10:59.310 D/dalvikvm( 4431): GC_CONCURRENT freed 437K, 16% free 3355K/3992K, paused 4ms+8ms, total 123ms
10-10 16:11:01.780 D/dalvikvm( 4431): GC_CONCURRENT freed 414K, 16% free 3362K/3992K, paused 13ms+22ms, total 203ms
10-10 16:11:03.670 D/dalvikvm( 4431): GC_CONCURRENT freed 428K, 17% free 3334K/3992K, paused 16ms+13ms, total 185ms
10-10 16:11:04.960 D/dalvikvm( 4431): GC_CONCURRENT freed 377K, 16% free 3366K/3992K, paused 15ms+22ms, total 201ms
10-10 16:11:06.180 W/dalvikvm( 4431): Unable to match class for part: 'Landroid/graphics/drawable/Icon;)V'
10-10 16:11:06.320 E/JavaBinder( 4431): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
10-10 16:11:06.320 E/JavaBinder( 4431): java.lang.NoClassDefFoundError: android/graphics/drawable/Icon
10-10 16:11:06.320 E/JavaBinder( 4431):         at java.lang.Class.getDeclaredMethods(Native Method)
10-10 16:11:06.320 E/JavaBinder( 4431):         at java.lang.Class.getDeclaredMethods(Class.java:656)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.getExportedPropertyMethods(ViewDebug.java:960)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.exportMethods(ViewDebug.java:1047)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:997)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:983)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dumpView(ViewDebug.java:900)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:870)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dump(ViewDebug.java:793)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewDebug.dispatchCommand(ViewDebug.java:416)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.ViewRootImpl$W.executeCommand(ViewRootImpl.java:6258)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.view.IWindow$Stub.onTransact(IWindow.java:65)
10-10 16:11:06.320 E/JavaBinder( 4431):         at android.os.Binder.execTransact(Binder.java:404)
10-10 16:11:06.320 E/JavaBinder( 4431):         at dalvik.system.NativeStart.run(Native Method)
10-10 16:11:06.320 E/JavaBinder( 4431): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.Icon" on path: DexPathList[[zip file "/data/app/com.flowcrypt.email-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flowcrypt.email-1, /vendor/lib, /system/lib]]
10-10 16:11:06.320 E/JavaBinder( 4431):         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-10 16:11:06.320 E/JavaBinder( 4431):         at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-10 16:11:06.320 E/JavaBinder( 4431):         at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-10 16:11:06.320 E/JavaBinder( 4431):         ... 19 more
10-10 16:11:06.320 W/dalvikvm( 4431): threadid=10: thread exiting with uncaught exception (group=0xafa57bf0)
10-10 16:11:06.430 E/ACRA    ( 4431): ACRA caught a NoClassDefFoundError for com.flowcrypt.email
10-10 16:11:06.430 E/ACRA    ( 4431): java.lang.NoClassDefFoundError: android/graphics/drawable/Icon
10-10 16:11:06.430 E/ACRA    ( 4431):   at java.lang.Class.getDeclaredMethods(Native Method)
10-10 16:11:06.430 E/ACRA    ( 4431):   at java.lang.Class.getDeclaredMethods(Class.java:656)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.getExportedPropertyMethods(ViewDebug.java:960)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.exportMethods(ViewDebug.java:1047)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:997)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:983)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dumpView(ViewDebug.java:900)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:870)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dump(ViewDebug.java:793)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewDebug.dispatchCommand(ViewDebug.java:416)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.ViewRootImpl$W.executeCommand(ViewRootImpl.java:6258)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.view.IWindow$Stub.onTransact(IWindow.java:65)
10-10 16:11:06.430 E/ACRA    ( 4431):   at android.os.Binder.execTransact(Binder.java:404)
10-10 16:11:06.430 E/ACRA    ( 4431):   at dalvik.system.NativeStart.run(Native Method)
10-10 16:11:06.430 E/ACRA    ( 4431): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.Icon" on path: DexPathList[[zip file "/data/app/com.flowcrypt.email-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flowcrypt.email-1, /vendor/lib, /system/lib]]
10-10 16:11:06.430 E/ACRA    ( 4431):   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-10 16:11:06.430 E/ACRA    ( 4431):   at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-10 16:11:06.430 E/ACRA    ( 4431):   at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-10 16:11:06.430 E/ACRA    ( 4431):   ... 19 more
10-10 16:11:06.460 I/dalvikvm( 4431): Could not find method android.media.MediaCodecList.<init>, referenced from method org.acra.collector.MediaCodecListCollector.collectMediaCodecList
10-10 16:11:06.460 W/dalvikvm( 4431): VFY: unable to resolve direct method 1059: Landroid/media/MediaCodecList;.<init> (I)V
10-10 16:11:06.460 D/dalvikvm( 4431): VFY: replacing opcode 0x70 at 0x001e


[SHARED_PREFERENCES]
{"default": {"acra.legacyAlreadyConvertedToJson": true, "acra.legacyAlreadyConvertedTo4.8.0": true, "acra.lastVersionNr": 9}}


[ENVIRONMENT]
{"isEncryptedFilesystemEnabled": false, "getLegacyExternalStorageObbDirectory": "/storage/emulated/legacy/Android/obb", "getLegacyExternalStorageDirectory": "/storage/emulated/legacy", "getSecureDataDirectory": "/data", "getExternalStorageState": "mounted", "getSystemSecureDirectory": "/data/system", "getMediaStorageDirectory": "/data/media/0", "getExternalStorageDirectory": "/storage/emulated/0", "isExternalStorageEmulated": true, "getDataDirectory": "/data", "isExternalStorageRemovable": false, "getRootDirectory": "/system", "getDownloadCacheDirectory": "/cache", "getEmulatedStorageObbSource": "/mnt/shell/emulated/obb"}


[TOTAL_MEM_SIZE]
567640064


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 5, "locale": "en_US", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 260, "screenWidthDp": 434, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR", "compatScreenHeightDp": 478, "fontScale": 1, "smallestScreenWidthDp": 434, "densityDpi": 106, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 650, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DISPLAY]
{"0": {"refreshRate": 723.3790893554688, "realMetrics": {"density": 0.6625000238418579, "scaledDensity": "x0.6625", "xdpi": 106, "widthPixels": 288, "heightPixels": 480, "densityDpi": 106, "ydpi": 106}, "orientation": 0, "isValid": true, "currentSizeRange": {"smallest": [288, 271], "largest": [452, 431]}, "rectSize": [0, 0, 288, 448], "height": 448, "metrics": {"density": 0.6625000238418579, "scaledDensity": "x0.6625", "xdpi": 106, "widthPixels": 288, "heightPixels": 448, "densityDpi": 106, "ydpi": 106}, "width": 288, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "size": [288, 448], "rotation": "ROTATION_0", "realSize": [288, 480], "name": "Built-in Screen"}}


[AVAILABLE_MEM_SIZE]
329658368


[PHONE_MODEL]
SM-G900R7


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 5, "locale": "en_US", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 260, "screenWidthDp": 434, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR", "compatScreenHeightDp": 478, "fontScale": 1, "smallestScreenWidthDp": 434, "densityDpi": 106, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 650, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DEVICE_FEATURES]
{"android.software.input_methods": true, "android.hardware.faketouch": true, "android.software.app_widgets": true, "android.software.live_wallpaper": true, "android.hardware.usb.accessory": true, "android.hardware.microphone": true, "android.hardware.bluetooth": true, "android.hardware.location.network": true, "android.hardware.touchscreen.multitouch": true, "android.hardware.touchscreen": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.hardware.screen.portrait": true, "android.hardware.camera.any": true, "android.hardware.sensor.compass": true, "android.hardware.camera": true, "android.software.device_admin": true, "android.software.home_screen": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.camera.autofocus": true, "android.hardware.location": true, "android.hardware.sensor.accelerometer": true, "glEsVersion": "0.0", "android.hardware.screen.landscape": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email", "VERSION_NAME": "0.0.9", "VERSION_CODE": 9, "DEBUG": false, "FLAVOR": "", "BUILD_TYPE": "release"}


[FILE_PATH]
/data/data/com.flowcrypt.email/files


[INSTALLATION_ID]
8ac39cdd-863f-46c4-86c5-1ff285d136a2


[USER_CRASH_DATE]
2017-10-10T16:11:07.616-04:00


[HASH]
CDD6BA4E54


[APP_VERSION_NAME]
0.0.9


[USER_APP_START_DATE]
2017-10-10T16:09:57.836-04:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "goldfish", "BOARD": "MSM8974", "MODEL": "SM-G900R7", "BOOTLOADER": "unknown", "DISPLAY": "KOT49H", "CPU_ABI2": "armeabi", "FINGERPRINT": "samsung/klteacg/klteacg:4.4.2/KOT49H/G900R7WWU2AND8:user/release-keys", "TAGS": "release-keys", "HOST": "SWDD3013", "VERSION": {"RESOURCES_SDK_INT": 19, "SDK_INT": 19, "INCREMENTAL": "937116", "RELEASE": "4.4.2", "CODENAME": "REL", "SDK": "19"}, "DEVICE": "klteacg", "SERIAL": "03dd0fe8e07853f4", "ID": "KOT49H", "MANUFACTURER": "samsung", "PRODUCT": "klteacg", "BRAND": "samsung", "IS_DEBUGGABLE": true, "RADIO": "unknown", "CPU_ABI": "armeabi-v7a", "TIME": 1386201169000, "TYPE": "user", "USER": "android-build"}


[DUMPSYS_MEMINFO]
Permission Denial: can't dump meminfo from from pid=4524, uid=10048 without permission android.permission.DUMP


[USER_EMAIL]
N/A


[REPORT_ID]
ee819061-4675-4e83-87fe-221846f9d309


[PRODUCT]
klteacg


[PACKAGE_NAME]
com.flowcrypt.email


[BRAND]
samsung


[ANDROID_VERSION]
4.4.2


[APP_VERSION_CODE]
9


[IS_SILENT]
false


[CUSTOM_DATA]
{}

```

**Comment by DenBond7** [comment]
This is not a popular bug.
https://stackoverflow.com/questions/46030189/android-java-lang-noclassdeffounderror-samsung-s5-4-4-2
https://stackoverflow.com/questions/44398826/java-lang-noclassdeffounderror-when-using-large-icon-in-notification

Some people recommend using a lower version of android support library. But I don't think that we must do it for this case. Because it's the very rare case.

**Comment by tomholub** [comment]
So we should wait for future update to the library, or just close it?

**Comment by DenBond7** [comment]
We physically cannot fix bugs for the entire zoo of android devices. This error is the exception to the rule. And this is not our fault, this is Google's mistake. I think we can just close it.

**Comment by tomholub** [comment]
ok
