### ISSUE TITLE
NPE:  com.flowcrypt.email.api.email.Folder.getServerFullFolderName()' 

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#122]
```
[STACK_TRACE]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.Folder.getServerFullFolderName()' on a null object reference
        at com.flowcrypt.email.service.EmailSyncService$IncomingHandler.handleMessage(EmailSyncService.java:602)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6334)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)



[LOGCAT]
10-20 10:46:32.810 W/System.err(12033):         at java.lang.Thread.run(Thread.java:761)
10-20 10:50:52.354 D/AppTracker(12033): App Event: start
10-20 10:50:58.545 D/AppTracker(12033): App Event: stop
10-20 10:50:58.621 D/AppTracker(12033): App Event: start
10-20 10:51:01.091 I/System.out(12033): duration decode: 8
10-20 10:51:01.110 I/art     (12033): Starting a blocking GC AddRemoveAppImageSpace
10-20 10:51:01.114 D/ApplicationLoaders(12033): ignored Vulkan layer search path /data/app/com.android.chrome-1/lib/arm:/data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a for namespace 0xecaf60d0
10-20 10:51:01.117 I/WebViewFactory(12033): Loading com.android.chrome version 61.0.3163.98 (code 316309852)
10-20 10:51:01.135 I/cr_LibraryLoader(12033): Time to load native libraries: 2 ms (timestamps 8975-8977)
10-20 10:51:01.140 I/chromium(12033): [INFO:library_loader_hooks.cc(136)] Chromium logging enabled: level = 0, default verbosity = 0
10-20 10:51:01.141 I/cr_LibraryLoader(12033): Expected native library version number "61.0.3163.98", actual native library version number "61.0.3163.98"
10-20 10:51:01.150 I/cr_BrowserStartup(12033): Initializing chromium process, singleProcess=true
10-20 10:51:01.193 W/cr_media(12033): Requires BLUETOOTH permission
10-20 10:51:01.214 E/libEGL  (12033): validate_display:99 error 3008 (EGL_BAD_DISPLAY)
10-20 10:51:01.226 W/cr_CrashFileManager(12033): /data/user/0/com.flowcrypt.email/cache/WebView/Crash Reports does not exist or is not a directory
10-20 10:51:01.239 W/VideoCapabilities(12033): Unrecognized profile 2130706433 for video/avc
10-20 10:51:01.239 W/VideoCapabilities(12033): Unrecognized profile 2130706434 for video/avc
10-20 10:51:01.244 W/VideoCapabilities(12033): Unrecognized profile 2130706433 for video/avc
10-20 10:51:01.244 W/VideoCapabilities(12033): Unrecognized profile 2130706434 for video/avc
10-20 10:51:01.245 W/VideoCapabilities(12033): Unrecognized profile 2130706433 for video/avc
10-20 10:51:01.245 W/VideoCapabilities(12033): Unrecognized profile 2130706434 for video/avc
10-20 10:51:01.247 W/VideoCapabilities(12033): Unrecognized profile/level 0/3 for video/mpeg2
10-20 10:51:01.248 W/VideoCapabilities(12033): Unrecognized profile/level 0/3 for video/mpeg2
10-20 10:51:01.251 W/VideoCapabilities(12033): Unsupported mime video/x-ms-wmv
10-20 10:51:01.252 W/VideoCapabilities(12033): Unsupported mime video/x-ms-wmv
10-20 10:51:01.253 W/VideoCapabilities(12033): Unsupported mime video/divx
10-20 10:51:01.254 W/VideoCapabilities(12033): Unsupported mime video/divx311
10-20 10:51:01.255 W/VideoCapabilities(12033): Unsupported mime video/divx4
10-20 10:51:01.264 W/VideoCapabilities(12033): Unsupported mime video/mp4v-esdp
10-20 10:51:01.274 I/VideoCapabilities(12033): Unsupported profile 4 for video/mp4v-es
10-20 10:51:01.303 I/chromium(12033): [INFO:CONSOLE(1)] "The key "" is not recognized and ignored.", source: about:blank (1)
10-20 10:51:14.074 D/AppTracker(12033): App Event: stop
10-20 10:51:14.126 D/AppTracker(12033): App Event: start
--------- beginning of system
10-20 10:51:14.582 E/ActivityThread(12033): Activity com.flowcrypt.email.ui.activity.MessageDetailsActivity has leaked IntentReceiver org.chromium.content.browser.accessibility.LollipopWebContentsAccessibility$1@b15e0c7 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-20 10:51:14.582 E/ActivityThread(12033): android.app.IntentReceiverLeaked: Activity com.flowcrypt.email.ui.activity.MessageDetailsActivity has leaked IntentReceiver org.chromium.content.browser.accessibility.LollipopWebContentsAccessibility$1@b15e0c7 that was originally registered here. Are you missing a call to unregisterReceiver()?
10-20 10:51:14.582 E/ActivityThread(12033):     at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:1208)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:977)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1319)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1299)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.app.ContextImpl.registerReceiver(ContextImpl.java:1293)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:587)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:587)
10-20 10:51:14.582 E/ActivityThread(12033):     at org.chromium.content.browser.accessibility.LollipopWebContentsAccessibility.<init>(LollipopWebContentsAccessibility.java:3)
10-20 10:51:14.582 E/ActivityThread(12033):     at org.chromium.content.browser.ContentViewCore.getAccessibilityNodeProvider(ContentViewCore.java:659)
10-20 10:51:14.582 E/ActivityThread(12033):     at com.android.webview.chromium.WebViewChromium.getAccessibilityNodeProvider(WebViewChromium.java:636)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.webkit.WebView.getAccessibilityNodeProvider(WebView.java:2475)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.createAccessibilityNodeInfoInternal(View.java:6602)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.createAccessibilityNodeInfo(View.java:6592)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:145)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.onInitializeAccessibilityEventInternal(View.java:6544)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.webkit.WebView.onInitializeAccessibilityEventInternal(WebView.java:2504)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.onInitializeAccessibilityEvent(View.java:6532)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:6397)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.sendAccessibilityEventUnchecked(View.java:6382)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.sendAccessibilityEventInternal(View.java:6359)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.sendAccessibilityEvent(View.java:6326)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.onFocusChanged(View.java:6263)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.webkit.WebView.onFocusChanged(WebView.java:2575)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.handleFocusGainInternal(View.java:6004)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:717)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.requestFocusNoSearch(View.java:9169)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.requestFocus(View.java:9148)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.requestFocus(ViewGroup.java:2834)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.webkit.WebView.-wrap12(WebView.java)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.webkit.WebView$PrivateAccess.super_requestFocus(WebView.java:2193)
10-20 10:51:14.582 E/ActivityThread(12033):     at com.android.webview.chromium.WebViewChromium.requestFocus(WebViewChromium.java:841)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.webkit.WebView.requestFocus(WebView.java:2603)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:2879)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.requestFocus(ViewGroup.java:2835)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.requestFocus(View.java:9115)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.requestFocus(View.java:9094)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:3270)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.ViewGroup.focusableViewAvailable(ViewGroup.java:760)
10-20 10:51:14.582 E/ActivityThread(12033):     at android.view.View.setFlags(View.j
10-20 10:51:19.024 D/AppTracker(12033): App Event: stop
10-20 10:51:19.058 D/AppTracker(12033): App Event: start
10-20 10:51:19.125 D/OpenGLRenderer(12033): endAllActiveAnimators on 0xe22e0600 (ListView) with handle 0xc9eae920
10-20 10:51:21.066 I/System.out(12033): duration decode: 16
10-20 10:51:21.101 I/chromium(12033): [INFO:CONSOLE(1)] "The key "" is not recognized and ignored.", source: about:blank (1)
10-20 10:51:22.681 D/AndroidRuntime(12033): Shutting down VM
10-20 10:51:22.682 E/ACRA    (12033): ACRA caught a NullPointerException for com.flowcrypt.email
10-20 10:51:22.682 E/ACRA    (12033): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.Folder.getServerFullFolderName()' on a null object reference
10-20 10:51:22.682 E/ACRA    (12033):   at com.flowcrypt.email.service.EmailSyncService$IncomingHandler.handleMessage(EmailSyncService.java:602)
10-20 10:51:22.682 E/ACRA    (12033):   at android.os.Handler.dispatchMessage(Handler.java:102)
10-20 10:51:22.682 E/ACRA    (12033):   at android.os.Looper.loop(Looper.java:154)
10-20 10:51:22.682 E/ACRA    (12033):   at android.app.ActivityThread.main(ActivityThread.java:6334)
10-20 10:51:22.682 E/ACRA    (12033):   at java.lang.reflect.Method.invoke(Native Method)
10-20 10:51:22.682 E/ACRA    (12033):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
10-20 10:51:22.682 E/ACRA    (12033):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)


[SHARED_PREFERENCES]
{"default": {"acra.legacyAlreadyConvertedToJson": true, "acra.legacyAlreadyConvertedTo4.8.0": true, "acra.lastVersionNr": 9, "preference_key_secret": "HCFne3VJFy19PrkocG9903f71ItiUV0tx6yYa82pMoGBi8JC9JDzCSJ6jjTpjAVTsqhebesQyS42\nfxG6AApw5cgJCjbayUCwEW95LmxxJmR0k/ksamIr36IzRpQY8OAIb+s+3pYNJlGf2O22ngXmFdfM\nzOIX7mQWF29SnyyrITedD4QmJy+kEINU6qLKy8r2rhgMks0wHO0CuRWm3A3d+Vp+TxbPDbziEHqJ\nZI9gl/RW5YDgWsIQx2qcl+MW3Ymg7mh9wwfgWCMnFcwztyMT9H2mjkYcD97Z0WkL+BHoK/o8qw8R\n8sWUxPMajor6teFuF7xygvLL0cKDCfDYvR8S9w==\n    "}}


[ENVIRONMENT]
{"getDataSystemDirectory": "/data/system", "getDataPreloadsDirectory": "/data/preloads", "getOdmDirectory": "/odm", "getDataMiscDirectory": "/data/misc", "getDataSystemCeDirectory": "/data/system_ce", "getExpandDirectory": "/mnt/expand", "getRootDirectory": "/system", "getLegacyExternalStorageDirectory": "/sdcard", "getDataPreloadsAppsDirectory": "/data/preloads/apps", "getDataPreloadsDemoDirectory": "/data/preloads/demo", "getDataPreloadsMediaDirectory": "/data/preloads/media", "isExternalStorageEmulated": true, "isExternalStorageRemovable": false, "getDownloadCacheDirectory": "/data/cache", "getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getExternalStorageState": "mounted", "getStorageDirectory": "/storage", "getExternalStorageDirectory": "/storage/emulated/0", "getOemDirectory": "/oem", "getDataDirectory": "/data", "getDataSystemDeDirectory": "/data/system_de"}


[TOTAL_MEM_SIZE]
119526244352


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 138, "locale": "fr_FR", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 15, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 547, "fontScale": 1, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 208, "oneplusfont": 0, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 616, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "mOpExtraConfiguration": "mThemeChanged = 1", "navigation": "NAVIGATION_NONAV"}


[DISPLAY]
{"0": {"refreshRate": 60.000003814697266, "metrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 403.4110107421875, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 480, "ydpi": 399.73699951171875}, "name": "\u00c9cran int\u00e9gr\u00e9", "realSize": [1080, 1920], "isValid": true, "currentSizeRange": {"smallest": [1080, 1008], "largest": [1920, 1848]}, "rectSize": [0, 0, 1080, 1920], "height": 1920, "realMetrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 403.4110107421875, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 480, "ydpi": 399.73699951171875}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 1920], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
100257488896


[PHONE_MODEL]
ONEPLUS A5000


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 474, "locale": "fr_FR", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 15, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 547, "fontScale": 1, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 208, "oneplusfont": 0, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 616, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "mOpExtraConfiguration": "mThemeChanged = 1", "navigation": "NAVIGATION_NONAV"}


[DEVICE_FEATURES]
{"android.software.input_methods": true, "android.hardware.nfc.hcef": true, "android.hardware.faketouch": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "android.software.file_based_encryption": true, "android.hardware.usb.accessory": true, "android.hardware.location.network": true, "android.software.voice_recognizers": true, "oem.otg.positive.negative.plug.support": true, "oem.timePoweroffWakeup.support": true, "android.hardware.audio.output": true, "android.hardware.bluetooth": true, "oem.voice.anc.support": true, "oem.pdaf.not.support": true, "oem.blackScreenGesture_2.support": true, "android.hardware.nfc.hce": true, "oem.hall.auto.test.support": true, "oem.button.light.support": true, "oem.otgSwitch.support": true, "oem.service.adb.tcp.port.support": true, "oem.rgb.sensor.support": true, "oem.op_dark_mode.support": true, "android.hardware.vulkan.level": true, "android.hardware.wifi.direct": true, "android.hardware.screen.landscape": true, "oem.dual.back.camera.support": true, "android.software.connectionservice": true, "oem.op_intelligent_background_management.support": true, "oem.dual.led.support": true, "oem.background.control": true, "android.software.managed_users": true, "android.hardware.telephony": true, "oem.audiotuner.support": true, "android.hardware.sensor.light": true, "oem.op_legal_information.support": true, "oem.qcom.fastchager.support": true, "oem.high.gain.mode.support": true, "android.software.midi": true, "android.hardware.wifi": true, "oem.dcip3.support": true, "oem.lift_up_display.support": true, "android.hardware.touchscreen": true, "oem.read_mode.support": true, "android.hardware.sensor.compass": true, "android.hardware.telephony.cdma": true, "android.software.print": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.opengles.aep": true, "android.hardware.sensor.stepdetector": true, "android.hardware.location": true, "android.software.device_admin": true, "oem.finger.print.support": true, "android.hardware.camera.capability.manual_post_processing": true, "oem.ambient.support": true, "android.hardware.bluetooth_le": true, "android.software.backup": true, "android.software.live_wallpaper": true, "android.software.securely_removes_users": true, "android.hardware.telephony.gsm": true, "android.hardware.vulkan.version": true, "oem.prox.calibration.support": true, "android.software.webview": true, "android.software.sip.voip": true, "android.hardware.fingerprint": true, "android.hardware.touchscreen.multitouch": true, "oem.opcamera_manual_zsl.support": true, "android.hardware.sensor.stepcounter": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "oem.blackScreenGesture.support": true, "android.hardware.camera.any": true, "oem.inexact.alarm": true, "com.oneplus.software.oos": true, "oem.gyroscope.support": true, "android.hardware.camera.level.full": true, "oem.new_led_color.support": true, "oem.vooc.fastchager.support": true, "glEsVersion": "3.2", "oem.small.board.not.support": true, "android.hardware.usb.host": true, "android.hardware.nfc": true, "android.software.verified_boot": true, "oem.no_need_power_on_password.support": true, "oem.serial_cdev.support": true, "android.hardware.camera.capability.raw": true, "oem.breathLight.support": true, "oem.keyDefine.support": true, "oem.picture.color.mode.srgb": true, "android.hardware.camera.flash": true, "com.nxp.mifare": true, "oem.threeStageKey.support": true, "android.hardware.location.gps": true, "oem.linear.motor.support": true, "android.hardware.microphone": true, "android.hardware.sensor.gyroscope": true, "android.hardware.camera.capability.manual_sensor": true, "oem.direct.support": true, "android.software.sip": true, "android.hardware.screen.portrait": true, "oem.otg.switch.support": true, "oem.dualsim.support": true, "android.hardware.sensor.proximity": true, "android.hardware.camera": true, "oem.hapticsService.support": true, "oem.threeScreenshot.support": true, "oem.hw.manufacturer.qualcomm": true, "android.software.home_screen": true, "com.oneplus.software.oos.n_theme_ready": true, "oem.autobrightctl.animation.support": true, "android.hardware.camera.autofocus": true, "android.hardware.sensor.accelerometer": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email", "VERSION_CODE": 9, "BUILD_TYPE": "release", "DEBUG": false, "VERSION_NAME": "0.0.9", "FLAVOR": ""}


[FILE_PATH]
/data/user/0/com.flowcrypt.email/files


[INSTALLATION_ID]
892d6446-a149-4ab0-8f01-eff71cba6a3f


[USER_CRASH_DATE]
2017-10-20T10:51:22.741+02:00


[HASH]
E8A843110E


[APP_VERSION_NAME]
0.0.9


[USER_APP_START_DATE]
2017-10-14T16:24:07.250+02:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "qcom", "BOARD": "msm8998", "MODEL": "ONEPLUS A5000", "BOOTLOADER": "unknown", "DISPLAY": "ONEPLUS A5000_24_170825", "CPU_ABI2": "armeabi", "DEBUG_ONEPLUS": false, "FINGERPRINT": "OnePlus/OnePlus5/OnePlus5:7.1.1/NMF26X/08141919:user/release-keys", "IS_EMULATOR": false, "TAGS": "release-keys", "AUTO_TEST_ONEPLUS": false, "IS_DEBUGGABLE": false, "VERSION": {"IS_CTA_BUILD": false, "PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 25, "SDK_INT": 25, "INCREMENTAL": "273", "BASE_OS": "", "RELEASE": "7.1.1", "CODENAME": "REL", "SECURITY_PATCH": "2017-07-01", "ACTIVE_CODENAMES": [], "SDK": "25"}, "IS_BETA_ROM": false, "PERMISSIONS_REVIEW_REQUIRED": false, "DEVICE": "OnePlus5", "SERIAL": "cd7a72fc", "ID": "NMF26X", "MANUFACTURER": "OnePlus", "PRODUCT": "OnePlus5", "SUPPORTED_ABIS": ["arm64-v8a", "armeabi-v7a", "armeabi"], "HOST": "ubuntu-158", "SOFT_VERSION": "O.15", "SUPPORTED_64_BIT_ABIS": ["arm64-v8a"], "RADIO": "unknown", "BRAND": "OnePlus", "CPU_ABI": "armeabi-v7a", "TIME": 1503675989000, "SUPPORTED_32_BIT_ABIS": ["armeabi-v7a", "armeabi"], "TYPE": "user", "REGION": "OverSeas", "USER": "OnePlus"}


[DUMPSYS_MEMINFO]



[USER_EMAIL]
N/A


[REPORT_ID]
6f64ff4d-f322-47b2-b4b5-b35f3eb13eac


[PRODUCT]
OnePlus5


[PACKAGE_NAME]
com.flowcrypt.email


[BRAND]
OnePlus


[ANDROID_VERSION]
7.1.1


[APP_VERSION_CODE]
9


[IS_SILENT]
false


[CUSTOM_DATA]
{}
```

**Comment by DenBond7** [comment]
I added debug code because I tested the app with different providers(Gmail, Outlook, Yahoo, UKR.NET) and did not receive such errors. Moved this issue to the version 0.4.0.

**Comment by DenBond7** [comment]
Fixed by https://github.com/FlowCrypt/flowcrypt-android/commit/020d2e57cb4f31df0f9842261388a4cffbca7f68

Before this commit, the app was crashing if a user used a non-Gmail account and tried to move messages to the archive folder.
