### ISSUE TITLE
java.lang.NoClassDefFoundError: android/graphics/drawable/Icon

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#126]
```
[STACK_TRACE]
java.lang.NoClassDefFoundError: android/graphics/drawable/Icon
        at java.lang.Class.getDeclaredMethods(Native Method)
        at java.lang.Class.getDeclaredMethods(Class.java:656)
        at android.view.ViewDebug.getExportedPropertyMethods(ViewDebug.java:960)
        at android.view.ViewDebug.exportMethods(ViewDebug.java:1047)
        at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:997)
        at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:983)
        at android.view.ViewDebug.dumpView(ViewDebug.java:900)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:870)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dump(ViewDebug.java:793)
        at android.view.ViewDebug.dispatchCommand(ViewDebug.java:416)
        at android.view.ViewRootImpl$W.executeCommand(ViewRootImpl.java:6258)
        at android.view.IWindow$Stub.onTransact(IWindow.java:65)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.Icon" on path: DexPathList[[zip file "/data/app/com.flowcrypt.email-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flowcrypt.email-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        ... 19 more
java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.Icon" on path: DexPathList[[zip file "/data/app/com.flowcrypt.email-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flowcrypt.email-1, /vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
        at java.lang.Class.getDeclaredMethods(Native Method)
        at java.lang.Class.getDeclaredMethods(Class.java:656)
        at android.view.ViewDebug.getExportedPropertyMethods(ViewDebug.java:960)
        at android.view.ViewDebug.exportMethods(ViewDebug.java:1047)
        at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:997)
        at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:983)
        at android.view.ViewDebug.dumpView(ViewDebug.java:900)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:870)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
        at android.view.ViewDebug.dump(ViewDebug.java:793)
        at android.view.ViewDebug.dispatchCommand(ViewDebug.java:416)
        at android.view.ViewRootImpl$W.executeCommand(ViewRootImpl.java:6258)
        at android.view.IWindow$Stub.onTransact(IWindow.java:65)
        at android.os.Binder.execTransact(Binder.java:404)
        at dalvik.system.NativeStart.run(Native Method)



[LOGCAT]
10-22 03:16:31.660 I/dalvikvm( 4240): Could not find method android.widget.TextView.getAutoSizeStepGranularity, referenced from method android.support.v7.widget.AppCompatTextView.getAutoSizeStepGranularity
10-22 03:16:31.660 W/dalvikvm( 4240): VFY: unable to resolve virtual method 12931: Landroid/widget/TextView;.getAutoSizeStepGranularity ()I
10-22 03:16:31.660 D/dalvikvm( 4240): VFY: replacing opcode 0x6f at 0x0006
10-22 03:16:31.660 I/dalvikvm( 4240): Could not find method android.widget.TextView.getAutoSizeTextAvailableSizes, referenced from method android.support.v7.widget.AppCompatTextView.getAutoSizeTextAvailableSizes
10-22 03:16:31.660 W/dalvikvm( 4240): VFY: unable to resolve virtual method 12932: Landroid/widget/TextView;.getAutoSizeTextAvailableSizes ()[I
10-22 03:16:31.660 D/dalvikvm( 4240): VFY: replacing opcode 0x6f at 0x0006
10-22 03:16:31.670 I/dalvikvm( 4240): Could not find method android.widget.TextView.getAutoSizeTextType, referenced from method android.support.v7.widget.AppCompatTextView.getAutoSizeTextType
10-22 03:16:31.670 W/dalvikvm( 4240): VFY: unable to resolve virtual method 12933: Landroid/widget/TextView;.getAutoSizeTextType ()I
10-22 03:16:31.670 D/dalvikvm( 4240): VFY: replacing opcode 0x6f at 0x0008
10-22 03:16:31.670 I/dalvikvm( 4240): Could not find method android.widget.TextView.setAutoSizeTextTypeUniformWithConfiguration, referenced from method android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeUniformWithConfiguration
10-22 03:16:31.670 W/dalvikvm( 4240): VFY: unable to resolve virtual method 12974: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithConfiguration (IIII)V
10-22 03:16:31.670 D/dalvikvm( 4240): VFY: replacing opcode 0x6f at 0x0006
10-22 03:16:31.680 I/dalvikvm( 4240): Could not find method android.widget.TextView.setAutoSizeTextTypeUniformWithPresetSizes, referenced from method android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeUniformWithPresetSizes
10-22 03:16:31.680 W/dalvikvm( 4240): VFY: unable to resolve virtual method 12975: Landroid/widget/TextView;.setAutoSizeTextTypeUniformWithPresetSizes ([II)V
10-22 03:16:31.680 D/dalvikvm( 4240): VFY: replacing opcode 0x6f at 0x0006
10-22 03:16:31.680 I/dalvikvm( 4240): Could not find method android.widget.TextView.setAutoSizeTextTypeWithDefaults, referenced from method android.support.v7.widget.AppCompatTextView.setAutoSizeTextTypeWithDefaults
10-22 03:16:31.680 W/dalvikvm( 4240): VFY: unable to resolve virtual method 12976: Landroid/widget/TextView;.setAutoSizeTextTypeWithDefaults (I)V
10-22 03:16:31.680 D/dalvikvm( 4240): VFY: replacing opcode 0x6f at 0x0006
10-22 03:16:31.900 D/dalvikvm( 4240): GC_CONCURRENT freed 238K, 10% free 2877K/3192K, paused 7ms+8ms, total 95ms
10-22 03:16:31.930 I/dalvikvm( 4240): Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.zzo.zzy
10-22 03:16:31.930 W/dalvikvm( 4240): VFY: unable to resolve virtual method 581: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;
10-22 03:16:31.940 D/dalvikvm( 4240): VFY: replacing opcode 0x6e at 0x0012
10-22 03:16:33.660 W/GooglePlayServicesUtil( 4240): Google Play services out of date.  Requires 11020000 but found 8489030
10-22 03:16:34.290 I/Choreographer( 4240): Skipped 104 frames!  The application may be doing too much work on its main thread.
10-22 03:16:34.360 D/gralloc_goldfish( 4240): Emulator without GPU emulation detected.
10-22 03:16:35.070 D/dalvikvm( 4240): GC_CONCURRENT freed 231K, 10% free 3104K/3424K, paused 5ms+19ms, total 155ms
10-22 03:16:35.390 I/Choreographer( 4240): Skipped 127 frames!  The application may be doing too much work on its main thread.
10-22 03:16:36.620 I/Choreographer( 4240): Skipped 67 frames!  The application may be doing too much work on its main thread.
10-22 03:17:06.300 D/dalvikvm( 4240): GC_CONCURRENT freed 239K, 10% free 3274K/3600K, paused 15ms+11ms, total 98ms
10-22 03:17:07.090 D/dalvikvm( 4240): GC_CONCURRENT freed 367K, 12% free 3330K/3780K, paused 6ms+7ms, total 132ms
10-22 03:17:07.790 D/dalvikvm( 4240): GC_CONCURRENT freed 380K, 12% free 3368K/3824K, paused 6ms+9ms, total 110ms
10-22 03:17:08.520 D/dalvikvm( 4240): GC_CONCURRENT freed 418K, 13% free 3398K/3904K, paused 6ms+15ms, total 120ms
10-22 03:17:09.130 D/dalvikvm( 4240): GC_CONCURRENT freed 390K, 12% free 3451K/3912K, paused 17ms+7ms, total 135ms
10-22 03:17:09.720 D/dalvikvm( 4240): GC_CONCURRENT freed 424K, 13% free 3462K/3972K, paused 19ms+16ms, total 109ms
10-22 03:17:10.470 D/dalvikvm( 4240): GC_CONCURRENT freed 424K, 14% free 3452K/3972K, paused 10ms+17ms, total 110ms
10-22 03:17:11.420 D/dalvikvm( 4240): GC_CONCURRENT freed 511K, 15% free 3378K/3972K, paused 7ms+19ms, total 172ms
10-22 03:17:12.270 D/dalvikvm( 4240): GC_CONCURRENT freed 413K, 15% free 3390K/3972K, paused 15ms+9ms, total 135ms
10-22 03:17:12.970 D/dalvikvm( 4240): GC_CONCURRENT freed 415K, 15% free 3396K/3972K, paused 41ms+10ms, total 148ms
10-22 03:17:13.780 D/dalvikvm( 4240): GC_CONCURRENT freed 457K, 15% free 3390K/3972K, paused 15ms+14ms, total 146ms
10-22 03:17:14.790 D/dalvikvm( 4240): GC_CONCURRENT freed 450K, 16% free 3338K/3972K, paused 7ms+21ms, total 138ms
10-22 03:17:15.870 D/dalvikvm( 4240): GC_CONCURRENT freed 394K, 15% free 3399K/3972K, paused 14ms+40ms, total 189ms
10-22 03:17:16.950 D/dalvikvm( 4240): GC_CONCURRENT freed 483K, 16% free 3358K/3972K, paused 19ms+14ms, total 189ms
10-22 03:17:17.890 D/dalvikvm( 4240): GC_CONCURRENT freed 412K, 16% free 3347K/3972K, paused 6ms+14ms, total 103ms
10-22 03:17:18.180 W/dalvikvm( 4240): Unable to match class for part: 'Landroid/graphics/drawable/Icon;)V'
10-22 03:17:18.240 E/JavaBinder( 4240): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
10-22 03:17:18.240 E/JavaBinder( 4240): java.lang.NoClassDefFoundError: android/graphics/drawable/Icon
10-22 03:17:18.240 E/JavaBinder( 4240):         at java.lang.Class.getDeclaredMethods(Native Method)
10-22 03:17:18.240 E/JavaBinder( 4240):         at java.lang.Class.getDeclaredMethods(Class.java:656)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.getExportedPropertyMethods(ViewDebug.java:960)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.exportMethods(ViewDebug.java:1047)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:997)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:983)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dumpView(ViewDebug.java:900)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:870)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dump(ViewDebug.java:793)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewDebug.dispatchCommand(ViewDebug.java:416)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.ViewRootImpl$W.executeCommand(ViewRootImpl.java:6258)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.view.IWindow$Stub.onTransact(IWindow.java:65)
10-22 03:17:18.240 E/JavaBinder( 4240):         at android.os.Binder.execTransact(Binder.java:404)
10-22 03:17:18.240 E/JavaBinder( 4240):         at dalvik.system.NativeStart.run(Native Method)
10-22 03:17:18.240 E/JavaBinder( 4240): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.Icon" on path: DexPathList[[zip file "/data/app/com.flowcrypt.email-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flowcrypt.email-1, /vendor/lib, /system/lib]]
10-22 03:17:18.240 E/JavaBinder( 4240):         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-22 03:17:18.240 E/JavaBinder( 4240):         at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-22 03:17:18.240 E/JavaBinder( 4240):         at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-22 03:17:18.240 E/JavaBinder( 4240):         ... 19 more
10-22 03:17:18.240 W/dalvikvm( 4240): threadid=9: thread exiting with uncaught exception (group=0xafa1ebf0)
10-22 03:17:18.310 E/ACRA    ( 4240): ACRA caught a NoClassDefFoundError for com.flowcrypt.email
10-22 03:17:18.310 E/ACRA    ( 4240): java.lang.NoClassDefFoundError: android/graphics/drawable/Icon
10-22 03:17:18.310 E/ACRA    ( 4240):   at java.lang.Class.getDeclaredMethods(Native Method)
10-22 03:17:18.310 E/ACRA    ( 4240):   at java.lang.Class.getDeclaredMethods(Class.java:656)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.getExportedPropertyMethods(ViewDebug.java:960)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.exportMethods(ViewDebug.java:1047)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:997)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dumpViewProperties(ViewDebug.java:983)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dumpView(ViewDebug.java:900)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:870)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dumpViewHierarchy(ViewDebug.java:867)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dump(ViewDebug.java:793)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewDebug.dispatchCommand(ViewDebug.java:416)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.ViewRootImpl$W.executeCommand(ViewRootImpl.java:6258)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.view.IWindow$Stub.onTransact(IWindow.java:65)
10-22 03:17:18.310 E/ACRA    ( 4240):   at android.os.Binder.execTransact(Binder.java:404)
10-22 03:17:18.310 E/ACRA    ( 4240):   at dalvik.system.NativeStart.run(Native Method)
10-22 03:17:18.310 E/ACRA    ( 4240): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.graphics.drawable.Icon" on path: DexPathList[[zip file "/data/app/com.flowcrypt.email-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.flowcrypt.email-1, /vendor/lib, /system/lib]]
10-22 03:17:18.310 E/ACRA    ( 4240):   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-22 03:17:18.310 E/ACRA    ( 4240):   at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
10-22 03:17:18.310 E/ACRA    ( 4240):   at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
10-22 03:17:18.310 E/ACRA    ( 4240):   ... 19 more
10-22 03:17:18.340 I/dalvikvm( 4240): Could not find method android.media.MediaCodecList.<init>, referenced from method org.acra.collector.MediaCodecListCollector.collectMediaCodecList
10-22 03:17:18.340 W/dalvikvm( 4240): VFY: unable to resolve direct method 1064: Landroid/media/MediaCodecList;.<init> (I)V
10-22 03:17:18.340 D/dalvikvm( 4240): VFY: replacing opcode 0x70 at 0x001e


[ENVIRONMENT]
{"isEncryptedFilesystemEnabled": false, "getLegacyExternalStorageObbDirectory": "/storage/emulated/legacy/Android/obb", "getLegacyExternalStorageDirectory": "/storage/emulated/legacy", "getSecureDataDirectory": "/data", "getExternalStorageState": "mounted", "getSystemSecureDirectory": "/data/system", "getMediaStorageDirectory": "/data/media/0", "getExternalStorageDirectory": "/storage/emulated/0", "isExternalStorageEmulated": true, "getDataDirectory": "/data", "isExternalStorageRemovable": false, "getRootDirectory": "/system", "getDownloadCacheDirectory": "/cache", "getEmulatedStorageObbSource": "/mnt/shell/emulated/obb"}


[TOTAL_MEM_SIZE]
567640064


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 5, "locale": "en_US", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 260, "screenWidthDp": 434, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR", "compatScreenHeightDp": 478, "fontScale": 1, "smallestScreenWidthDp": 434, "densityDpi": 106, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 650, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DISPLAY]
{"0": {"refreshRate": 723.3790893554688, "realMetrics": {"density": 0.6625000238418579, "scaledDensity": "x0.6625", "xdpi": 106, "widthPixels": 288, "heightPixels": 480, "densityDpi": 106, "ydpi": 106}, "orientation": 0, "isValid": true, "currentSizeRange": {"smallest": [288, 271], "largest": [452, 431]}, "rectSize": [0, 0, 288, 448], "height": 448, "metrics": {"density": 0.6625000238418579, "scaledDensity": "x0.6625", "xdpi": 106, "widthPixels": 288, "heightPixels": 448, "densityDpi": 106, "ydpi": 106}, "width": 288, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "size": [288, 448], "rotation": "ROTATION_0", "realSize": [288, 480], "name": "Built-in Screen"}}


[AVAILABLE_MEM_SIZE]
328327168


[PHONE_MODEL]
SM-G900R7


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 5, "locale": "en_US", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 260, "screenWidthDp": 434, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR", "compatScreenHeightDp": 478, "fontScale": 1, "smallestScreenWidthDp": 434, "densityDpi": 106, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 650, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DEVICE_FEATURES]
{"android.software.input_methods": true, "android.hardware.faketouch": true, "android.software.app_widgets": true, "android.software.live_wallpaper": true, "android.hardware.usb.accessory": true, "android.hardware.microphone": true, "android.hardware.bluetooth": true, "android.hardware.location.network": true, "android.hardware.touchscreen.multitouch": true, "android.hardware.touchscreen": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.hardware.screen.portrait": true, "android.hardware.camera.any": true, "android.hardware.sensor.compass": true, "android.hardware.camera": true, "android.software.device_admin": true, "android.software.home_screen": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.camera.autofocus": true, "android.hardware.location": true, "android.hardware.sensor.accelerometer": true, "glEsVersion": "0.0", "android.hardware.screen.landscape": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email", "VERSION_NAME": "0.2.0", "VERSION_CODE": 20, "DEBUG": false, "FLAVOR": "", "BUILD_TYPE": "release"}


[FILE_PATH]
/data/data/com.flowcrypt.email/files


[INSTALLATION_ID]
ce5147f2-edd4-4916-98d4-ea704f7df3d5


[USER_CRASH_DATE]
2017-10-22T03:17:19.108-04:00


[HASH]
CDD6BA4E54


[APP_VERSION_NAME]
0.2.0


[USER_APP_START_DATE]
2017-10-22T03:16:30.214-04:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "goldfish", "BOARD": "MSM8974", "MODEL": "SM-G900R7", "BOOTLOADER": "unknown", "DISPLAY": "KOT49H", "CPU_ABI2": "armeabi", "FINGERPRINT": "samsung/klteacg/klteacg:4.4.2/KOT49H/G900R7WWU2AND8:user/release-keys", "TAGS": "release-keys", "HOST": "SWDD3013", "VERSION": {"RESOURCES_SDK_INT": 19, "SDK_INT": 19, "INCREMENTAL": "937116", "RELEASE": "4.4.2", "CODENAME": "REL", "SDK": "19"}, "DEVICE": "klteacg", "SERIAL": "03dd0fe8e07853f4", "ID": "KOT49H", "MANUFACTURER": "samsung", "PRODUCT": "klteacg", "BRAND": "samsung", "IS_DEBUGGABLE": true, "RADIO": "unknown", "CPU_ABI": "armeabi-v7a", "TIME": 1386201169000, "TYPE": "user", "USER": "android-build"}


[DUMPSYS_MEMINFO]
Permission Denial: can't dump meminfo from from pid=4355, uid=10048 without permission android.permission.DUMP


[USER_EMAIL]
N/A


[REPORT_ID]
7c08c842-d20e-48e5-8dab-b855622acc68


[PRODUCT]
klteacg


[PACKAGE_NAME]
com.flowcrypt.email


[BRAND]
samsung


[ANDROID_VERSION]
4.4.2


[APP_VERSION_CODE]
20


[IS_SILENT]
false


[CUSTOM_DATA]
{}
```

**Comment by DenBond7** [comment]
#117

**Comment by tomholub** [comment]
Hmm we should probably have these ignored automatically
