### ISSUE TITLE
 Error: Invalid key: need at least key and user ID packet

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#138]
This error happened when I try listening clipboard.

```
[STACK_TRACE]
undefined:23: Error: Invalid key: need at least key and user ID packet
      throw e;
      ^
Error: Invalid key: need at least key and user ID packet
    at new Key (<anonymous>:13173:11)
    at Object.Key (<anonymous>:13163:12)
    at Object.crypto_key_normalize [as normalize] (<anonymous>:1839:27)
com.eclipsesource.v8.V8ScriptExecutionException
        at com.eclipsesource.v8.V8._executeStringFunction(Native Method)
        at com.eclipsesource.v8.V8.executeStringFunction(V8.java:1117)
        at com.eclipsesource.v8.V8Object.executeStringFunction(V8Object.java:288)
        at com.flowcrypt.email.js.Js.call(Js.java:268)
        at com.flowcrypt.email.js.Js.call(Js.java:256)
        at com.flowcrypt.email.js.Js.crypto_key_normalize(Js.java:122)
        at com.flowcrypt.email.service.CheckClipboardToFindPrivateKeyService$ServiceWorkerHandler.handleMessage(CheckClipboardToFindPrivateKeyService.java:206)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.os.HandlerThread.run(HandlerThread.java:61)



[LOGCAT]
11-07 09:17:40.459 I/System.out( 6143):         b=ck/RXpeESckgFD/LqKNq0LopBZfYYb2+kYziBgAXO3+4D8u/74r90tqXcvD5JGa6oH
11-07 09:17:40.460 I/System.out( 6143):          xCgQMeyUmvkcZ4877zIY1BPikchLNI6WmoH3Dmi/EDQ3/Dxcb8has4s0ns2tz9n5hxF6
11-07 09:17:40.460 I/System.out( 6143):          NZFdoUTgwSe60//AtTFsxqvUZHThQ3pm4mSP3bw/4oyNVwepYicVogOHQxrA1yKyW0fW
11-07 09:17:40.460 I/System.out( 6143):          3dlyD9iWp87wvIJMMenGxzKw/VMr3e06HaSK3a1DlPfaEF6q3/DhkLUwxGoLytSqzxXL
11-07 09:17:40.460 I/System.out( 6143):          tcNRyBl7q62Ui5GG9RJ6ssDc1Xri3ikhn0pQvHUr+kg72wFcWw4lRJIiA4wIhBrBx/j6
11-07 09:17:40.460 I/System.out( 6143):          T/MA==
11-07 09:17:40.460 I/System.out( 6143): X-Gm-Message-State: AMCzsaW2xf7Hm3Ywfe3rSMC/bRske58IyC1M8Bc0Imuw+462fwmeqC4C
11-07 09:17:40.460 I/System.out( 6143):         Ql/3sJVNJE6a9rlwQPJBAVggmzvllUeL+5sqCf7b9kBB
11-07 09:17:40.460 I/System.out( 6143): X-Google-Smtp-Source: ABhQp+TgcdHfRLENPEK+QI7f1X4XeM/txRgvPvyDNYeWyZ4GsCa9FZjOv7w4GTXSHJgQeLPi39jeeVgcCAw7NUJAiW0=
11-07 09:17:40.460 I/System.out( 6143): X-Received: by 10.129.80.131 with SMTP id e125mr11931316ywb.20.1510064172968;
11-07 09:17:40.461 I/System.out( 6143):  Tue, 07 Nov 2017 06:16:12 -0800 (PST)
11-07 09:17:40.461 I/System.out( 6143): MIME-Version: 1.0
11-07 09:17:40.461 I/System.out( 6143): Received: by 10.37.130.79 with HTTP; Tue, 7 Nov 2017 06:16:11 -0800 (PST)
11-07 09:17:40.461 I/System.out( 6143): From: Denis Bondarenko <denbond7@gmail.com>
11-07 09:17:40.461 I/System.out( 6143): Date: Tue, 7 Nov 2017 16:16:11 +0200
11-07 09:17:40.461 I/System.out( 6143): Message-ID: <CALvPciV9+VYW-g0vMRfjCPk7-Msc_fni6Rsw12yix0frLZ_ymQ@mail.gmail.com>
11-07 09:17:40.461 I/System.out( 6143): Subject: Email from Tom
11-07 09:17:40.461 I/System.out( 6143): To: denbond7test@gmail.com
11-07 09:17:40.461 I/System.out( 6143): Content-Type: text/plain; charset="UTF-8"
11-07 09:17:40.461 I/System.out( 6143): -----BEGIN PGP MESSAGE-----
11-07 09:17:40.461 I/System.out( 6143): Version: FlowCrypt 5.0.4 Gmail Encryption flowcrypt.com
11-07 09:17:40.461 I/System.out( 6143): Comment: Seamlessly send, receive and search encrypted email
11-07 09:17:40.461 I/System.out( 6143): wcFMAzBfgamu0SA1ARAAjv9kn/8Ie3bxzKVu76urpVYHa+85FF4AN2qBb8JI
11-07 09:17:40.461 I/System.out( 6143): KJ25KGR2GOYqk8WpDEH8ku7Gl6AsvbGl0QmwfFI78V5p7nSNBY0f4at0A2JY
11-07 09:17:40.461 I/System.out( 6143): 0Y/0Pv+uSJ/bNrdI4412JgSUGCwt1RieMoOzmB0JfHKedpubNXoALtEhcsCx
11-07 09:17:40.461 I/System.out( 6143): YCAun5W0eha8nQLVyIPVdDkapxFBdjO94FQI/oe0OZvRuWV7wjgi2k1/0Eo3
11-07 09:17:40.461 I/System.out( 6143): inu+0/O5cHlAwaJF1XCWLI29PWutpTwAfKdQReS9lrxBT1XEq6OdzBxH4Eka
11-07 09:17:40.461 I/System.out( 6143): ZHOq/DQrvmHrzyyZUelHFv0q7seDb0N0LuiV24b4hRJWeJ81+QLD8mVqw5rC
11-07 09:17:40.461 I/System.out( 6143): Zpj2jaOWyqBEJEuYY3mKCA9Q9Sp3PwVk4CoGastL4BjtoLlViFT5vEno8wYa
11-07 09:17:40.461 I/System.out( 6143): gOATqxRiFQ+/cBOxWCZDJZsOY3UZu9/8NzPSdWjRBaD5n8LEZ112w+BHmp3h
11-07 09:17:40.461 I/System.out( 6143): bOAc0Nl6v/M2y9z948tzZ5Z4s/Wug1b5uGWQeF4nSYiOBnsrVXdVJ8E3OMf2
11-07 09:17:40.461 I/System.out( 6143): v3HwVQsOuoiEfU9H2yj7vw87R6EPX2eGCZZjkhwUV0pJiRod0QJpItFEES9E
11-07 09:17:40.461 I/System.out( 6143): dUPEfArKLKRhcv+zqgTMQdxBTVrErf16nDmm/yZHqFzelroZmDhzvkER+U2M
11-07 09:17:40.461 I/System.out( 6143): aAOVtununvz69Ln7Q0EIwFCCKreD2wwGPePfX+T2q07BwUwDkqT4n6mgiEUB
11-07 09:17:40.461 I/System.out( 6143): D/99ha01PW7Na0qYhZs7yXUraCH0PZ+zO/nKZiFELPDKvvIrlXCMe1jp2/8V
11-07 09:17:40.461 I/System.out( 6143): +FOgeHj6HATuLyK8qlbyiDSN8lVY8Z1I+DrEn3IS0efioShme5UgI6vkRmT2
11-07 09:17:40.461 I/System.out( 6143): 93lF6QmHj5kGVWIuxEoF4FTxDyA+vuWZhNipFLuxqrXSpfP8wCaewQTxl8r/
11-07 09:17:40.461 I/System.out( 6143): czKeTk84ht9/GlFldr24mwZi3fVTciph8JKHZmTIpFfKURGeDRhs1u11vPiX
11-07 09:17:40.461 I/System.out( 6143): lDcRuxbHeSjJE6pbKDj8YpdCmnDg/bNCiMY55DvyB07pXZJOmxMWoddYNGvq
11-07 09:17:40.462 I/System.out( 6143): QvhX59yfQQlnDT2AUf21f1Wcpe90pJ1K6PTielQMh5rUkgU/PzTo4a+8/6X2
11-07 09:17:40.462 I/System.out( 6143): Fei1BKVLhL7NOTxo7DTnCb+4PnhDx/RG/x4dzhuyzdUYWUQc3qe9R0/ExXWr
11-07 09:17:40.462 I/System.out( 6143): dLe9vEsUUm+G4RRdjSYgiO7+i2cUMGVAPWUux2A42HDETbWbi3KyEJusR5Eb
11-07 09:17:40.462 I/System.out( 6143): 7Mb5D6kycSwZc6DmDO8ZzXD3AHNqK3sF09bSiPzGomPlLrTBv8mdwcAsFT+m
11-07 09:17:40.462 I/System.out( 6143): TJCBWCWxYmqeKkqGWen4x0Cg7vH5BvbYPYZbIqbRJYrlhj+Gdyqxlqsy16f1
11-07 09:17:40.462 I/System.out( 6143): lAfWOufKQcQaShY6cBLehjQZf/8I7zqTMgmRgOBhyArpQhlfURVu7Zcoy1ET
11-07 09:17:40.462 I/System.out( 6143): 0mUyLOUqvGM6ptDx7QC5pEp2GNJxAXHfi7/Rsyy3W9Ps9oQDni30mtMH0pba
11-07 09:17:40.462 I/System.out( 6143): LFIB3L5q7Qnll+0lDKaWJkiFFUdsCPN0lLAYF8kUTZRLB0atqj/R80VbS9Jw
11-07 09:17:40.462 I/System.out( 6143): 3sDj1etjos1N7WoMxB//c+fgWZxQIWoIeof61lv7yVU5d9RSpJc5cTvX6YE=
11-07 09:17:40.462 I/System.out( 6143): =+5TT
11-07 09:17:40.462 I/System.out( 6143): -----END PGP MESSAGE-----
11-07 09:17:40.462 I/System.out( 6143): )
11-07 09:17:40.462 I/System.out( 6143): A34 OK Success
11-07 09:17:40.463 I/System.out( 6143): A35 STORE 107 +FLAGS (\Seen)
11-07 09:17:40.498 V/FragmentManager( 6143): movefrom STARTED: EmailListFragment{303dcbc #0 id=0x7f08006a}
11-07 09:17:40.498 V/FragmentManager( 6143): movefrom STARTED: zzdb{346e05 #1 SupportLifecycleFragmentImpl}
11-07 09:17:40.499 V/FragmentManager( 6143): movefrom STARTED: SupportRequestManagerFragment{7b865ac #2 com.bumptech.glide.manager}{parent=null}
11-07 09:17:40.499 D/MessageDetailsActivity( 6143): onStop
11-07 09:17:40.500 V/FragmentManager( 6143): movefrom STOPPED: EmailListFragment{303dcbc #0 id=0x7f08006a}
11-07 09:17:40.500 V/FragmentManager( 6143): movefrom STOPPED: zzdb{346e05 #1 SupportLifecycleFragmentImpl}
11-07 09:17:40.500 V/FragmentManager( 6143): movefrom STOPPED: SupportRequestManagerFragment{7b865ac #2 com.bumptech.glide.manager}{parent=null}
11-07 09:17:40.637 I/System.out( 6143): A35 OK Success
11-07 09:17:40.638 I/System.out( 6143): A36 LIST INBOX ""
11-07 09:17:40.807 I/System.out( 6143): * LIST (\Noselect) "/" "/"
11-07 09:17:40.807 I/System.out( 6143): A36 OK Success
11-07 09:17:40.807 I/System.out( 6143): A37 LIST "" INBOX
11-07 09:17:40.977 I/System.out( 6143): * LIST (\HasNoChildren) "/" "INBOX"
11-07 09:17:40.977 I/System.out( 6143): A37 OK Success
11-07 09:17:40.982 I/System.out( 6143): A38 UNSELECT
11-07 09:17:41.152 I/System.out( 6143): A38 OK Returned to authenticated state. (Success)
11-07 09:17:41.152 I/System.out( 6143): DEBUG GIMAPS: added an Authenticated connection -- size: 1
11-07 09:17:41.152 D/SyncTaskRunnable( 6143): The task = LoadMessageDetailsSyncTask completed
11-07 09:17:41.152 D/SyncTaskRunnable( 6143): SyncTaskBlockingQueue size = 0
11-07 09:17:43.989 V/FragmentManager( 6143): movefrom RESUMED: MessageDetailsFragment{275e4a2 #0 id=0x7f0800dc}
11-07 09:17:44.006 D/ImportPrivateKeyActivity( 6143): onCreate
11-07 09:17:44.018 D/ImportPrivateKeyActivity( 6143): onStart
11-07 09:17:44.019 D/ImportPrivateKeyActivity( 6143): onResume
11-07 09:17:44.146 E/EGL_emulation( 6143): tid 6199: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
11-07 09:17:44.146 W/OpenGLRenderer( 6143): Failed to set EGL_SWAP_BEHAVIOR on surface 0xc324fe20, error=EGL_BAD_MATCH
11-07 09:17:44.147 D/CheckClipboardToFindPrivateKeyService( 6143): onCreate
11-07 09:17:44.150 D/CheckClipboardToFindPrivateKeyService( 6143): onBind:Intent { cmp=com.flowcrypt.email.debug/com.flowcrypt.email.service.CheckClipboardToFindPrivateKeyService }
11-07 09:17:44.462 D/OpenGLRenderer( 6143): endAllActiveAnimators on 0xc52b3f80 (RippleDrawable) with handle 0xc55b3ff0
11-07 09:17:44.582 E/ACRA    ( 6143): ACRA caught a V8ScriptExecutionException for com.flowcrypt.email.debug
11-07 09:17:44.582 E/ACRA    ( 6143): undefined:23: Error: Invalid key: need at least key and user ID packet
11-07 09:17:44.582 E/ACRA    ( 6143):       throw e;
11-07 09:17:44.582 E/ACRA    ( 6143):       ^
11-07 09:17:44.582 E/ACRA    ( 6143): Error: Invalid key: need at least key and user ID packet
11-07 09:17:44.582 E/ACRA    ( 6143):     at new Key (<anonymous>:13173:11)
11-07 09:17:44.582 E/ACRA    ( 6143):     at Object.Key (<anonymous>:13163:12)
11-07 09:17:44.582 E/ACRA    ( 6143):     at Object.crypto_key_normalize [as normalize] (<anonymous>:1839:27)
11-07 09:17:44.582 E/ACRA    ( 6143): com.eclipsesource.v8.V8ScriptExecutionException
11-07 09:17:44.582 E/ACRA    ( 6143):   at com.eclipsesource.v8.V8._executeStringFunction(Native Method)
11-07 09:17:44.582 E/ACRA    ( 6143):   at com.eclipsesource.v8.V8.executeStringFunction(V8.java:1117)
11-07 09:17:44.582 E/ACRA    ( 6143):   at com.eclipsesource.v8.V8Object.executeStringFunction(V8Object.java:288)
11-07 09:17:44.582 E/ACRA    ( 6143):   at com.flowcrypt.email.js.Js.call(Js.java:268)
11-07 09:17:44.582 E/ACRA    ( 6143):   at com.flowcrypt.email.js.Js.call(Js.java:256)
11-07 09:17:44.582 E/ACRA    ( 6143):   at com.flowcrypt.email.js.Js.crypto_key_normalize(Js.java:122)
11-07 09:17:44.582 E/ACRA    ( 6143):   at com.flowcrypt.email.service.CheckClipboardToFindPrivateKeyService$ServiceWorkerHandler.handleMessage(CheckClipboardToFindPrivateKeyService.java:206)
11-07 09:17:44.582 E/ACRA    ( 6143):   at android.os.Handler.dispatchMessage(Handler.java:102)
11-07 09:17:44.582 E/ACRA    ( 6143):   at android.os.Looper.loop(Looper.java:154)
11-07 09:17:44.582 E/ACRA    ( 6143):   at android.os.HandlerThread.run(HandlerThread.java:61)


[ENVIRONMENT]
{"getDataSystemDirectory": "/data/system", "getDataPreloadsDirectory": "/data/preloads", "getOdmDirectory": "/odm", "getDataMiscDirectory": "/data/misc", "getDataSystemCeDirectory": "/data/system_ce", "getExpandDirectory": "/mnt/expand", "getRootDirectory": "/system", "getLegacyExternalStorageDirectory": "/sdcard", "getDataPreloadsAppsDirectory": "/data/preloads/apps", "getDataPreloadsDemoDirectory": "/data/preloads/demo", "getDataPreloadsMediaDirectory": "/data/preloads/media", "isExternalStorageEmulated": true, "isExternalStorageRemovable": false, "getDownloadCacheDirectory": "/cache", "getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getExternalStorageState": "mounted", "getStorageDirectory": "/storage", "getExternalStorageDirectory": "/storage/emulated/0", "getOemDirectory": "/oem", "getDataDirectory": "/data", "getDataSystemDeDirectory": "/data/system_de"}


[TOTAL_MEM_SIZE]
13375950848


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 7, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 270, "screenWidthDp": 411, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 512, "fontScale": 1, "smallestScreenWidthDp": 411, "densityDpi": 420, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 659, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_NO", "navigation": "NAVIGATION_DPAD"}


[DISPLAY]
{"0": {"refreshRate": 60.000003814697266, "metrics": {"density": 2.625, "scaledDensity": "x2.625", "xdpi": 420, "widthPixels": 1080, "heightPixels": 1794, "densityDpi": 420, "ydpi": 420}, "name": "Built-in Screen", "realSize": [1080, 1920], "isValid": true, "currentSizeRange": {"smallest": [1080, 1017], "largest": [1794, 1731]}, "rectSize": [0, 0, 1080, 1794], "height": 1794, "realMetrics": {"density": 2.625, "scaledDensity": "x2.625", "xdpi": 420, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 420, "ydpi": 420}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 1794], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
9880330240


[PHONE_MODEL]
Google Nexus 5X - 7.1.0 - API 25 - 1080x1920


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 7, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 270, "screenWidthDp": 411, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 512, "fontScale": 1, "smallestScreenWidthDp": 411, "densityDpi": 420, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 659, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_NO", "navigation": "NAVIGATION_DPAD"}


[DEVICE_FEATURES]
{"android.software.input_methods": true, "android.software.managed_users": true, "android.hardware.faketouch": true, "android.software.backup": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "android.software.live_wallpaper": true, "android.hardware.sensor.accelerometer": true, "android.hardware.telephony": true, "android.hardware.telephony.gsm": true, "com.google.android.feature.EXCHANGE_6_2": true, "android.hardware.location.gps": true, "android.hardware.usb.accessory": true, "android.software.webview": true, "android.software.sip.voip": true, "android.hardware.microphone": true, "android.hardware.location.network": true, "android.hardware.touchscreen.multitouch": true, "android.software.voice_recognizers": true, "android.hardware.touchscreen": true, "com.google.android.feature.GOOGLE_EXPERIENCE": true, "android.hardware.audio.output": true, "com.google.android.feature.GOOGLE_BUILD": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.software.sip": true, "android.hardware.camera.any": true, "android.hardware.camera": true, "android.hardware.wifi": true, "android.software.print": true, "android.software.home_screen": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.screen.portrait": true, "android.hardware.location": true, "android.software.device_admin": true, "glEsVersion": "2.0", "android.hardware.screen.landscape": true, "android.hardware.usb.host": true, "android.software.connectionservice": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email.debug", "VERSION_CODE": 20, "BUILD_TYPE": "debug", "DEBUG": true, "VERSION_NAME": "0.2.0_20__2017_11_07_16_16", "FLAVOR": ""}


[FILE_PATH]
/data/user/0/com.flowcrypt.email.debug/files


[INSTALLATION_ID]
8faa8daf-8649-4c02-9f5d-fb039d34a4e0


[USER_CRASH_DATE]
2017-11-07T09:17:44.607-05:00


[HASH]
2CCF058D1B


[APP_VERSION_NAME]
0.2.0_20__2017_11_07_16_16


[USER_APP_START_DATE]
2017-11-07T09:16:56.122-05:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "vbox86", "BOARD": "unknown", "MODEL": "Google Nexus 5X - 7.1.0 - API 25 - 1080x1920", "BOOTLOADER": "unknown", "DISPLAY": "vbox86p-userdebug 7.1.1 NMF26Q eng.genymo.20170320.224321 test-keys", "CPU_ABI2": "armeabi-v7a", "FINGERPRINT": "Android/vbox86p/vbox86p:7.1.1/NMF26Q/genymo03202243:userdebug/test-keys", "IS_EMULATOR": true, "TAGS": "test-keys", "HOST": "94993daba111", "VERSION": {"PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 25, "SDK_INT": 25, "INCREMENTAL": "eng.genymo.20170320.224321", "BASE_OS": "", "RELEASE": "7.1.1", "CODENAME": "REL", "SECURITY_PATCH": "2016-12-05", "ACTIVE_CODENAMES": [], "SDK": "25"}, "PERMISSIONS_REVIEW_REQUIRED": false, "DEVICE": "vbox86p", "SERIAL": "unknown", "ID": "NMF26Q", "MANUFACTURER": "Genymotion", "PRODUCT": "vbox86p", "SUPPORTED_ABIS": ["x86", "armeabi-v7a", "armeabi"], "IS_DEBUGGABLE": true, "SUPPORTED_64_BIT_ABIS": [], "RADIO": "unknown", "CPU_ABI": "x86", "TIME": 1490049801000, "SUPPORTED_32_BIT_ABIS": ["x86", "armeabi-v7a", "armeabi"], "TYPE": "userdebug", "BRAND": "Android", "USER": "genymotion"}


[DUMPSYS_MEMINFO]
Permission Denial: can't dump meminfo from from pid=6235, uid=10250 without permission android.permission.DUMP


[USER_EMAIL]
N/A


[REPORT_ID]
7e48f833-368d-404f-bec1-49089d8e1533


[PRODUCT]
vbox86p


[PACKAGE_NAME]
com.flowcrypt.email.debug


[BRAND]
Android


[ANDROID_VERSION]
7.1.1


[APP_VERSION_CODE]
20


[IS_SILENT]
false


[CUSTOM_DATA]
{}
```

**Comment by tomholub** [comment]
I'll look at that. What was in your clipboard?

**Comment by tomholub** [comment]
Ok, I'll look into it. Either way, the JavaScript should not be crashing on you, so we should catch this in JavaScript.

**Comment by tomholub** [comment]
Very weird. I will be doing some work on error handling.
