### ISSUE TITLE
NPE GeneralMessageDetails.getRawMessageWithoutAttachments()

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#150]
ref https://mail.google.com/mail/u/0/#inbox/15fb186fa3a55340

```
[STACK_TRACE]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.flowcrypt.email/com.flowcrypt.email.ui.activity.MessageDetailsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.model.GeneralMessageDetails.getRawMessageWithoutAttachments()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.model.GeneralMessageDetails.getRawMessageWithoutAttachments()' on a null object reference
        at com.flowcrypt.email.ui.activity.MessageDetailsActivity.onCreate(MessageDetailsActivity.java:83)
        at android.app.Activity.performCreate(Activity.java:5937)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
        ... 10 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.model.GeneralMessageDetails.getRawMessageWithoutAttachments()' on a null object reference
        at com.flowcrypt.email.ui.activity.MessageDetailsActivity.onCreate(MessageDetailsActivity.java:83)
        at android.app.Activity.performCreate(Activity.java:5937)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
        at android.app.ActivityThread.access$800(ActivityThread.java:144)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5221)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)



[LOGCAT]
--------- beginning of main
11-12 20:36:55.369 I/art     ( 3009): Background sticky concurrent mark sweep GC freed 6799(345KB) AllocSpace objects, 0(0B) LOS objects, 25% free, 849KB/1135KB, paused 5.746ms total 297.595ms
11-12 20:36:55.611 I/ACRA    ( 3009): Migrating unsent ACRA reports to new file locations
11-12 20:36:55.635 I/ACRA    ( 3009): Migrated 0 unsent reports
11-12 20:36:55.657 I/ACRA    ( 3009): Converting unsent ACRA reports to json
11-12 20:36:55.712 I/ACRA    ( 3009): Converted 0 unsent reports
11-12 20:36:55.716 I/ACRA    ( 3009): ACRA is enabled for com.flowcrypt.email, initializing...
11-12 20:36:55.955 I/art     ( 3009): Background partial concurrent mark sweep GC freed 2412(154KB) AllocSpace objects, 2(32KB) LOS objects, 52% free, 922KB/1946KB, paused 8.675ms total 230.019ms
11-12 20:36:57.741 W/art     ( 3009): Suspending all threads took: 41.007ms
11-12 20:36:57.769 I/art     ( 3009): Background sticky concurrent mark sweep GC freed 2435(295KB) AllocSpace objects, 1(16KB) LOS objects, 20% free, 1553KB/1946KB, paused 47.290ms total 165.165ms
11-12 20:36:58.781 W/GooglePlayServicesUtil( 3009): Google Play services out of date.  Requires 11400000 but found 8489230
11-12 20:36:58.829 I/art     ( 3009): Background sticky concurrent mark sweep GC freed 771(59KB) AllocSpace objects, 0(0B) LOS objects, 7% free, 1800KB/1946KB, paused 18.218ms total 109.896ms
11-12 20:36:59.515 I/art     ( 3009): Background partial concurrent mark sweep GC freed 1593(101KB) AllocSpace objects, 1(16KB) LOS objects, 39% free, 1779KB/2MB, paused 4.208ms total 139.796ms
11-12 20:37:00.947 I/Choreographer( 3009): Skipped 1038 frames!  The application may be doing too much work on its main thread.
11-12 20:37:01.044 D/gralloc_goldfish( 3009): Emulator without GPU emulation detected.
11-12 20:37:02.646 I/Choreographer( 3009): Skipped 875 frames!  The application may be doing too much work on its main thread.
11-12 20:37:03.752 I/Choreographer( 3009): Skipped 263 frames!  The application may be doing too much work on its main thread.
11-12 20:37:17.911 I/Choreographer( 3009): Skipped 33 frames!  The application may be doing too much work on its main thread.
11-12 20:37:18.162 I/Choreographer( 3009): Skipped 97 frames!  The application may be doing too much work on its main thread.
11-12 20:37:18.200 W/GooglePlayServicesUtil( 3009): Google Play services out of date.  Requires 11400000 but found 8489230
11-12 20:37:18.200 W/AutoManageHelper( 3009): Unresolved error while connecting client. Stopping auto-manage.
11-12 20:37:25.739 I/Choreographer( 3009): Skipped 71 frames!  The application may be doing too much work on its main thread.
11-12 20:37:53.411 I/Choreographer( 3009): Skipped 254 frames!  The application may be doing too much work on its main thread.
11-12 20:38:10.054 I/art     ( 3009): Background sticky concurrent mark sweep GC freed 5691(397KB) AllocSpace objects, 0(0B) LOS objects, 14% free, 2MB/2MB, paused 9.152ms total 205.888ms
11-12 20:38:10.816 D/AndroidRuntime( 3009): Shutting down VM
11-12 20:38:10.877 E/ACRA    ( 3009): ACRA caught a RuntimeException for com.flowcrypt.email
11-12 20:38:10.877 E/ACRA    ( 3009): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.flowcrypt.email/com.flowcrypt.email.ui.activity.EmailManagerActivity}: java.lang.IllegalArgumentException: You must pass an AccountDao to this activity.
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.app.ActivityThread.access$800(ActivityThread.java:144)
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.os.Handler.dispatchMessage(Handler.java:102)
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.os.Looper.loop(Looper.java:135)
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.app.ActivityThread.main(ActivityThread.java:5221)
11-12 20:38:10.877 E/ACRA    ( 3009):   at java.lang.reflect.Method.invoke(Native Method)
11-12 20:38:10.877 E/ACRA    ( 3009):   at java.lang.reflect.Method.invoke(Method.java:372)
11-12 20:38:10.877 E/ACRA    ( 3009):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
11-12 20:38:10.877 E/ACRA    ( 3009):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
11-12 20:38:10.877 E/ACRA    ( 3009): Caused by: java.lang.IllegalArgumentException: You must pass an AccountDao to this activity.
11-12 20:38:10.877 E/ACRA    ( 3009):   at com.flowcrypt.email.ui.activity.EmailManagerActivity.onCreate(EmailManagerActivity.java:117)
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.app.Activity.performCreate(Activity.java:5937)
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
11-12 20:38:10.877 E/ACRA    ( 3009):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
11-12 20:38:10.877 E/ACRA    ( 3009):   ... 10 more
11-12 20:38:10.988 I/art     ( 3009): Background sticky concurrent mark sweep GC freed 613(71KB) AllocSpace objects, 0(0B) LOS objects, 5% free, 2MB/2MB, paused 10.608ms total 125.970ms
11-12 20:38:11.465 I/art     ( 3009): Background partial concurrent mark sweep GC freed 1474(110KB) AllocSpace objects, 0(0B) LOS objects, 40% free, 2MB/4MB, paused 2.357ms total 413.646ms
11-12 20:38:17.056 I/Process ( 3009): Sending signal. PID: 3009 SIG: 9
--------- beginning of system
11-12 20:38:17.690 W/Zygote  ( 3254): Slow operation: 1105ms so far, now at Zygote.postForkCommon
11-12 20:38:17.691 W/Zygote  ( 3254): Slow operation: 1189ms so far, now at zygoteConnection.runOnce: postForkAndSpecialize
11-12 20:38:21.095 I/ACRA    ( 3254): Sending report /data/data/com.flowcrypt.email/app_ACRA-approved/2017-11-12T20:38:12.240+02:00-IS_SILENT.stacktrace
11-12 20:38:25.428 I/ACRA    ( 3254): Request received by server
11-12 20:38:39.442 I/art     ( 3336): Background sticky concurrent mark sweep GC freed 6459(330KB) AllocSpace objects, 0(0B) LOS objects, 25% free, 851KB/1135KB, paused 2.287ms total 190.813ms
11-12 20:38:39.556 I/ACRA    ( 3336): ACRA is enabled for com.flowcrypt.email, initializing...
11-12 20:38:39.736 I/art     ( 3336): Background partial concurrent mark sweep GC freed 2626(164KB) AllocSpace objects, 3(48KB) LOS objects, 53% free, 875KB/1899KB, paused 10.783ms total 168.006ms
11-12 20:38:41.561 W/art     ( 3336): Suspending all threads took: 19.852ms
11-12 20:38:41.629 I/art     ( 3336): Background sticky concurrent mark sweep GC freed 2383(270KB) AllocSpace objects, 0(0B) LOS objects, 24% free, 1437KB/1899KB, paused 26.660ms total 487.808ms
11-12 20:38:43.118 I/art     ( 3336): Background partial concurrent mark sweep GC freed 978(89KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 1614KB/2MB, paused 5.747ms total 763.780ms
11-12 20:38:43.391 D/AndroidRuntime( 3336): Shutting down VM
11-12 20:38:43.412 E/ACRA    ( 3336): ACRA caught a RuntimeException for com.flowcrypt.email
11-12 20:38:43.412 E/ACRA    ( 3336): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.flowcrypt.email/com.flowcrypt.email.ui.activity.MessageDetailsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.model.GeneralMessageDetails.getRawMessageWithoutAttachments()' on a null object reference
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.app.ActivityThread.access$800(ActivityThread.java:144)
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.os.Handler.dispatchMessage(Handler.java:102)
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.os.Looper.loop(Looper.java:135)
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.app.ActivityThread.main(ActivityThread.java:5221)
11-12 20:38:43.412 E/ACRA    ( 3336):   at java.lang.reflect.Method.invoke(Native Method)
11-12 20:38:43.412 E/ACRA    ( 3336):   at java.lang.reflect.Method.invoke(Method.java:372)
11-12 20:38:43.412 E/ACRA    ( 3336):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
11-12 20:38:43.412 E/ACRA    ( 3336):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
11-12 20:38:43.412 E/ACRA    ( 3336): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.model.GeneralMessageDetails.getRawMessageWithoutAttachments()' on a null object reference
11-12 20:38:43.412 E/ACRA    ( 3336):   at com.flowcrypt.email.ui.activity.MessageDetailsActivity.onCreate(MessageDetailsActivity.java:83)
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.app.Activity.performCreate(Activity.java:5937)
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
11-12 20:38:43.412 E/ACRA    ( 3336):   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
11-12 20:38:43.412 E/ACRA    ( 3336):   ... 10 more


[ENVIRONMENT]
{"isEncryptedFilesystemEnabled": false, "getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/storage/sdcard/Android/obb", "getLegacyExternalStorageDirectory": "/storage/sdcard", "getSecureDataDirectory": "/data", "getExternalStorageState": "mounted", "getSystemSecureDirectory": "/data/system", "getMediaStorageDirectory": "/data/media", "getOemDirectory": "/oem", "getExternalStorageDirectory": "/storage/sdcard", "isExternalStorageEmulated": false, "getDataDirectory": "/data", "isExternalStorageRemovable": false, "getRootDirectory": "/system", "getDownloadCacheDirectory": "/cache", "getEmulatedStorageObbSource": "obb"}


[TOTAL_MEM_SIZE]
567640064


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 5, "locale": "en_US", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 101, "screenWidthDp": 320, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR", "compatScreenHeightDp": 455, "fontScale": 1, "smallestScreenWidthDp": 320, "densityDpi": 160, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 226, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 455, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_NO", "navigation": "NAVIGATION_TRACKBALL"}


[DISPLAY]
{"0": {"refreshRate": 651.041259765625, "metrics": {"density": 1, "scaledDensity": "x1.0", "xdpi": 160, "widthPixels": 320, "heightPixels": 480, "densityDpi": 160, "ydpi": 160}, "name": "Built-in Screen", "realSize": [320, 480], "isValid": true, "currentSizeRange": {"smallest": [320, 295], "largest": [480, 455]}, "rectSize": [0, 0, 320, 480], "height": 480, "realMetrics": {"density": 1, "scaledDensity": "x1.0", "xdpi": 160, "widthPixels": 320, "heightPixels": 480, "densityDpi": 160, "ydpi": 160}, "width": 320, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [320, 480], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
231141376


[PHONE_MODEL]
XT320


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 5, "locale": "en_US", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 101, "screenWidthDp": 320, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR", "compatScreenHeightDp": 455, "fontScale": 1, "smallestScreenWidthDp": 320, "densityDpi": 160, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 226, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 455, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_NO", "navigation": "NAVIGATION_TRACKBALL"}


[DEVICE_FEATURES]
{"android.software.input_methods": true, "android.software.managed_users": true, "android.hardware.faketouch": true, "android.software.backup": true, "android.software.app_widgets": true, "android.software.live_wallpaper": true, "android.hardware.usb.accessory": true, "android.software.webview": true, "android.hardware.microphone": true, "android.hardware.bluetooth": true, "android.hardware.location.network": true, "android.hardware.touchscreen.multitouch": true, "android.software.voice_recognizers": true, "android.hardware.touchscreen": true, "android.hardware.audio.output": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.hardware.screen.portrait": true, "android.hardware.camera.any": true, "android.hardware.sensor.compass": true, "android.hardware.camera": true, "android.software.device_admin": true, "android.software.print": true, "android.software.home_screen": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.camera.autofocus": true, "android.hardware.location": true, "android.hardware.sensor.accelerometer": true, "glEsVersion": "0.0", "android.hardware.screen.landscape": true, "android.software.connectionservice": true}


[BUILD_CONFIG]
{"FLAVOR": "", "APPLICATION_ID": "com.flowcrypt.email", "VERSION_CODE": 30, "DEBUG": false, "VERSION_NAME": "0.3.0", "BUILD_TYPE": "release"}


[FILE_PATH]
/data/data/com.flowcrypt.email/files


[INSTALLATION_ID]
03e74520-8cf7-4fcf-b9f1-918236ceb14a


[USER_CRASH_DATE]
2017-11-12T20:38:44.460+02:00


[HASH]
2ECDA250C5


[APP_VERSION_NAME]
0.3.0


[USER_APP_START_DATE]
2017-11-12T20:38:39.697+02:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "goldfish", "BOARD": "unknown", "MODEL": "XT320", "BOOTLOADER": "unknown", "DISPLAY": "cst_mob-eng 5.0.2 XCOMEW 2.6.39+EXALT rtl", "CPU_ABI2": "armeabi", "FINGERPRINT": "generic/Batwing/generic:5.0.2/XCOMEW/2.6.39+EXALT:eng/rtl", "TAGS": "rtl", "IS_DEBUGGABLE": true, "VERSION": {"RESOURCES_SDK_INT": 21, "SDK_INT": 21, "INCREMENTAL": "2.6.39+EXALT", "RELEASE": "5.0.2", "CODENAME": "REL", "ACTIVE_CODENAMES": [], "SDK": "21"}, "DEVICE": "generic", "SERIAL": "unknown", "ID": "XCOMEW", "MANUFACTURER": "Batmobile", "PRODUCT": "Batwing", "BRAND": "generic", "HOST": "tnbst", "SUPPORTED_64_BIT_ABIS": [], "RADIO": "unknown", "CPU_ABI": "armeabi-v7a", "TIME": 1469055951000, "SUPPORTED_32_BIT_ABIS": ["armeabi-v7a", "armeabi"], "TYPE": "eng", "SUPPORTED_ABIS": ["armeabi-v7a", "armeabi"], "USER": "blder"}


[DUMPSYS_MEMINFO]
Permission Denial: can't dump meminfo from from pid=3368, uid=10059 without permission android.permission.DUMP


[USER_EMAIL]
N/A


[REPORT_ID]
a73318db-85a5-49cd-bee0-6bdc75fed67f


[PRODUCT]
Batwing


[PACKAGE_NAME]
com.flowcrypt.email


[BRAND]
generic


[ANDROID_VERSION]
5.0.2


[APP_VERSION_CODE]
30


[IS_SILENT]
false


[CUSTOM_DATA]
{}
```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#inbox/15fd02901db0a90a
