### ISSUE TITLE
NPE: Sending email with two small attachments

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#153]
Happened to me just now
```
[STACK_TRACE]
java.lang.Exception: EmailSyncService.onError
        at com.flowcrypt.email.service.EmailSyncService.onError(EmailSyncService.java:345)
        at com.flowcrypt.email.api.email.sync.tasks.BaseSyncTask.handleException(BaseSyncTask.java:80)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.handleException(SendMessageSyncTask.java:72)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$SyncTaskRunnable.run(EmailSyncManager.java:365)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.runSMTPAction(SendMessageSyncTask.java:127)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$SyncTaskRunnable.run(EmailSyncManager.java:358)
        ... 5 more
java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.runSMTPAction(SendMessageSyncTask.java:127)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$SyncTaskRunnable.run(EmailSyncManager.java:358)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)



[LOGCAT]
11-16 22:48:47.661 W/System.err(20484):         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
11-16 22:48:47.661 W/System.err(20484):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-16 22:48:47.661 W/System.err(20484):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-16 22:48:47.662 W/System.err(20484):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-16 22:48:47.662 W/System.err(20484):         at java.lang.Thread.run(Thread.java:761)
11-16 22:48:48.077 I/ACRA    (21305): Sending report /data/user/0/com.flowcrypt.email/app_ACRA-approved/2017-11-16T22:48:47.771-06:00-IS_SILENT.stacktrace
11-16 22:48:48.095 D/NetworkSecurityConfig(21305): No Network Security Config specified, using platform default
11-16 22:48:49.306 I/ACRA    (21305): Request received by server
11-16 22:48:56.709 D/OpenGLRenderer(20484): endAllActiveAnimators on 0x93123480 (RippleDrawable) with handle 0x94637e60
11-16 22:48:56.716 W/IInputConnectionWrapper(20484): reportFullscreenMode on inexistent InputConnection
--------- beginning of system
11-16 22:49:40.894 W/ViewRootImpl[CreateMessageActivity](20484): Dropping event due to no window focus: KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=53772946, downTime=53772946, deviceId=-1, source=0x101 }
11-16 22:49:44.530 D/OpenGLRenderer(20484): endAllActiveAnimators on 0x941e2580 (MenuPopupWindow$MenuDropDownListView) with handle 0x94637e70
11-16 22:49:49.796 E/SQLiteDatabase(20484): Error inserting fingerprint=null client=null email=human@flowcrypt.com name=Human at FlowCrypt has_pgp=true last_use=0 long_id=null keywords=null public_key=-----BEGIN PGP PUBLIC KEY BLOCK-----
11-16 22:49:49.796 E/SQLiteDatabase(20484): Version: FlowCrypt Android 0.3.1 Email Encryption: flowcrypt.com
11-16 22:49:49.796 E/SQLiteDatabase(20484): Comment: Seamlessly send, receive and search encrypted email
11-16 22:49:49.796 E/SQLiteDatabase(20484):
11-16 22:49:49.796 E/SQLiteDatabase(20484): xsFNBFn7XPcBEAC4vqCA+3+voI35TvvrUZqMclLV9NFcgx0fyT+YXpMjbUZR
11-16 22:49:49.796 E/SQLiteDatabase(20484): d0+LFB+4took74VLlHIkyTGO8mqleXdT+2/8v+TWAeIYYii7eVWRWwxn2sfM
11-16 22:49:49.796 E/SQLiteDatabase(20484): SqeEEKsgQv2whosQRrWdE7DrT6O1VxOvBxN5ZVx7iBBglruqCCpHP3zPgQw1
11-16 22:49:49.796 E/SQLiteDatabase(20484): mwdFtJHIS3tFwQ66ojvcbWznX/yr3qRG1zUzTrvf1kSWr5ZRBRb7Ti8FF9Wa
11-16 22:49:49.796 E/SQLiteDatabase(20484): 70RraxF2wBa2LNwO1AwUvpTl1el3Fm9tUQnPAcw53R+HdZzxYjvyhHoJYJu1
11-16 22:49:49.796 E/SQLiteDatabase(20484): 07NKgTmwkDyLcxm7MRJKh9SOSjrFAA2cgp0W4SSCYUpVyCqUclYRv09XXg0S
11-16 22:49:49.796 E/SQLiteDatabase(20484): 2zXHJLlLJ8cSlM6jsZnq7jUUVqgbts3gmusGHjkuMMYbj3L6U+/gAHQ0kjAc
11-16 22:49:49.796 E/SQLiteDatabase(20484): z1Zfh0CWKz2C0aLyl4pxRQh9XUwCAUdR8Hcz9i4TfAFpVCAicCXR+2wWcy1z
11-16 22:49:49.796 E/SQLiteDatabase(20484): zKmtRuqmWi2WdgJpC3hr774QeXZQ4m7jMiR6fwCRz0tb7OYMVdFB9UShWcpv
11-16 22:49:49.796 E/SQLiteDatabase(20484): Aq6DPsjTfMz6NWJ1izi8umy2wDhvncTa4nVi12TQORSNVnsMGZiJkl0GZbsn
11-16 22:49:49.796 E/SQLiteDatabase(20484): YXugPrnCirtZlGuCoIwI4iVFIbn6B7hZ+7+FXN/7Jtc1pvGb0GBtJWZR95wL
11-16 22:49:49.796 E/SQLiteDatabase(20484): fFSAFwRSc0zkPfYGjQCDjrKl5n/tJIKqv0botQARAQABzShIdW1hbiBhdCBG
11-16 22:49:49.796 E/SQLiteDatabase(20484): bG93Q3J5cHQgPGh1bWFuQGZsb3djcnlwdC5jb20+wsF1BBABCAApBQJZ+1z5
11-16 22:49:49.796 E/SQLiteDatabase(20484): BgsJBwgDAgkQDJwuak0nPG8EFQgKAgMWAgECGQECGwMCHgEAAO/jD/4uSXmN
11-16 22:49:49.796 E/SQLiteDatabase(20484): sKOl3siImBGOc/KjxcZ0iz8Suj4ERyqSZFK+9EtREuWhgzghtSrfwNM54ym+
11-16 22:49:49.796 E/SQLiteDatabase(20484): t6uvea6BNDLk3kouyKz20pFIyGHrBVyLdnP2qcRMbo1bSyS8KLXojzI6NgW5
11-16 22:49:49.796 E/SQLiteDatabase(20484): JnKEbmz8a8pZ8J7YETi0rKn3LALOSXgvlGsblemC+WcNdT1opCGAw7pwh/l3
11-16 22:49:49.796 E/SQLiteDatabase(20484): RHfyyrmOcL5ufR2GWPITRCrb1Ib+MBibs7mwtHNkcHd06EPGHdkTK6/Sg738
11-16 22:49:49.796 E/SQLiteDatabase(20484): 1C3eDgcEnRetQbcGJJqHhg/9sMzCwlD81x9VhSZm01U/2+tDELT2DP6FP5BY
11-16 22:49:49.796 E/SQLiteDatabase(20484): +13rIYuodyLDOMj8onu9vOI4HkQdhnQ7fqnkTh6RMCD4cSdWMrEZzWkJ1rEh
11-16 22:49:49.796 E/SQLiteDatabase(20484): an0pnWVsueGvtEwVUKhX7VDOW+tdBwjcNm2nNMQqFtwAtpagoUHScHtGnEMg
11-16 22:49:49.796 E/SQLiteDatabase(20484): TM+adzBgDNqjMPslKRmpASsBLuH8vTsqPOW/S1OM9QJxjoP1VDAC4P6KQmbj
11-16 22:49:49.796 E/SQLiteDatabase(20484): mht51A5TTNMOIi0XIe1xt6aghaIGvlgpKFZPy+5+bcmQDp7/Wxo4YOeXKXBa
11-16 22:49:49.796 E/SQLiteDatabase(20484): 2hUMLl0R4WellL3zsB9CREz1Dr9M20VfBUeYBttNh7rNK9ZhSUEtVzbTIlm9
11-16 22:49:49.796 E/SQLiteDatabase(20484): V40Qw4eP6emXsvX0qbJpEwTRJg6DfzvDVYZ0NO1cUuPsZT420YGNTPR0tKX1
11-16 22:49:49.796 E/SQLiteDatabase(20484): 1axxiyj1uErYWZLbwM7BTQRZ+1z3ARAAyweJ6JULSa2ToqNRHDbLCVf7auho
11-16 22:49:49.796 E/SQLiteDatabase(20484): 2EebZcZifKEz5Sbxd5I8cVne7v3rl4is32VfENtO2swefq3K5U+U8BKudUPT
11-16 22:49:49.796 E/SQLiteDatabase(20484): Dn96kh7t8ojxT7waGmTPi8WpxuvLZPIMsoatmkNv1I5KRt5IAWDGAlQA8FaM
11-16 22:49:49.796 E/SQLiteDatabase(20484): L0x3h4Rghxx09QxHQT0ogjrUckApkbU7afFpdWZXxFOem3UOodZQiqPsQVSA
11-16 22:49:49.796 E/SQLiteDatabase(20484): e8kCjYtlNk3s+ZABcgFYeSIXXi9SuMy+Dxo4L1i4Zu5YGhbxjC6LgN1Xy41I
11-16 22:49:49.796 E/SQLiteDatabase(20484): 0mabhiF1XSlqe+vNG8fixi5R4vH3oFwVIDiEHPVM8YGyAsk/pBucIlfHcqyn
11-16 22:49:49.796 E/SQLiteDatabase(20484): Sw+8RqHzw63vP7zR30PgQpxG5kXU6u7ykLFNEs7JD8iL/3ycQ5SZ+LptCk+1
11-16 22:49:49.796 E/SQLiteDatabase(20484): TPMDGUNfG7qitJ19NhT9M29fA4qiVO/1S9X9T55YY7dfQlCY9FrtHX3L2pKU
11-16 22:49:49.796 E/SQLiteDatabase(20484): mUq3yYiksGtZ/p9LZZpVwl4sRW7W6Mp54/aL4yR5R4MJNZz2nJXR1S59iZWO
11-16 22:49:49.796 E/SQLiteDatabase(20484): +TrYgfeZPDoY8l6rK2QEPgu3rdBXQNGHSDuZZoSI3HAZZnh2QN+ECyg0q51F
11-16 22:49:49.796 E/SQLiteDatabase(20484): IJdBZwYquBSWNTgniqWcyHnumcqMMF3Cyv++QVrCikb+OUIYorMXh1aodQI2
11-16 22:49:49.796 E/SQLiteDatabase(20484): P01jJ67xseYKRZlaXRbhl8DRaQFtQR6s7INizyjVhi9ecz0AbfvjsJkAEQEA
11-16 22:49:49.796 E/SQLiteDatabase(20484): AcLBXwQYAQgAEwUCWftc+gkQDJwuak0nPG8CGwwAANffD/sFWMRhALoMyjj0
11-16 22:49:49.796 E/SQLiteDatabase(20484): hB1K3QeP6nklCdmXTtCbGIuQ9WHYUAeVxivZFqZXL/NKooIDOcVbd/zWPtPR
11-16 22:49:49.796 E/SQLiteDatabase(20484): hUWGB9rOgfqpOriQOLw9AA+AyzNGbnMrNNpXqsK49gQqXHL0O9UA8aZAa1gF
11-16 22:49:49.796 E/SQLiteDatabase(20484): kYY80jMSNoA/Kw0mtlv+t/5BrBt36O/+E1szhRciFEC64BY/sols6C8IojPq
11-16 22:49:49.796 E/SQLiteDatabase(20484): oso1PEI8bQNNmOz9P08qPSDHOWbo0Xhmqo/YYteV7pv3jnmY8RNzeK4QbZ0i
11-16 22:49:49.796 E/SQLiteDatabase(20484): tEdCryChtwwYTi2mb+G3KeSyl+qmY+Lh0xadv3M9iGlx3QBcEJ1gB1ZCBqYb
11-16 22:49:49.796 E/SQLiteDatabase(20484): vyKBm3rXZttXjSnYkWKZI4Lp7+KbhkuC3Er/OEv30xjl+YESMdeD53vERMUz
11-16 22:49:49.796 E/SQLiteDatabase(20484): 1mcwCtwtVU5KfmfMWf19ptjngIMudQ2W8o78qLMZx9UYRwynIHAOYK7lPjMI
11-16 22:49:49.796 E/SQLiteDatabase(20484): x67/ax4ig+Y9wIl0tAerE5eXQM+we6O+CGOV3M6re9Edslr2S6rmgkuWCwwz
11-16 22:49:49.796 E/SQLiteDatabase(20484): ZRhmASurbivJbPJYNyixT19QGZ1KPESJhr0JVOt26ip7qLcD5Rjlz0dVtpVb
11-16 22:49:49.796 E/SQLiteDatabase(20484): kwPxqjvOk1fBeDXaLr0hh77RiTsiLfoV8WOv4mKm1jsq0dIhyDqf9nezJb2T
11-16 22:49:49.796 E/SQLiteDatabase(20484): chhpDE9dq7dVfX2VHEKNwRyZwO6e/WQizIHIfcAi6K3aiO7MfzNpBzVpF3dv
11-16 22:49:49.796 E/SQLiteDatabase(20484): 0olhtO+rAg==
11-16 22:49:49.796 E/SQLiteDatabase(20484): =4TLm
11-16 22:49:49.796 E/SQLiteDatabase(20484): -----END PGP PUBLIC KEY BLOCK-----
11-16 22:49:49.796 E/SQLiteDatabase(20484):
11-16 22:49:49.796 E/SQLiteDatabase(20484):  attested=false
11-16 22:49:49.796 E/SQLiteDatabase(20484): android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: contacts.email (code 2067)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1472)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1343)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at com.flowcrypt.email.database.provider.SecurityContentProvider.insert(SecurityContentProvider.java:125)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at android.content.ContentProvider$Transport.insert(ContentProvider.java:264)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at android.content.ContentResolver.insert(ContentResolver.java:1274)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at com.flowcrypt.email.database.dao.source.ContactsDaoSource.addRow(ContactsDaoSource.java:103)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.getAccountPublicKey(SendMessageSyncTask.java:367)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.getPubKeys(SendMessageSyncTask.java:337)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.createMimeMessage(SendMessageSyncTask.java:200)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.runSMTPAction(SendMessageSyncTask.java:113)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at com.flowcrypt.email.api.email.sync.EmailSyncManager$SyncTaskRunnable.run(EmailSyncManager.java:358)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-16 22:49:49.796 E/SQLiteDatabase(20484):     at java.lang.Thread.run(Thread.java:761)
11-16 22:49:49.966 W/System.err(20484): java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
11-16 22:49:49.966 W/System.err(20484):         at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.runSMTPAction(SendMessageSyncTask.java:127)
11-16 22:49:49.966 W/System.err(20484):         at com.flowcrypt.email.api.email.sync.EmailSyncManager$SyncTaskRunnable.run(EmailSyncManager.java:358)
11-16 22:49:49.966 W/System.err(20484):         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
11-16 22:49:49.966 W/System.err(20484):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-16 22:49:49.966 W/System.err(20484):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-16 22:49:49.966 W/System.err(20484):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-16 22:49:49.966 W/System.err(20484):         at java.lang.Thread.run(Thread.java:761)


[ENVIRONMENT]
{"getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getLegacyExternalStorageDirectory": "/sdcard", "getDataSystemDirectory": "/data/system", "getDataMiscDirectory": "/data/misc", "getDataSystemCeDirectory": "/data/system_ce", "getExternalStorageState": "mounted", "getStorageDirectory": "/storage", "getExpandDirectory": "/mnt/expand", "getOemDirectory": "/oem", "getExternalStorageDirectory": "/storage/emulated/0", "isExternalStorageEmulated": true, "getDataDirectory": "/data", "isExternalStorageRemovable": false, "getDataSystemDeDirectory": "/data/system_de", "getOdmDirectory": "/odm", "getRootDirectory": "/system", "getDownloadCacheDirectory": "/cache"}


[TOTAL_MEM_SIZE]
11746017280


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 24, "locale": "en_US", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 260, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 504, "fontScale": 1, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 568, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DISPLAY]
{"0": {"refreshRate": 60, "metrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 403.4110107421875, "widthPixels": 1080, "heightPixels": 1776, "densityDpi": 480, "ydpi": 403.0409851074219}, "name": "Built-in Screen", "realSize": [1080, 1920], "isValid": true, "currentSizeRange": {"smallest": [1080, 1008], "largest": [1776, 1704]}, "rectSize": [0, 0, 1080, 1776], "height": 1776, "realMetrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 403.4110107421875, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 480, "ydpi": 403.0409851074219}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 1776], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
9350209536


[PHONE_MODEL]
Moto G (4)


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 24, "locale": "en_US", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 260, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 504, "fontScale": 1, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 568, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DEVICE_FEATURES]
{"com.google.preload_photos": true, "android.software.verified_boot": true, "com.motorola.software.storageoptimizer": true, "com.motorola.software.device.athene": true, "android.hardware.ethernet": true, "android.hardware.sensor.proximity": true, "android.software.input_methods": true, "com.motorola.software.fmradioservice": true, "com.motorola.easyprefix": true, "com.motorola.software.guideme": true, "android.software.device_admin": true, "android.hardware.faketouch": true, "android.software.backup": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "com.motorola.software.modality": true, "android.hardware.sensor.accelerometer": true, "com.motorola.hardware.tier.G": true, "com.motorola.actions": true, "com.motorola.software.x_line": true, "android.hardware.camera.flash": true, "android.hardware.sensor.light": true, "com.motorola.moto.MOTO_VOICE_DISABLED_4_3": true, "android.hardware.location.gps": true, "android.hardware.usb.accessory": true, "android.software.webview": true, "com.motorola.software.DirectedSMSProxy": true, "android.software.sip.voip": true, "android.hardware.microphone": true, "android.hardware.bluetooth": true, "android.hardware.location.network": true, "android.software.midi": true, "android.hardware.touchscreen.multitouch": true, "android.software.voice_recognizers": true, "android.hardware.touchscreen": true, "android.hardware.audio.output": true, "com.motorola.motodisplay.doze.glimpse": true, "android.hardware.bluetooth_le": true, "android.hardware.telephony": true, "android.hardware.sensor.stepcounter": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.hardware.sensor.gyroscope": true, "com.motorola.moto": true, "android.software.sip": true, "android.hardware.camera.autofocus": true, "android.software.live_wallpaper": true, "com.motorola.sensorhub.stml0xx": true, "android.hardware.camera.any": true, "android.hardware.telephony.gsm": true, "android.hardware.telephony.cdma": true, "android.hardware.camera": true, "com.motorola.hardware.wave.2016.1": true, "android.hardware.wifi": true, "android.software.print": true, "android.hardware.location": true, "android.software.home_screen": true, "com.motorola.cameraone": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.opengles.aep": true, "android.hardware.sensor.stepdetector": true, "android.hardware.usb.host": true, "android.hardware.screen.portrait": true, "android.software.managed_users": true, "com.motorola.software.product.athene_retail": true, "android.hardware.wifi.direct": true, "glEsVersion": "3.2", "android.hardware.screen.landscape": true, "com.motorola.msimsettings": true, "android.software.connectionservice": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email", "VERSION_CODE": 31, "BUILD_TYPE": "release", "DEBUG": false, "VERSION_NAME": "0.3.1", "FLAVOR": ""}


[FILE_PATH]
/data/user/0/com.flowcrypt.email/files


[INSTALLATION_ID]
3c057ef7-cdbb-4762-a988-39c2c89eca2a


[USER_CRASH_DATE]
2017-11-16T22:49:50.017-06:00


[HASH]
61931A33CB


[APP_VERSION_NAME]
0.3.1


[USER_APP_START_DATE]
2017-11-16T22:47:28.586-06:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "qcom", "BOARD": "msm8952", "MODEL": "Moto G (4)", "BOOTLOADER": "0xB106", "DISPLAY": "NPJ25.93-14.7", "CPU_ABI2": "armeabi", "FINGERPRINT": "motorola/athene/athene:7.0/NPJ25.93-14.7/7:user/release-keys", "IS_EMULATOR": false, "TAGS": "release-keys", "HOST": "ilclbld36", "VERSION": {"PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 24, "SDK_INT": 24, "INCREMENTAL": "7", "BASE_OS": "", "RELEASE": "7.0", "CODENAME": "REL", "SECURITY_PATCH": "2017-09-01", "ACTIVE_CODENAMES": [], "SDK": "24"}, "PERMISSIONS_REVIEW_REQUIRED": false, "DEVICE": "athene", "SERIAL": "ZY223GW7FS", "ID": "NPJ25.93-14.7", "MANUFACTURER": "motorola", "PRODUCT": "athene", "SUPPORTED_ABIS": ["armeabi-v7a", "armeabi"], "IS_DEBUGGABLE": false, "SUPPORTED_64_BIT_ABIS": [], "RADIO": "unknown", "CPU_ABI": "armeabi-v7a", "TIME": 1504111410000, "SUPPORTED_32_BIT_ABIS": ["armeabi-v7a", "armeabi"], "TYPE": "user", "BRAND": "motorola", "USER": "hudsoncm"}


[DUMPSYS_MEMINFO]



[USER_EMAIL]
N/A


[REPORT_ID]
92d6fb50-b77d-4660-a08f-478b7000ed77
```

**Comment by DenBond7** [comment]
I don't understand how it happened. The stack trace is not clear. 

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.runSMTPAction(SendMessageSyncTask.java:127)
at com.flowcrypt.email.api.email.sync.EmailSyncManager$SyncTaskRunnable.run(EmailSyncManager.java:358)
```
But I don't see the getBytes() call in my code.

![image](https://user-images.githubusercontent.com/2863246/33314357-0d2e63ea-d436-11e7-8d62-ed359c4ec4db.png)

**Comment by tomholub** [comment]
Tested again and it looks good. Not sure what happened there, maybe some old version.
