### ISSUE TITLE
Key has no suitable encryption subkeys.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1590]
```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
com.flowcrypt.email.util.exception.ForceHandlingException: java.lang.IllegalArgumentException: Key has no suitable encryption subkeys.
java.lang.IllegalArgumentException: Key has no suitable encryption subkeys.


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.kt:157)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
Caused by: com.flowcrypt.email.util.exception.ForceHandlingException: java.lang.IllegalArgumentException: Key has no suitable encryption subkeys.
        ... 8 more
Caused by: java.lang.IllegalArgumentException: Key has no suitable encryption subkeys.
        at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:195)
        at org.pgpainless.encryption_signing.EncryptionOptions.addRecipient(EncryptionOptions.java:176)
        at com.flowcrypt.email.example.file.PgpEncrypt.encryptAndOrSign(PgpEncrypt.kt:97)
        at com.flowcrypt.email.example.file.PgpEncrypt.encryptAndOrSign(PgpEncrypt.kt:75)
        at com.flowcrypt.email.example.file.PgpEncrypt.encryptAndOrSignMsg(PgpEncrypt.kt:38)
        at com.flowcrypt.email.api.email.EmailUtil$Companion.prepareMsgContent(EmailUtil.kt:1140)
        at com.flowcrypt.email.api.email.EmailUtil$Companion.prepareNewMsg(EmailUtil.kt:1061)
        at com.flowcrypt.email.api.email.EmailUtil$Companion.genMessage(EmailUtil.kt:701)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.kt:104)
        ... 7 more



[ANDROID_VERSION]
11
```

**Comment by DenBond7** [comment]
https://github.com/pgpainless/pgpainless/issues/223

**Comment by DenBond7** [comment]
gpg --default-new-key-algo rsa3072 --gen-key

**Comment by DenBond7** [comment]
no_encryption_subkeys@flowcrypt.test

```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGGoseUBDAC+rKhZ8nrDsrKDRh3RfSPywgPk8hnOFPioamZFrn/cySgXAh82
9gWewD0YezSlnOFd15rf86UovHo0Sk5pVyaeAV04s8Nfc2sZZZDayFr232/mcK6L
IM9I5UxirEzSFSHPdV+zCjr9v/6Yn5m0agc16g6McmHGmSnOLyMjy9Hg9gUCGpMg
ZYXSab8NGEaYy6Z5ChaBjS/l5ZyezBU55/+7cHkIAHYUxmDdY1po+y2U5CTna/Ab
XDnlXCfhtnTDpKI8q72DDINgF9qEyJzWOX3uiwoyWnLUpzmeFGWPR0UsbP4e3UdJ
rqNzbFXNLNJSN/EQ/2TGs1wbyQ20csUoEiuA+Y14vn+Kc1zjo4YRIB861pf7yude
BsNOCy+37Jad71DL7FLYsBp7/fhG8u+9JCA1evDBh7FvXJKma/1tJkD92lWXWVUc
qRRZdO84AQXpgXEsJX7DCwlNy/bBmwDXgK8pdIWfDEcB417eMxC3QiehzIVjsg2Z
DeqgGVBqBZ/4GEcAEQEAAbQkbm9fZW5jcnlwdGlvbl9zdWJrZXlzQGZsb3djcnlw
dC50ZXN0iQHUBBMBCAA+FiEEWN8hB7lSujchpggaoGu/gqIHsh4FAmGoseUCGwMF
CQPCZwAFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQoGu/gqIHsh4HeAv/eHWD
eaKLHy0W+p34vl7lobZ6ndpZekCdP8ve29Mtdu46CS7W5N2u5lTEcd6ir+tq8WB0
6MqZ/Kr6o1HsVDrsrDeH4pQxN6FzuIY4uiPbySsIBvy6ZLSxjO7U1dayfA2a9BIG
nJd2W9fYIsyqokUXdX+0m+SoYIVglLUvEJZbZNKI4oNepRU73gyKMbU9HQN9mvPR
fCpigPh+xPoiafgwF1cPDl2drGcBZOE5H7LTcyIFKqH8sFMDiZRB7Werq/uFEx5v
k2iu0D9a/cZGE+UVtoVok0rAFGi2QtRixDcfe+wq60UfjCRBObFlBUgvl1HISlWE
0C5P6HClHqqzhbr8ZbkTvNqeR3ae2Nbiy1ImV8uLdRNZFrtOgvtFa6gjszsGE0FX
wRtJP9ayy02yPrpMzMkv34ApEy5+07wORTbaCsaWdzKsYOJIxlmx3eBATrgNjVSo
Rt0qgcuC6CEmV+jmAWurIFndYlp/AJYyJZ9JYm8JlBJhltkcDSxyhZrUYof4
=0YiW
-----END PGP PUBLIC KEY BLOCK-----

```

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/144416556-4401faf7-bb99-4c2a-86e0-bd90e34c9d60.png)

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/144441798-1b1d3ba1-76cf-4308-9a41-ea342abdc47d.png)
