### ISSUE TITLE
Java InterruptedException

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#163]
```
[STACK_TRACE]
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2010)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$SyncTaskRunnable.run(EmailSyncManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)



[LOGCAT]
12-04 12:52:41.112 I/System.out(21325): A270 LIST "" "*"
12-04 12:52:41.155 I/System.out(21325): * LIST (\HasNoChildren) "/" "INBOX"
12-04 12:52:41.160 I/System.out(21325): * LIST (\HasChildren \Noselect) "/" "[Gmail]"
12-04 12:52:41.160 I/System.out(21325): * LIST (\All \HasNoChildren) "/" "[Gmail]/All Mail"
12-04 12:52:41.160 I/System.out(21325): * LIST (\Drafts \HasNoChildren) "/" "[Gmail]/Drafts"
12-04 12:52:41.160 I/System.out(21325): * LIST (\HasNoChildren \Important) "/" "[Gmail]/Important"
12-04 12:52:41.160 I/System.out(21325): * LIST (\HasNoChildren \Sent) "/" "[Gmail]/Sent Mail"
12-04 12:52:41.161 I/System.out(21325): * LIST (\HasNoChildren \Junk) "/" "[Gmail]/Spam"
12-04 12:52:41.161 I/System.out(21325): * LIST (\Flagged \HasNoChildren) "/" "[Gmail]/Starred"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasNoChildren \Trash) "/" "[Gmail]/Trash"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasNoChildren) "/" "alert"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasNoChildren) "/" "compatibility"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasNoChildren) "/" "fixed"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasNoChildren) "/" "money"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasNoChildren) "/" "to think about"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasNoChildren) "/" "to:fix"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasNoChildren) "/" "to:followup"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasChildren) "/" "to:test"
12-04 12:52:41.162 I/System.out(21325): * LIST (\HasNoChildren) "/" "to:test/firefox"
12-04 12:52:41.162 I/System.out(21325): A270 OK Success
12-04 12:52:41.172 D/EmailSyncService(21325): onFolderInfoReceived:[INBOX, [Gmail], [Gmail]/All Mail, [Gmail]/Drafts, [Gmail]/Important, [Gmail]/Sent Mail, [Gmail]/Spam, [Gmail]/Starred, [Gmail]/Trash, alert, compatibility, fixed, money, to think about, to:fix, to:followup, to:test, to:test/firefox]
12-04 12:52:41.173 I/System.out(21325): A271 STATUS INBOX (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.220 I/System.out(21325): * STATUS "INBOX" (MESSAGES 37 RECENT 0 UIDNEXT 13330 UIDVALIDITY 1 UNSEEN 1)
12-04 12:52:41.220 I/System.out(21325): A271 OK Success
12-04 12:52:41.221 I/System.out(21325): A272 STATUS "[Gmail]/All Mail" (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.280 I/System.out(21325): * STATUS "[Gmail]/All Mail" (MESSAGES 21606 RECENT 0 UIDNEXT 89370 UIDVALIDITY 11 UNSEEN 1202)
12-04 12:52:41.280 I/System.out(21325): A272 OK Success
12-04 12:52:41.282 I/System.out(21325): A273 STATUS [Gmail]/Drafts (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.344 I/System.out(21325): * STATUS "[Gmail]/Drafts" (MESSAGES 2 RECENT 0 UIDNEXT 67631 UIDVALIDITY 6 UNSEEN 0)
12-04 12:52:41.344 I/System.out(21325): A273 OK Success
12-04 12:52:41.345 I/System.out(21325): A274 STATUS [Gmail]/Important (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.398 I/System.out(21325): * STATUS "[Gmail]/Important" (MESSAGES 14668 RECENT 0 UIDNEXT 14764 UIDVALIDITY 9 UNSEEN 785)
12-04 12:52:41.398 I/System.out(21325): A274 OK Success
12-04 12:52:41.400 I/System.out(21325): A275 STATUS "[Gmail]/Sent Mail" (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.450 I/System.out(21325): * STATUS "[Gmail]/Sent Mail" (MESSAGES 7795 RECENT 0 UIDNEXT 7800 UIDVALIDITY 5 UNSEEN 14)
12-04 12:52:41.450 I/System.out(21325): A275 OK Success
12-04 12:52:41.451 I/System.out(21325): A276 STATUS [Gmail]/Spam (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.526 I/System.out(21325): * STATUS "[Gmail]/Spam" (MESSAGES 5 RECENT 0 UIDNEXT 37 UIDVALIDITY 3 UNSEEN 1)
12-04 12:52:41.526 I/System.out(21325): A276 OK Success
12-04 12:52:41.527 I/System.out(21325): A277 STATUS [Gmail]/Starred (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.570 I/System.out(21325): * STATUS "[Gmail]/Starred" (MESSAGES 18 RECENT 0 UIDNEXT 34 UIDVALIDITY 4 UNSEEN 1)
12-04 12:52:41.570 I/System.out(21325): A277 OK Success
12-04 12:52:41.572 I/System.out(21325): A278 STATUS [Gmail]/Trash (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.632 I/System.out(21325): * STATUS "[Gmail]/Trash" (MESSAGES 1 RECENT 0 UIDNEXT 101 UIDVALIDITY 2 UNSEEN 0)
12-04 12:52:41.632 I/System.out(21325): A278 OK Success
12-04 12:52:41.634 I/System.out(21325): A279 STATUS alert (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.697 I/System.out(21325): * STATUS "alert" (MESSAGES 759 RECENT 0 UIDNEXT 772 UIDVALIDITY 16 UNSEEN 0)
12-04 12:52:41.697 I/System.out(21325): A279 OK Success
12-04 12:52:41.698 I/System.out(21325): A280 STATUS compatibility (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.790 I/System.out(21325): * STATUS "compatibility" (MESSAGES 49 RECENT 0 UIDNEXT 59 UIDVALIDITY 13 UNSEEN 0)
12-04 12:52:41.790 I/System.out(21325): A280 OK Success
12-04 12:52:41.791 I/System.out(21325): A281 STATUS fixed (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.867 I/System.out(21325): * STATUS "fixed" (MESSAGES 0 RECENT 0 UIDNEXT 4 UIDVALIDITY 17 UNSEEN 0)
12-04 12:52:41.867 I/System.out(21325): A281 OK Success
12-04 12:52:41.868 I/System.out(21325): A282 STATUS money (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:41.944 I/System.out(21325): * STATUS "money" (MESSAGES 78 RECENT 0 UIDNEXT 99 UIDVALIDITY 21 UNSEEN 0)
12-04 12:52:41.944 I/System.out(21325): A282 OK Success
12-04 12:52:41.946 I/System.out(21325): A283 STATUS "to think about" (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:42.010 I/System.out(21325): * STATUS "to think about" (MESSAGES 7 RECENT 0 UIDNEXT 13 UIDVALIDITY 19 UNSEEN 0)
12-04 12:52:42.010 I/System.out(21325): A283 OK Success
12-04 12:52:42.011 I/System.out(21325): A284 STATUS to:fix (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:42.069 I/System.out(21325): * STATUS "to:fix" (MESSAGES 259 RECENT 0 UIDNEXT 573 UIDVALIDITY 12 UNSEEN 0)
12-04 12:52:42.069 I/System.out(21325): A284 OK Success
12-04 12:52:42.072 I/System.out(21325): A285 STATUS to:followup (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:42.132 I/System.out(21325): * STATUS "to:followup" (MESSAGES 182 RECENT 0 UIDNEXT 359 UIDVALIDITY 15 UNSEEN 0)
12-04 12:52:42.132 I/System.out(21325): A285 OK Success
12-04 12:52:42.134 I/System.out(21325): A286 STATUS to:test (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:42.170 I/System.out(21325): * STATUS "to:test" (MESSAGES 180 RECENT 0 UIDNEXT 335 UIDVALIDITY 14 UNSEEN 0)
12-04 12:52:42.171 I/System.out(21325): A286 OK Success
12-04 12:52:42.172 I/System.out(21325): A287 STATUS to:test/firefox (MESSAGES RECENT UNSEEN UIDNEXT UIDVALIDITY)
12-04 12:52:42.240 I/System.out(21325): * STATUS "to:test/firefox" (MESSAGES 44 RECENT 0 UIDNEXT 45 UIDVALIDITY 20 UNSEEN 0)
12-04 12:52:42.240 I/System.out(21325): A287 OK Success
12-04 12:52:42.263 D/SyncTaskRunnable(21325): The task = UpdateLabelsSyncTask completed
12-04 12:52:42.263 D/SyncTaskRunnable(21325): SyncTaskBlockingQueue size = 0
12-04 12:52:43.051 V/FragmentManager(21325): movefrom RESUMED: EmailListFragment{9757d99 #0 id=0x7f08006c}
12-04 12:52:43.051 V/FragmentManager(21325): movefrom RESUMED: zzdb{9467094 #1 SupportLifecycleFragmentImpl}
12-04 12:52:43.052 V/FragmentManager(21325): movefrom RESUMED: SupportRequestManagerFragment{7beb30 #2 com.bumptech.glide.manager}{parent=null}
12-04 12:52:43.138 D/EmailSyncService(21325): onStartCommand |intent =Intent { act=ACTION_SWITCH_ACCOUNT cmp=com.flowcrypt.email.debug/com.flowcrypt.email.service.EmailSyncService }|flags = 0|startId = 2
12-04 12:52:43.310 D/EmailSyncManager(21325): beginSync | isNeedReset = true
12-04 12:52:43.311 W/System.err(21325): java.lang.InterruptedException
12-04 12:52:43.314 W/System.err(21325):         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2010)
12-04 12:52:43.314 W/System.err(21325):         at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2044)
12-04 12:52:43.314 W/System.err(21325):         at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:413)
12-04 12:52:43.314 W/System.err(21325):         at com.flowcrypt.email.api.email.sync.EmailSyncManager$SyncTaskRunnable.run(EmailSyncManager.java:350)
12-04 12:52:43.314 W/System.err(21325):         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
12-04 12:52:43.314 W/System.err(21325):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-04 12:52:43.314 W/System.err(21325):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
12-04 12:52:43.314 W/System.err(21325):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
12-04 12:52:43.314 W/System.err(21325):         at java.lang.Thread.run(Thread.java:761)
12-04 12:52:43.322 D/EmailManagerActivity(21325): onCreate
12-04 12:52:43.337 V/FragmentManager(21325): onCreateView: id=0x7f08006c fname=com.flowcrypt.email.ui.activity.fragment.EmailListFragment existing=null
12-04 12:52:43.338 V/FragmentManager(21325): add: EmailListFragment{3d04b36 id=0x7f08006c}
12-04 12:52:43.338 V/FragmentManager(21325): Allocated fragment index EmailListFragment{3d04b36 #0 id=0x7f08006c}
12-04 12:52:43.338 V/FragmentManager(21325): moveto CREATED: EmailListFragment{3d04b36 #0 id=0x7f08006c}
12-04 12:52:43.377 D/EmailManagerActivity(21325): bind to EmailSyncService
12-04 12:52:43.379 V/FragmentManager(21325): Commit: BackStackEntry{80c13e9}
12-04 12:52:43.379 D/FragmentManager(21325):   mName=null mIndex=-1 mCommitted=false
12-04 12:52:43.379 D/FragmentManager(21325):   Operations:
12-04 12:52:43.379 D/FragmentManager(21325):     Op #0: ADD zzdb{a6ba86e SupportLifecycleFragmentImpl}
12-04 12:52:43.379 D/AutoManageHelper(21325): starting AutoManage for client 0 false null


[ENVIRONMENT]
{"getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getLegacyExternalStorageDirectory": "/sdcard", "getDataSystemDirectory": "/data/system", "getDataMiscDirectory": "/data/misc", "getDataSystemCeDirectory": "/data/system_ce", "getExternalStorageState": "mounted", "getStorageDirectory": "/storage", "getExpandDirectory": "/mnt/expand", "getOemDirectory": "/oem", "getExternalStorageDirectory": "/storage/emulated/0", "isExternalStorageEmulated": true, "getDataDirectory": "/data", "isExternalStorageRemovable": false, "getDataSystemDeDirectory": "/data/system_de", "getOdmDirectory": "/odm", "getRootDirectory": "/system", "getDownloadCacheDirectory": "/cache"}


[TOTAL_MEM_SIZE]
11746017280


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 7, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 260, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 504, "fontScale": 1, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 568, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DISPLAY]
{"0": {"refreshRate": 60, "metrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 403.4110107421875, "widthPixels": 1080, "heightPixels": 1776, "densityDpi": 480, "ydpi": 403.0409851074219}, "name": "Built-in Screen", "realSize": [1080, 1920], "isValid": true, "currentSizeRange": {"smallest": [1080, 1008], "largest": [1776, 1704]}, "rectSize": [0, 0, 1080, 1776], "height": 1776, "realMetrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 403.4110107421875, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 480, "ydpi": 403.0409851074219}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 1776], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
7441707008


[PHONE_MODEL]
Moto G (4)


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 7, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 260, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 504, "fontScale": 1, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 568, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DEVICE_FEATURES]
{"com.google.preload_photos": true, "android.software.verified_boot": true, "com.motorola.software.storageoptimizer": true, "com.motorola.software.device.athene": true, "android.hardware.ethernet": true, "android.hardware.sensor.proximity": true, "android.software.input_methods": true, "com.motorola.software.fmradioservice": true, "com.motorola.easyprefix": true, "com.motorola.software.guideme": true, "android.software.device_admin": true, "android.hardware.faketouch": true, "android.software.backup": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "com.motorola.software.modality": true, "android.hardware.sensor.accelerometer": true, "com.motorola.hardware.tier.G": true, "com.motorola.actions": true, "com.motorola.software.x_line": true, "android.hardware.camera.flash": true, "android.hardware.sensor.light": true, "com.motorola.moto.MOTO_VOICE_DISABLED_4_3": true, "android.hardware.location.gps": true, "android.hardware.usb.accessory": true, "android.software.webview": true, "com.motorola.software.DirectedSMSProxy": true, "android.software.sip.voip": true, "android.hardware.microphone": true, "android.hardware.bluetooth": true, "android.hardware.location.network": true, "android.software.midi": true, "android.hardware.touchscreen.multitouch": true, "android.software.voice_recognizers": true, "android.hardware.touchscreen": true, "android.hardware.audio.output": true, "com.motorola.motodisplay.doze.glimpse": true, "android.hardware.bluetooth_le": true, "android.hardware.telephony": true, "android.hardware.sensor.stepcounter": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.hardware.sensor.gyroscope": true, "com.motorola.moto": true, "android.software.sip": true, "android.hardware.camera.autofocus": true, "android.software.live_wallpaper": true, "com.motorola.sensorhub.stml0xx": true, "android.hardware.camera.any": true, "android.hardware.telephony.gsm": true, "android.hardware.telephony.cdma": true, "android.hardware.camera": true, "com.motorola.hardware.wave.2016.1": true, "android.hardware.wifi": true, "android.software.print": true, "android.hardware.location": true, "android.software.home_screen": true, "com.motorola.cameraone": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.opengles.aep": true, "android.hardware.sensor.stepdetector": true, "android.hardware.usb.host": true, "android.hardware.screen.portrait": true, "android.software.managed_users": true, "com.motorola.software.product.athene_retail": true, "android.hardware.wifi.direct": true, "glEsVersion": "3.2", "android.hardware.screen.landscape": true, "com.motorola.msimsettings": true, "android.software.connectionservice": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email.debug", "VERSION_CODE": 30, "BUILD_TYPE": "debug", "DEBUG": true, "VERSION_NAME": "0.3.0_30__2017_12_05_02_08", "FLAVOR": "", "serialVersionUID": -6921988441490417973}


[FILE_PATH]
/data/user/0/com.flowcrypt.email.debug/files


[INSTALLATION_ID]
4f2781ea-fdf2-40db-bae4-f1fa3a76604c


[USER_CRASH_DATE]
2017-12-04T12:52:43.437-06:00


[HASH]
0A7BA93B00


[APP_VERSION_NAME]
0.3.0_30__2017_12_05_02_08


[USER_APP_START_DATE]
2017-12-04T12:08:52.732-06:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "qcom", "BOARD": "msm8952", "MODEL": "Moto G (4)", "BOOTLOADER": "0xB106", "DISPLAY": "NPJ25.93-14.7", "CPU_ABI2": "armeabi", "FINGERPRINT": "motorola/athene/athene:7.0/NPJ25.93-14.7/7:user/release-keys", "IS_EMULATOR": false, "TAGS": "release-keys", "HOST": "ilclbld36", "VERSION": {"PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 24, "SDK_INT": 24, "INCREMENTAL": "7", "BASE_OS": "", "RELEASE": "7.0", "CODENAME": "REL", "SECURITY_PATCH": "2017-09-01", "ACTIVE_CODENAMES": [], "SDK": "24"}, "PERMISSIONS_REVIEW_REQUIRED": false, "DEVICE": "athene", "SERIAL": "ZY223GW7FS", "ID": "NPJ25.93-14.7", "MANUFACTURER": "motorola", "PRODUCT": "athene", "SUPPORTED_ABIS": ["armeabi-v7a", "armeabi"], "IS_DEBUGGABLE": false, "SUPPORTED_64_BIT_ABIS": [], "RADIO": "unknown", "CPU_ABI": "armeabi-v7a", "TIME": 1504111410000, "SUPPORTED_32_BIT_ABIS": ["armeabi-v7a", "armeabi"], "TYPE": "user", "BRAND": "motorola", "USER": "hudsoncm"}


[DUMPSYS_MEMINFO]



[USER_EMAIL]
N/A


[REPORT_ID]
e5ce91e8-2865-4968-93b6-795a7c620ad6


[PRODUCT]
athene


[PACKAGE_NAME]
com.flowcrypt.email.debug


[BRAND]
motorola


[ANDROID_VERSION]
7.0


[APP_VERSION_CODE]
30


[IS_SILENT]
false


[CUSTOM_DATA]
{}
```

**Comment by tomholub** [comment]
@DenBond7 This should be the last issue for 0.4.0 unless I discover something

**Comment by DenBond7** [comment]
There are no errors. It's a normal behavior. Typically, this occurs when the user switches between accounts.

com.flowcrypt.email.api.email.sync.EmailSyncManager

![image](https://user-images.githubusercontent.com/2863246/33600103-f09e3e6e-d9b0-11e7-8656-d303d9abef87.png)

![image](https://user-images.githubusercontent.com/2863246/33600280-72e45a5c-d9b1-11e7-9c7e-0c4a7e9f6a27.png)

![image](https://user-images.githubusercontent.com/2863246/33600385-c350bd00-d9b1-11e7-8375-25757b2d646a.png)

In the log we can see next
com.flowcrypt.email.api.email.sync.EmailSyncManager$SyncTaskRunnable.run(EmailSyncManager.java:350) - the root where the error was happened

![image](https://user-images.githubusercontent.com/2863246/33600574-5067ff46-d9b2-11e7-8cec-503cc7b35821.png)

![image](https://user-images.githubusercontent.com/2863246/33600961-7e562c56-d9b3-11e7-9fd0-f530c68f4100.png)

![image](https://user-images.githubusercontent.com/2863246/33601005-a6f0a52e-d9b3-11e7-9f23-70675d50e195.png)


So while in the logs we can see the line "beginSync | isNeedReset = true" it means that all works fine.
If need we can easily remove notification about this.

**Comment by tomholub** [comment]
If this is normal part of the operation and handled in the code, we should probably not be reporting it. It's good to report things that are unexpected or not properly handled.
