### ISSUE TITLE
javax.crypto.IllegalBlockSizeException

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#168]
```
[STACK_TRACE]
javax.crypto.IllegalBlockSizeException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
        at javax.crypto.Cipher.doFinal(Cipher.java:2056)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.decryptWithRSA(KeyStoreCryptoManager.java:254)
        at com.flowcrypt.email.database.dao.source.AccountDaoSource.getCurrentAuthCredentialsFromCursor(AccountDaoSource.java:167)
        at com.flowcrypt.email.database.dao.source.AccountDaoSource.getCurrentAccountDao(AccountDaoSource.java:117)
        at com.flowcrypt.email.database.dao.source.AccountDaoSource.getActiveAccountInformation(AccountDaoSource.java:233)
        at com.flowcrypt.email.service.EmailSyncService.onCreate(EmailSyncService.java:142)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3478)
        at android.app.ActivityThread.-wrap6(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: android.security.KeyStoreException: Unknown error
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1097)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        ... 15 more
android.security.KeyStoreException: Unknown error
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1097)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at javax.crypto.Cipher.doFinal(Cipher.java:2056)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.decryptWithRSA(KeyStoreCryptoManager.java:254)
        at com.flowcrypt.email.database.dao.source.AccountDaoSource.getCurrentAuthCredentialsFromCursor(AccountDaoSource.java:167)
        at com.flowcrypt.email.database.dao.source.AccountDaoSource.getCurrentAccountDao(AccountDaoSource.java:117)
        at com.flowcrypt.email.database.dao.source.AccountDaoSource.getActiveAccountInformation(AccountDaoSource.java:233)
        at com.flowcrypt.email.service.EmailSyncService.onCreate(EmailSyncService.java:142)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3478)
        at android.app.ActivityThread.-wrap6(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)



[LOGCAT]
--------- beginning of main
12-06 23:56:36.761 I/SELinux (16421): SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.flowcrypt.email
12-06 23:56:36.861 D/TimaKeyStoreProvider(16421): TimaSignature is unavailable
12-06 23:56:36.867 D/ActivityThread(16421): Added TimaKeyStore provider
12-06 23:56:37.460 I/ACRA    (16421): ACRA is enabled for com.flowcrypt.email, initializing...
12-06 23:56:37.501 D/ContextRelationMgrBrdg(16421): loadKlass() : caller=com.samsung.android.bridge.multiscreen.common.ContextRelationManagerBridge.<clinit>:28 android.app.LoadedApk.makeApplication:840
12-06 23:56:37.625 D/TextView(16421): setTypeface with style : 0
12-06 23:56:37.629 D/TextView(16421): setTypeface with style : 0
12-06 23:56:37.631 D/TextView(16421): setTypeface with style : 0
12-06 23:56:37.643 D/TextView(16421): setTypeface with style : 0
12-06 23:56:37.648 D/TextView(16421): setTypeface with style : 0
12-06 23:56:37.650 D/TextView(16421): setTypeface with style : 0
12-06 23:56:37.653 D/TextView(16421): setTypeface with style : 0
12-06 23:56:38.165 W/System.err(16421): javax.crypto.IllegalBlockSizeException
12-06 23:56:38.168 W/System.err(16421):         at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
12-06 23:56:38.168 W/System.err(16421):         at javax.crypto.Cipher.doFinal(Cipher.java:2056)
12-06 23:56:38.168 W/System.err(16421):         at com.flowcrypt.email.security.KeyStoreCryptoManager.decryptWithRSA(KeyStoreCryptoManager.java:254)
12-06 23:56:38.169 W/System.err(16421):         at com.flowcrypt.email.database.dao.source.AccountDaoSource.getCurrentAuthCredentialsFromCursor(AccountDaoSource.java:167)
12-06 23:56:38.169 W/System.err(16421):         at com.flowcrypt.email.database.dao.source.AccountDaoSource.getCurrentAccountDao(AccountDaoSource.java:117)
12-06 23:56:38.169 W/System.err(16421):         at com.flowcrypt.email.database.dao.source.AccountDaoSource.getActiveAccountInformation(AccountDaoSource.java:233)
12-06 23:56:38.169 W/System.err(16421):         at com.flowcrypt.email.ui.activity.SplashActivity.onCreate(SplashActivity.java:64)
12-06 23:56:38.169 W/System.err(16421):         at android.app.Activity.performCreate(Activity.java:6912)
12-06 23:56:38.169 W/System.err(16421):         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
12-06 23:56:38.169 W/System.err(16421):         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
12-06 23:56:38.169 W/System.err(16421):         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
12-06 23:56:38.169 W/System.err(16421):         at android.app.ActivityThread.-wrap14(ActivityThread.java)
12-06 23:56:38.169 W/System.err(16421):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
12-06 23:56:38.169 W/System.err(16421):         at android.os.Handler.dispatchMessage(Handler.java:102)
12-06 23:56:38.169 W/System.err(16421):         at android.os.Looper.loop(Looper.java:154)
12-06 23:56:38.169 W/System.err(16421):         at android.app.ActivityThread.main(ActivityThread.java:6692)
12-06 23:56:38.169 W/System.err(16421):         at java.lang.reflect.Method.invoke(Native Method)
12-06 23:56:38.169 W/System.err(16421):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
12-06 23:56:38.169 W/System.err(16421):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
12-06 23:56:38.169 W/System.err(16421): Caused by: android.security.KeyStoreException: Unknown error
12-06 23:56:38.170 W/System.err(16421):         at android.security.KeyStore.getKeyStoreException(KeyStore.java:1097)
12-06 23:56:38.170 W/System.err(16421):         at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
12-06 23:56:38.170 W/System.err(16421):         at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
12-06 23:56:38.170 W/System.err(16421):         ... 18 more
12-06 23:56:38.389 I/SELinux (16455): SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.flowcrypt.email:acra
12-06 23:56:38.411 D/TimaKeyStoreProvider(16455): TimaSignature is unavailable
12-06 23:56:38.412 D/ActivityThread(16455): Added TimaKeyStore provider
12-06 23:56:38.523 D/ContextRelationMgrBrdg(16455): loadKlass() : caller=com.samsung.android.bridge.multiscreen.common.ContextRelationManagerBridge.<clinit>:28 android.app.LoadedApk.makeApplication:840
12-06 23:56:38.691 I/ACRA    (16455): Sending report /data/user/0/com.flowcrypt.email/app_ACRA-approved/2017-12-06T23:56:38.272+00:00-IS_SILENT.stacktrace
12-06 23:56:38.930 D/NetworkSecurityConfig(16455): No Network Security Config specified, using platform default
12-06 23:56:39.027 W/System.err(16421): javax.crypto.IllegalBlockSizeException
12-06 23:56:39.028 W/System.err(16421):         at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
12-06 23:56:39.028 W/System.err(16421):         at javax.crypto.Cipher.doFinal(Cipher.java:2056)
12-06 23:56:39.028 W/System.err(16421):         at com.flowcrypt.email.security.KeyStoreCryptoManager.decryptWithRSA(KeyStoreCryptoManager.java:254)
12-06 23:56:39.028 W/System.err(16421):         at com.flowcrypt.email.database.dao.source.AccountDaoSource.getCurrentAuthCredentialsFromCursor(AccountDaoSource.java:167)
12-06 23:56:39.028 W/System.err(16421):         at com.flowcrypt.email.database.dao.source.AccountDaoSource.getCurrentAccountDao(AccountDaoSource.java:117)
12-06 23:56:39.028 W/System.err(16421):         at com.flowcrypt.email.database.dao.source.AccountDaoSource.getActiveAccountInformation(AccountDaoSource.java:233)
12-06 23:56:39.028 W/System.err(16421):         at com.flowcrypt.email.service.EmailSyncService.onCreate(EmailSyncService.java:142)
12-06 23:56:39.028 W/System.err(16421):         at android.app.ActivityThread.handleCreateService(ActivityThread.java:3478)
12-06 23:56:39.028 W/System.err(16421):         at android.app.ActivityThread.-wrap6(ActivityThread.java)
12-06 23:56:39.028 W/System.err(16421):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1725)
12-06 23:56:39.028 W/System.err(16421):         at android.os.Handler.dispatchMessage(Handler.java:102)
12-06 23:56:39.028 W/System.err(16421):         at android.os.Looper.loop(Looper.java:154)
12-06 23:56:39.028 W/System.err(16421):         at android.app.ActivityThread.main(ActivityThread.java:6692)
12-06 23:56:39.028 W/System.err(16421):         at java.lang.reflect.Method.invoke(Native Method)
12-06 23:56:39.028 W/System.err(16421):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
12-06 23:56:39.029 W/System.err(16421):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
12-06 23:56:39.029 W/System.err(16421): Caused by: android.security.KeyStoreException: Unknown error
12-06 23:56:39.029 W/System.err(16421):         at android.security.KeyStore.getKeyStoreException(KeyStore.java:1097)
12-06 23:56:39.029 W/System.err(16421):         at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
12-06 23:56:39.029 W/System.err(16421):         at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
12-06 23:56:39.029 W/System.err(16421):         ... 15 more


[ENVIRONMENT]
{"getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getLegacyExternalStorageDirectory": "/sdcard", "getDataSystemDirectory": "/data/system", "getDataMiscDirectory": "/data/misc", "getDataSystemCeDirectory": "/data/system_ce", "getExternalStorageState": "mounted", "getStorageDirectory": "/storage", "getExpandDirectory": "/mnt/expand", "getOemDirectory": "/oem", "getExternalStorageDirectory": "/storage/emulated/0", "isExternalStorageEmulated": true, "getDataDirectory": "/data", "isExternalStorageRemovable": false, "getDataSystemDeDirectory": "/data/system_de", "getOdmDirectory": "/odm", "getRootDirectory": "/system", "getDownloadCacheDirectory": "/cache"}


[TOTAL_MEM_SIZE]
26697031680


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 13, "locale": "en_US", "compatSmallestScreenWidthDp": 320, "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 3, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "showButtonBackground": 0, "compatScreenHeightDp": 547, "isOverridden": false, "fontScale": 1, "FlipFont": 0, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 272, "compatScreenWidthDp": 320, "semMobileKeyboardCovered": 0, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 616, "themeSeq": 0, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DISPLAY]
{"0": {"refreshRate": 59, "metrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 435.4282531738281, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 480, "ydpi": 431.57476806640625}, "name": "Built-in Screen", "realSize": [1080, 1920], "isValid": true, "currentSizeRange": {"smallest": [1080, 1008], "largest": [1920, 1848]}, "rectSize": [0, 0, 1080, 1920], "height": 1920, "realMetrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 435.4282531738281, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 480, "ydpi": 431.57476806640625}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 1920], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
3754754048


[PHONE_MODEL]
SM-G930F


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 13, "locale": "en_US", "compatSmallestScreenWidthDp": 320, "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 3, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "showButtonBackground": 0, "compatScreenHeightDp": 547, "isOverridden": false, "fontScale": 1, "FlipFont": 0, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 272, "compatScreenWidthDp": 320, "semMobileKeyboardCovered": 0, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 616, "themeSeq": 0, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DEVICE_FEATURES]
{"com.sec.feature.cover.flip": true, "com.samsung.android.sdk.camera.processor.panorama": true, "android.software.input_methods": true, "android.hardware.sensor.hifi_sensors": true, "com.sec.feature.motionrecognition_service": true, "android.hardware.nfc.hcef": true, "com.sec.feature.sensorhub": true, "android.hardware.faketouch": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "com.samsung.android.sdk.camera.processor.dof": true, "android.hardware.screen.portrait": true, "com.samsung.android.api.version.2402": true, "android.hardware.usb.accessory": true, "com.samsung.android.sdk.camera.processor.lls": true, "android.hardware.location.network": true, "com.samsung.feature.samsung_experience_mobile": true, "android.software.voice_recognizers": true, "com.sec.feature.spo2": true, "android.hardware.audio.output": true, "com.sec.feature.findo": true, "android.hardware.bluetooth": true, "com.samsung.feature.device_category_phone_high_end": true, "android.hardware.nfc.hce": true, "com.samsung.android.sdk.camera.processor.haze": true, "android.hardware.wifi.direct": true, "android.hardware.screen.landscape": true, "android.software.connectionservice": true, "com.sec.feature.support_mst": true, "com.samsung.android.authfw": true, "com.sec.feature.nsflp": true, "android.software.managed_users": true, "android.hardware.telephony": true, "android.hardware.sensor.light": true, "com.samsung.android.sdk.camera.processor": true, "com.sec.feature.cover": true, "android.software.midi": true, "android.hardware.wifi": true, "com.samsung.feature.mirrorlink_fw": true, "android.hardware.touchscreen": true, "com.samsung.android.sdk.camera.processor.hdr": true, "android.hardware.sensor.heartrate": true, "com.sec.feature.overlaymagnifier": true, "com.sec.android.smartface.smart_stay": true, "android.software.print": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.opengles.aep": true, "android.hardware.sensor.stepdetector": true, "android.hardware.sensor.barometer": true, "android.hardware.location": true, "com.sec.feature.barcode_emulator": true, "android.software.device_admin": true, "com.sec.feature.cover.clearcover": true, "android.hardware.camera.capability.manual_post_processing": true, "com.sec.feature.cover.nfcledcover": true, "com.samsung.feature.aodservice": true, "com.sec.feature.slocation": true, "com.sec.feature.fingerprint_manager_service": true, "android.hardware.bluetooth_le": true, "android.software.backup": true, "android.hardware.sensor.compass": true, "android.software.live_wallpaper": true, "com.sec.feature.cover.sviewcover": true, "android.hardware.telephony.gsm": true, "android.hardware.vulkan.version": true, "com.samsung.android.sdk.camera.ipx": true, "android.software.webview": true, "android.software.sip.voip": true, "android.hardware.fingerprint": true, "android.hardware.touchscreen.multitouch": true, "com.sec.android.mdm": true, "android.software.vr.mode": true, "android.hardware.sensor.stepcounter": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.hardware.camera.any": true, "android.hardware.camera.level.full": true, "com.sec.feature.cover.sview": true, "com.samsung.android.sdk.camera.processor.effect": true, "android.software.freeform_window_management": true, "glEsVersion": "3.2", "android.hardware.vulkan.level": true, "android.hardware.usb.host": true, "com.sec.feature.cover.nfc_authentication": true, "android.hardware.nfc": true, "android.software.verified_boot": true, "com.samsung.android.knox.knoxsdk": true, "android.hardware.camera.capability.raw": true, "com.samsung.feature.hdr_capable": true, "com.samsung.android.sdk.camera.processor.gif": true, "android.hardware.camera.flash": true, "android.hardware.location.gps": true, "com.sec.android.secimaging": true, "android.hardware.microphone": true, "android.hardware.sensor.gyroscope": true, "com.sec.feature.secretmode_service": true, "com.samsung.feature.hmt": true, "android.hardware.camera.capability.manual_sensor": true, "android.software.sip": true, "com.samsung.feature.radiobasedlocation": true, "android.hardware.sensor.proximity": true, "android.hardware.camera": true, "com.samsung.feature.virtualscreen": true, "android.software.home_screen": true, "android.hardware.camera.autofocus": true, "android.hardware.sensor.accelerometer": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email", "VERSION_CODE": 40, "BUILD_TYPE": "release", "DEBUG": false, "VERSION_NAME": "0.4.0", "FLAVOR": ""}


[FILE_PATH]
/data/user/0/com.flowcrypt.email/files


[INSTALLATION_ID]
302f9b52-da5d-4345-b16b-70d8c03f25a9


[USER_CRASH_DATE]
2017-12-06T23:56:39.214+00:00


[HASH]
AF57227A18


[APP_VERSION_NAME]
0.4.0


[USER_APP_START_DATE]
2017-12-06T23:56:37.474+00:00


[BUILD]
{"IS_SYSTEM_SECURE": false, "UNKNOWN": "unknown", "HARDWARE": "samsungexynos8890", "BOARD": "universal8890", "MODEL": "SM-G930F", "BOOTLOADER": "G930FXXU1DQJ8", "DISPLAY": "NRD90M.G930FXXU1DQJ8", "CPU_ABI2": "armeabi", "FINGERPRINT": "samsung/heroltexx/herolte:7.0/NRD90M/G930FXXU1DQJ8:user/release-keys", "IS_EMULATOR": false, "TAGS": "release-keys", "HOST": "SWDG5301", "VERSION": {"SEM_INT": 2402, "SECURITY_PATCH": "2017-10-01", "PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 24, "SDK_INT": 24, "INCREMENTAL": "G930FXXU1DQJ8", "BASE_OS": "", "RELEASE": "7.0", "CODENAME": "REL", "SEM_PLATFORM_INT": 80000, "ACTIVE_CODENAMES": [], "SDK": "24"}, "PERMISSIONS_REVIEW_REQUIRED": false, "DEVICE": "herolte", "SERIAL": "ce11160b4843693a05", "ID": "NRD90M", "MANUFACTURER": "samsung", "PRODUCT": "heroltexx", "BRAND": "samsung", "IS_DEBUGGABLE": false, "SUPPORTED_64_BIT_ABIS": ["arm64-v8a"], "RADIO": "G930FXXU1DQJ1", "CPU_ABI": "armeabi-v7a", "TIME": 1508826763000, "SUPPORTED_32_BIT_ABIS": ["armeabi-v7a", "armeabi"], "TYPE": "user", "SUPPORTED_ABIS": ["arm64-v8a", "armeabi-v7a", "armeabi"], "USER": "dpi"}


[DUMPSYS_MEMINFO]



[USER_EMAIL]
N/A


[REPORT_ID]
9e325cbf-259d-4001-a673-f1dd784d8dd1


[PRODUCT]
heroltexx


[PACKAGE_NAME]
com.flowcrypt.email


[BRAND]
samsung


[ANDROID_VERSION]
7.0


[APP_VERSION_CODE]
40


[IS_SILENT]
false


[CUSTOM_DATA]
{}
```

**Comment by DenBond7** [comment]
For me https://issuetracker.google.com/issues/37075898
https://stackoverflow.com/questions/36015194/android-keystoreexception-unknown-error

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#inbox/16035e35596fdb1d
