### ISSUE TITLE
Cannot move/archive a message

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#171]
```

[STACK_TRACE]
java.lang.IllegalArgumentException: com.google| Cannot move the message. The destination folder is null.
        at com.flowcrypt.email.service.EmailSyncService$IncomingHandler.handleMessage(EmailSyncService.java:799)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5728)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)



[LOGCAT]
--------- beginning of main
12-09 02:01:25.992 E/MultiWindowProxy(13966): getServiceInstance failed!
12-09 02:01:26.328 E/MultiWindowProxy(13966): getServiceInstance failed!
12-09 02:01:26.406 W/CursorWrapperInner(13966): Cursor finalized without prior close()
12-09 02:01:26.407 W/CursorWrapperInner(13966): Cursor finalized without prior close()
12-09 02:01:26.467 W/Glide   (13966): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
12-09 02:01:26.975 D/libc-netbsd(13966): [getaddrinfo]: hostname=imap.gmail.com; servname=(null); netid=0; mark=0
12-09 02:01:26.975 D/libc-netbsd(13966): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
12-09 02:01:26.976 D/libc-netbsd(13966): [getaddrinfo]: hostname=imap.gmail.com; servname=(null); netid=0; mark=0
12-09 02:01:26.976 D/libc-netbsd(13966): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
12-09 02:01:27.008 D/libc-netbsd(13966): getaddrinfo: imap.gmail.com get result from proxy gai_error = 0
12-09 02:01:27.044 D/libc-netbsd(13966): [getaddrinfo]: hostname=imap.gmail.com; servname=(null); netid=0; mark=0
12-09 02:01:27.044 D/libc-netbsd(13966): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=4; ai_family=0
12-09 02:01:27.079 E/NativeCrypto(13966): ssl=0xee951500 cert_verify_callback x509_store_ctx=0xeeabec5c arg=0x0
12-09 02:01:27.079 E/NativeCrypto(13966): ssl=0xee951500 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
12-09 02:02:05.307 E/MultiWindowProxy(13966): getServiceInstance failed!
12-09 02:02:12.797 I/cr_LibraryLoader(13966): Time to load native libraries: 1 ms (timestamps 3558-3559)
12-09 02:02:12.857 D/WebView (13966): WebView<init>
12-09 02:02:12.881 I/chromium(13966): [INFO:library_loader_hooks.cc(46)] Chromium logging enabled: level = 0, default verbosity = 0
12-09 02:02:12.881 I/cr_LibraryLoader(13966): Expected native library version number "62.0.3202.84", actual native library version number "62.0.3202.84"
12-09 02:02:12.945 I/cr_BrowserStartup(13966): Initializing chromium process, singleProcess=true
12-09 02:02:13.247 E/MPlugin (13966): Unsupported class: com.mediatek.common.telephony.IOnlyOwnerSimSupport
12-09 02:02:13.287 D/WebView (13966): loadDataWithBaseURL=null
12-09 02:02:13.299 W/cr_media(13966): Requires BLUETOOTH permission
12-09 02:02:13.461 W/cr_CrashFileManager(13966): /data/user/0/com.flowcrypt.email/cache/WebView/Crash Reports does not exist or is not a directory
12-09 02:02:13.629 E/libEGL  (13966): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
12-09 02:02:13.666 W/AudioCapabilities(13966): Unsupported mime audio/mpeg-L2
12-09 02:02:13.667 W/AudioCapabilities(13966): Unsupported mime audio/x-adpcm-ms
12-09 02:02:13.668 W/AudioCapabilities(13966): Unsupported mime audio/x-adpcm-dvi-ima
12-09 02:02:13.672 W/AudioCapabilities(13966): Unsupported mime audio/ape
12-09 02:02:13.673 W/AudioCapabilities(13966): Unsupported mime audio/alac
12-09 02:02:13.677 W/AudioCapabilities(13966): Unsupported mime audio/x-adpcm-ms
12-09 02:02:13.678 W/AudioCapabilities(13966): Unsupported mime audio/x-adpcm-dvi-ima
12-09 02:02:13.687 W/VideoCapabilities(13966): Unrecognized profile/level 32768/2 for video/mp4v-es
12-09 02:02:13.698 W/VideoCapabilities(13966): Unsupported mime video/x-ms-wmv
12-09 02:02:13.700 W/VideoCapabilities(13966): Unsupported mime video/divx
12-09 02:02:13.702 W/VideoCapabilities(13966): Unsupported mime video/divx3
12-09 02:02:13.704 W/VideoCapabilities(13966): Unsupported mime video/xvid
12-09 02:02:13.706 W/VideoCapabilities(13966): Unsupported mime video/flv1
12-09 02:02:13.742 I/VideoCapabilities(13966): Unsupported profile 4 for video/mp4v-es
12-09 02:02:13.746 W/cr_MediaCodecUtil(13966): HW encoder for video/avc is not available on this device.
12-09 02:02:13.838 D/libc-netbsd(13966): [getaddrinfo]: hostname=o.dripemail2.com; servname=(null); netid=0; mark=0
12-09 02:02:13.838 D/libc-netbsd(13966): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
12-09 02:02:14.618 D/libc-netbsd(13966): getaddrinfo: o.dripemail2.com get result from proxy gai_error = 0
12-09 02:02:33.242 E/ACRA    (13966): ACRA caught a IllegalArgumentException for com.flowcrypt.email
12-09 02:02:33.242 E/ACRA    (13966): java.lang.IllegalArgumentException: com.google| Cannot move the message. The destination folder is null.
12-09 02:02:33.242 E/ACRA    (13966):   at com.flowcrypt.email.service.EmailSyncService$IncomingHandler.handleMessage(EmailSyncService.java:799)
12-09 02:02:33.242 E/ACRA    (13966):   at android.os.Handler.dispatchMessage(Handler.java:111)
12-09 02:02:33.242 E/ACRA    (13966):   at android.os.Looper.loop(Looper.java:207)
12-09 02:02:33.242 E/ACRA    (13966):   at android.app.ActivityThread.main(ActivityThread.java:5728)
12-09 02:02:33.242 E/ACRA    (13966):   at java.lang.reflect.Method.invoke(Native Method)
12-09 02:02:33.242 E/ACRA    (13966):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
12-09 02:02:33.242 E/ACRA    (13966):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)


[ENVIRONMENT]
{"isEncryptedFilesystemEnabled": false, "getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getLegacyExternalStorageDirectory": "/sdcard", "getSecureDataDirectory": "/data", "getExternalStorageState": "mounted", "getSystemSecureDirectory": "/data/system", "getStorageDirectory": "/storage", "getOemDirectory": "/oem", "getExternalStorageDirectory": "/storage/emulated/0", "isExternalStorageEmulated": true, "getDataDirectory": "/data", "isExternalStorageRemovable": false, "getRootDirectory": "/system", "getDownloadCacheDirectory": "/cache"}


[TOTAL_MEM_SIZE]
11589988352


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 10, "locale": "de_DE", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "simSetLocale": false, "mnc": 1, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 504, "fontScale": 0.85, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 262, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 568, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DISPLAY]
{"0": {"refreshRate": 57.83000183105469, "metrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 428.625, "widthPixels": 1080, "heightPixels": 1776, "densityDpi": 480, "ydpi": 424.0690002441406}, "name": "Integrierter Bildschirm", "realSize": [1080, 1920], "isValid": true, "currentSizeRange": {"smallest": [1080, 1008], "largest": [1794, 1704]}, "rectSize": [0, 0, 1080, 1776], "height": 1776, "realMetrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 428.625, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 480, "ydpi": 424.0690002441406}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 1776], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
1823682560


[PHONE_MODEL]
FEVER


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 10, "locale": "de_DE", "userSetLocale": true, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "simSetLocale": false, "mnc": 1, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 504, "fontScale": 0.85, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 262, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 568, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DEVICE_FEATURES]
{"android.hardware.sensor.proximity": true, "android.software.input_methods": true, "android.hardware.bluetooth_le": true, "android.software.device_admin": true, "android.hardware.faketouch": true, "android.software.backup": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "android.software.live_wallpaper": true, "android.hardware.sensor.accelerometer": true, "android.hardware.telephony": true, "android.hardware.telephony.gsm": true, "android.hardware.camera.flash": true, "android.hardware.sensor.light": true, "android.hardware.location.gps": true, "android.hardware.usb.accessory": true, "android.software.webview": true, "android.hardware.microphone": true, "android.hardware.bluetooth": true, "android.hardware.location.network": true, "android.hardware.touchscreen.multitouch": true, "android.software.voice_recognizers": true, "android.hardware.touchscreen": true, "android.hardware.audio.output": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.hardware.sensor.gyroscope": true, "android.hardware.screen.portrait": true, "android.software.managed_users": true, "android.hardware.camera.any": true, "android.hardware.sensor.compass": true, "android.hardware.camera": true, "android.hardware.wifi": true, "android.software.print": true, "android.software.home_screen": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.camera.autofocus": true, "android.hardware.location": true, "android.hardware.wifi.direct": true, "glEsVersion": "3.0", "android.hardware.screen.landscape": true, "android.hardware.usb.host": true, "android.software.connectionservice": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email", "VERSION_CODE": 40, "BUILD_TYPE": "release", "DEBUG": false, "VERSION_NAME": "0.4.0", "FLAVOR": ""}


[FILE_PATH]
/data/user/0/com.flowcrypt.email/files


[INSTALLATION_ID]
bafcb4a4-8a15-43dc-811d-6d33aac52281


[USER_CRASH_DATE]
2017-12-09T02:02:33.351+01:00


[HASH]
E15F114DC4


[APP_VERSION_NAME]
0.4.0


[USER_APP_START_DATE]
2017-12-09T02:01:25.899+01:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "mt6735", "BOARD": "l5460", "MODEL": "FEVER", "BOOTLOADER": "unknown", "DISPLAY": "alps-mp-m0.mp1-V2.39.1_tinno6735.35u.m0_P44", "CPU_ABI2": "armeabi", "FINGERPRINT": "WIKO/l5460/l5460:6.0/MRA58K/1460597594:user/release-keys", "TAGS": "release-keys", "HOST": "HTSVR7", "VERSION": {"PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 23, "SDK_INT": 23, "INCREMENTAL": "1460597594", "BASE_OS": "", "RELEASE": "6.0", "CODENAME": "REL", "SECURITY_PATCH": "2016-10-05", "ACTIVE_CODENAMES": [], "SDK": "23"}, "DEVICE": "l5460", "SERIAL": "0123456789ABCDEF", "ID": "MRA58K", "MANUFACTURER": "WIKO", "PRODUCT": "l5460", "BRAND": "WIKO", "IS_DEBUGGABLE": false, "SUPPORTED_64_BIT_ABIS": ["arm64-v8a"], "RADIO": "unknown", "CPU_ABI": "armeabi-v7a", "TIME": 1481770179000, "SUPPORTED_32_BIT_ABIS": ["armeabi-v7a", "armeabi"], "TYPE": "user", "SUPPORTED_ABIS": ["arm64-v8a", "armeabi-v7a", "armeabi"], "USER": "android"}


[DUMPSYS_MEMINFO]
Permission Denial: can't dump meminfo from from pid=14110, uid=10066 without permission android.permission.DUMP


[USER_EMAIL]
N/A


[REPORT_ID]
fa13ace5-c6b9-48a9-a894-4071c5734060


[PRODUCT]
l5460


[PACKAGE_NAME]
com.flowcrypt.email


[BRAND]
WIKO


[ANDROID_VERSION]
6.0


[APP_VERSION_CODE]
40


[IS_SILENT]
false


[CUSTOM_DATA]
{}


This was on Gmail. It only happened once - cannot reproduce again. 

I clicked on it again and it worked.

--
Human at FlowCrypt, formerly called CryptUp (ask me to try our Android app). 

Show quoted text

```

**Comment by DenBond7** [comment]
deprecated
