### ISSUE TITLE
Could not send a password-protected message if 'to' doesn't contain recipients without pub keys

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1731]
It relates to the enterprise issue with password-protected messages

```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
com.flowcrypt.email.util.exception.ApiException: API error: code = 400, message = Bad Request


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.jetpack.workmanager.HandlePasswordProtectedMsgWorker$handleExceptionsForMessage$2.invokeSuspend(HandlePasswordProtectedMsgWorker.kt:231)
        at com.flowcrypt.email.jetpack.workmanager.HandlePasswordProtectedMsgWorker$handleExceptionsForMessage$2.invoke(Unknown Source:8)
        at com.flowcrypt.email.jetpack.workmanager.HandlePasswordProtectedMsgWorker$handleExceptionsForMessage$2.invoke(Unknown Source:4)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
        at com.flowcrypt.email.jetpack.workmanager.HandlePasswordProtectedMsgWorker.handleExceptionsForMessage(HandlePasswordProtectedMsgWorker.kt:230)
        at com.flowcrypt.email.jetpack.workmanager.HandlePasswordProtectedMsgWorker.access$handleExceptionsForMessage(HandlePasswordProtectedMsgWorker.kt:71)
        at com.flowcrypt.email.jetpack.workmanager.HandlePasswordProtectedMsgWorker$prepareAndUploadPasswordProtectedMsgsToFES$2.invokeSuspend(HandlePasswordProtectedMsgWorker.kt:207)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:147)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.UndispatchedCoroutine.afterResume(CoroutineContext.kt:147)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: com.flowcrypt.email.util.exception.ApiException: API error: code = 400, message = Bad Request
        at com.flowcrypt.email.api.retrofit.base.BaseApiRepository$DefaultImpls.getResult(BaseApiRepository.kt:64)
        at com.flowcrypt.email.api.retrofit.base.BaseApiRepository$getResult$1.invokeSuspend(Unknown Source:18)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        ... 7 more
```

```json
{
   "code":400,
   "message":"Missing recipient",
   "details":"For more details, see FlowCrypt Enterprise Server logs."
}
```

**Comment by DenBond7** [comment]
It happens for the following case

![image](https://user-images.githubusercontent.com/2863246/161703033-c243e562-a4d9-4426-9d5d-5a231237e135.png)

We use the following request (#1615)

```json
{
   "associateReplyToken":"******",
   "bcc":[
      
   ],
   "cc":[
      "test@test.test"
   ],
   "from":"Den \u003cden@flowcrypt.com\u003e",
   "to":[
      
   ]
}
```

I thought we should create `MessageUploadRequest` only with recipients that don't have a public key.

https://github.com/FlowCrypt/flowcrypt-android/blob/316cf32c7778f8178ce2384547f14637d029cba2/FlowCrypt/src/main/java/com/flowcrypt/email/jetpack/workmanager/HandlePasswordProtectedMsgWorker.kt#L316

 @tomholub Am I wrong?

Should I use all recipients that were provided by a user to create `MessageUploadRequest`?

**Comment by tomholub** [comment]
Let me check, not sure myself.

**Comment by DenBond7** [comment]
It seems other recipients can be used for replyAll

![image](https://user-images.githubusercontent.com/2863246/161735270-64e0dbe1-665a-4fee-8370-dc0288dcc24e.png)

**Comment by tomholub** [comment]
Which means it should contain all of them. I just checked on browser extension, which works in this scenario: it sends all.

@martgil please check this scenario on iOS

**Comment by tomholub** [comment]
@martgil please add documentation to the OpenAPI comments on flowcrypt-enterprise-on-prem code that says on this call that recipients must be all recipients, not only password recipients. And that these are used for reply-all functionality.

**Comment by DenBond7** [comment]
One more question

```kotlin
val replyInfoData = ReplyInfoData(
              sender = fromAddress.address,
              recipient = (toCandidates + ccCandidates + bccCandidates)
                .mapNotNull { (it as? InternetAddress)?.address }
                .filterNot {
                  it.equals(fromAddress.address, true)
                },
              subject = plainMimeMsgWithAttachments.subject,
              token = replyToken
            )

            //prepare bodyWithReplyToken
            val replyInfo = Base64.getEncoder().encodeToString(
              GsonBuilder().create().toJson(replyInfoData).toByteArray()
            )
```

what about `ReplyInfoData.recipient`? Should it contain all recipients too?

**Comment by tomholub** [comment]
Here is the browser extension code

```
  const recipients = getUniqueRecipientEmails(newMsgData.recipients);
    try {
      const response = await this.view.acctServer.messageToken(authInfo);
      const infoDiv = Ui.e('div', {
        'style': 'display: none;',
        'class': 'cryptup_reply',
        'cryptup-data': Str.htmlAttrEncode({
          sender: newMsgData.from,
          recipient: Value.arr.withoutVal(Value.arr.withoutVal(recipients, newMsgData.from), this.acctEmail),
          subject: newMsgData.subject,
          token: response.replyToken,
        })
      });
```

Seems to send all, unique, with the sender removed.

**Comment by tomholub** [comment]
You can let the customer know we'll release a fix
