### ISSUE TITLE
java.io.IOException: NetworkError

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#182]
Looks like a silent error. Should anything be done about it?
```
[STACK_TRACE]
java.io.IOException: NetworkError
        at com.google.android.gms.auth.zze.zzac(Unknown Source)
        at com.google.android.gms.auth.zzd.zza(Unknown Source)
        at com.google.android.gms.auth.zzd.zzb(Unknown Source)
        at com.google.android.gms.auth.zzd.getToken(Unknown Source)
        at com.google.android.gms.auth.zzd.getToken(Unknown Source)
        at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:70)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:139)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:458)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:487)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:555)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)



[LOGCAT]
--------- beginning of main
01-10 14:21:49.228 I/art     (28891): Late-enabling -Xcheck:jni
01-10 14:21:49.337 I/art     (28891): Starting a blocking GC AddRemoveAppImageSpace
01-10 14:21:50.791 I/ACRA    (28891): ACRA is enabled for com.flowcrypt.email.debug, initializing...
01-10 14:21:50.839 I/InstantRun(28891): starting instant run server: is main process
01-10 14:21:53.408 I/System.out(28891): [crypt, up, cryptup, flow, flowcrypt, encryption, pgp, email, set, backup, passphrase, best, pass, phrases, are, long, and, have, several, words, in, them, Best pass phrases are long, have several words, in them, bestpassphrasesarelong, haveseveralwords, inthem, Loss of this pass phrase, cannot be recovered, Note it down, on a paper, lossofthispassphrase, cannotberecovered, noteitdown, onapaper, setpassword, set password, set pass word, setpassphrase, set pass phrase, set passphrase]
01-10 14:21:53.419 I/System.out(28891): false
01-10 14:21:53.419 I/System.out(28891): 10
01-10 14:21:53.419 I/System.out(28891): 7 seconds
01-10 14:21:53.419 I/System.out(28891): weak
01-10 14:21:53.419 I/System.out(28891): red
01-10 14:21:53.426 I/MultiDex(28891): VM with version 2.1.0 has multidex support
01-10 14:21:53.426 I/MultiDex(28891): Installing application
01-10 14:21:53.426 I/MultiDex(28891): VM has multidex support, MultiDex support library is disabled.
01-10 14:21:53.482 D/EmailSyncService(28891): onCreate
01-10 14:21:53.738 D/EmailSyncService(28891): onStartCommand |intent =null|flags = 0|startId = 8
01-10 14:21:53.738 D/EmailSyncManager(28891): beginSync | isResetNeeded = false
01-10 14:21:53.744 D/ActiveSyncTaskRunnable(28891):  run!
01-10 14:21:53.744 D/ActiveSyncTaskRunnable(28891): ActiveSyncTaskBlockingQueue size = 1
01-10 14:21:53.744 D/EmailSyncService(28891): onActionProgress: accountDaocom.flowcrypt.email.database.dao.source.AccountDao@2abdd1| ownerKey =null| requestCode =0
01-10 14:21:53.744 D/ActiveSyncTaskRunnable(28891): Not connected. Start a reconnection ...
01-10 14:21:53.744 D/EmailSyncService(28891): onActionProgress: accountDaocom.flowcrypt.email.database.dao.source.AccountDao@2abdd1| ownerKey =null| requestCode =0
01-10 14:21:53.745 D/PassiveSyncTaskRunnable(28891):  run!
01-10 14:21:53.745 D/PassiveSyncTaskRunnable(28891): PassiveSyncTaskBlockingQueue size = 0
01-10 14:21:53.747 W/art     (28891): Before Android 4.1, method javax.mail.Session com.sun.mail.imap.IMAPStore.getSession() would have incorrectly overridden the package-private method in javax.mail.Service
01-10 14:21:54.072 I/System.out(28891): DEBUG: setDebug: JavaMail version 1.6.0
01-10 14:21:54.077 I/System.out(28891): DEBUG: getProvider() returning javax.mail.Provider[STORE,gimaps,com.sun.mail.gimap.GmailSSLStore,Oracle]
01-10 14:21:54.101 I/System.out(28891): DEBUG GIMAPS: mail.imap.fetchsize: 16384
01-10 14:21:54.101 I/System.out(28891): DEBUG GIMAPS: mail.imap.ignorebodystructuresize: false
01-10 14:21:54.101 I/System.out(28891): DEBUG GIMAPS: mail.imap.statuscachetimeout: 1000
01-10 14:21:54.101 I/System.out(28891): DEBUG GIMAPS: mail.imap.appendbuffersize: -1
01-10 14:21:54.102 I/System.out(28891): DEBUG GIMAPS: mail.imap.minidletime: 10
01-10 14:21:54.102 I/System.out(28891): DEBUG GIMAPS: closeFoldersOnStoreFailure
01-10 14:21:54.282 W/System.err(28891): java.io.IOException: NetworkError
01-10 14:21:54.285 W/System.err(28891):         at com.google.android.gms.auth.zze.zzac(Unknown Source)
01-10 14:21:54.285 W/System.err(28891):         at com.google.android.gms.auth.zzd.zza(Unknown Source)
01-10 14:21:54.285 W/System.err(28891):         at com.google.android.gms.auth.zzd.zzb(Unknown Source)
01-10 14:21:54.285 W/System.err(28891):         at com.google.android.gms.auth.zzd.getToken(Unknown Source)
01-10 14:21:54.285 W/System.err(28891):         at com.google.android.gms.auth.zzd.getToken(Unknown Source)
01-10 14:21:54.285 W/System.err(28891):         at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source)
01-10 14:21:54.285 W/System.err(28891):         at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:70)
01-10 14:21:54.285 W/System.err(28891):         at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:139)
01-10 14:21:54.285 W/System.err(28891):         at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:458)
01-10 14:21:54.285 W/System.err(28891):         at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:487)
01-10 14:21:54.286 W/System.err(28891):         at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:555)
01-10 14:21:54.286 W/System.err(28891):         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
01-10 14:21:54.286 W/System.err(28891):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-10 14:21:54.286 W/System.err(28891):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-10 14:21:54.286 W/System.err(28891):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-10 14:21:54.286 W/System.err(28891):         at java.lang.Thread.run(Thread.java:761)


[ENVIRONMENT]
{"getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getLegacyExternalStorageDirectory": "/sdcard", "getDataSystemDirectory": "/data/system", "getDataMiscDirectory": "/data/misc", "getDataSystemCeDirectory": "/data/system_ce", "getExternalStorageState": "mounted", "getStorageDirectory": "/storage", "getExpandDirectory": "/mnt/expand", "getOemDirectory": "/oem", "getExternalStorageDirectory": "/storage/emulated/0", "isExternalStorageEmulated": true, "getDataDirectory": "/data", "isExternalStorageRemovable": false, "getDataSystemDeDirectory": "/data/system_de", "getOdmDirectory": "/odm", "getRootDirectory": "/system", "getDownloadCacheDirectory": "/cache"}


[TOTAL_MEM_SIZE]
11746017280


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 45, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 1, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 504, "fontScale": 1, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 230, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 568, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DISPLAY]
{"0": {"refreshRate": 60, "metrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 403.4110107421875, "widthPixels": 1080, "heightPixels": 1776, "densityDpi": 480, "ydpi": 403.0409851074219}, "name": "Built-in Screen", "realSize": [1080, 1920], "isValid": true, "currentSizeRange": {"smallest": [1080, 1008], "largest": [1776, 1704]}, "rectSize": [0, 0, 1080, 1776], "height": 1776, "realMetrics": {"density": 3, "scaledDensity": "x3.0", "xdpi": 403.4110107421875, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 480, "ydpi": 403.0409851074219}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 1776], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
5126979584


[PHONE_MODEL]
Moto G (4)


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 45, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 1, "screenWidthDp": 360, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 504, "fontScale": 1, "smallestScreenWidthDp": 360, "densityDpi": 480, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 230, "compatScreenWidthDp": 320, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 568, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DEVICE_FEATURES]
{"com.google.preload_photos": true, "android.software.verified_boot": true, "com.motorola.software.storageoptimizer": true, "com.motorola.software.device.athene": true, "android.hardware.ethernet": true, "android.hardware.sensor.proximity": true, "android.software.input_methods": true, "com.motorola.software.fmradioservice": true, "com.motorola.easyprefix": true, "com.motorola.software.guideme": true, "android.software.device_admin": true, "android.hardware.faketouch": true, "android.software.backup": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "com.motorola.software.modality": true, "android.hardware.sensor.accelerometer": true, "com.motorola.hardware.tier.G": true, "com.motorola.actions": true, "com.motorola.software.x_line": true, "android.hardware.camera.flash": true, "android.hardware.sensor.light": true, "com.motorola.moto.MOTO_VOICE_DISABLED_4_3": true, "android.hardware.location.gps": true, "android.hardware.usb.accessory": true, "android.software.webview": true, "com.motorola.software.DirectedSMSProxy": true, "android.software.sip.voip": true, "android.hardware.microphone": true, "android.hardware.bluetooth": true, "android.hardware.location.network": true, "android.software.midi": true, "android.hardware.touchscreen.multitouch": true, "android.software.voice_recognizers": true, "android.hardware.touchscreen": true, "android.hardware.audio.output": true, "com.motorola.motodisplay.doze.glimpse": true, "android.hardware.bluetooth_le": true, "android.hardware.telephony": true, "android.hardware.sensor.stepcounter": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.hardware.sensor.gyroscope": true, "com.motorola.moto": true, "android.software.sip": true, "android.hardware.camera.autofocus": true, "android.software.live_wallpaper": true, "com.motorola.sensorhub.stml0xx": true, "android.hardware.camera.any": true, "android.hardware.telephony.gsm": true, "android.hardware.telephony.cdma": true, "android.hardware.camera": true, "com.motorola.hardware.wave.2016.1": true, "android.hardware.wifi": true, "android.software.print": true, "android.hardware.location": true, "android.software.home_screen": true, "com.motorola.cameraone": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.opengles.aep": true, "android.hardware.sensor.stepdetector": true, "android.hardware.usb.host": true, "android.hardware.screen.portrait": true, "android.software.managed_users": true, "com.motorola.software.product.athene_retail": true, "android.hardware.wifi.direct": true, "glEsVersion": "3.2", "android.hardware.screen.landscape": true, "com.motorola.msimsettings": true, "android.software.connectionservice": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email.debug", "VERSION_CODE": 41, "BUILD_TYPE": "debug", "DEBUG": true, "VERSION_NAME": "0.4.1_41__2018_01_07_20_02", "FLAVOR": "", "serialVersionUID": -6921988441490417973}


[FILE_PATH]
/data/user/0/com.flowcrypt.email.debug/files


[INSTALLATION_ID]
4f2781ea-fdf2-40db-bae4-f1fa3a76604c


[USER_CRASH_DATE]
2018-01-10T14:21:54.486+01:00


[HASH]
C96C983EEE


[APP_VERSION_NAME]
0.4.1_41__2018_01_07_20_02


[USER_APP_START_DATE]
2018-01-10T14:21:50.808+01:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "qcom", "BOARD": "msm8952", "MODEL": "Moto G (4)", "BOOTLOADER": "0xB106", "DISPLAY": "NPJ25.93-14.7", "CPU_ABI2": "armeabi", "FINGERPRINT": "motorola/athene/athene:7.0/NPJ25.93-14.7/7:user/release-keys", "IS_EMULATOR": false, "TAGS": "release-keys", "HOST": "ilclbld36", "VERSION": {"PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 24, "SDK_INT": 24, "INCREMENTAL": "7", "BASE_OS": "", "RELEASE": "7.0", "CODENAME": "REL", "SECURITY_PATCH": "2017-09-01", "ACTIVE_CODENAMES": [], "SDK": "24"}, "PERMISSIONS_REVIEW_REQUIRED": false, "DEVICE": "athene", "SERIAL": "ZY223GW7FS", "ID": "NPJ25.93-14.7", "MANUFACTURER": "motorola", "PRODUCT": "athene", "SUPPORTED_ABIS": ["armeabi-v7a", "armeabi"], "IS_DEBUGGABLE": false, "SUPPORTED_64_BIT_ABIS": [], "RADIO": "unknown", "CPU_ABI": "armeabi-v7a", "TIME": 1504111410000, "SUPPORTED_32_BIT_ABIS": ["armeabi-v7a", "armeabi"], "TYPE": "user", "BRAND": "motorola", "USER": "hudsoncm"}


[DUMPSYS_MEMINFO]



[USER_EMAIL]
N/A


[REPORT_ID]
2f523878-6817-4fa7-b5c2-2c1adbdafd74


[PRODUCT]
athene


[PACKAGE_NAME]
com.flowcrypt.email.debug


[BRAND]
motorola


[ANDROID_VERSION]
7.0


[APP_VERSION_CODE]
41


[IS_SILENT]
false


[CUSTOM_DATA]
{}
```

**Comment by DenBond7** [comment]
Such error is happening when the app can't receive a token from Google. Because has happened a network issue.(No connection for example). 

The app handles such errors correct. I have removed the notification of this error from the ACRA.
