### ISSUE TITLE
javax.mail.StoreClosedException: * BYE System Error (5A0659863E)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#183]
These happen while testing the app for 0.4.2
```
[STACK_TRACE]
javax.mail.StoreClosedException: * BYE System Error
        at com.sun.mail.imap.IMAPFolder.getMessageCount(IMAPFolder.java:1678)
        at com.flowcrypt.email.api.email.FoldersManager.generateFolder(FoldersManager.java:80)
        at com.flowcrypt.email.api.email.FoldersManager.prepareFolderKey(FoldersManager.java:280)
        at com.flowcrypt.email.api.email.FoldersManager.addFolder(FoldersManager.java:198)
        at com.flowcrypt.email.service.EmailSyncService.onFolderInfoReceived(EmailSyncService.java:402)
        at com.flowcrypt.email.api.email.sync.tasks.UpdateLabelsSyncTask.runIMAPAction(UpdateLabelsSyncTask.java:43)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:503)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:559)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by DenBond7** [comment]
http://mutt-dev.mutt.narkive.com/yIix2HyU/3106-bye-system-error-from-gmail
https://productforums.google.com/forum/#!topic/gmail/Tfyn8mufldI
https://stackoverflow.com/questions/16622132/imaplib2-imap-gmail-com-handler-bye-response-system-error
https://community.oracle.com/thread/2419792?start=0
http://markmail.org/message/qqvloo7vnom7sssi#query:+page:1+mid:3f7f3pgo4kyzoljl+state:results
https://www.limilabs.com/qa/1126/gmail-error-message-bye-system-error
http://getpopfile.org/discussion/3/85

All of this links contain information about such issue. But no one doesn't contain 100% right answer.

**Comment by DenBond7** [comment]
As I understood this is a Gmail server error. I investigated logs and saw that it happened in the same place. I changed the source code and I think it will help us.

**Comment by DenBond7** [comment]
@tomholub One more question: how does the application behave after such an error? I can not reproduce the error on my phone.

**Comment by tomholub** [comment]
@DenBond7 I'm not sure if it happened on mine, but it if did, I did not notice it yet. Not sure.

**Comment by tomholub** [comment]
@DenBond7 Ah I see that I submitted it myself. I think there was no visible bad behavior, if the app crashed etc, I would not have released it.

**Comment by DenBond7** [comment]
Ok, I close this issue now. We will reopen it if need in the future
