### ISSUE TITLE
Fix navigation issue in FixNeedPassphraseIssueDialogFragment

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1838]
```
[SUMMARY]
java.lang.IllegalArgumentException: Navigation action/destination com.flowcrypt.email.enterprise:id/action_securitySettingsFragment_to_checkPassphraseStrengthFragment cannot be found from the current destination Destination(com.flowcrypt.email.enterprise:id/fixNeedPassphraseIssueDialogFragment)


[STACK_TRACE]
java.lang.IllegalArgumentException: Navigation action/destination com.flowcrypt.email.enterprise:id/action_securitySettingsFragment_to_checkPassphraseStrengthFragment cannot be found from the current destination Destination(com.flowcrypt.email.enterprise:id/fixNeedPassphraseIssueDialogFragment)
        at androidx.navigation.NavController.navigate(NavController.java:940)
        at androidx.navigation.NavController.navigate(NavController.java:877)
        at androidx.navigation.NavController.navigate(NavController.java:863)
        at androidx.navigation.NavController.navigate(NavController.java:1159)
        at com.flowcrypt.email.ui.activity.fragment.preferences.SecuritySettingsFragment.navigateToCheckPassphraseStrengthFragment(SecuritySettingsFragment.kt:104)
        at com.flowcrypt.email.ui.activity.fragment.preferences.SecuritySettingsFragment.access$navigateToCheckPassphraseStrengthFragment(SecuritySettingsFragment.kt:32)
        at com.flowcrypt.email.ui.activity.fragment.preferences.SecuritySettingsFragment$subscribeFixNeedPassphraseIssueDialogFragment$1.invoke(SecuritySettingsFragment.kt:99)
        at com.flowcrypt.email.ui.activity.fragment.preferences.SecuritySettingsFragment$subscribeFixNeedPassphraseIssueDialogFragment$1.invoke(SecuritySettingsFragment.kt:98)
        at [androidx.fragment.app](http://androidx.fragment.app/).FragmentKt.setFragmentResultListener$lambda-0(Fragment.kt:65)
        at [androidx.fragment.app](http://androidx.fragment.app/).FragmentKt.$r8$lambda$i257It-r9epgOyGhyTl2zq_C8dk(Unknown Source:0)
        at [androidx.fragment.app](http://androidx.fragment.app/).FragmentKt$$ExternalSyntheticLambda0.onFragmentResult(Unknown Source:2)
        at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager$LifecycleAwareResultListener.onFragmentResult(FragmentManager.java:235)
        at [androidx.fragment.app](http://androidx.fragment.app/).FragmentManager.setFragmentResult(FragmentManager.java:866)
        at [androidx.fragment.app](http://androidx.fragment.app/).FragmentKt.setFragmentResult(Fragment.kt:33)
        at com.flowcrypt.email.ui.activity.fragment.dialog.FixNeedPassphraseIssueDialogFragment.setupCheckPrivateKeysViewModel$lambda-15(FixNeedPassphraseIssueDialogFragment.kt:237)
        at com.flowcrypt.email.ui.activity.fragment.dialog.FixNeedPassphraseIssueDialogFragment.$r8$lambda$6n7heBlLM2SMLgd5LaxkNA0TeD4(Unknown Source:0)
        at com.flowcrypt.email.ui.activity.fragment.dialog.FixNeedPassphraseIssueDialogFragment$$ExternalSyntheticLambda4.onChanged(Unknown Source:4)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.flowcrypt.email.jetpack.viewmodel.CheckPrivateKeysViewModel$checkKeys$1.invokeSuspend(CheckPrivateKeysViewModel.kt:43)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:234)
        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:190)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:161)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1412)
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1519)
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323)
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240)
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906)
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863)
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f18728d, Dispatchers.Main.immediate]
```

**Comment by DenBond7** [comment]
same as #1835
