### ISSUE TITLE
Fix navigation issue in AddOtherAccountFragment

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1839]
```
[SUMMARY]
java.lang.IllegalArgumentException: Navigation action/destination com.flowcrypt.email:id/action_mainSignInFragment_to_addOtherAccountFragment cannot be found from the current destination Destination(com.flowcrypt.email:id/addOtherAccountFragment) class=com.flowcrypt.email.ui.activity.fragment.AddOtherAccountFragment


[STACK_TRACE]
java.lang.IllegalArgumentException: Navigation action/destination com.flowcrypt.email:id/action_mainSignInFragment_to_addOtherAccountFragment cannot be found from the current destination Destination(com.flowcrypt.email:id/addOtherAccountFragment) class=com.flowcrypt.email.ui.activity.fragment.AddOtherAccountFragment
        at androidx.navigation.NavController.navigate(NavController.java:940)
        at androidx.navigation.NavController.navigate(NavController.java:877)
        at androidx.navigation.NavController.navigate(NavController.java:863)
        at androidx.navigation.NavController.navigate(NavController.java:1159)
        at com.flowcrypt.email.ui.activity.fragment.MainSignInFragment.initViews$lambda-2(MainSignInFragment.kt:177)
        at com.flowcrypt.email.ui.activity.fragment.MainSignInFragment.$r8$lambda$3fxMbL7kyhbYaaCqK44F9ZEPm2A(Unknown Source:0)
        at com.flowcrypt.email.ui.activity.fragment.MainSignInFragment$$ExternalSyntheticLambda2.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7455)
        at android.view.View.performClickInternal(View.java:7432)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28810)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7870)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by DenBond7** [comment]
same as https://github.com/FlowCrypt/flowcrypt-android/issues/1835
