### ISSUE TITLE
NPE in LoadGmailAliasesLoader

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#185]
```
[STACK_TRACE]
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:67)
        at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:34)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$532ebdd5(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        ... 3 more
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:67)
        at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:34)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$532ebdd5(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by DenBond7** [comment]
ref [160eacb2234fbd59](https://mail.google.com/mail/u/0/#inbox/160eacb2234fbd59)

**Comment by DenBond7** [comment]
I have moved this to "later". It's a strange error.

It happened on line 67. But if alias == null ==> we must received NPE error on line 61.

![image](https://user-images.githubusercontent.com/2863246/34883545-8e7782ec-f7c2-11e7-8eaa-6ba7a693c32e.png)

I don't think that this is a normal error. I think it's a bug with Gmail API. This is rather an exception to the rules

**Comment by DenBond7** [comment]
#192
