### ISSUE TITLE
J2V8 Threading error

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#187]
```
[STACK_TRACE]
java.lang.Error: Invalid V8 thread access: current thread is Thread[main,5,main] while the locker has thread Thread[ModernAsyncTask #3,5,main]
        at com.eclipsesource.v8.V8Locker.checkThread(V8Locker.java:99)
        at com.eclipsesource.v8.V8.checkThread(V8.java:771)
        at com.eclipsesource.v8.V8Object.<init>(V8Object.java:43)
        at com.eclipsesource.v8.V8Object.<init>(V8Object.java:37)
        at com.eclipsesource.v8.V8Array.<init>(V8Array.java:32)
        at com.flowcrypt.email.js.Js.crypto_key_longid(Js.java:152)
        at com.flowcrypt.email.js.PgpKey.getLongid(PgpKey.java:34)
        at com.flowcrypt.email.database.dao.source.KeysDaoSource.removeKey(KeysDaoSource.java:143)
        at com.flowcrypt.email.ui.activity.CreatePrivateKeyActivity.onBackPressed(CreatePrivateKeyActivity.java:122)
        at android.app.Activity.onKeyUp(Activity.java:2725)
        at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
        at android.app.Activity.dispatchKeyEvent(Activity.java:3026)
        at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
        at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
        at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
        at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
        at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
        at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
        at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
        at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
        at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)



[LOGCAT]
01-16 05:25:37.410 D/OkHttp  (26748): Access-Control-Allow-Headers: Content-Type, api-version, user-account, user-uuid, user-token
01-16 05:25:37.410 D/OkHttp  (26748): {"sent": true}
01-16 05:25:37.410 D/OkHttp  (26748): <-- END HTTP (14-byte body)
01-16 05:25:42.818 W/IInputConnectionWrapper(26748): finishComposingText on inactive InputConnection
01-16 05:27:22.198 E/InputEventSender(26748): Exception dispatching finished signal.
01-16 05:27:22.198 E/MessageQueue-JNI(26748): Exception in MessageQueue callback: handleReceiveCallback
01-16 05:27:22.219 E/MessageQueue-JNI(26748): java.lang.Error: Invalid V8 thread access: current thread is Thread[main,5,main] while the locker has thread Thread[ModernAsyncTask #3,5,main]
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.eclipsesource.v8.V8Locker.checkThread(V8Locker.java:99)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.eclipsesource.v8.V8.checkThread(V8.java:771)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.eclipsesource.v8.V8Object.<init>(V8Object.java:43)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.eclipsesource.v8.V8Object.<init>(V8Object.java:37)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.eclipsesource.v8.V8Array.<init>(V8Array.java:32)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.flowcrypt.email.js.Js.crypto_key_longid(Js.java:152)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.flowcrypt.email.js.PgpKey.getLongid(PgpKey.java:34)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.flowcrypt.email.database.dao.source.KeysDaoSource.removeKey(KeysDaoSource.java:143)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.flowcrypt.email.ui.activity.CreatePrivateKeyActivity.onBackPressed(CreatePrivateKeyActivity.java:122)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.app.Activity.onKeyUp(Activity.java:2725)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.app.Activity.dispatchKeyEvent(Activity.java:3026)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.os.MessageQueue.nativePollOnce(Native Method)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.os.MessageQueue.next(MessageQueue.java:323)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.os.Looper.loop(Looper.java:136)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at android.app.ActivityThread.main(ActivityThread.java:6119)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at java.lang.reflect.Method.invoke(Native Method)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-16 05:27:22.219 E/MessageQueue-JNI(26748):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
01-16 05:27:22.219 D/AndroidRuntime(26748): Shutting down VM
01-16 05:27:22.219 E/ACRA    (26748): ACRA caught a Error for com.flowcrypt.email.debug
01-16 05:27:22.219 E/ACRA    (26748): java.lang.Error: Invalid V8 thread access: current thread is Thread[main,5,main] while the locker has thread Thread[ModernAsyncTask #3,5,main]
01-16 05:27:22.219 E/ACRA    (26748):   at com.eclipsesource.v8.V8Locker.checkThread(V8Locker.java:99)
01-16 05:27:22.219 E/ACRA    (26748):   at com.eclipsesource.v8.V8.checkThread(V8.java:771)
01-16 05:27:22.219 E/ACRA    (26748):   at com.eclipsesource.v8.V8Object.<init>(V8Object.java:43)
01-16 05:27:22.219 E/ACRA    (26748):   at com.eclipsesource.v8.V8Object.<init>(V8Object.java:37)
01-16 05:27:22.219 E/ACRA    (26748):   at com.eclipsesource.v8.V8Array.<init>(V8Array.java:32)
01-16 05:27:22.219 E/ACRA    (26748):   at com.flowcrypt.email.js.Js.crypto_key_longid(Js.java:152)
01-16 05:27:22.219 E/ACRA    (26748):   at com.flowcrypt.email.js.PgpKey.getLongid(PgpKey.java:34)
01-16 05:27:22.219 E/ACRA    (26748):   at com.flowcrypt.email.database.dao.source.KeysDaoSource.removeKey(KeysDaoSource.java:143)
01-16 05:27:22.219 E/ACRA    (26748):   at com.flowcrypt.email.ui.activity.CreatePrivateKeyActivity.onBackPressed(CreatePrivateKeyActivity.java:122)
01-16 05:27:22.219 E/ACRA    (26748):   at android.app.Activity.onKeyUp(Activity.java:2725)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.KeyEvent.dispatch(KeyEvent.java:2712)
01-16 05:27:22.219 E/ACRA    (26748):   at android.app.Activity.dispatchKeyEvent(Activity.java:3026)
01-16 05:27:22.219 E/ACRA    (26748):   at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:534)
01-16 05:27:22.219 E/ACRA    (26748):   at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:58)
01-16 05:27:22.219 E/ACRA    (26748):   at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:316)
01-16 05:27:22.219 E/ACRA    (26748):   at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:319)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4331)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4302)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4032)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:4193)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2400)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1964)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1955)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2377)
01-16 05:27:22.219 E/ACRA    (26748):   at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
01-16 05:27:22.219 E/ACRA    (26748):   at android.os.MessageQueue.nativePollOnce(Native Method)
01-16 05:27:22.219 E/ACRA    (26748):   at android.os.MessageQueue.next(MessageQueue.java:323)
01-16 05:27:22.219 E/ACRA    (26748):   at android.os.Looper.loop(Looper.java:136)
01-16 05:27:22.219 E/ACRA    (26748):   at android.app.ActivityThread.main(ActivityThread.java:6119)
01-16 05:27:22.219 E/ACRA    (26748):   at java.lang.reflect.Method.invoke(Native Method)
01-16 05:27:22.219 E/ACRA    (26748):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
01-16 05:27:22.219 E/ACRA    (26748):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)


[ENVIRONMENT]
{"getDataSystemDirectory": "/data/system", "getDataPreloadsDirectory": "/data/preloads", "getOdmDirectory": "/odm", "getDataMiscDirectory": "/data/misc", "getDataSystemCeDirectory": "/data/system_ce", "getExpandDirectory": "/mnt/expand", "getRootDirectory": "/system", "getLegacyExternalStorageDirectory": "/sdcard", "getDataPreloadsAppsDirectory": "/data/preloads/apps", "getDataPreloadsDemoDirectory": "/data/preloads/demo", "getDataPreloadsMediaDirectory": "/data/preloads/media", "isExternalStorageEmulated": true, "isExternalStorageRemovable": false, "getDownloadCacheDirectory": "/cache", "getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getExternalStorageState": "mounted", "getStorageDirectory": "/storage", "getExternalStorageDirectory": "/storage/emulated/0", "getOemDirectory": "/oem", "getDataDirectory": "/data", "getDataSystemDeDirectory": "/data/system_de"}


[TOTAL_MEM_SIZE]
13375950848


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 7, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 270, "screenWidthDp": 411, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 512, "fontScale": 1, "smallestScreenWidthDp": 411, "densityDpi": 420, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 659, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_NO", "navigation": "NAVIGATION_DPAD"}


[DISPLAY]
{"0": {"refreshRate": 60.000003814697266, "metrics": {"density": 2.625, "scaledDensity": "x2.625", "xdpi": 420, "widthPixels": 1080, "heightPixels": 1794, "densityDpi": 420, "ydpi": 420}, "name": "Built-in Screen", "realSize": [1080, 1920], "isValid": true, "currentSizeRange": {"smallest": [1080, 1017], "largest": [1794, 1731]}, "rectSize": [0, 0, 1080, 1794], "height": 1794, "realMetrics": {"density": 2.625, "scaledDensity": "x2.625", "xdpi": 420, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 420, "ydpi": 420}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 1794], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
9463570432


[PHONE_MODEL]
Google Nexus 5X - 7.1.0 - API 25 - 1080x1920


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 7, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 270, "screenWidthDp": 411, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 512, "fontScale": 1, "smallestScreenWidthDp": 411, "densityDpi": 420, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 659, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_NO", "navigation": "NAVIGATION_DPAD"}


[DEVICE_FEATURES]
{"android.software.input_methods": true, "android.software.managed_users": true, "android.hardware.faketouch": true, "android.software.backup": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "android.software.live_wallpaper": true, "android.hardware.sensor.accelerometer": true, "android.hardware.telephony": true, "android.hardware.telephony.gsm": true, "com.google.android.feature.EXCHANGE_6_2": true, "android.hardware.location.gps": true, "android.hardware.usb.accessory": true, "android.software.webview": true, "android.software.sip.voip": true, "android.hardware.microphone": true, "android.hardware.location.network": true, "android.hardware.touchscreen.multitouch": true, "android.software.voice_recognizers": true, "android.hardware.touchscreen": true, "com.google.android.feature.GOOGLE_EXPERIENCE": true, "android.hardware.audio.output": true, "com.google.android.feature.GOOGLE_BUILD": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.software.sip": true, "android.hardware.camera.any": true, "android.hardware.camera": true, "android.hardware.wifi": true, "android.software.print": true, "android.software.home_screen": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.screen.portrait": true, "android.hardware.location": true, "android.software.device_admin": true, "glEsVersion": "2.0", "android.hardware.screen.landscape": true, "android.hardware.usb.host": true, "android.software.connectionservice": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email.debug", "VERSION_CODE": 42, "BUILD_TYPE": "debug", "DEBUG": true, "VERSION_NAME": "0.4.2_42__2018_01_16_12_24", "FLAVOR": ""}


[FILE_PATH]
/data/user/0/com.flowcrypt.email.debug/files


[INSTALLATION_ID]
51037c5b-6514-473e-954f-0f302ea4fe14


[USER_CRASH_DATE]
2018-01-16T05:27:22.238-05:00


[HASH]
D6E3FE78CC


[APP_VERSION_NAME]
0.4.2_42__2018_01_16_12_24


[USER_APP_START_DATE]
2018-01-16T05:24:36.179-05:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "vbox86", "BOARD": "unknown", "MODEL": "Google Nexus 5X - 7.1.0 - API 25 - 1080x1920", "BOOTLOADER": "unknown", "DISPLAY": "vbox86p-userdebug 7.1.1 NMF26Q eng.genymo.20170320.224321 test-keys", "CPU_ABI2": "armeabi-v7a", "FINGERPRINT": "Android/vbox86p/vbox86p:7.1.1/NMF26Q/genymo03202243:userdebug/test-keys", "IS_EMULATOR": true, "TAGS": "test-keys", "HOST": "94993daba111", "VERSION": {"PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 25, "SDK_INT": 25, "INCREMENTAL": "eng.genymo.20170320.224321", "BASE_OS": "", "RELEASE": "7.1.1", "CODENAME": "REL", "SECURITY_PATCH": "2016-12-05", "ACTIVE_CODENAMES": [], "SDK": "25"}, "PERMISSIONS_REVIEW_REQUIRED": false, "DEVICE": "vbox86p", "SERIAL": "unknown", "ID": "NMF26Q", "MANUFACTURER": "Genymotion", "PRODUCT": "vbox86p", "SUPPORTED_ABIS": ["x86", "armeabi-v7a", "armeabi"], "IS_DEBUGGABLE": true, "SUPPORTED_64_BIT_ABIS": [], "RADIO": "unknown", "CPU_ABI": "x86", "TIME": 1490049801000, "SUPPORTED_32_BIT_ABIS": ["x86", "armeabi-v7a", "armeabi"], "TYPE": "userdebug", "BRAND": "Android", "USER": "genymotion"}


[DUMPSYS_MEMINFO]
Permission Denial: can't dump meminfo from from pid=26965, uid=10294 without permission android.permission.DUMP


[USER_EMAIL]
N/A


[REPORT_ID]
48972b6d-980d-4499-80bc-c28518291cf6


[PRODUCT]
vbox86p


[PACKAGE_NAME]
com.flowcrypt.email.debug


[BRAND]
Android


[ANDROID_VERSION]
7.1.1


[APP_VERSION_CODE]
42


[IS_SILENT]
false


[CUSTOM_DATA]
{}

```

**Comment by DenBond7** [comment]
It happened while testing the app.

**Comment by tomholub** [comment]
Ah, I thought it was related to the new release! I'll improve the emails to make them clearer.
