### ISSUE TITLE
GoogleSignInAccount is null

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#188]
```
[STACK_TRACE]
java.lang.NullPointerException: GoogleSignInAccount is null!
at com.flowcrypt.email.ui.activity.SplashActivity.addGmailAccount(SplashActivity.java:302)
at com.flowcrypt.email.ui.activity.SplashActivity.runEmailManagerActivityWithCurrentGmailAccount(SplashActivity.java:257)
at com.flowcrypt.email.ui.activity.SplashActivity.onActivityResult(SplashActivity.java:115)
at android.app.Activity.dispatchActivityResult(Activity.java:6932)
at android.app.ActivityThread.deliverResults(ActivityThread.java:4085)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3403)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3469)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)



[LOGCAT]
01-16 06:39:13.128 I/System.out(30084): /8DTK1eV+PYwvZXGjr+yVSCvD4I3kK/gOsXPPRsz8XoyP5ZOasy7T9MTM+9i
01-16 06:39:13.128 I/System.out(30084): MXenRabB1EhY8/37CKoITpAV1RSgcYpRJvTe4KoWGVvByIn5KCspYf41MAZU
01-16 06:39:13.128 I/System.out(30084): 3ui4hc4Dr0s0QngMboQxKhZNnyqAIgM4ylPtLIePNXSKnDdY6GHttIfPzDjZ
01-16 06:39:13.128 I/System.out(30084): Nh7IMxARVs3OcJj4z4SBGgqSOTRSwC+KIvfJMmZuu2obrfnah8LAXwQYAQgA
01-16 06:39:13.128 I/System.out(30084): EwUCWl3kYAkQDlmyvB/xBusCGwwAAJv/B/4x/Aq0eG/0S8KbRvKzNO3qPapu
01-16 06:39:13.128 I/System.out(30084): bKkDEuXA9G+afbUH7SaitZLCuDm1qLRGM7+riMd17VMkaFx5bQgPM3G96nnK
01-16 06:39:13.128 I/System.out(30084): Axl+lJeP+nwdYwEzTeHyoBQKBriEpl2+JV8LHaglPEs6NO6x6xtBqfQJFo1P
01-16 06:39:13.128 I/System.out(30084): EKNmAMTKP9K3MF3/OdMVCCh3JVg/CdbxlW2IC8JF3tENWUd2p/F1wnr+ZPJa
01-16 06:39:13.128 I/System.out(30084): 0H8rSjhn3eKEgkIny8sU0Kg4sTEDEuWMe00SDBSrcaajgJ3oVyiV+c4UjH+1
01-16 06:39:13.128 I/System.out(30084): rhGKtJ3cROaVM9yDjoOyjxaKwq9ZnrL0ftMrRFrvotAa5TAyl7ZMnqFDBluJ
01-16 06:39:13.128 I/System.out(30084): nN/+VizOfk19Qw4X
01-16 06:39:13.128 I/System.out(30084): =fYLn
01-16 06:39:13.128 I/System.out(30084): -----END PGP PRIVATE KEY BLOCK-----
01-16 06:39:13.128 I/System.out(30084): ------=_Part_0_126305476.1516102752789--
01-16 06:39:13.128 I/System.out(30084): .
01-16 06:39:13.835 I/System.out(30084): 250 2.0.0 OK 1516102751 h62sm343424lfh.3 - gsmtp
01-16 06:39:13.836 I/System.out(30084): DEBUG SMTP: message successfully delivered to mail server
01-16 06:39:13.855 D/OkHttp (30084): --> POST https://attester.flowcrypt.com/initial/legacy_submit
01-16 06:39:13.855 D/OkHttp (30084): Content-Type: application/json; charset=UTF-8
01-16 06:39:13.855 D/OkHttp (30084): Content-Length: 2419
01-16 06:39:13.855 D/OkHttp (30084): api-version: 3
01-16 06:39:13.855 D/OkHttp (30084): {"attest":false,"email":"denbond7test@gmail.com","pubkey":"



\r\n\r\n"}
01-16 06:39:13.855 D/OkHttp (30084): --> END POST (2419-byte body)
01-16 06:39:13.949 I/art (30084): Do partial code cache collection, code=124KB, data=103KB
01-16 06:39:13.950 I/art (30084): After code cache collection, code=124KB, data=103KB
01-16 06:39:13.950 I/art (30084): Increasing code cache capacity to 512KB
01-16 06:39:14.270 D/OkHttp (30084): <-- 200 OK https://attester.flowcrypt.com/initial/legacy_submit (414ms)
01-16 06:39:14.270 D/OkHttp (30084): Server: nginx/1.10.3 (Ubuntu)
01-16 06:39:14.270 D/OkHttp (30084): Date: Tue, 16 Jan 2018 11:39:12 GMT
01-16 06:39:14.270 D/OkHttp (30084): Content-Type: application/json
01-16 06:39:14.270 D/OkHttp (30084): Content-Length: 55
01-16 06:39:14.270 D/OkHttp (30084): Connection: keep-alive
01-16 06:39:14.270 D/OkHttp (30084): Access-Control-Allow-Origin: *
01-16 06:39:14.270 D/OkHttp (30084): Access-Control-Allow-Headers: Content-Type, api-version, user-account, user-uuid, user-token
01-16 06:39:14.270 D/OkHttp (30084): {"attested": false, "saved": false, "attesting": false}
01-16 06:39:14.271 D/OkHttp (30084): <-- END HTTP (55-byte body)
01-16 06:39:14.288 D/OkHttp (30084): --> POST https://attester.flowcrypt.com/test/welcome
01-16 06:39:14.288 D/OkHttp (30084): Content-Type: application/json; charset=UTF-8
01-16 06:39:14.289 D/OkHttp (30084): Content-Length: 2404
01-16 06:39:14.290 D/OkHttp (30084): api-version: 3
01-16 06:39:14.290 D/OkHttp (30084): {"email":"denbond7test@gmail.com","pubkey":"



\r\n\r\n"}
01-16 06:39:14.290 D/OkHttp (30084): --> END POST (2404-byte body)
01-16 06:39:15.570 D/OkHttp (30084): <-- 200 OK https://attester.flowcrypt.com/test/welcome (1279ms)
01-16 06:39:15.571 D/OkHttp (30084): Server: nginx/1.10.3 (Ubuntu)
01-16 06:39:15.571 D/OkHttp (30084): Date: Tue, 16 Jan 2018 11:39:13 GMT
01-16 06:39:15.571 D/OkHttp (30084): Content-Type: application/json
01-16 06:39:15.571 D/OkHttp (30084): Content-Length: 14
01-16 06:39:15.571 D/OkHttp (30084): Connection: keep-alive
01-16 06:39:15.571 D/OkHttp (30084): Access-Control-Allow-Origin: *
01-16 06:39:15.571 D/OkHttp (30084): Access-Control-Allow-Headers: Content-Type, api-version, user-account, user-uuid, user-token
01-16 06:39:15.573 D/OkHttp (30084): {"sent": true}
01-16 06:39:15.573 D/OkHttp (30084): <-- END HTTP (14-byte body)
01-16 06:39:46.456 D/CreatePrivateKeyActivity(30084): onStop
01-16 06:39:46.914 W/IInputConnectionWrapper(30084): reportFullscreenMode on inexistent InputConnection
01-16 06:39:46.914 W/IInputConnectionWrapper(30084): finishComposingText on inactive InputConnection
01-16 06:40:01.188 I/art (30084): System.exit called, status: 1
01-16 06:40:01.188 I/AndroidRuntime(30084): VM exiting with result code 1, cleanup skipped.
01-16 06:40:02.222 I/art (30225): Late-enabling -Xcheck:jni
01-16 06:40:02.223 W/art (30225): Unexpected CPU variant for X86 using defaults: x86
01-16 06:40:02.242 E/art (30225): Failed sending reply to debugger: Broken pipe
01-16 06:40:02.242 I/art (30225): Debugger is no longer active
01-16 06:40:02.242 I/art (30225): Starting a blocking GC Instrumentation
01-16 06:40:02.256 I/MultiDex(30225): VM with version 2.1.0 has multidex support
01-16 06:40:02.256 I/MultiDex(30225): Installing application
01-16 06:40:02.256 I/MultiDex(30225): VM has multidex support, MultiDex support library is disabled.
01-16 06:40:02.266 I/ACRA (30225): ACRA is enabled for com.flowcrypt.email.debug, initializing...
01-16 06:40:02.599 D/CheckClipboardToFindKeyService(30225): onCreate
01-16 06:40:15.153 W/art (30225): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-16 06:40:15.155 D/CreatePrivateKeyActivity(30225): onCreate
01-16 06:40:15.208 D/CreatePrivateKeyActivity(30225): onStart
01-16 06:40:15.487 I/art (30225): Do partial code cache collection, code=30KB, data=30KB
01-16 06:40:15.487 I/art (30225): After code cache collection, code=23KB, data=26KB
01-16 06:40:15.487 I/art (30225): Increasing code cache capacity to 128KB
01-16 06:40:15.511 D/CreatePrivateKeyActivity(30225): onResume
01-16 06:40:15.583 D/ (30225): HostConnection::get() New Host Connection established 0xd4149340, tid 30225
01-16 06:40:15.600 W/ (30225): Process pipe failed
01-16 06:40:15.810 D/libEGL (30225): Emulator has host GPU support, qemu.gles is set to 1.
01-16 06:40:15.810 E/libEGL (30225): load_driver(/system/lib/egl/libGLES_emulation.so): dlopen failed: library "/system/lib/egl/libGLES_emulation.so" not found
01-16 06:40:15.814 D/libEGL (30225): loaded /system/lib/egl/libEGL_emulation.so
01-16 06:40:15.818 D/libEGL (30225): loaded /system/lib/egl/libGLESv1_CM_emulation.so
01-16 06:40:15.848 D/libEGL (30225): loaded /system/lib/egl/libGLESv2_emulation.so
01-16 06:40:15.874 D/ (30225): HostConnection::get() New Host Connection established 0xd4a22b00, tid 30253
01-16 06:40:15.893 I/OpenGLRenderer(30225): Initialized EGL, version 1.4
01-16 06:40:15.893 D/OpenGLRenderer(30225): Swap behavior 1
01-16 06:40:15.957 E/EGL_emulation(30225): tid 30253: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
01-16 06:40:15.957 W/OpenGLRenderer(30225): Failed to set EGL_SWAP_BEHAVIOR on surface 0xd4a564c0, error=EGL_BAD_MATCH
01-16 06:40:26.905 D/CreateOrImportKeyActivity(30225): onCreate
01-16 06:40:26.914 D/CreateOrImportKeyActivity(30225): onStart
01-16 06:40:26.927 D/CreateOrImportKeyActivity(30225): onResume
01-16 06:40:27.055 D/CheckClipboardToFindKeyService(30225): onBind:Intent { cmp=com.flowcrypt.email.debug/com.flowcrypt.email.service.CheckClipboardToFindKeyService }
01-16 06:40:27.160 V/FragmentManager(30225): Instantiated fragment zzdb{6323f20 #0 SupportLifecycleFragmentImpl}
01-16 06:40:27.160 V/FragmentManager(30225): restoreAllState: active #0: zzdb{6323f20 #0 SupportLifecycleFragmentImpl}
01-16 06:40:27.160 V/FragmentManager(30225): restoreAllState: added #0: zzdb{6323f20 #0 SupportLifecycleFragmentImpl}
01-16 06:40:27.161 V/FragmentManager(30225): moveto CREATED: zzdb{6323f20 #0 SupportLifecycleFragmentImpl}
01-16 06:40:27.161 D/SplashActivity(30225): onCreate
01-16 06:40:27.180 D/AutoManageHelper(30225): starting AutoManage for client 0 false null
01-16 06:40:27.184 V/FragmentManager(30225): moveto ACTIVITY_CREATED: zzdb{6323f20 #0 SupportLifecycleFragmentImpl}
01-16 06:40:27.184 V/FragmentManager(30225): moveto STARTED: zzdb{6323f20 #0 SupportLifecycleFragmentImpl}
01-16 06:40:27.184 D/AutoManageHelper(30225): onStart true {0=com.google.android.gms.common.api.internal.zzi$zza@2ad0a3c}
01-16 06:40:27.189 D/SplashActivity(30225): onStart


[ENVIRONMENT]
{"getDataSystemDirectory": "/data/system", "getDataPreloadsDirectory": "/data/preloads", "getOdmDirectory": "/odm", "getDataMiscDirectory": "/data/misc", "getDataSystemCeDirectory": "/data/system_ce", "getExpandDirectory": "/mnt/expand", "getRootDirectory": "/system", "getLegacyExternalStorageDirectory": "/sdcard", "getDataPreloadsAppsDirectory": "/data/preloads/apps", "getDataPreloadsDemoDirectory": "/data/preloads/demo", "getDataPreloadsMediaDirectory": "/data/preloads/media", "isExternalStorageEmulated": true, "isExternalStorageRemovable": false, "getDownloadCacheDirectory": "/cache", "getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getExternalStorageState": "mounted", "getStorageDirectory": "/storage", "getExternalStorageDirectory": "/storage/emulated/0", "getOemDirectory": "/oem", "getDataDirectory": "/data", "getDataSystemDeDirectory": "/data/system_de"}


[TOTAL_MEM_SIZE]
13375950848


[INITIAL_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 7, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 270, "screenWidthDp": 411, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 512, "fontScale": 1, "smallestScreenWidthDp": 411, "densityDpi": 420, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 659, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_NO", "navigation": "NAVIGATION_DPAD"}


[DISPLAY]
{"0": {"refreshRate": 60.000003814697266, "metrics": {"density": 2.625, "scaledDensity": "x2.625", "xdpi": 420, "widthPixels": 1080, "heightPixels": 1794, "densityDpi": 420, "ydpi": 420}, "name": "Built-in Screen", "realSize": [1080, 1920], "isValid": true, "currentSizeRange": {"smallest": [1080, 1017], "largest": [1794, 1731]}, "rectSize": [0, 0, 1080, 1794], "height": 1794, "realMetrics": {"density": 2.625, "scaledDensity": "x2.625", "xdpi": 420, "widthPixels": 1080, "heightPixels": 1920, "densityDpi": 420, "ydpi": 420}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 1794], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
9463164928


[PHONE_MODEL]
Google Nexus 5X - 7.1.0 - API 25 - 1080x1920


[CRASH_CONFIGURATION]
{"orientation": "ORIENTATION_PORTRAIT", "seq": 7, "locale": "en_US", "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_QWERTY", "mnc": 270, "screenWidthDp": 411, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "compatScreenHeightDp": 512, "fontScale": 1, "smallestScreenWidthDp": 411, "densityDpi": 420, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 310, "compatScreenWidthDp": 319, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_NO", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 659, "compatSmallestScreenWidthDp": 320, "navigationHidden": "NAVIGATIONHIDDEN_NO", "navigation": "NAVIGATION_DPAD"}


[DEVICE_FEATURES]
{"android.software.input_methods": true, "android.software.managed_users": true, "android.hardware.faketouch": true, "android.software.backup": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "android.software.live_wallpaper": true, "android.hardware.sensor.accelerometer": true, "android.hardware.telephony": true, "android.hardware.telephony.gsm": true, "com.google.android.feature.EXCHANGE_6_2": true, "android.hardware.location.gps": true, "android.hardware.usb.accessory": true, "android.software.webview": true, "android.software.sip.voip": true, "android.hardware.microphone": true, "android.hardware.location.network": true, "android.hardware.touchscreen.multitouch": true, "android.software.voice_recognizers": true, "android.hardware.touchscreen": true, "com.google.android.feature.GOOGLE_EXPERIENCE": true, "android.hardware.audio.output": true, "com.google.android.feature.GOOGLE_BUILD": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.software.sip": true, "android.hardware.camera.any": true, "android.hardware.camera": true, "android.hardware.wifi": true, "android.software.print": true, "android.software.home_screen": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.screen.portrait": true, "android.hardware.location": true, "android.software.device_admin": true, "glEsVersion": "2.0", "android.hardware.screen.landscape": true, "android.hardware.usb.host": true, "android.software.connectionservice": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email.debug", "VERSION_CODE": 42, "BUILD_TYPE": "debug", "DEBUG": true, "VERSION_NAME": "0.4.2_42__2018_01_16_13_35", "FLAVOR": ""}


[FILE_PATH]
/data/user/0/com.flowcrypt.email.debug/files


[INSTALLATION_ID]
7c97f338-da99-42a0-8b4e-456e3bf02403


[USER_CRASH_DATE]
2018-01-16T06:40:27.227-05:00


[HASH]
9F0BE097B2


[APP_VERSION_NAME]
0.4.2_42__2018_01_16_13_35


[USER_APP_START_DATE]
2018-01-16T06:40:02.271-05:00


[BUILD]
{"UNKNOWN": "unknown", "HARDWARE": "vbox86", "BOARD": "unknown", "MODEL": "Google Nexus 5X - 7.1.0 - API 25 - 1080x1920", "BOOTLOADER": "unknown", "DISPLAY": "vbox86p-userdebug 7.1.1 NMF26Q eng.genymo.20170320.224321 test-keys", "CPU_ABI2": "armeabi-v7a", "FINGERPRINT": "Android/vbox86p/vbox86p:7.1.1/NMF26Q/genymo03202243:userdebug/test-keys", "IS_EMULATOR": true, "TAGS": "test-keys", "HOST": "94993daba111", "VERSION": {"PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 25, "SDK_INT": 25, "INCREMENTAL": "eng.genymo.20170320.224321", "BASE_OS": "", "RELEASE": "7.1.1", "CODENAME": "REL", "SECURITY_PATCH": "2016-12-05", "ACTIVE_CODENAMES": [], "SDK": "25"}, "PERMISSIONS_REVIEW_REQUIRED": false, "DEVICE": "vbox86p", "SERIAL": "unknown", "ID": "NMF26Q", "MANUFACTURER": "Genymotion", "PRODUCT": "vbox86p", "SUPPORTED_ABIS": ["x86", "armeabi-v7a", "armeabi"], "IS_DEBUGGABLE": true, "SUPPORTED_64_BIT_ABIS": [], "RADIO": "unknown", "CPU_ABI": "x86", "TIME": 1490049801000, "SUPPORTED_32_BIT_ABIS": ["x86", "armeabi-v7a", "armeabi"], "TYPE": "userdebug", "BRAND": "Android", "USER": "genymotion"}


[DUMPSYS_MEMINFO]
Permission Denial: can't dump meminfo from from pid=30263, uid=10297 without permission android.permission.DUMP


[USER_EMAIL]
N/A


[REPORT_ID]
db119596-c455-41e2-b8c5-cff0937fc2d8


[PRODUCT]
vbox86p


[PACKAGE_NAME]
com.flowcrypt.email.debug


[BRAND]
Android


[ANDROID_VERSION]
7.1.1


[APP_VERSION_CODE]
42


[IS_SILENT]
false


[CUSTOM_DATA]
{}
```

**Comment by DenBond7** [comment]
Fixed: https://github.com/FlowCrypt/flowcrypt-android/commit/a34f3afc74aff270efc08cf255335a6e743ee3b5
