### ISSUE TITLE
AccountDao null

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#189]
```
[STACK_TRACE]
java.lang.NullPointerException: AccountDao must not be a null!
at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.getSessionForAccountDao(OpenStoreHelper.java:131)
at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:459)
at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:489)
at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:559)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by DenBond7** [comment]
#188

**Comment by DenBond7** [comment]
The issue #188 produced this bug.

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKkprvNtVLsSfnhkhKLGSwLCR
