### ISSUE TITLE
Connection closed by peer: IMAP

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#190]
```
[STACK_TRACE]
javax.mail.MessagingException: Connection closed by peer;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:737)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:92)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:69)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:139)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:460)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:489)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:559)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
Caused by: javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:619)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:393)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:124)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:128)
        at com.sun.mail.gimap.protocol.GmailProtocol.<init>(GmailProtocol.java:106)
        at com.sun.mail.gimap.GmailStore.newIMAPProtocol(GmailStore.java:98)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:693)
        ... 13 more
javax.net.ssl.SSLHandshakeException: Connection closed by peer
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:357)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:619)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:393)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:124)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:128)
        at com.sun.mail.gimap.protocol.GmailProtocol.<init>(GmailProtocol.java:106)
        at com.sun.mail.gimap.GmailStore.newIMAPProtocol(GmailStore.java:98)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:693)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:92)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:69)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:139)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:460)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:489)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:559)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```

**Comment by DenBond7** [comment]
https://github.com/square/okhttp/issues/3188

**Comment by DenBond7** [comment]
https://github.com/square/retrofit/issues/2388

It looks like "Communication issue" (Slow connection etc.)
Such errors are happening when we create an SSL connection and **JavaMail** call `sslsocket.startHandshake().`
I have reproduced such error and the app has handled this situation correct.

I will exclude such notifications in ACRA.
