### ISSUE TITLE
app crash on reply: java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#192]
> Hello, 
> Thanks for giving me the opportunity to test out the app! 
> I am able to login to my Gmail account and import my private key. I can delete and archive emails. The issue I am having is everytime I attempt to reply to an email or compose a new one, the app crashes and restarts itself. I have uninstalled & reinstalled the app and experience the same issue. 
> Samsung S8+
> SM-G955U
> Android 7.0
> Please let me know if you need anymore info from me. Looking forward to the next update. 
> Thanks, 

stack:
```
[STACK_TRACE]
java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:67)
        at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:34)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$532ebdd5(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        ... 3 more
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
        at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:67)
        at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:34)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$532ebdd5(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)



[LOGCAT]
01-21 15:54:55.349 D/TextView(28356): setTypeface with style : 0
01-21 15:54:55.352 D/TextView(28356): setTypeface with style : 0
01-21 15:54:55.352 D/TextView(28356): setTypeface with style : 0
01-21 15:54:55.358 I/SemDesktopModeManager(28356): registerListener: android.view.ViewRootImpl$3@306ed8e
01-21 15:54:55.359 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): ThreadedRenderer.create() translucent=false
01-21 15:54:55.362 D/InputTransport(28356): Input channel constructed: fd=113
01-21 15:54:55.362 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): setView = DecorView@c76f1bc[MessageDetailsActivity] touchMode=true
01-21 15:54:55.364 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): dispatchAttachedToWindow
01-21 15:54:55.383 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1080,2220] result=0x27 surface={isValid=true -1133193216} surfaceGenerationChanged=true
01-21 15:54:55.383 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): mHardwareRenderer.initialize() mSurface={isValid=true -1133193216} hwInitialized=true
01-21 15:54:55.396 D/ScrollView(28356):  onsize change changed
01-21 15:54:55.417 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 126) vi=Rect(0, 63 - 0, 126) or=1
01-21 15:54:55.417 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): MSG_WINDOW_FOCUS_CHANGED 1
01-21 15:54:55.417 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -1133193216}
01-21 15:54:55.418 V/InputMethodManager(28356): Starting input: tba=android.view.inputmethod.EditorInfo@5ba6d87 nm : com.flowcrypt.email ic=null
01-21 15:54:55.418 I/InputMethodManager(28356): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
01-21 15:54:55.424 D/InputTransport(28356): Input channel constructed: fd=138
01-21 15:54:55.424 D/InputTransport(28356): Input channel destroyed: fd=146
01-21 15:54:55.452 D/OpenGLRenderer(28356): endAllActiveAnimators on 0xc73c7400 (ListView) with handle 0xc4e7eb00
01-21 15:54:55.453 D/ViewRootImpl@59ee2b4[EmailManagerActivity](28356): mHardwareRenderer.destroy()#1
01-21 15:54:55.456 D/ViewRootImpl@59ee2b4[EmailManagerActivity](28356): Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
01-21 15:54:57.518 D/ConnectivityManager(28356): unregisterNetworkCallback; CallingUid : 10289, CallingPid : 28356
01-21 15:54:57.521 E/ConnectivityManager.CallbackHandler(28356): callback not found for RELEASED message
01-21 15:54:57.715 D/ConnectivityManager(28356): requestNetwork; CallingUid : 10289, CallingPid : 28356
01-21 15:54:57.751 D/TextView(28356): setTypeface with style : 0
01-21 15:54:57.753 D/TextView(28356): setTypeface with style : 0
01-21 15:54:57.754 D/TextView(28356): setTypeface with style : 0
01-21 15:54:57.762 V/InputMethodManager(28356): Starting input: tba=android.view.inputmethod.EditorInfo@e4fe681 nm : com.flowcrypt.email ic=null
01-21 15:54:57.762 I/InputMethodManager(28356): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
01-21 15:54:57.763 D/InputTransport(28356): Input channel constructed: fd=146
01-21 15:54:57.763 D/InputTransport(28356): Input channel destroyed: fd=138
01-21 15:54:57.801 D/ScrollView(28356):  onsize change changed
01-21 15:54:57.831 D/ViewRootImpl@59ee2b4[EmailManagerActivity](28356): Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=false
01-21 15:54:58.154 D/ScrollView(28356):  onsize change changed
01-21 15:55:02.066 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): ViewPostImeInputStage processPointer 0
01-21 15:55:02.153 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): ViewPostImeInputStage processPointer 1
01-21 15:55:02.203 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): MSG_WINDOW_FOCUS_CHANGED 0
01-21 15:55:02.217 V/ActivityThread(28356): performLaunchActivity: mActivityCurrentConfig={0 1.0 themeSeq = 0 showBtnBg = 0 311mcc480mnc [en_US] ldltr sw411dp w411dp h773dp 420dpi nrml long port ?dc finger -keyb/v/h -nav/h mkbd/h desktop/d s.17}
01-21 15:55:02.303 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.320 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.323 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.324 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.333 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.334 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.336 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.341 I/SemDesktopModeManager(28356): registerListener: android.view.ViewRootImpl$3@6a22aa3
01-21 15:55:02.343 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): ThreadedRenderer.create() translucent=false
01-21 15:55:02.347 D/InputTransport(28356): Input channel constructed: fd=160
01-21 15:55:02.347 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): setView = DecorView@b2ba159[CreateMessageActivity] touchMode=true
01-21 15:55:02.356 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): dispatchAttachedToWindow
01-21 15:55:02.360 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.385 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1080,2220] result=0x27 surface={isValid=true -962152448} surfaceGenerationChanged=true
01-21 15:55:02.385 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): mHardwareRenderer.initialize() mSurface={isValid=true -962152448} hwInitialized=true
01-21 15:55:02.420 E/sms     (28356): Unable to find resource: 0
01-21 15:55:02.427 D/ScrollView(28356):  onsize change changed
01-21 15:55:02.435 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.438 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.438 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.462 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): MSG_RESIZED_REPORT: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 126) vi=Rect(0, 63 - 0, 126) or=1
01-21 15:55:02.463 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): MSG_WINDOW_FOCUS_CHANGED 1
01-21 15:55:02.463 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): mHardwareRenderer.initializeIfNeeded()#2 mSurface={isValid=true -962152448}
01-21 15:55:02.474 V/InputMethodManager(28356): Starting input: tba=android.view.inputmethod.EditorInfo@a2508b nm : com.flowcrypt.email ic=com.android.internal.widget.EditableInputConnection@28d568
01-21 15:55:02.474 I/InputMethodManager(28356): [IMM] startInputInner - mService.startInputOrWindowGainedFocus
01-21 15:55:02.484 D/InputTransport(28356): Input channel constructed: fd=162
01-21 15:55:02.484 D/InputTransport(28356): Input channel destroyed: fd=146
01-21 15:55:02.500 I/System.out(28356): (HTTPLog)-Static: isSBSettingEnabled false
01-21 15:55:02.500 I/System.out(28356): (HTTPLog)-Static: isSBSettingEnabled false
01-21 15:55:02.524 D/OpenGLRenderer(28356): endAllActiveAnimators on 0xbc5b4300 (RippleDrawable) with handle 0xbc5868b0
01-21 15:55:02.525 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): mHardwareRenderer.destroy()#1
01-21 15:55:02.533 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=true
01-21 15:55:02.534 E/SpannableStringBuilder(28356): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-21 15:55:02.534 E/SpannableStringBuilder(28356): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-21 15:55:02.541 E/SpannableStringBuilder(28356): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-21 15:55:02.541 E/SpannableStringBuilder(28356): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-21 15:55:02.550 E/SpannableStringBuilder(28356): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-21 15:55:02.550 E/SpannableStringBuilder(28356): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-21 15:55:02.691 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): MSG_RESIZED: frame=Rect(0, 0 - 1080, 2220) ci=Rect(0, 63 - 0, 860) vi=Rect(0, 63 - 0, 860) or=1
01-21 15:55:02.696 D/TextView(28356): setTypeface with style : 0
01-21 15:55:02.699 E/sms     (28356): Unable to find resource: 0
01-21 15:55:02.709 D/ViewRootImpl@91c01a0[CreateMessageActivity](28356): Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x1 surface={isValid=true -962152448} surfaceGenerationChanged=false
01-21 15:55:02.714 D/ScrollView(28356):  onsize change changed
01-21 15:55:02.904 D/ViewRootImpl@2899af[MessageDetailsActivity](28356): Relayout returned: oldFrame=[0,0][1080,2220] newFrame=[0,0][1080,2220] result=0x5 surface={isValid=false 0} surfaceGenerationChanged=false
01-21 15:55:03.137 E/ACRA    (28356): ACRA caught a RuntimeException for com.flowcrypt.email
01-21 15:55:03.137 E/ACRA    (28356): java.lang.RuntimeException: An error occurred while executing doInBackground()
01-21 15:55:03.137 E/ACRA    (28356):   at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
01-21 15:55:03.137 E/ACRA    (28356):   at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
01-21 15:55:03.137 E/ACRA    (28356):   at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
01-21 15:55:03.137 E/ACRA    (28356):   at java.util.concurrent.FutureTask.run(FutureTask.java:242)
01-21 15:55:03.137 E/ACRA    (28356):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-21 15:55:03.137 E/ACRA    (28356):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-21 15:55:03.137 E/ACRA    (28356):   at java.lang.Thread.run(Thread.java:762)
01-21 15:55:03.137 E/ACRA    (28356): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
01-21 15:55:03.137 E/ACRA    (28356):   at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:67)
01-21 15:55:03.137 E/ACRA    (28356):   at com.flowcrypt.email.ui.loader.LoadGmailAliasesLoader.loadInBackground(LoadGmailAliasesLoader.java:34)
01-21 15:55:03.137 E/ACRA    (28356):   at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
01-21 15:55:03.137 E/ACRA    (28356):   at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$532ebdd5(AsyncTaskLoader.java:59)
01-21 15:55:03.137 E/ACRA    (28356):   at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
01-21 15:55:03.137 E/ACRA    (28356):   at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
01-21 15:55:03.137 E/ACRA    (28356):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-21 15:55:03.137 E/ACRA    (28356):   ... 3 more


[ENVIRONMENT]
{"getVendorDirectory": "/vendor", "getLegacyExternalStorageObbDirectory": "/sdcard/Android/obb", "getLegacyExternalStorageDirectory": "/sdcard", "getDataSystemDirectory": "/data/system", "getDataMiscDirectory": "/data/misc", "getDataSystemCeDirectory": "/data/system_ce", "getExternalStorageState": "mounted", "getStorageDirectory": "/storage", "getExpandDirectory": "/mnt/expand", "getOemDirectory": "/oem", "getExternalStorageDirectory": "/storage/emulated/0", "isExternalStorageEmulated": true, "getDataDirectory": "/data", "isExternalStorageRemovable": false, "getDataSystemDeDirectory": "/data/system_de", "getOdmDirectory": "/odm", "getRootDirectory": "/system", "getDownloadCacheDirectory": "/cache"}


[TOTAL_MEM_SIZE]
57226952704


[INITIAL_CONFIGURATION]
{"dexCompatEnabled": 0, "semDesktopModeEnabled": 0, "orientation": "ORIENTATION_PORTRAIT", "seq": 17, "locale": "en_US", "compatSmallestScreenWidthDp": 320, "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 480, "screenWidthDp": 411, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "showButtonBackground": 0, "compatScreenHeightDp": 601, "isOverridden": false, "fontScale": 1.1, "FlipFont": 0, "smallestScreenWidthDp": 411, "densityDpi": 420, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 311, "rilSetLocale": false, "compatScreenWidthDp": 319, "semMobileKeyboardCovered": 0, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 773, "themeSeq": 0, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DISPLAY]
{"0": {"refreshRate": 60.000003814697266, "metrics": {"density": 2.625, "scaledDensity": "x2.625", "xdpi": 391.885498046875, "widthPixels": 1080, "heightPixels": 2094, "densityDpi": 420, "ydpi": 394.321533203125}, "name": "Built-in Screen", "realSize": [1080, 2220], "isValid": true, "currentSizeRange": {"smallest": [1080, 1017], "largest": [2094, 2031]}, "rectSize": [0, 0, 1080, 2094], "height": 2094, "realMetrics": {"density": 2.625, "scaledDensity": "x2.625", "xdpi": 391.885498046875, "widthPixels": 1080, "heightPixels": 2220, "densityDpi": 420, "ydpi": 394.321533203125}, "width": 1080, "pixelFormat": 1, "flags": "FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE", "rotation": "ROTATION_0", "size": [1080, 2094], "orientation": 0}}


[AVAILABLE_MEM_SIZE]
42319163392


[PHONE_MODEL]
SM-G955U


[CRASH_CONFIGURATION]
{"dexCompatEnabled": 0, "semDesktopModeEnabled": 0, "orientation": "ORIENTATION_PORTRAIT", "seq": 17, "locale": "en_US", "compatSmallestScreenWidthDp": 320, "userSetLocale": false, "keyboardHidden": "KEYBOARDHIDDEN_NO", "keyboard": "KEYBOARD_NOKEYS", "mnc": 480, "screenWidthDp": 411, "screenLayout": "SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_YES+SCREENLAYOUT_LAYOUTDIR_LTR+SCREENLAYOUT_ROUND_NO", "showButtonBackground": 0, "compatScreenHeightDp": 601, "isOverridden": false, "fontScale": 1.1, "FlipFont": 0, "smallestScreenWidthDp": 411, "densityDpi": 420, "touchscreen": "TOUCHSCREEN_FINGER", "mcc": 311, "rilSetLocale": false, "compatScreenWidthDp": 319, "semMobileKeyboardCovered": 0, "hardKeyboardHidden": "HARDKEYBOARDHIDDEN_YES", "uiMode": "UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO", "screenHeightDp": 773, "themeSeq": 0, "navigationHidden": "NAVIGATIONHIDDEN_YES", "navigation": "NAVIGATION_NONAV"}


[DEVICE_FEATURES]
{"com.sec.feature.cover.flip": true, "com.samsung.android.sdk.camera.processor.panorama": true, "android.software.input_methods": true, "android.hardware.sensor.hifi_sensors": true, "com.sec.feature.motionrecognition_service": true, "android.hardware.nfc.hcef": true, "com.sec.feature.sensorhub": true, "android.hardware.faketouch": true, "android.hardware.camera.front": true, "android.software.app_widgets": true, "com.samsung.android.sdk.camera.processor.dof": true, "com.samsung.feature.mmfw_monitor": true, "android.hardware.screen.portrait": true, "com.samsung.android.api.version.2402": true, "com.samsung.android.api.version.2403": true, "android.hardware.usb.accessory": true, "com.samsung.android.sdk.camera.processor.lls": true, "android.hardware.location.network": true, "com.samsung.feature.samsung_experience_mobile": true, "android.software.voice_recognizers": true, "com.sec.feature.spo2": true, "com.samsung.feature.hdr_capable": true, "com.sec.feature.findo": true, "android.hardware.bluetooth": true, "com.samsung.feature.device_category_phone_high_end": true, "com.samsung.android.bio.face": true, "android.hardware.nfc.hce": true, "com.samsung.android.sdk.camera.processor.haze": true, "android.hardware.wifi.direct": true, "android.hardware.screen.landscape": true, "android.software.connectionservice": true, "com.sec.feature.support_mst": true, "com.samsung.android.authfw": true, "com.sec.feature.nsflp": true, "android.software.managed_users": true, "com.sec.feature.multiwindow.long_device_snap_mode": true, "android.hardware.telephony": true, "android.hardware.sensor.light": true, "com.samsung.android.sdk.camera.processor": true, "com.sec.feature.cover": true, "android.software.midi": true, "android.hardware.wifi": true, "com.samsung.feature.mirrorlink_fw": true, "android.hardware.touchscreen": true, "com.samsung.android.sdk.camera.processor.hdr": true, "android.hardware.sensor.heartrate": true, "com.sec.feature.fingerprint_ui": true, "com.sec.feature.overlaymagnifier": true, "com.sec.android.smartface.smart_stay": true, "android.hardware.telephony.cdma": true, "android.software.print": true, "android.hardware.vr.high_performance": true, "com.sec.feature.people_edge_notification": true, "android.hardware.touchscreen.multitouch.distinct": true, "android.hardware.opengles.aep": true, "android.hardware.sensor.stepdetector": true, "android.hardware.sensor.barometer": true, "android.hardware.location": true, "com.sec.feature.barcode_emulator": true, "android.software.device_admin": true, "com.sec.feature.cover.clearcover": true, "com.verizon.hardware.telephony.srlte": true, "android.hardware.camera.capability.manual_post_processing": true, "com.sec.feature.cover.nfcledcover": true, "com.sec.feature.slocation": true, "com.sec.feature.fingerprint_manager_service": true, "android.hardware.bluetooth_le": true, "com.sec.feature.multiwindow.ensure_docked_view": true, "android.software.backup": true, "android.hardware.sensor.compass": true, "android.software.live_wallpaper": true, "android.hardware.telephony.gsm": true, "android.hardware.vulkan.version": true, "com.samsung.android.sdk.camera.ipx": true, "android.software.webview": true, "com.sec.feature.multiwindow.snap_view": true, "android.software.sip.voip": true, "android.hardware.fingerprint": true, "android.hardware.touchscreen.multitouch": true, "com.sec.android.mdm": true, "android.software.vr.mode": true, "android.hardware.sensor.stepcounter": true, "android.hardware.touchscreen.multitouch.jazzhand": true, "android.hardware.camera.any": true, "com.samsung.android.camera.iris": true, "android.hardware.camera.level.full": true, "com.sec.feature.cover.sview": true, "com.samsung.android.sdk.camera.processor.effect": true, "com.verizon.hardware.telephony.ehrpd": true, "android.software.freeform_window_management": true, "glEsVersion": "3.2", "android.hardware.vulkan.level": true, "android.hardware.usb.host": true, "com.sec.feature.cover.nfc_authentication": true, "android.hardware.nfc": true, "android.software.verified_boot": true, "com.samsung.android.knox.knoxsdk": true, "com.sec.feature.cocktailpanel": true, "android.hardware.camera.capability.raw": true, "android.hardware.audio.output": true, "com.samsung.android.sdk.camera.processor.gif": true, "android.hardware.camera.flash": true, "com.nxp.mifare": true, "com.samsung.feature.aodservice_v03": true, "android.hardware.location.gps": true, "com.sec.android.secimaging": true, "android.hardware.microphone": true, "android.hardware.sensor.gyroscope": true, "com.samsung.feature.hmt": true, "android.hardware.camera.capability.manual_sensor": true, "android.software.sip": true, "com.samsung.feature.radiobasedlocation": true, "com.verizon.hardware.telephony.lte": true, "android.hardware.sensor.proximity": true, "android.hardware.camera": true, "com.sec.feature.edge_v03": true, "com.samsung.feature.virtualscreen": true, "android.software.home_screen": true, "android.hardware.camera.autofocus": true, "android.hardware.sensor.accelerometer": true}


[BUILD_CONFIG]
{"APPLICATION_ID": "com.flowcrypt.email", "VERSION_CODE": 42, "BUILD_TYPE": "release", "DEBUG": false, "VERSION_NAME": "0.4.2", "FLAVOR": ""}


[FILE_PATH]
/data/user/0/com.flowcrypt.email/files


[INSTALLATION_ID]
790d8889-6965-41e6-88a9-a47cc8ccbe7d


[USER_CRASH_DATE]
2018-01-21T15:55:03.232-05:00


[HASH]
C7418D148C


[APP_VERSION_NAME]
0.4.2


[USER_APP_START_DATE]
2018-01-21T15:49:52.668-05:00


[BUILD]
{"IS_SYSTEM_SECURE": false, "UNKNOWN": "unknown", "HARDWARE": "qcom", "BOARD": "msm8998", "MODEL": "SM-G955U", "BOOTLOADER": "G955USQS2BQL1", "DISPLAY": "NRD90M.G955USQS2BQL1", "CPU_ABI2": "armeabi", "FINGERPRINT": "samsung/dream2qltesq/dream2qltesq:7.0/NRD90M/G955USQS2BQL1:user/release-keys", "IS_EMULATOR": false, "TAGS": "release-keys", "HOST": "SWDD5521", "VERSION": {"SEM_INT": 2403, "SECURITY_PATCH": "2017-12-01", "PREVIEW_SDK_INT": 0, "RESOURCES_SDK_INT": 24, "SDK_INT": 24, "INCREMENTAL": "G955USQS2BQL1", "SECURITY_INDEX": "1", "BASE_OS": "samsung/dream2qltesq/dream2qltesq:7.0/NRD90M/G955USQU2BQK5:user/release-keys", "RELEASE": "7.0", "CODENAME": "REL", "SEM_PLATFORM_INT": 80100, "ACTIVE_CODENAMES": [], "SDK": "24"}, "PERMISSIONS_REVIEW_REQUIRED": false, "DEVICE": "dream2qltesq", "SERIAL": "988995424b38325833", "ID": "NRD90M", "MANUFACTURER": "samsung", "PRODUCT": "dream2qltesq", "BRAND": "samsung", "IS_DEBUGGABLE": false, "SUPPORTED_64_BIT_ABIS": ["arm64-v8a"], "RADIO": "G955USQS2BQL1", "CPU_ABI": "armeabi-v7a", "TIME": 1512461438000, "SUPPORTED_32_BIT_ABIS": ["armeabi-v7a", "armeabi"], "TYPE": "user", "SUPPORTED_ABIS": ["arm64-v8a", "armeabi-v7a", "armeabi"], "USER": "dpi"}


[DUMPSYS_MEMINFO]



[USER_EMAIL]
N/A


[REPORT_ID]
0ffdac63-3e91-489a-9dd9-ef960c7ea936


[PRODUCT]
dream2qltesq


[PACKAGE_NAME]
com.flowcrypt.email


[BRAND]
samsung


[ANDROID_VERSION]
7.0


[APP_VERSION_CODE]
42


[IS_SILENT]
false


[CUSTOM_DATA]
{}
```

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1611a79a3d160e43
