### ISSUE TITLE
javax.mail.AuthenticationFailedException: [AUTHENTICATIONFAILED] Invalid credentials

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#196]
```
[STACK_TRACE]
javax.mail.AuthenticationFailedException: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:727)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:92)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:69)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:139)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:460)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:489)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$PassiveSyncTaskRunnable.run(EmailSyncManager.java:537)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1611eeac2bcea746
