### ISSUE TITLE
javax.mail.MessagingException: Failed to fetch headers

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#197]
```
[STACK_TRACE]
javax.mail.MessagingException: Failed to fetch headers
        at com.flowcrypt.email.service.EmailSyncService.getAttachmentsInfoFromPart(EmailSyncService.java:618)
        at com.flowcrypt.email.service.EmailSyncService.getAttachmentsInfoFromPart(EmailSyncService.java:608)
        at com.flowcrypt.email.service.EmailSyncService.updateAttachmentTable(EmailSyncService.java:564)
        at com.flowcrypt.email.service.EmailSyncService.onMessagesReceived(EmailSyncService.java:328)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessagesToCacheSyncTask.runIMAPAction(LoadMessagesToCacheSyncTask.java:85)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:503)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:559)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)

```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#search/Failed+to+fetch+headers/1611e40dac70f8f0

**Comment by DenBond7** [comment]
https://mail.google.com/mail/u/0/#inbox/1617bff8b17eaef3
