### ISSUE TITLE
Failed to load info about recipient - color

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#198]

**Comment by DenBond7** [comment]
```
[STACK_TRACE]
java.net.SocketTimeoutException: timeout
        at okio.Okio$4.newTimeoutException(Okio.java:230)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:275)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:243)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:212)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.flowcrypt.email.api.retrofit.okhttp.ApiVersionInterceptor.intercept(ApiVersionInterceptor.java:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:91)
        at com.flowcrypt.email.ui.loader.UpdateInfoAboutPgpContactsAsyncTaskLoader.getLookUpEmailResponse(UpdateInfoAboutPgpContactsAsyncTaskLoader.java:185)
        at com.flowcrypt.email.ui.loader.UpdateInfoAboutPgpContactsAsyncTaskLoader.getPgpContactInfoFromServer(UpdateInfoAboutPgpContactsAsyncTaskLoader.java:157)
        at com.flowcrypt.email.ui.loader.UpdateInfoAboutPgpContactsAsyncTaskLoader.loadInBackground(UpdateInfoAboutPgpContactsAsyncTaskLoader.java:105)
        at com.flowcrypt.email.ui.loader.UpdateInfoAboutPgpContactsAsyncTaskLoader.loadInBackground(UpdateInfoAboutPgpContactsAsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground$532ebdd5(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by tomholub** [comment]
Changing the issue.

When a recipient fails loading, their email address text should be showing in red color, to make it clear which recipient failed. Also, it would be good if clicking the recipient would retry loading, but maybe that's for another issue.

**Comment by DenBond7** [comment]
deprecated
