### ISSUE TITLE
NPE in SelectContactsActivity

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#206]
```
STACK_TRACE]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setQuery(java.lang.CharSequence, boolean)' on a null object reference
        at com.flowcrypt.email.ui.activity.SelectContactsActivity.onPrepareOptionsMenu(SelectContactsActivity.java:115)
        at android.app.Activity.onPreparePanel(Activity.java:3165)
        at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:503)
        at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:491)
        at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:98)
        at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:359)
        at android.support.v7.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:98)
        at android.support.v7.app.ToolbarActionBar$ToolbarCallbackWrapper.onPreparePanel(ToolbarActionBar.java:521)
        at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
        at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:55)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:7325)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1617a24251293d1a
