### ISSUE TITLE
.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.del

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#225]
```
[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:88)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:106)
        at com.flowcrypt.email.security.SecurityStorageConnector.<init>(SecurityStorageConnector.java:36)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.del(java.lang.String, int)' on a null object reference
        at android.security.KeyStore.delete(KeyStore.java:186)
        at android.security.Credentials.deletePrivateKeyTypeForAlias(Credentials.java:292)
        at android.security.Credentials.deleteAllTypesForAlias(Credentials.java:251)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:464)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.generateKeyIfAndroidVersionEqualOrHigherThenMarshmallow(KeyStoreCryptoManager.java:334)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.createRSAKeyPair(KeyStoreCryptoManager.java:306)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.initRsaKeyPair(KeyStoreCryptoManager.java:286)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.<init>(KeyStoreCryptoManager.java:99)
        at com.flowcrypt.email.security.SecurityUtils.getPrivateKeysInfo(SecurityUtils.java:40)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:99)
        ... 7 more
java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.del(java.lang.String, int)' on a null object reference
        at android.security.KeyStore.delete(KeyStore.java:186)
        at android.security.Credentials.deletePrivateKeyTypeForAlias(Credentials.java:292)
        at android.security.Credentials.deleteAllTypesForAlias(Credentials.java:251)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:464)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.generateKeyIfAndroidVersionEqualOrHigherThenMarshmallow(KeyStoreCryptoManager.java:334)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.createRSAKeyPair(KeyStoreCryptoManager.java:306)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.initRsaKeyPair(KeyStoreCryptoManager.java:286)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.<init>(KeyStoreCryptoManager.java:99)
        at com.flowcrypt.email.security.SecurityUtils.getPrivateKeysInfo(SecurityUtils.java:40)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:99)
        at com.flowcrypt.email.security.SecurityStorageConnector.<init>(SecurityStorageConnector.java:36)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)

```

[APP_VERSION_NAME]
0.6.1

[BRAND]
HUAWEI

[ANDROID_VERSION]
7.0

**Comment by DenBond7** [comment]
https://github.com/iamMehedi/Secured-Preference-Store/issues/25

**Comment by DenBond7** [comment]
I've decided to reopen this issue. We are still receiving such errors and will be better if that issue will be open.

Such errors are happening on HUAWEI devices. The system of that devices has some issues (as I understood HUAWEI has changed some default behavior in Android KeyStore) and that's why we can't save the encrypted user password (auth credentials) ---> The users with HUAWEI devices can't use FlowCrypt as is. They only can open the app but can't setup it.

**Comment by tomholub** [comment]
It's ok with me to just show an error to the user when we catch this exception: "Your device is currently not supported: KeystoreService not available." or something like that.

**Comment by DenBond7** [comment]
deprecated
