### ISSUE TITLE
NullPointerException in EmailSyncService

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#229]
```
[STACK_TRACE]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.Folder.getServerFullFolderName()' on a null object reference
        at com.flowcrypt.email.service.EmailSyncService$IncomingHandler.handleMessage(EmailSyncService.java:763)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:6274)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

ref https://mail.google.com/mail/u/0/#inbox/1623f43f0d661cdf

**Comment by DenBond7** [comment]
Steps:
1) checkout 0.6.2
2) git pull
3) sync everything
4) run on my phone
5) connect to gmail
6) enter pass phrase
7) inbox screen shows, but doesn't load. I pull down to refresh the empty list and it crashes
