### ISSUE TITLE
java.lang.IllegalStateException: Not allowed to start service Intent

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#230]
```
[STACK_TRACE]
java.lang.RuntimeException: Unable to create application com.flowcrypt.email.FlowCryptApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.flowcrypt.email/.service.JsBackgroundService }: app is in background uid UidRecord{3a16a43 u0a146 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.flowcrypt.email/.service.JsBackgroundService }: app is in background uid UidRecord{3a16a43 u0a146 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at com.flowcrypt.email.service.JsBackgroundService.start(JsBackgroundService.java:70)
        at com.flowcrypt.email.FlowCryptApplication.onCreate(FlowCryptApplication.java:78)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        ... 8 more
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.flowcrypt.email/.service.JsBackgroundService }: app is in background uid UidRecord{3a16a43 u0a146 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
        at android.app.ContextImpl.startService(ContextImpl.java:1477)
        at android.content.ContextWrapper.startService(ContextWrapper.java:650)
        at com.flowcrypt.email.service.JsBackgroundService.start(JsBackgroundService.java:70)
        at com.flowcrypt.email.FlowCryptApplication.onCreate(FlowCryptApplication.java:78)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#inbox/162430a068763985
