### ISSUE TITLE
java.security.ProviderException: Failed to load generated key pair from keystore

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#231]
```
[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:88)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:106)
        at com.flowcrypt.email.security.SecurityStorageConnector.<init>(SecurityStorageConnector.java:36)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: java.security.ProviderException: Failed to load generated key pair from keystore
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:518)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.generateKeyIfAndroidVersionEqualOrHigherThenMarshmallow(KeyStoreCryptoManager.java:334)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.createRSAKeyPair(KeyStoreCryptoManager.java:306)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.initRsaKeyPair(KeyStoreCryptoManager.java:286)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.<init>(KeyStoreCryptoManager.java:99)
        at com.flowcrypt.email.security.SecurityUtils.getPrivateKeysInfo(SecurityUtils.java:40)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:99)
        ... 7 more
Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:230)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:509)
        ... 15 more
Caused by: android.security.KeyStoreException: -22
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:676)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:231)
        ... 17 more
java.security.ProviderException: Failed to load generated key pair from keystore
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:518)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.generateKeyIfAndroidVersionEqualOrHigherThenMarshmallow(KeyStoreCryptoManager.java:334)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.createRSAKeyPair(KeyStoreCryptoManager.java:306)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.initRsaKeyPair(KeyStoreCryptoManager.java:286)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.<init>(KeyStoreCryptoManager.java:99)
        at com.flowcrypt.email.security.SecurityUtils.getPrivateKeysInfo(SecurityUtils.java:40)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:99)
        at com.flowcrypt.email.security.SecurityStorageConnector.<init>(SecurityStorageConnector.java:36)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:230)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:509)
        ... 15 more
Caused by: android.security.KeyStoreException: -22
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:676)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:231)
        ... 17 more
java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:230)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:509)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.generateKeyIfAndroidVersionEqualOrHigherThenMarshmallow(KeyStoreCryptoManager.java:334)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.createRSAKeyPair(KeyStoreCryptoManager.java:306)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.initRsaKeyPair(KeyStoreCryptoManager.java:286)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.<init>(KeyStoreCryptoManager.java:99)
        at com.flowcrypt.email.security.SecurityUtils.getPrivateKeysInfo(SecurityUtils.java:40)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:99)
        at com.flowcrypt.email.security.SecurityStorageConnector.<init>(SecurityStorageConnector.java:36)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: android.security.KeyStoreException: -22
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:676)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:231)
        ... 17 more
android.security.KeyStoreException: -22
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:676)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:231)
        at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:509)
        at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.generateKeyIfAndroidVersionEqualOrHigherThenMarshmallow(KeyStoreCryptoManager.java:334)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.createRSAKeyPair(KeyStoreCryptoManager.java:306)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.initRsaKeyPair(KeyStoreCryptoManager.java:286)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.<init>(KeyStoreCryptoManager.java:99)
        at com.flowcrypt.email.security.SecurityUtils.getPrivateKeysInfo(SecurityUtils.java:40)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:99)
        at com.flowcrypt.email.security.SecurityStorageConnector.<init>(SecurityStorageConnector.java:36)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#inbox/162613b299efefb3

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1628d6bac29a7422

**Comment by DenBond7** [comment]
Similar to #232
