### ISSUE TITLE
JavaScript error when opening plain text or html messages

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#242]
```
[STACK_TRACE]
java.lang.Exception: JsBackgroundService.onError
        at com.flowcrypt.email.service.JsBackgroundService.onError(JsBackgroundService.java:157)
        at com.flowcrypt.email.js.tasks.BaseJsTask.handleException(BaseJsTask.java:31)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.runJsTask(JsInBackgroundManager.java:229)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:198)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.UnsupportedOperationException
        at com.eclipsesource.v8.V8Array$Undefined.length(V8Array.java:1121)
        at com.flowcrypt.email.js.ProcessedMime.getAddressHeader(ProcessedMime.java:34)
        at com.flowcrypt.email.js.tasks.DecryptRawMimeMessageJsTask.runAction(DecryptRawMimeMessageJsTask.java:71)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.runJsTask(JsInBackgroundManager.java:220)
        ... 6 more
java.lang.UnsupportedOperationException
        at com.eclipsesource.v8.V8Array$Undefined.length(V8Array.java:1121)
        at com.flowcrypt.email.js.ProcessedMime.getAddressHeader(ProcessedMime.java:34)
        at com.flowcrypt.email.js.tasks.DecryptRawMimeMessageJsTask.runAction(DecryptRawMimeMessageJsTask.java:71)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.runJsTask(JsInBackgroundManager.java:220)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:198)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

```

**Comment by DenBond7** [comment]
Duplicate #237
