### ISSUE TITLE
AddNewAccountActivity GoogleSignInAccount == null

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#246]
```
[STACK_TRACE]
java.lang.RuntimeException: Unable to resume activity {com.flowcrypt.email/com.flowcrypt.email.ui.activity.AddNewAccountActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=-1, data=null} to activity {com.flowcrypt.email/com.flowcrypt.email.ui.activity.AddNewAccountActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.auth.api.signin.GoogleSignInAccount.getEmail()' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3121)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2499)
        at android.app.ActivityThread.access$900(ActivityThread.java:157)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5525)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=-1, data=null} to activity {com.flowcrypt.email/com.flowcrypt.email.ui.activity.AddNewAccountActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.auth.api.signin.GoogleSignInAccount.getEmail()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3742)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3107)
        ... 10 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.auth.api.signin.GoogleSignInAccount.getEmail()' on a null object reference
        at com.flowcrypt.email.ui.activity.AddNewAccountActivity.saveGmailAccountToDatabase(AddNewAccountActivity.java:252)
        at com.flowcrypt.email.ui.activity.AddNewAccountActivity.returnResultOk(AddNewAccountActivity.java:239)
        at com.flowcrypt.email.ui.activity.AddNewAccountActivity.onActivityResult(AddNewAccountActivity.java:139)
        at android.app.Activity.dispatchActivityResult(Activity.java:6463)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3738)
        ... 11 more
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=101, result=-1, data=null} to activity {com.flowcrypt.email/com.flowcrypt.email.ui.activity.AddNewAccountActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.auth.api.signin.GoogleSignInAccount.getEmail()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3742)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3107)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2499)
        at android.app.ActivityThread.access$900(ActivityThread.java:157)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5525)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.auth.api.signin.GoogleSignInAccount.getEmail()' on a null object reference
        at com.flowcrypt.email.ui.activity.AddNewAccountActivity.saveGmailAccountToDatabase(AddNewAccountActivity.java:252)
        at com.flowcrypt.email.ui.activity.AddNewAccountActivity.returnResultOk(AddNewAccountActivity.java:239)
        at com.flowcrypt.email.ui.activity.AddNewAccountActivity.onActivityResult(AddNewAccountActivity.java:139)
        at android.app.Activity.dispatchActivityResult(Activity.java:6463)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3738)
        ... 11 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.android.gms.auth.api.signin.GoogleSignInAccount.getEmail()' on a null object reference
        at com.flowcrypt.email.ui.activity.AddNewAccountActivity.saveGmailAccountToDatabase(AddNewAccountActivity.java:252)
        at com.flowcrypt.email.ui.activity.AddNewAccountActivity.returnResultOk(AddNewAccountActivity.java:239)
        at com.flowcrypt.email.ui.activity.AddNewAccountActivity.onActivityResult(AddNewAccountActivity.java:139)
        at android.app.Activity.dispatchActivityResult(Activity.java:6463)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:3738)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3107)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2499)
        at android.app.ActivityThread.access$900(ActivityThread.java:157)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5525)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
```

ref https://mail.google.com/mail/u/0/#inbox/162d78eba27bde10

**Comment by DenBond7** [comment]
Similar to #188 but in another activity
