### ISSUE TITLE
EmailWebView$CustomWebClient.shouldOverrideUrlLoading need to do resolveActivity

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#247]
```
[STACK_TRACE]
android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=cid:5ad677ca89368905e797dad1.svg@www.emailprivacytester.com (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
        at android.app.Activity.startActivityForResult(Activity.java:4487)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
        at android.app.Activity.startActivityForResult(Activity.java:4445)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
        at android.app.Activity.startActivity(Activity.java:4806)
        at android.support.v4.content.ContextCompat.startActivity(ContextCompat.java:143)
        at android.support.customtabs.CustomTabsIntent.launchUrl(CustomTabsIntent.java:262)
        at com.flowcrypt.email.ui.widget.EmailWebView$CustomWebClient.showUrlUsingChromeCustomTabs(EmailWebView.java:99)
        at com.flowcrypt.email.ui.widget.EmailWebView$CustomWebClient.shouldOverrideUrlLoading(EmailWebView.java:86)
        at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:397)
        at org.chromium.android_webview.AwContentsClient.shouldIgnoreNavigation(AwContentsClient.java:173)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:389)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:51)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6499)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

ref https://mail.google.com/mail/u/0/#inbox/162d5c7cde95faf4

**Comment by DenBond7** [comment]
Resolved by https://github.com/FlowCrypt/flowcrypt-android/commit/57742e943676eb750d59baca67f60c9f3224cf80
