### ISSUE TITLE
BaseSyncRunnable AuthCredentials.getUsername() == null

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#248]
```
[STACK_TRACE]
java.lang.Exception: EmailSyncService.onError
        at com.flowcrypt.email.service.EmailSyncService.onError(EmailSyncService.java:409)
        at com.flowcrypt.email.api.email.sync.tasks.BaseSyncTask.handleException(BaseSyncTask.java:70)
        at com.flowcrypt.email.api.email.sync.tasks.UpdateLabelsSyncTask.handleException(UpdateLabelsSyncTask.java:26)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:499)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$PassiveSyncTaskRunnable.run(EmailSyncManager.java:552)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.model.AuthCredentials.getUsername()' on a null object reference
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.resetConnectionIfNeed(EmailSyncManager.java:414)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:469)
        ... 6 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.model.AuthCredentials.getUsername()' on a null object reference
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.resetConnectionIfNeed(EmailSyncManager.java:414)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:469)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$PassiveSyncTaskRunnable.run(EmailSyncManager.java:552)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

ref https://mail.google.com/mail/u/0/#inbox/162d1489b604f520

**Comment by DenBond7** [comment]
It's a platform bug (LineageOS). Similar to #232. AndroiKeyStore doesn't work properly -> We can't decrypt auth credentials.
