### ISSUE TITLE
Many com.flowcrypt.email.util.exception.ManualHandledException error reports

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-android#2595]
I checked exceptions reports for latest android releases and almost all of them are `com.flowcrypt.email.util.exception.ManualHandledException`:

```
title: com.flowcrypt.email.util.exception.ManualHandledException
message: Handled manually:
url: com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:27)
line: 27
column: 1
```

But stack trace for different versions has different `Caused by` messages, for example:

version 152
```
Caused by: com.flowcrypt.email.util.exception.GmailAPIException: Requested entity was not found.
at com.flowcrypt.email.api.email.gmail.GmailApiHelper$Companion.processException(GmailApiHelper.kt:1105)
at com.flowcrypt.email.api.email.gmail.GmailApiHelper$Companion.access$processException(GmailApiHelper.kt:86)
at com.flowcrypt.email.api.email.gmail.GmailApiHelper$Companion$executeWithResult$2.invokeSuspend(GmailApiHelper.kt:139)
... 22 more
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
GET https://gmail.example.file/gmail/v1/users/me/history?labelId=INBOX&startHistoryId=4111
{
"code": 404,
"errors": [
{
"domain": "global",
"message": "Requested entity was not found.",
"reason": "notFound"
}
],
"message": "Requested entity was not found.",
"status": "NOT_FOUND"
}
```

version 151
```
Caused by: android.os.DeadObjectException
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(BinderProxy.java:584)
```

version 150
```
Caused by: java.lang.NullPointerException: getLabelIds(...) must not be null
at com.flowcrypt.email.api.email.gmail.GmailApiHelper$Companion$processHistory$2.invokeSuspend(GmailApiHelper.kt:568)
at com.flowcrypt.email.api.email.gmail.GmailApiHelper$Companion$processHistory$2.invoke(Unknown Source:8)
at com.flowcrypt.email.api.email.gmail.GmailApiHelper$Companion$processHistory$2.invoke(Unknown Source:4)
```

Looks like most errors are reported as `com.flowcrypt.email.util.exception.ManualHandledException` while original error messages are different, making it complicated to find original errors.

Is it possible to improve error reporting code to send original error instead of `ManualHandledException`?

**Comment by DenBond7** [comment]
I will check how to fix it
