### ISSUE TITLE
Test FlowCrypt with G Suite (Service Account)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#266]
Need to test the app with G Suite accounts. Currently, I don't know how to do that.

We are receiving a lot of issues look like this:

```
[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:97)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:87)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:41)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Bad Request",
    "reason" : "failedPrecondition"
  } ],
  "message" : "Bad Request"
}
```

I've investigated some resources and found that it can be a problem with G Suite but I'm not sure.

**Comment by DenBond7** [comment]
https://groups.google.com/forum/#!topic/google-appengine/WlLYxMQcs3M

**Comment by tomholub** [comment]
I use G-suite. Maybe the G-suite admin dis-allowed Gmail access through oauth on the domain?
