### ISSUE TITLE
NPE in the Js tools

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#267]
https://github.com/FlowCrypt/flowcrypt-android/blob/b2a939746b5a058bfbcaf397caeae70738247bb6/FlowCrypt/src/main/java/com/flowcrypt/email/js/Js.java#L183

I think `((V8Object) cb_last_value[0]) == null` 
or `((V8Object) cb_last_value[0]).get("data") == null` sometimes

```
[STACK_TRACE]
java.lang.Exception: EmailSyncService.onError
        at com.flowcrypt.email.service.EmailSyncService.onError(EmailSyncService.java:460)
        at com.flowcrypt.email.api.email.sync.tasks.BaseSyncTask.handleException(BaseSyncTask.java:70)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.handleException(SendMessageSyncTask.java:77)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:538)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:613)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.eclipsesource.v8.V8Object.get(java.lang.String)' on a null object reference
        at com.flowcrypt.email.js.Js.crypto_message_encrypt(Js.java:183)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.generateRawMessageWithoutAttachments(SendMessageSyncTask.java:365)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.createMimeMessage(SendMessageSyncTask.java:236)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.runSMTPAction(SendMessageSyncTask.java:131)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:528)
        ... 6 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.eclipsesource.v8.V8Object.get(java.lang.String)' on a null object reference
        at com.flowcrypt.email.js.Js.crypto_message_encrypt(Js.java:183)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.generateRawMessageWithoutAttachments(SendMessageSyncTask.java:365)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.createMimeMessage(SendMessageSyncTask.java:236)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.runSMTPAction(SendMessageSyncTask.java:131)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:528)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:613)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvwxxZjnzDdtFwPcbRZlPvDsvSC

**Comment by tomholub** [comment]
likely resolved with Node
