### ISSUE TITLE
IdleSyncRunnable NPE Folder.getServerFullFolderName()

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#277]
```
[SUMMARY]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.Folder.getServerFullFolderName()' on a null object reference
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:110)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.idle(EmailSyncManager.java:786)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.run(EmailSyncManager.java:701)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.Folder.getServerFullFolderName()' on a null object reference
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.idle(EmailSyncManager.java:763)
        ... 6 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.email.Folder.getServerFullFolderName()' on a null object reference
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.idle(EmailSyncManager.java:763)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.run(EmailSyncManager.java:701)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvxBFlQRGhQbsbtbnBklZnhsXWS

Steps to reproduce:
1) Delete the app
2) Install the app
3) Setup an account
4) IdleSyncRunnable will run when we don't have any information about labels --> need to fix that

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/commit/9b957cd8d0bf73532b8c2de1ac5139ab5c110a47
