### ISSUE TITLE
Exlude "Connection dropped by server?" from the ACRA reports

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#312]
```
[SUMMARY]
com.sun.mail.iap.ConnectionException: * BYE JavaMail Exception: java.io.IOException: Connection dropped by server?
javax.mail.MessagingException: * BYE JavaMail Exception: java.io.IOException: Connection dropped by server?;
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:110)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:596)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$PassiveSyncTaskRunnable.run(EmailSyncManager.java:652)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: javax.mail.MessagingException: * BYE JavaMail Exception: java.io.IOException: Connection dropped by server?;
  nested exception is:
        com.sun.mail.iap.ConnectionException: * BYE JavaMail Exception: java.io.IOException: Connection dropped by server?
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:738)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:92)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:90)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:175)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:548)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:577)
        ... 6 more
Caused by: com.sun.mail.iap.ConnectionException: * BYE JavaMail Exception: java.io.IOException: Connection dropped by server?
        at com.sun.mail.iap.Protocol.handleResult(Protocol.java:442)
        at com.sun.mail.imap.protocol.IMAPProtocol.handleLoginResult(IMAPProtocol.java:1065)
        at com.sun.mail.imap.protocol.IMAPProtocol.authoauth2(IMAPProtocol.java:962)
        at com.sun.mail.imap.IMAPStore.authenticate(IMAPStore.java:921)
        at com.sun.mail.imap.IMAPStore.login(IMAPStore.java:824)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:705)
        ... 13 more
javax.mail.MessagingException: * BYE JavaMail Exception: java.io.IOException: Connection dropped by server?;
  nested exception is:
        com.sun.mail.iap.ConnectionException: * BYE JavaMail Exception: java.io.IOException: Connection dropped by server?
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:738)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:92)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:90)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:175)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:548)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:577)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$PassiveSyncTaskRunnable.run(EmailSyncManager.java:652)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: com.sun.mail.iap.ConnectionException: * BYE JavaMail Exception: java.io.IOException: Connection dropped by server?
        at com.sun.mail.iap.Protocol.handleResult(Protocol.java:442)
        at com.sun.mail.imap.protocol.IMAPProtocol.handleLoginResult(IMAPProtocol.java:1065)
        at com.sun.mail.imap.protocol.IMAPProtocol.authoauth2(IMAPProtocol.java:962)
        at com.sun.mail.imap.IMAPStore.authenticate(IMAPStore.java:921)
        at com.sun.mail.imap.IMAPStore.login(IMAPStore.java:824)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:705)
        ... 13 more
com.sun.mail.iap.ConnectionException: * BYE JavaMail Exception: java.io.IOException: Connection dropped by server?
        at com.sun.mail.iap.Protocol.handleResult(Protocol.java:442)
        at com.sun.mail.imap.protocol.IMAPProtocol.handleLoginResult(IMAPProtocol.java:1065)
        at com.sun.mail.imap.protocol.IMAPProtocol.authoauth2(IMAPProtocol.java:962)
        at com.sun.mail.imap.IMAPStore.authenticate(IMAPStore.java:921)
        at com.sun.mail.imap.IMAPStore.login(IMAPStore.java:824)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:705)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:92)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToGimapsStore(OpenStoreHelper.java:90)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper.openAndConnectToStore(OpenStoreHelper.java:175)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnectionToStore(EmailSyncManager.java:548)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:577)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$PassiveSyncTaskRunnable.run(EmailSyncManager.java:652)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKbLWVxnctgJmggMPqJnCdkTm

**Comment by tomholub** [comment]
This happened to me. I had to manually go back from the message, then open the message again (or something like that). The app should retry automatically one time, and still send ACRA report if there is exception when retrying (for now).

**Comment by tomholub** [comment]
I guess I mean reconnect + retry.
