### ISSUE TITLE
user_id_emails_and_keys SQLITE_CONSTRAINT_UNIQUE

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#315]
```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
android.database.SQLException: Failed to insert row into content://com.flowcrypt.email.SecurityContentProvider/user_id_emails_and_keys


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:110)
        at com.flowcrypt.email.database.provider.SecurityContentProvider.bulkInsert(SecurityContentProvider.java:247)
        at android.content.ContentProvider$Transport.bulkInsert(ContentProvider.java:280)
        at android.content.ContentResolver.bulkInsert(ContentResolver.java:1652)
        at com.flowcrypt.email.database.dao.source.UserIdEmailsKeysDaoSource.addRows(UserIdEmailsKeysDaoSource.java:92)
        at com.flowcrypt.email.service.actionqueue.actions.FillUserIdEmailsKeysTableAction.run(FillUserIdEmailsKeysTableAction.java:75)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.java:91)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.SQLException: Failed to insert row into content://com.flowcrypt.email.SecurityContentProvider/user_id_emails_and_keys
        at com.flowcrypt.email.database.provider.SecurityContentProvider.bulkInsert(SecurityContentProvider.java:233)
        ... 12 more
android.database.SQLException: Failed to insert row into content://com.flowcrypt.email.SecurityContentProvider/user_id_emails_and_keys
        at com.flowcrypt.email.database.provider.SecurityContentProvider.bulkInsert(SecurityContentProvider.java:233)
        at android.content.ContentProvider$Transport.bulkInsert(ContentProvider.java:280)
        at android.content.ContentResolver.bulkInsert(ContentResolver.java:1652)
        at com.flowcrypt.email.database.dao.source.UserIdEmailsKeysDaoSource.addRows(UserIdEmailsKeysDaoSource.java:92)
        at com.flowcrypt.email.service.actionqueue.actions.FillUserIdEmailsKeysTableAction.run(FillUserIdEmailsKeysTableAction.java:75)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.java:91)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKbLVkZRvDNRRvvVnFFCxCSvX

**Comment by tomholub** [comment]
Is this a key user id? User id emails may not always be unique in the keys. I may put three users in my key, all with the same email. You can skip duplicate uid emails.

**Comment by DenBond7** [comment]
> You can skip duplicate uid emails.

It was a bug in my code. I've fixed it.

Everything works according to #269
