### ISSUE TITLE
TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#318]
```
[SUMMARY]
undefined:325: TypeError: Cannot read property 'replace' of null
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:110)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:93)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:44)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: undefined:325: TypeError: Cannot read property 'replace' of null
    return str.replace(RegExp(String.fromCharCode(160), 'g'), String.fromCharCode(32)).replace(/\n /g, '\n');
              ^
TypeError: Cannot read property 'replace' of null
    at str_normalize_spaces (<anonymous>:325:15)
    at Object.crypto_armor_detect_blocks [as detect_blocks] (<anonymous>:1698:21)
com.eclipsesource.v8.V8ScriptExecutionException
        at com.eclipsesource.v8.V8._executeFunction(Native Method)
        at com.eclipsesource.v8.V8.executeFunction(V8.java:1125)
        at com.eclipsesource.v8.V8Object.executeObjectFunction(V8Object.java:349)
        at com.flowcrypt.email.js.Js.call(Js.java:298)
        at com.flowcrypt.email.js.Js.call(Js.java:277)
        at com.flowcrypt.email.js.Js.crypto_armor_detect_blocks(Js.java:127)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.getPrivateKeyBackupsUsingJavaMailAPI(LoadPrivateKeysFromMailAsyncTaskLoader.java:139)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:87)
        ... 9 more
undefined:325: TypeError: Cannot read property 'replace' of null
    return str.replace(RegExp(String.fromCharCode(160), 'g'), String.fromCharCode(32)).replace(/\n /g, '\n');
              ^
TypeError: Cannot read property 'replace' of null
    at str_normalize_spaces (<anonymous>:325:15)
    at Object.crypto_armor_detect_blocks [as detect_blocks] (<anonymous>:1698:21)
com.eclipsesource.v8.V8ScriptExecutionException
        at com.eclipsesource.v8.V8._executeFunction(Native Method)
        at com.eclipsesource.v8.V8.executeFunction(V8.java:1125)
        at com.eclipsesource.v8.V8Object.executeObjectFunction(V8Object.java:349)
        at com.flowcrypt.email.js.Js.call(Js.java:298)
        at com.flowcrypt.email.js.Js.call(Js.java:277)
        at com.flowcrypt.email.js.Js.crypto_armor_detect_blocks(Js.java:127)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.getPrivateKeyBackupsUsingJavaMailAPI(LoadPrivateKeysFromMailAsyncTaskLoader.java:139)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:87)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:44)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref [com.flowcrypt.email-0.6.6-E077D8F375: Cannot read property 'replace' of null > Handled manually:](https://mail.google.com/mail/u/0/?sw=1&token=%5B%22cftp%22,%22ec702379ce%22,%22uYBY6TMxuGB2_JeDDicUfw%5Cu003d%5Cu003d%22,%224xZtFcmMfDU-lL0gGe71dQ%5Cu003d%5Cu003d%22,%226853,7325,7186,7360,6887,6807,7321,6858,7164,7108,7426,7118,6761,6838,7195,7243,7008,7417,6812,7018,7068,6778,6929,6969,7367,6806,7017,7150,7196,10041,6912,7128,6758,6804,7179,6999,7203,7387,7395,7278,7384,7156,6767,7294,6772,7023,6944,6984,6949,7354,7408,7005,7391,6763,7183,7020,7269,6749,7161,6765,6905,7030,7310,7371,7027,7270,6842,7324,7016,7386,7398,7185,7392,7024,7292,7236,7238,7335,6821,7291,7147,7050,6839,7092,6755,7096,7401,7295,7026,7137,6745,6836,6851,6917,6792,7240,7034%22%5D&dilte=0#inbox/FMfcgxvzKbPxvSvMLQzGHCFZnfXdBrxL)

I've received this error when I was trying to add a new account.

`LoadPrivateKeysFromMailAsyncTaskLoader --> com.flowcrypt.email.js.Js.crypto_armor_detect_blocks(Js.java:127)`

**Comment by tomholub** [comment]
@DenBond7 The string was put into `Js.crypto_armor_detect_blocks` was a null, not a string. Look into where that null is coming from.
