### ISSUE TITLE
InterruptedException in EmailSyncManager

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#320]
```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
java.lang.InterruptedException


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:110)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager.refreshMessages(EmailSyncManager.java:331)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.syncFolderState(EmailSyncManager.java:830)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.idle(EmailSyncManager.java:778)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.idle(EmailSyncManager.java:791)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.run(EmailSyncManager.java:715)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1244)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:336)
        at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager.refreshMessages(EmailSyncManager.java:328)
        ... 9 more
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1244)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:336)
        at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager.refreshMessages(EmailSyncManager.java:328)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.syncFolderState(EmailSyncManager.java:830)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.idle(EmailSyncManager.java:778)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.idle(EmailSyncManager.java:791)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$IdleSyncRunnable.run(EmailSyncManager.java:715)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKbRHBxVTZwxgBWmrtCRhNVKl

**Comment by DenBond7** [comment]
Excluded from the ACRA reports. Such exceptions need only for local debugging.

**Comment by tomholub** [comment]
Thanks for mentioning this, I like to know how were exceptions handled and why. Thanks
