### ISSUE TITLE
sConnected failed: ENETUNREACH

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#324]
```
[SUMMARY]
android.system.ErrnoException: isConnected failed: ENETUNREACH (Network is unreachable)
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
java.net.ConnectException: failed to connect to www.googleapis.com/2a00:1450:4019:803::200a (port 443) after 20000ms: isConnected failed: ENETUNREACH (Network is unreachable)


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:110)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:93)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:44)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.ConnectException: failed to connect to www.googleapis.com/2a00:1450:4019:803::200a (port 443) after 20000ms: isConnected failed: ENETUNREACH (Network is unreachable)
        at libcore.io.IoBridge.isConnected(IoBridge.java:238)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
        at libcore.io.IoBridge.connect(IoBridge.java:122)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
        at java.net.Socket.connect(Socket.java:882)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
        at com.android.okhttp.Connection.connect(Connection.java:1222)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:395)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:105)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.flowcrypt.email.api.email.EmailUtil.getPrivateKeyBackupsUsingGmailAPI(EmailUtil.java:319)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:83)
        ... 9 more
Caused by: android.system.ErrnoException: isConnected failed: ENETUNREACH (Network is unreachable)
        at libcore.io.IoBridge.isConnected(IoBridge.java:223)
        ... 31 more
java.net.ConnectException: failed to connect to www.googleapis.com/2a00:1450:4019:803::200a (port 443) after 20000ms: isConnected failed: ENETUNREACH (Network is unreachable)
        at libcore.io.IoBridge.isConnected(IoBridge.java:238)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
        at libcore.io.IoBridge.connect(IoBridge.java:122)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
        at java.net.Socket.connect(Socket.java:882)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
        at com.android.okhttp.Connection.connect(Connection.java:1222)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:395)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:105)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.flowcrypt.email.api.email.EmailUtil.getPrivateKeyBackupsUsingGmailAPI(EmailUtil.java:319)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:83)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:44)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: isConnected failed: ENETUNREACH (Network is unreachable)
        at libcore.io.IoBridge.isConnected(IoBridge.java:223)
        ... 31 more
android.system.ErrnoException: isConnected failed: ENETUNREACH (Network is unreachable)
        at libcore.io.IoBridge.isConnected(IoBridge.java:223)
        at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
        at libcore.io.IoBridge.connect(IoBridge.java:122)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
        at java.net.Socket.connect(Socket.java:882)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:174)
        at com.android.okhttp.Connection.connect(Connection.java:1222)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:395)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:298)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:399)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
        at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:37)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:105)
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
        at com.flowcrypt.email.api.email.EmailUtil.getPrivateKeyBackupsUsingGmailAPI(EmailUtil.java:319)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:83)
        at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:44)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKkrBTfcXgqqGjBsHJtMvlGCS

**Comment by DenBond7** [comment]
The app handles such errors correctly. So I've excluded them from the ACRA reports.
