### ISSUE TITLE
SMTPSendFailedException: [EOF]

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#326]
```
[SUMMARY]
com.sun.mail.smtp.SMTPSendFailedException: [EOF]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:110)
        at com.flowcrypt.email.service.EmailSyncService.onError(EmailSyncService.java:554)
        at com.flowcrypt.email.api.email.sync.tasks.BaseSyncTask.handleException(BaseSyncTask.java:70)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.handleException(SendMessageSyncTask.java:79)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:597)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:676)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: com.sun.mail.smtp.SMTPSendFailedException: [EOF]
        at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2358)
        at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:2110)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1316)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.runSMTPAction(SendMessageSyncTask.java:140)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:587)
        ... 6 more
com.sun.mail.smtp.SMTPSendFailedException: [EOF]
        at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2358)
        at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:2110)
        at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1316)
        at com.flowcrypt.email.api.email.sync.tasks.SendMessageSyncTask.runSMTPAction(SendMessageSyncTask.java:140)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:587)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:676)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKkprvJQLGKQhWnNprrgddSvh

**Comment by DenBond7** [comment]
It's [a communication error](https://github.com/javaee/javamail/blob/8106b9dd15e917da63e96c33f8c6aea1cad40045/mail/src/main/java/com/sun/mail/smtp/SMTPTransport.java#L2428).  After release a new version such error will not matter, because we'll have a new sending logic. If a user will receive such error we'll send a message when connection will established.
