### ISSUE TITLE
NumberFormatException: For input string: "NaN" in Js.time_to_utc_timestamp

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#330]
```
[SUMMARY]
java.lang.NumberFormatException: For input string: "NaN"
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:110)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.runJsTask(JsInBackgroundManager.java:229)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:203)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NumberFormatException: For input string: "NaN"
        at java.lang.Long.parseLong(Long.java:590)
        at java.lang.Long.parseLong(Long.java:632)
        at com.flowcrypt.email.js.Js.time_to_utc_timestamp(Js.java:85)
        at com.flowcrypt.email.js.ProcessedMime.getTimeHeader(ProcessedMime.java:29)
        at com.flowcrypt.email.js.tasks.DecryptRawMimeMessageJsTask.runAction(DecryptRawMimeMessageJsTask.java:79)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.runJsTask(JsInBackgroundManager.java:225)
        ... 6 more
java.lang.NumberFormatException: For input string: "NaN"
        at java.lang.Long.parseLong(Long.java:590)
        at java.lang.Long.parseLong(Long.java:632)
        at com.flowcrypt.email.js.Js.time_to_utc_timestamp(Js.java:85)
        at com.flowcrypt.email.js.ProcessedMime.getTimeHeader(ProcessedMime.java:29)
        at com.flowcrypt.email.js.tasks.DecryptRawMimeMessageJsTask.runAction(DecryptRawMimeMessageJsTask.java:79)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.runJsTask(JsInBackgroundManager.java:225)
        at com.flowcrypt.email.js.JsInBackgroundManager$JsRunnable.run(JsInBackgroundManager.java:203)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#search/0.6.6+InterruptedException/FMfcgxvzKbPwggMWlmnszhDrPBBlNljr

**Comment by DenBond7** [comment]
@tomholub It happens for some messages when we are trying to decrypt them (when we are trying to receive date)
https://github.com/FlowCrypt/flowcrypt-android/blob/e738a8c0807e46c66b901c3ab3ee9a3cf4a54405/FlowCrypt/src/main/java/com/flowcrypt/email/js/tasks/DecryptRawMimeMessageJsTask.java#L79

Do you return `NaN` for some cases if the MIME message doesn't contain "date" header (or other cases)?

As I've understood, [Js.time_to_utc_timestamp](https://github.com/FlowCrypt/flowcrypt-android/blob/e738a8c0807e46c66b901c3ab3ee9a3cf4a54405/FlowCrypt/src/main/java/com/flowcrypt/email/js/Js.java#L84) receives a wrong date as String. I've not found any information where we receive NaN as the "date" header value.

**Comment by tomholub** [comment]
I bet it will show NaN when the header is missing or malformed. You could test that. Anyway, in such cases, getTimeHeader should probably return a null to be consistent, not a "NaN", and then you would hide the date field from displaying.

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#search/label%3Aunread/FMfcgxvzLDrvkWjxXJtFGJFpKjJVnvjw
