### ISSUE TITLE
NPE in MessageListAdapter

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#334]
```
[SUMMARY]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference


[STACK_TRACE]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
        at com.flowcrypt.email.ui.adapter.MessageListAdapter.updateItem(MessageListAdapter.java:108)
        at com.flowcrypt.email.ui.adapter.MessageListAdapter.bindView(MessageListAdapter.java:78)
        at android.widget.CursorAdapter.getView(CursorAdapter.java:289)
        at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:232)
        at android.widget.AbsListView.obtainView(AbsListView.java:3180)
        at android.widget.ListView.makeAndAddView(ListView.java:2197)
        at android.widget.ListView.fillSpecific(ListView.java:1522)
        at android.widget.ListView.layoutChildren(ListView.java:1914)
        at android.widget.AbsListView.onLayout(AbsListView.java:2952)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:606)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:132)
        at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
        at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1361)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:894)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1171)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1791)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1635)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1544)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:961)
        at android.view.View.layout(View.java:20950)
        at android.view.ViewGroup.layout(ViewGroup.java:6439)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3027)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2714)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1843)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7978)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7002)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKtTMFqTrCsFFhSVJNFhhrwhV

**Comment by tomholub** [comment]
Remember to get some rest as well :)
