### ISSUE TITLE
Permission Denial: opening provider

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#337]
```
[SUMMARY]
java.lang.SecurityException: Permission Denial: opening provider com.adobe.reader.misc.ARFileProvider from ProcessRecord{37c11a3c 16718:com.flowcrypt.email/u0a80} (pid=16718, uid=10080) that is not exported from uid 10096
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:117)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.java:162)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.adobe.reader.misc.ARFileProvider from ProcessRecord{37c11a3c 16718:com.flowcrypt.email/u0a80} (pid=16718, uid=10080) that is not exported from uid 10096
        at android.os.Parcel.readException(Parcel.java:1546)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3314)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:4624)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2472)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1442)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1064)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.addAttachmentsToCache(PrepareOutgoingMessagesJobIntentService.java:218)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.java:149)
        ... 7 more
java.lang.SecurityException: Permission Denial: opening provider com.adobe.reader.misc.ARFileProvider from ProcessRecord{37c11a3c 16718:com.flowcrypt.email/u0a80} (pid=16718, uid=10080) that is not exported from uid 10096
        at android.os.Parcel.readException(Parcel.java:1546)
        at android.os.Parcel.readException(Parcel.java:1499)
        at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3314)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:4624)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2472)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1442)
        at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1064)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
        at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.addAttachmentsToCache(PrepareOutgoingMessagesJobIntentService.java:218)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.java:149)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:391)
        at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:382)
        at android.os.AsyncTask$2.call(AsyncTask.java:292)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
```

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzLDrwzCTpKBvHDkKftvllfBSB

**Comment by tomholub** [comment]
When would this bug happen? When wanting to share / send a file from other apps through FlowCrypt?

**Comment by DenBond7** [comment]
> When wanting to share / send a file from other apps through FlowCrypt?

Yes. It's what I mean.
