### ISSUE TITLE
MessageRemovedException in MessageDaoSource

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#338]
```
[SUMMARY]
javax.mail.MessageRemovedException
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:117)
        at com.flowcrypt.email.jobscheduler.SyncJobService.onNewMessagesReceived(SyncJobService.java:289)
        at com.flowcrypt.email.api.email.sync.tasks.SyncFolderSyncTask.runIMAPAction(SyncFolderSyncTask.java:117)
        at com.flowcrypt.email.jobscheduler.SyncJobService$CheckNewMessagesJobTask.doInBackground(SyncJobService.java:326)
        at com.flowcrypt.email.jobscheduler.SyncJobService$CheckNewMessagesJobTask.doInBackground(SyncJobService.java:297)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
Caused by: javax.mail.MessageRemovedException
        at com.sun.mail.imap.IMAPMessage.checkExpunged(IMAPMessage.java:280)
        at com.sun.mail.imap.IMAPMessage.getReceivedDate(IMAPMessage.java:489)
        at com.flowcrypt.email.database.dao.source.imap.MessageDaoSource.prepareContentValues(MessageDaoSource.java:135)
        at com.flowcrypt.email.database.dao.source.imap.MessageDaoSource.addRows(MessageDaoSource.java:231)
        at com.flowcrypt.email.jobscheduler.SyncJobService.onNewMessagesReceived(SyncJobService.java:268)
        ... 9 more
javax.mail.MessageRemovedException
        at com.sun.mail.imap.IMAPMessage.checkExpunged(IMAPMessage.java:280)
        at com.sun.mail.imap.IMAPMessage.getReceivedDate(IMAPMessage.java:489)
        at com.flowcrypt.email.database.dao.source.imap.MessageDaoSource.prepareContentValues(MessageDaoSource.java:135)
        at com.flowcrypt.email.database.dao.source.imap.MessageDaoSource.addRows(MessageDaoSource.java:231)
        at com.flowcrypt.email.jobscheduler.SyncJobService.onNewMessagesReceived(SyncJobService.java:268)
        at com.flowcrypt.email.api.email.sync.tasks.SyncFolderSyncTask.runIMAPAction(SyncFolderSyncTask.java:117)
        at com.flowcrypt.email.jobscheduler.SyncJobService$CheckNewMessagesJobTask.doInBackground(SyncJobService.java:326)
        at com.flowcrypt.email.jobscheduler.SyncJobService$CheckNewMessagesJobTask.doInBackground(SyncJobService.java:297)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzLDrwMTCcKQXCxxwsKrfXbCQW

**Comment by DenBond7** [comment]
Also in need to look at https://mail.google.com/mail/u/0/#inbox/FMfcgxvzLDrvsdWGChDTmDjNSvZDvWQV

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#search/label%3Aunread/FMfcgxvzLDrvkSLDpWTdHGkJpJXkHjWW
