### ISSUE TITLE
IllegalArgumentException: There are no private keys for example@example.com

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#345]
How to reproduce

1. Install the app

1. Setup the first account (import private keys)

1. Setup the second account which has backups (Select `USE EXISTING KEYS`)

1. Go to Settings -> Backups -> Select `SEE MORE BACKUP OPTIONS` -> try to backup private keys

```
[SUMMARY]
java.lang.IllegalArgumentException: There are no private keys for info@nvimp.com
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:117)
        at com.flowcrypt.email.ui.loader.SavePrivateKeyAsFileAsyncTaskLoader.loadInBackground(SavePrivateKeyAsFileAsyncTaskLoader.java:50)
        at com.flowcrypt.email.ui.loader.SavePrivateKeyAsFileAsyncTaskLoader.loadInBackground(SavePrivateKeyAsFileAsyncTaskLoader.java:31)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.IllegalArgumentException: There are no private keys for info@nvimp.com
        at com.flowcrypt.email.security.SecurityUtils.generatePrivateKeysBackup(SecurityUtils.java:133)
        at com.flowcrypt.email.ui.loader.SavePrivateKeyAsFileAsyncTaskLoader.loadInBackground(SavePrivateKeyAsFileAsyncTaskLoader.java:47)
        ... 9 more
java.lang.IllegalArgumentException: There are no private keys for info@nvimp.com
        at com.flowcrypt.email.security.SecurityUtils.generatePrivateKeysBackup(SecurityUtils.java:133)
        at com.flowcrypt.email.ui.loader.SavePrivateKeyAsFileAsyncTaskLoader.loadInBackground(SavePrivateKeyAsFileAsyncTaskLoader.java:47)
        at com.flowcrypt.email.ui.loader.SavePrivateKeyAsFileAsyncTaskLoader.loadInBackground(SavePrivateKeyAsFileAsyncTaskLoader.java:31)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

ref https://mail.google.com/mail/u/0/#label/Work%2FFlowCrypt%2FCrashes/FMfcgxvzLDzrvRPFpLljtSNvrVWNTWph

**Comment by tomholub** [comment]
What is the new behavior when this happens now?

**Comment by DenBond7** [comment]
> What is the new behavior when this happens now?

When a user clicks on the backup button I'm checking the imported private keys for the current account. If he doesn't have the imported private keys I'm showing the next hint:

![image](https://user-images.githubusercontent.com/2863246/47208036-76b59680-d395-11e8-89bb-fab96b6a7d7a.png)

**Comment by tomholub** [comment]
Ok, something to improve later. Thanks

**Comment by DenBond7** [comment]
Ok. I've reopened it and moved to the `even later` milestone.

**Comment by tomholub** [comment]
Better approach is to close include this in 0.6.8, because we have made a code change in current version, and then create a separate issue for future changes.

**Comment by DenBond7** [comment]
I didn't think about it. It has sense. Ok , I'll use such logic in the future. Thanks :)
