### ISSUE TITLE
sent message disappears / not actually sent

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#375]
I've had an issue on prod 0.6.8 on a Redmi 5 where messages would not really be sent, but no error shown.

1) Compose encrypted email to myself
2) Click send
3) Says `sending...`
4) Does not show in Outbox
5) Cannot find in sent
6) Not in inbox either

It just drops the message completely - very bad.

Not encrypted messages get delivered normally.

After I killed the app, I sent a new encrypted message and it got sent. But after that, sent messages were dropping again.

**Comment by tomholub** [comment]
I just tried again, still dropping sent messages even after I kill the app.

**Comment by tomholub** [comment]
Same thing happens on my Moto G 4 with standard Android

**Comment by tomholub** [comment]
Here on a debug build:

```
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
D/CreateMessageActivity: bind to JsBackgroundService
D/CreateMessageActivity: bind to EmailSyncService
V/FragmentManager: moveto ACTIVITY_CREATED: CreateMessageFragment{cc19a5f #0 id=0x7f09005a}
V/FragmentManager: moveto STARTED: CreateMessageFragment{cc19a5f #0 id=0x7f09005a}
D/CreateMessageActivity: onStart
D/CreateMessageActivity: onResume
V/FragmentManager: moveto RESUMED: CreateMessageFragment{cc19a5f #0 id=0x7f09005a}
I/Choreographer: Skipped 34 frames!  The application may be doing too much work on its main thread.
D/CreateMessageActivity: Activity connected to com.flowcrypt.email.service.JsBackgroundService
D/CreateMessageActivity: Activity connected to com.flowcrypt.email.service.EmailSyncService
V/FragmentManager: Saved state of EmailListFragment{e1d0ee8 #0 id=0x7f090082}: Bundle[{android:view_state={2131296386=android.view.AbsSavedState$1@a3e7812, 2131296387=android.view.AbsSavedState$1@a3e7812, 2131296445=android.view.AbsSavedState$1@a3e7812, 2131296516=AbsListView.SavedState{51acbe3 selectedId=-9223372036854775808 firstId=-1 viewTop=0 position=0 height=1536 filter=null checkState={}}, 2131296583=android.widget.ProgressBar$SavedState@b1a29e0, 2131296670=android.view.AbsSavedState$1@a3e7812, 2131296704=android.view.AbsSavedState$1@a3e7812, 2131296788=android.widget.ProgressBar$SavedState@6264499, 2131296789=android.view.AbsSavedState$1@a3e7812, 2131296790=android.view.AbsSavedState$1@a3e7812}}]
    Saved state of zzc{59baabc #1 SupportLifecycleFragmentImpl}: Bundle[{AutoManageHelper=Bundle[{}]}]
    Saved state of SupportRequestManagerFragment{ece2eb5 #2 com.bumptech.glide.manager}{parent=null}: null
    saveAllState: adding fragment #0: EmailListFragment{e1d0ee8 #0 id=0x7f090082}
    saveAllState: adding fragment #1: zzc{59baabc #1 SupportLifecycleFragmentImpl}
    saveAllState: adding fragment #2: SupportRequestManagerFragment{ece2eb5 #2 com.bumptech.glide.manager}{parent=null}
V/FragmentManager: movefrom STARTED: EmailListFragment{e1d0ee8 #0 id=0x7f090082}
    movefrom STARTED: zzc{59baabc #1 SupportLifecycleFragmentImpl}
V/FragmentManager: movefrom STARTED: SupportRequestManagerFragment{ece2eb5 #2 com.bumptech.glide.manager}{parent=null}
D/EmailManagerActivity: onStop
E/sms: Unable to find resource: 0
W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.app.JobIntentService$JobServiceEngineImpl>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/job/JobServiceEngine;
        at void com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.enqueueWork(android.content.Context, com.flowcrypt.email.api.email.model.OutgoingMessageInfo) (PrepareOutgoingMessagesJobIntentService.java:-1)
        at void com.flowcrypt.email.ui.activity.CreateMessageActivity.sendMessage(com.flowcrypt.email.api.email.model.OutgoingMessageInfo) (CreateMessageActivity.java:179)
        at void com.flowcrypt.email.ui.activity.fragment.base.CreateMessageFragment.sendMessage() (CreateMessageFragment.java:1536)
        at boolean com.flowcrypt.email.ui.activity.fragment.base.CreateMessageFragment.onOptionsItemSelected(android.view.MenuItem) (CreateMessageFragment.java:426)
        at boolean androidx.fragment.app.Fragment.performOptionsItemSelected(android.view.MenuItem) (Fragment.java:2587)
        at boolean androidx.fragment.app.FragmentManagerImpl.dispatchOptionsItemSelected(android.view.MenuItem) (FragmentManager.java:3368)
        at boolean androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(android.view.MenuItem) (FragmentController.java:356)
        at boolean androidx.fragment.app.FragmentActivity.onMenuItemSelected(int, android.view.MenuItem) (FragmentActivity.java:442)
        at boolean androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(int, android.view.MenuItem) (AppCompatActivity.java:196)
        at boolean androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(int, android.view.MenuItem) (WindowCallbackWrapper.java:109)
        at boolean androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(int, android.view.MenuItem) (WindowCallbackWrapper.java:109)
        at boolean androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(android.view.MenuItem) (ToolbarActionBar.java:64)
        at boolean androidx.appcompat.widget.Toolbar$1.onMenuItemClick(android.view.MenuItem) (Toolbar.java:204)
        at boolean androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(androidx.appcompat.view.menu.MenuBuilder, android.view.MenuItem) (ActionMenuView.java:781)
        at boolean androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(androidx.appcompat.view.menu.MenuBuilder, android.view.MenuItem) (MenuBuilder.java:840)
        at boolean androidx.appcompat.view.menu.MenuItemImpl.invoke() (MenuItemImpl.java:158)
        at boolean androidx.appcompat.view.menu.MenuBuilder.performItemAction(android.view.MenuItem, androidx.appcompat.view.menu.MenuPresenter, int) (MenuBuilder.java:991)
        at boolean androidx.appcompat.view.menu.MenuBuilder.performItemAction(android.view.MenuItem, int) (MenuBuilder.java:981)
        at boolean androidx.appcompat.widget.ActionMenuView.invokeItem(androidx.appcompat.view.menu.MenuItemImpl) (ActionMenuView.java:625)
        at void androidx.appcompat.view.menu.ActionMenuItemView.onClick(android.view.View) (ActionMenuItemView.java:151)
        at boolean android.view.View.performClick() (View.java:5612)
        at void android.view.View$PerformClick.run() (View.java:22285)
        at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.job.JobServiceEngine" on path: DexPathList[[zip file "/data/app/com.flowcrypt.email.debug-1/base.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.flowcrypt.email.debug-1/split_lib_slice_9_apk.apk"],nat
        at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
        at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
        at void com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.enqueueWork(android.content.Context, com.flowcrypt.email.api.email.model.OutgoingMessageInfo) (PrepareOutgoingMessagesJobIntentService.java:-1)
        at void com.flowcrypt.email.ui.activity.CreateMessageActivity.sendMessage(com.flowcrypt.email.api.email.model.OutgoingMessageInfo) (CreateMessageActivity.java:179)
        at void com.flowcrypt.email.ui.activity.fragment.base.CreateMessageFragment.sendMessage() (CreateMessageFragment.java:1536)
        at boolean com.flowcrypt.email.ui.activity.fragment.base.CreateMessageFragment.onOptionsItemSelected(android.view.MenuItem) (CreateMessageFragment.java:426)
        at boolean androidx.fragment.app.Fragment.performOptionsItemSelected(android.view.MenuItem) (Fragment.java:2587)
        at boolean androidx.fragment.app.FragmentManagerImpl.dispatchOptionsItemSelected(android.view.MenuItem) (FragmentManager.java:3368)
        at boolean androidx.fragment.app.FragmentController.dispatchOptionsItemSelected(android.view.MenuItem) (FragmentController.java:356)
        at boolean androidx.fragment.app.FragmentActivity.onMenuItemSelected(int, android.view.MenuItem) (FragmentActivity.java:442)
        at boolean androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(int, android.view.MenuItem) (AppCompatActivity.java:196)
        at boolean androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(int, android.view.MenuItem) (WindowCallbackWrapper.java:109)
        at boolean androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(int, android.view.MenuItem) (WindowCallbackWrapper.java:109)
        at boolean androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(android.view.MenuItem) (ToolbarActionBar.java:64)
        at boolean androidx.appcompat.widget.Toolbar$1.onMenuItemClick(android.view.MenuItem) (Toolbar.java:204)
        at boolean androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(androidx.appcompat.view.menu.MenuBuilder, android.view.MenuItem) (ActionMenuView.java:781)
        at boolean androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(androidx.appcompat.view.menu.MenuBuilder, android.view.MenuItem) (MenuBuilder.java:840)
        at boolean androidx.appcompat.view.menu.MenuItemImpl.invoke() (MenuItemImpl.java:158)
        at boolean androidx.appcompat.view.menu.MenuBuilder.performItemAction(android.view.MenuItem, androidx.appcompat.view.menu.MenuPresenter, int) (MenuBuilder.java:991)
        at boolean androidx.appcompat.view.menu.MenuBuilder.performItemAction(android.view.MenuItem, int) (MenuBuilder.java:981)
        at boolean androidx.appcompat.widget.ActionMenuView.invokeItem(androidx.appcompat.view.menu.MenuItemImpl) (ActionMenuView.java:625)
        at void androidx.appcompat.view.menu.ActionMenuItemView.onClick(android.view.View) (ActionMenuItemView.java:151)
        at boolean android.view.View.performClick() (View.java:5612)
        at void android.view.View$PerformClick.run() (View.java:22285)
I/art:     at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6123)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:867)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:757)
D/PrepareOutgoingMessagesJobIntentService: onCreate
D/PrepareOutgoingMessagesJobIntentService: onHandleWork
V/FragmentManager: movefrom RESUMED: CreateMessageFragment{cc19a5f #0 id=0x7f09005a}
D/PrepareOutgoingMessagesJobIntentService: Received a new job: MessageInfo{subject='Test build', message='Lék'}
V/FragmentManager: moveto STARTED: EmailListFragment{e1d0ee8 #0 id=0x7f090082}
V/FragmentManager: moveto STARTED: zzc{59baabc #1 SupportLifecycleFragmentImpl}
D/AutoManageHelper: onStart true {0=com.google.android.gms.common.api.internal.zaj$zaa@a7c9403}
V/FragmentManager: moveto STARTED: SupportRequestManagerFragment{ece2eb5 #2 com.bumptech.glide.manager}{parent=null}
D/EmailManagerActivity: onStart
D/EmailManagerActivity: onResume
V/FragmentManager: moveto RESUMED: EmailListFragment{e1d0ee8 #0 id=0x7f090082}
V/FragmentManager: moveto RESUMED: zzc{59baabc #1 SupportLifecycleFragmentImpl}
    moveto RESUMED: SupportRequestManagerFragment{ece2eb5 #2 com.bumptech.glide.manager}{parent=null}
V/FragmentManager: movefrom STARTED: CreateMessageFragment{cc19a5f #0 id=0x7f09005a}
D/CreateMessageActivity: onStop
V/FragmentManager: movefrom ACTIVITY_CREATED: CreateMessageFragment{cc19a5f #0 id=0x7f09005a}
V/FragmentManager: movefrom CREATED: CreateMessageFragment{cc19a5f #0 id=0x7f09005a}
V/FragmentManager: Freeing fragment index CreateMessageFragment{cc19a5f #0 id=0x7f09005a}
D/CreateMessageActivity: onDestroy
D/CreateMessageActivity: unbind from JsBackgroundService
D/CreateMessageActivity: unbind from EmailSyncService
W/System.err: com.flowcrypt.email.util.exception.NoKeyAvailableException: No key available for your email account. Please write human@flowcrypt.com for help.
        at com.flowcrypt.email.security.SecurityUtils.getSenderPublicKey(SecurityUtils.java:215)
        at com.flowcrypt.email.security.SecurityUtils.getRecipientsPubKeys(SecurityUtils.java:193)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.java:140)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:304)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
D/PrepareOutgoingMessagesJobIntentService: onDestroy
W/Glide: Load failed for https://plus.google.com/_/focus/photos/private/AIbEiAIAAABECIqJoOyM3fej1AEiC3ZjYXJkX3Bob3RvKig5MzhkNTBhNjQwNGM3YzViNmQ2ZmU0MjM0N2NjNjdkMDc5N2FiMGI5MAFByEbkIwRf4-NHV9NfvQKAAbT2JQ with size [144x144]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
    There was 1 cause:
    java.io.FileNotFoundException(https://plus.google.com/_/focus/photos/private/AIbEiAIAAABECIqJoOyM3fej1AEiC3ZjYXJkX3Bob3RvKig5MzhkNTBhNjQwNGM3YzViNmQ2ZmU0MjM0N2NjNjdkMDc5N2FiMGI5MAFByEbkIwRf4-NHV9NfvQKAAbT2JQ)
     call GlideException#logRootCauses(String) for more detail
      Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetching data failed, class java.io.InputStream, REMOTE
    There was 1 cause:
    java.io.FileNotFoundException(https://plus.google.com/_/focus/photos/private/AIbEiAIAAABECIqJoOyM3fej1AEiC3ZjYXJkX3Bob3RvKig5MzhkNTBhNjQwNGM3YzViNmQ2ZmU0MjM0N2NjNjdkMDc5N2FiMGI5MAFByEbkIwRf4-NHV9NfvQKAAbT2JQ)
     call GlideException#logRootCauses(String) for more detail
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Fetch failed
    There was 1 cause:
    java.io.FileNotFoundException(https://plus.google.com/_/focus/photos/private/AIbEiAIAAABECIqJoOyM3fej1AEiC3ZjYXJkX3Bob3RvKig5MzhkNTBhNjQwNGM3YzViNmQ2ZmU0MjM0N2NjNjdkMDc5N2FiMGI5MAFByEbkIwRf4-NHV9NfvQKAAbT2JQ)
     call GlideException#logRootCauses(String) for more detail
          Cause (1 of 1): class java.io.FileNotFoundException: https://plus.google.com/_/focus/photos/private/AIbEiAIAAABECIqJoOyM3fej1AEiC3ZjYXJkX3Bob3RvKig5MzhkNTBhNjQwNGM3YzViNmQ2ZmU0MjM0N2NjNjdkMDc5N2FiMGI5MAFByEbkIwRf4-NHV9NfvQKAAbT2JQ
I/Glide: Root cause (1 of 1)
    java.io.FileNotFoundException: https://plus.google.com/_/focus/photos/private/AIbEiAIAAABECIqJoOyM3fej1AEiC3ZjYXJkX3Bob3RvKig5MzhkNTBhNjQwNGM3YzViNmQ2ZmU0MjM0N2NjNjdkMDc5N2FiMGI5MAFByEbkIwRf4-NHV9NfvQKAAbT2JQ
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadDataWithRedirects(HttpUrlFetcher.java:106)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:59)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.startNextOrFail(MultiModelLoader.java:150)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.onLoadFailed(MultiModelLoader.java:144)
        at com.bumptech.glide.load.data.HttpUrlFetcher.loadData(HttpUrlFetcher.java:65)
        at com.bumptech.glide.load.model.MultiModelLoader$MultiFetcher.loadData(MultiModelLoader.java:99)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:62)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:302)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:272)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:233)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
D/PassiveSyncTaskRunnable: Disconnected. Wait new tasks.

```

**Comment by tomholub** [comment]
This happens quite consistently :(

**Comment by DenBond7** [comment]
Can you reproduce it again?
Are you able to read the encrypted messages at this time?

I see an exception `com.flowcrypt.email.util.exception.NoKeyAvailableException: No key available for your email account. Please write human@flowcrypt.com for help.`. It means the app has not found a sender public key.

Have you used a primary account or an alias?

**Comment by tomholub** [comment]
Yes, it has to do with which address I use for sending. My key only has human@flowcrypt.com in it, but I have several alias addresses. When I send from human@flowcrypt.com then it works, else it drops.

There are several issues we need to address:

1) A message can never say "Sending" and then disappear. The error needs to surface somewhere: For example it should be saved into Outbox as "Error", so that the user can see there was an issue and contact us. When the user clicks on the error, it could even show the stack trace, or describe which error happened. Then there can be the trash icon on the top to delete the error, just like there is one when deleting a message.

2) When choosing addresses to send from, can you make addresses we have no keys for disabled (gray and not clickable)? I still want them to show, but I should only be able to choose addresses that I can actually use. This is only if I'm sending encrypted messages. If sending plain text, all should be selectable.

3) Later we will add a settings button to edit the key and resolve disabled addresses, but that is for another issue, for another version.

**Comment by tomholub** [comment]
I've created two issues to address this where we can discuss it separately. Thanks for investigating.
