### ISSUE TITLE
Permission Denial: reading com.owncloud.android.providers.FileContentProvider 

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#380]
```
[SUMMARY]
java.lang.SecurityException: Permission Denial: reading com.owncloud.android.providers.FileContentProvider uri content://org.nextcloud/ from pid=2398, uid=1010107 requires null, or grantUriPermission()
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:117)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:114)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:34)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.SecurityException: Permission Denial: reading com.owncloud.android.providers.FileContentProvider uri content://org.nextcloud/ from pid=2398, uid=1010107 requires null, or grantUriPermission()
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
        at android.content.ContentResolver.query(ContentResolver.java:534)
        at android.content.ContentResolver.query(ContentResolver.java:475)
        at com.flowcrypt.email.util.GeneralUtil.getFileSizeFromUri(GeneralUtil.java:107)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.isKeyTooBig(ParseKeysFromResourceAsyncTaskLoader.java:133)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:66)
        ... 9 more
java.lang.SecurityException: Permission Denial: reading com.owncloud.android.providers.FileContentProvider uri content://org.nextcloud/ from pid=2398, uid=1010107 requires null, or grantUriPermission()
        at android.os.Parcel.readException(Parcel.java:1684)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
        at android.content.ContentResolver.query(ContentResolver.java:534)
        at android.content.ContentResolver.query(ContentResolver.java:475)
        at com.flowcrypt.email.util.GeneralUtil.getFileSizeFromUri(GeneralUtil.java:107)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.isKeyTooBig(ParseKeysFromResourceAsyncTaskLoader.java:133)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:66)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:34)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

```

ref https://mail.google.com/mail/u/0/#label/Work%2FFlowCrypt%2FCrashes/FMfcgxvzLhnFcfjBZCpDDVXtKRLsCGSD

**Comment by DenBond7** [comment]
https://codezjx.com/2018/03/30/content-provider-security-exception-issue/

**Comment by DenBond7** [comment]
I'm closing it. It is not our bug. We've added all required steps for [Storage Access Framework (SAF)](https://developer.android.com/guide/topics/providers/document-provider). I've found the device where this error happened is using the LineagOs. So it can be a system bug.

P.S. This error happened only for one device.
