### ISSUE TITLE
JavaScriptError: Error: Unknown ASCII armor type

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#391]
```
[SUMMARY]
com.flowcrypt.email.js.JavaScriptError: Error: Unknown ASCII armor type


[STACK_TRACE]
com.flowcrypt.email.js.JavaScriptError: Error: Unknown ASCII armor type
        at com.flowcrypt.email.js.JavaMethodsForJavaScript.report(Js.java:538)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.eclipsesource.v8.V8.callVoidJavaMethod(V8.java:897)
        at com.eclipsesource.v8.V8._executeStringFunction(Native Method)
        at com.eclipsesource.v8.V8.executeStringFunction(V8.java:1117)
        at com.eclipsesource.v8.V8Object.executeStringFunction(V8Object.java:288)
        at com.flowcrypt.email.js.Js.call(Js.java:300)
        at com.flowcrypt.email.js.Js.call(Js.java:288)
        at com.flowcrypt.email.js.Js.crypto_key_normalize(Js.java:145)
        at com.flowcrypt.email.service.CheckClipboardToFindKeyService$ServiceWorkerHandler.handleMessage(CheckClipboardToFindKeyService.java:205)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

ref [com.flowcrypt.email-0.6.9-512C4FF7B2: Unknown ASCII armor type](https://mail.google.com/mail/u/0/#label/Work%2FFlowCrypt%2FCrashes/FMfcgxvzMBjNKvZhKVBwhLzZlKhRslzj)

**Comment by DenBond7** [comment]
@tomholub Is that a real problem or we can move it to the later milestones?

**Comment by tomholub** [comment]
This happens when the key is either not really a key, or badly formatted. It would be good to fix it (eg at least make sure that the user experience makes sense), but I'd rather release this version now.

**Comment by tomholub** [comment]
I don't think we're fixing things in J2V8 and Js anymore. It's using a very old javascript codebase (probably 1 year old or more). This should get closed once we move to Node.

**Comment by tomholub** [comment]
I'm closing this as it's likely solved with Node
