### ISSUE TITLE
IllegalStateException in KeyDetailsFragment.onActivityResult

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#392]
```
[SUMMARY]
java.lang.IllegalStateException: Already exists /storage/emulated/0/Download/0x78E67EF35C4255E9.asc
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:117)
        at com.flowcrypt.email.ui.activity.fragment.KeyDetailsFragment.onActivityResult(KeyDetailsFragment.java:129)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:160)
        at android.app.Activity.dispatchActivityResult(Activity.java:7548)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4485)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4532)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: Already exists /storage/emulated/0/Download/0x78E67EF35C4255E9.asc
        at android.os.Parcel.readException(Parcel.java:1975)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
        at android.content.ContentProviderClient.call(ContentProviderClient.java:483)
        at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1217)
        at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1200)
        at com.flowcrypt.email.ui.activity.fragment.KeyDetailsFragment.onActivityResult(KeyDetailsFragment.java:125)
        ... 12 more
java.lang.IllegalStateException: Already exists /storage/emulated/0/Download/0x78E67EF35C4255E9.asc
        at android.os.Parcel.readException(Parcel.java:1975)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
        at android.content.ContentProviderClient.call(ContentProviderClient.java:483)
        at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1217)
        at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1200)
        at com.flowcrypt.email.ui.activity.fragment.KeyDetailsFragment.onActivityResult(KeyDetailsFragment.java:125)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:160)
        at android.app.Activity.dispatchActivityResult(Activity.java:7548)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4485)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4532)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

ref https://mail.google.com/mail/u/0/#label/Work%2FFlowCrypt%2FCrashes/FMfcgxvzMBhFlcbNLDgQKxMWkCXsqsnD

**Comment by DenBond7** [comment]
It looks like this

![device-2018-12-12-184234](https://user-images.githubusercontent.com/2863246/49885071-0419e200-fe3f-11e8-8a60-6f184a9af4c2.png)


Maybe we can leave it as is. It's pretty informatively.

@tomholub What do you think?

**Comment by tomholub** [comment]
Looks ok, maybe a bit better: `Not saved because file already exists: Download/0x.....asc`

Then it's a bit clearer it was not saved. Anyway, if they already have the public key, they should not need to save it again.

**Comment by DenBond7** [comment]
@tomholub 
I can't know the file destination as a real file path (Android doesn't allow that. I can work only with Uri. It's a common practice). `Already exists /storage/.../0x...asc` - the system return an error with such message (string). And that message can be different depends on the Android version.

So I can only show a message `Not saved because the file already exists` or something else if the error message contains `exists`

**Comment by tomholub** [comment]
Ok if it's an IllegalStateException and start with "Already exists", then let's show the message you proposed.

It's OK if `Already exists` doesn't cover most platforms, as long as it covers standard Android OS. We can add more wordings later if we receive other exceptions like that.
