### ISSUE TITLE
AddressException in MessageDaoSource.prepareContentValues

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#393]
```
[SUMMARY]
javax.mail.internet.AddressException: Missing '<' in string ``example  >> example @gmail.com'' at position 8
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:117)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.java:183)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:2392)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: javax.mail.internet.AddressException: Missing '<' in string ``example  >> example @gmail.com'' at position 8
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:954)
        at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:777)
        at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:756)
        at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:582)
        at com.flowcrypt.email.database.dao.source.imap.MessageDaoSource.prepareContentValues(MessageDaoSource.java:152)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.prepareContentValues(PrepareOutgoingMessagesJobIntentService.java:220)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.java:149)
        ... 6 more
javax.mail.internet.AddressException: Missing '<' in string ``example  >> example @gmail.com'' at position 8
        at javax.mail.internet.InternetAddress.parse(InternetAddress.java:954)
        at javax.mail.internet.InternetAddress.parseHeader(InternetAddress.java:777)
        at javax.mail.internet.MimeMessage.getAddressHeader(MimeMessage.java:756)
        at javax.mail.internet.MimeMessage.getRecipients(MimeMessage.java:582)
        at com.flowcrypt.email.database.dao.source.imap.MessageDaoSource.prepareContentValues(MessageDaoSource.java:152)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.prepareContentValues(PrepareOutgoingMessagesJobIntentService.java:220)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.java:149)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:2392)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#label/Work%2FFlowCrypt%2FCrashes/FMfcgxvzLrQPkXxSkBKKvbznkZjzJvrN

**Comment by DenBond7** [comment]
It's a parsing addresses bug. 

```
example  >> example@gmail.com - it's wrong
example  <example@gmail.com> - it's right
```

But new users won't receive it, because we've already added a new logic for the addresses saving. So it happened for a user who uses the app for a long time. I think we don't need to fix this only for a couple for users. I'm closing it.

**Comment by DenBond7** [comment]
https://stackoverflow.com/questions/30693478/imap-envelope-email-address-format

**Comment by tomholub** [comment]
What will the client see when this happens? As long as the apps behaves ok and the user has a way to work around it

**Comment by DenBond7** [comment]
@tomholub 

> What will the client see when this happens?

![image](https://user-images.githubusercontent.com/2863246/49925231-fa38c300-fec0-11e8-800d-fd9ae4938b43.png)

For all the time we received only 2 such errors.

```
Missing '<' in string ``example >> example @gmail.com'' at position 8
Missing '<' in string ``example@gmail.com>'' at position 23
```

Of course, I can handle such error and show `Could not create: wrong address`. When user will click on the message I can show a hint `Sorry, we could not create a message. (@tomholub Please add the text here)`.
And I will remove the recipient addresses from the local database. Then the user can create a right contact.

**Comment by tomholub** [comment]
You can create another issue to do that later, and link to this conversation. Once it becomes more frequent, we'll fix it.
