### ISSUE TITLE
NPE in CustomNotificationManager

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#400]
```
[SUMMARY]
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:117)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:587)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$PassiveSyncTaskRunnable.run(EmailSyncManager.java:645)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at android.text.SpannableString.<init>(SpannableString.java:30)
        at com.flowcrypt.email.ui.notifications.CustomNotificationManager.formatText(CustomNotificationManager.java:51)
        at com.flowcrypt.email.service.MessagesNotificationManager.notifyWithSingleNotification(MessagesNotificationManager.java:189)
        at com.flowcrypt.email.service.MessagesNotificationManager.notify(MessagesNotificationManager.java:92)
        at com.flowcrypt.email.service.EmailSyncService.onNewMessagesReceived(EmailSyncService.java:384)
        at com.flowcrypt.email.api.email.sync.tasks.CheckNewMessagesSyncTask.runIMAPAction(CheckNewMessagesSyncTask.java:101)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:574)
        ... 6 more
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
        at android.text.SpannableString.<init>(SpannableString.java:30)
        at com.flowcrypt.email.ui.notifications.CustomNotificationManager.formatText(CustomNotificationManager.java:51)
        at com.flowcrypt.email.service.MessagesNotificationManager.notifyWithSingleNotification(MessagesNotificationManager.java:189)
        at com.flowcrypt.email.service.MessagesNotificationManager.notify(MessagesNotificationManager.java:92)
        at com.flowcrypt.email.service.EmailSyncService.onNewMessagesReceived(EmailSyncService.java:384)
        at com.flowcrypt.email.api.email.sync.tasks.CheckNewMessagesSyncTask.runIMAPAction(CheckNewMessagesSyncTask.java:101)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:574)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$PassiveSyncTaskRunnable.run(EmailSyncManager.java:645)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

ref https://mail.google.com/mail/u/0/#label/Work%2FFlowCrypt%2FCrashes/FMfcgxvzMBsdDQJhPxrPhKKhgwffsDfj

**Comment by DenBond7** [comment]
https://mail.google.com/mail/u/0/#label/Work%2FFlowCrypt%2FCrashes/FMfcgxwBVWPDvGGhpbpxKztnqHJHngbW
