### ISSUE TITLE
NPE keyStore.getCertificate() == null (Moto G (5))

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#418]
```
[SUMMARY]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:131)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:106)
        at com.flowcrypt.email.security.SecurityStorageConnector.<init>(SecurityStorageConnector.java:36)
        at com.flowcrypt.email.js.UiJsManager.<init>(UiJsManager.java:34)
        at com.flowcrypt.email.js.UiJsManager.getInstance(UiJsManager.java:54)
        at com.flowcrypt.email.js.UiJsManager.init(UiJsManager.java:47)
        at com.flowcrypt.email.FlowCryptApplication.onCreate(FlowCryptApplication.java:76)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1141)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5854)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at com.flowcrypt.email.security.KeyStoreCryptoManager.initRsaKeyPair(KeyStoreCryptoManager.java:307)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.<init>(KeyStoreCryptoManager.java:98)
        at com.flowcrypt.email.security.SecurityUtils.getPrivateKeysInfo(SecurityUtils.java:52)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:99)
        ... 15 more
java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.PublicKey java.security.cert.Certificate.getPublicKey()' on a null object reference
        at com.flowcrypt.email.security.KeyStoreCryptoManager.initRsaKeyPair(KeyStoreCryptoManager.java:307)
        at com.flowcrypt.email.security.KeyStoreCryptoManager.<init>(KeyStoreCryptoManager.java:98)
        at com.flowcrypt.email.security.SecurityUtils.getPrivateKeysInfo(SecurityUtils.java:52)
        at com.flowcrypt.email.security.SecurityStorageConnector.init(SecurityStorageConnector.java:99)
        at com.flowcrypt.email.security.SecurityStorageConnector.<init>(SecurityStorageConnector.java:36)
        at com.flowcrypt.email.js.UiJsManager.<init>(UiJsManager.java:34)
        at com.flowcrypt.email.js.UiJsManager.getInstance(UiJsManager.java:54)
        at com.flowcrypt.email.js.UiJsManager.init(UiJsManager.java:47)
        at com.flowcrypt.email.FlowCryptApplication.onCreate(FlowCryptApplication.java:76)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1141)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5854)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1697)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
```

ref https://mail.google.com/mail/u/0/#label/Work%2FFlowCrypt%2FCrashes/FMfcgxwBVMgHjnkvLWGpMCmvczcTxjWV

**Comment by DenBond7** [comment]
Need to exclude it from the ACRA reports

**Comment by DenBond7** [comment]
Need to apply the following logic https://github.com/FlowCrypt/flowcrypt-android/issues/401

**Comment by DenBond7** [comment]
deprecated
