### ISSUE TITLE
Node.js cannot parse request part as json. 

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#421]
I always receive the next error, when I'm sending a few private keys for `decryptFile`. I've cheked the request format and it looks fine.

```
{
   "error":{
      "message":"Error: cannot parse request part as json",
      "stack":"Error: cannot parse request part as json\n    at IncomingMessage.r.on ([eval]:46889:16)\n    at emitNone (events.js:105:13)\n    at IncomingMessage.emit (events.js:207:7)\n    at endReadableNT (_stream_readable.js:1059:12)\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)"
   }
}
```

**Comment by DenBond7** [comment]
@tomholub I've added some changes to `TestData.java`. Now you can easily reproduce it.

**Comment by tomholub** [comment]
ok will check

**Comment by tomholub** [comment]
In the future if you need to debug Node inputs, you can turn it on by passing a "true" below:
```Java
src += genConst("NODE_DEBUG", "false");
```
