### ISSUE TITLE
Outbox not found

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#463]
```
[SUMMARY]
javax.mail.FolderNotFoundException: Outbox not found
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:131)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:574)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:660)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: javax.mail.FolderNotFoundException: Outbox not found
        at com.sun.mail.imap.IMAPFolder.checkExists(IMAPFolder.java:455)
        at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:1068)
        at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:1001)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessagesToCacheSyncTask.runIMAPAction(LoadMessagesToCacheSyncTask.java:53)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:561)
        ... 6 more
javax.mail.FolderNotFoundException: Outbox not found
        at com.sun.mail.imap.IMAPFolder.checkExists(IMAPFolder.java:455)
        at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:1068)
        at com.sun.mail.imap.IMAPFolder.open(IMAPFolder.java:1001)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessagesToCacheSyncTask.runIMAPAction(LoadMessagesToCacheSyncTask.java:53)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask(EmailSyncManager.java:561)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.java:660)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#search/label%3Awork-flowcrypt-crashes+label%3Aunread+Moto/FMfcgxwBVgrPxqsJbJvHMhKPCtkXkMQb

**Comment by DenBond7** [comment]
I'm closing it. It's an old error (0.7.0).
