### ISSUE TITLE
Can't download an attachment when open a message from the search screen

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#465]
```
[SUMMARY]
java.lang.IllegalArgumentException: Folder "" not found in the local cache
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:31)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.java:581)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: Folder "" not found in the local cache
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.java:544)
        ... 5 more
java.lang.IllegalArgumentException: Folder "" not found in the local cache
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.java:544)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
ref https://mail.google.com/mail/u/0/#search/label%3Awork-flowcrypt-crashes+label%3Aunread/FMfcgxwBVgjMvwXkWfSpHzsmnjXqNWxH

**Comment by DenBond7** [comment]
Steps to reproduce:

1. Open the app

1. Click on the `Search` icon

1. Type some text and click on the `Search` icon

1. Open any message with some attachments

1. Try to download some attachment

**Comment by DenBond7** [comment]
#507
