### ISSUE TITLE
com.google|Cannot move the message. The dest folder is null.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#466]
```
[SUMMARY]
java.lang.IllegalArgumentException: com.google|Cannot move the message. The dest folder is null.


[STACK_TRACE]
java.lang.IllegalArgumentException: com.google|Cannot move the message. The dest folder is null.
        at com.flowcrypt.email.service.EmailSyncService$IncomingHandler.handleMessage(EmailSyncService.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

ref https://mail.google.com/mail/u/0/#search/label%3Awork-flowcrypt-crashes+label%3Aunread/FMfcgxwBVglfFCVRKPfgfbXjSSHQwrXr

**Comment by DenBond7** [comment]
I'm closing it. Deprecated.
