### ISSUE TITLE
pre-launch report with issues

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#472]
```
Device(s) with issues
Google Pixel 2 (walleye) - Android 9

Exceptions
java.lang.IllegalStateException: UiAutomation not connected!
```

**Comment by DenBond7** [comment]
@tomholub Do you have more details? Where did you see that error?

**Comment by DenBond7** [comment]
https://stackoverflow.com/questions/47854705/google-fabric-uiautomation-not-connected

**Comment by DenBond7** [comment]
@tomholub As I understood this error relates to testing (Google test devices). But our tests are specific and can be run only on my side.

**Comment by tomholub** [comment]
I'll get you more info. This came from Google play console

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/55404449-6f4f0780-5547-11e9-81ac-07a817828668.png)

![image](https://user-images.githubusercontent.com/6306961/55404473-7f66e700-5547-11e9-9b34-3847b82150a7.png)

![image](https://user-images.githubusercontent.com/6306961/55404572-b5a46680-5547-11e9-89e7-7e5d97e315db.png)

**Comment by tomholub** [comment]
It seems to have received a 400 bad request from google?

```
03-05 13:11:57.203: W/System.err(13281): com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
03-05 13:11:57.203: W/System.err(13281): {
03-05 13:11:57.203: W/System.err(13281):   "code" : 400,
03-05 13:11:57.203: W/System.err(13281):   "errors" : [ {
03-05 13:11:57.203: W/System.err(13281):     "domain" : "global",
03-05 13:11:57.203: W/System.err(13281):     "message" : "Bad Request",
03-05 13:11:57.203: W/System.err(13281):     "reason" : "failedPrecondition"
03-05 13:11:57.203: W/System.err(13281):   } ],
03-05 13:11:57.203: W/System.err(13281):   "message" : "Bad Request"
03-05 13:11:57.203: W/System.err(13281): }
03-05 13:11:57.204: W/System.err(13281): 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
03-05 13:11:57.204: W/System.err(13281): 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
03-05 13:11:57.204: W/System.err(13281): 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:417)
03-05 13:11:57.204: W/System.err(13281): 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1132)
03-05 13:11:57.204: W/System.err(13281): 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:515)
03-05 13:11:57.204: W/System.err(13281): 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:448)
03-05 13:11:57.204: W/System.err(13281): 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:565)
03-05 13:11:57.204: W/System.err(13281): 	at com.flowcrypt.email.api.email.EmailUtil.getPrivateKeyBackupsViaGmailAPI(EmailUtil.java:357)
03-05 13:11:57.204: W/System.err(13281): 	at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:80)
03-05 13:11:57.204: W/System.err(13281): 	at com.flowcrypt.email.ui.loader.LoadPrivateKeysFromMailAsyncTaskLoader.loadInBackground(LoadPrivateKeysFromMailAsyncTaskLoader.java:44)
03-05 13:11:57.204: W/System.err(13281): 	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
03-05 13:11:57.204: W/System.err(13281): 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground$532ebdd5(AsyncTaskLoader.java:60)
03-05 13:11:57.204: W/System.err(13281): 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
03-05 13:11:57.204: W/System.err(13281): 	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
03-05 13:11:57.204: W/System.err(13281): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-05 13:11:57.204: W/System.err(13281): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-05 13:11:57.204: W/System.err(13281): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-05 13:11:57.204: W/System.err(13281): 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by tomholub** [comment]
And here the exception

```js
FATAL EXCEPTION: ControllerMessenger
Process: com.flowcrypt.email, PID: 13281
java.lang.IllegalStateException: UiAutomation not connected!
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1112)
	at android.app.UiAutomation.waitForIdle(UiAutomation.java:669)
	at android.support.test.uiautomator.r.a(QueryController.java:36)
	at android.support.test.uiautomator.r.c(QueryController.java:32)
	at android.support.test.uiautomator.r.a(QueryController.java:9)
	at android.support.test.uiautomator.y.g(UiDevice.java:91)
	at androidx.test.tools.crawler.platform.uiautomator.UiAutomatorScreenStateBuilder.getCurrentActivity(UiAutomatorScreenStateBuilder.java:39)
	at androidx.test.tools.crawler.platform.uiautomator.UiAutomatorStateExtractor.getCurrentActivity(UiAutomatorStateExtractor.java:34)
	at androidx.test.tools.crawler.platform.hybrid.HybridStateExtractor.getCurrentActivity(HybridStateExtractor.java:31)
	at androidx.test.tools.crawler.controller.remote.RemotePlatform.handlePerformActionMessage(RemotePlatform.java:25)
	at androidx.test.tools.crawler.controller.remote.RemotePlatform.access$300(RemotePlatform.java:91)
	at androidx.test.tools.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:8)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by tomholub** [comment]
Google seems to be doing AI-driven app tests where it clicks around the app to see if it crashes, and this is a report of one of them crashing.

**Comment by DenBond7** [comment]
@tomholub 
> It seems to have received a 400 bad request from google?

Yes, it is. It happened when the app was trying to receive messages with public keys. But I think it's not realy our problem. We don't know which settings this tested device have, we don't how this Google account configured (maybe this device has special settings, `"reason" : "failedPrecondition"` tells us that something is wrong with this account). We know nothing about it. I don't see any errors which can break the app.

I think this error is related to the base UI testing process and sounds like a bug in the Google testing process(maybe UiAutomation works wrongly, maybe something else)

**Comment by tomholub** [comment]
Ok. We can ignore it
