### ISSUE TITLE
FileNotFoundException: Missing file for primary

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#497]
```
[SUMMARY]
java.io.FileNotFoundException: Missing file for primary:.estrongs/0x121D66F8C6F8D710.key at /storage/emulated/0/.estrongs/0x121D66F8C6F8D710.key
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:31)
        at com.flowcrypt.email.ui.activity.fragment.KeyDetailsFragment.saveKey(KeyDetailsFragment.java:175)
        at com.flowcrypt.email.ui.activity.fragment.KeyDetailsFragment.onActivityResult(KeyDetailsFragment.java:111)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:160)
        at android.app.Activity.dispatchActivityResult(Activity.java:7758)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4577)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4626)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.io.FileNotFoundException: Missing file for primary:.estrongs/0x121D66F8C6F8D710.key at /storage/emulated/0/.estrongs/0x121D66F8C6F8D710.key
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
        at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
        at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
        at android.os.Parcel.readParcelable(Parcel.java:2790)
        at android.os.Parcel.createException(Parcel.java:1961)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
        at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
        at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1236)
        at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1219)
        at com.flowcrypt.email.ui.activity.fragment.KeyDetailsFragment.saveKey(KeyDetailsFragment.java:153)
        ... 15 more
java.io.FileNotFoundException: Missing file for primary:.estrongs/0x121D66F8C6F8D710.key at /storage/emulated/0/.estrongs/0x121D66F8C6F8D710.key
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.os.ParcelableException.readFromParcel(ParcelableException.java:56)
        at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:82)
        at android.os.ParcelableException$1.createFromParcel(ParcelableException.java:79)
        at android.os.Parcel.readParcelable(Parcel.java:2790)
        at android.os.Parcel.createException(Parcel.java:1961)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
        at android.content.ContentProviderClient.call(ContentProviderClient.java:492)
        at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1236)
        at android.provider.DocumentsContract.renameDocument(DocumentsContract.java:1219)
        at com.flowcrypt.email.ui.activity.fragment.KeyDetailsFragment.saveKey(KeyDetailsFragment.java:153)
        at com.flowcrypt.email.ui.activity.fragment.KeyDetailsFragment.onActivityResult(KeyDetailsFragment.java:111)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:160)
        at android.app.Activity.dispatchActivityResult(Activity.java:7758)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4577)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4626)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

ref https://mail.google.com/mail/u/0/#search/label%3Awork-flowcrypt-crashes++%22Missing+file%22

**Comment by DenBond7** [comment]
#357
