### ISSUE TITLE
Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#499]
#380 

```
[SUMMARY]
java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{3023a46 17732:com.flowcrypt.email/u0a256} (pid=17732, uid=10256) that is not exported from UID 10287
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:31)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:85)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:32)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground$532ebdd5(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{3023a46 17732:com.flowcrypt.email/u0a256} (pid=17732, uid=10256) that is not exported from UID 10287
        at android.os.Parcel.readException(Parcel.java:1967)
        at android.os.Parcel.readException(Parcel.java:1913)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5290)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6164)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2559)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1786)
        at android.content.ContentResolver.query(ContentResolver.java:744)
        at android.content.ContentResolver.query(ContentResolver.java:710)
        at android.content.ContentResolver.query(ContentResolver.java:668)
        at com.flowcrypt.email.util.GeneralUtil.getFileSizeFromUri(GeneralUtil.java:112)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.isKeyTooBig(ParseKeysFromResourceAsyncTaskLoader.java:104)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:62)
        ... 9 more
java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{3023a46 17732:com.flowcrypt.email/u0a256} (pid=17732, uid=10256) that is not exported from UID 10287
        at android.os.Parcel.readException(Parcel.java:1967)
        at android.os.Parcel.readException(Parcel.java:1913)
        at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5290)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6164)
        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2559)
        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1786)
        at android.content.ContentResolver.query(ContentResolver.java:744)
        at android.content.ContentResolver.query(ContentResolver.java:710)
        at android.content.ContentResolver.query(ContentResolver.java:668)
        at com.flowcrypt.email.util.GeneralUtil.getFileSizeFromUri(GeneralUtil.java:112)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.isKeyTooBig(ParseKeysFromResourceAsyncTaskLoader.java:104)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:62)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.java:32)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground$532ebdd5(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#search/label%3Awork-flowcrypt-crashes+label%3Aunread/FMfcgxwBWStJnmDBzGQmNJlRfHnzSGCP

**Comment by DenBond7** [comment]
The problem was I used the wrong action [Intent.ACTION_GET_CONTENT](https://developer.android.com/reference/android/content/Intent.html#ACTION_GET_CONTENT). This action allows only to receive raw data. But it doesn't allow to know the file size or name.
