### ISSUE TITLE
Error when test a new logic of parse a message

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#53]
I received an error when test a new logic of parse a message. It happened after this [commit ](https://github.com/FlowCrypt/flowcrypt-android/commit/e35878a78e18d099c8c8deacccbcc6e8419dc6c1). Use a new branch "issue_37" for debug.

You can try to open "Your CryptUp Backup" to test this behavior.

```
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err: undefined:23: TypeError: Cannot read property 'replace' of undefined
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:       throw e;
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:       ^
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err: TypeError: Cannot read property 'replace' of undefined
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at str_normalize_spaces (<anonymous>:320:15)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at crypto_armor_detect_blocks (<anonymous>:1641:21)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at <anonymous>:992:20
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at <anonymous>:1052:13
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at MimeParser.parser.onend (<anonymous>:1053:13)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at MimeParser.end (<anonymous>:285:14)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at <anonymous>:1056:16
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at mime_require (<anonymous>:975:9)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at mime_decode (<anonymous>:1021:5)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at Object.mime_process [as process] (<anonymous>:991:5)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err: com.eclipsesource.v8.V8ScriptExecutionException
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at com.eclipsesource.v8.V8._executeFunction(Native Method)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at com.eclipsesource.v8.V8.executeFunction(V8.java:996)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at com.eclipsesource.v8.V8Object.executeObjectFunction(V8Object.java:334)
07-18 11:39:43.358 3952-4042/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.js.Js.call(Js.java:221)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.js.Js.call(Js.java:200)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.js.Js.mime_process(Js.java:109)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader.parseRawMessage(DecryptMessageAsyncTaskLoader.java:83)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader.loadInBackground(DecryptMessageAsyncTaskLoader.java:59)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader.loadInBackground(DecryptMessageAsyncTaskLoader.java:40)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:302)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
07-18 11:39:43.359 3952-4042/com.flowcrypt.email.debug W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

**Comment by tomholub** [comment]
Found the issue. Happens to HTML-only emails. I'll fix it tonight so that you can continue tomorrow.
