### ISSUE TITLE
Fix database upgrading for old builds

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#541]
```
[SUMMARY]
android.database.sqlite.SQLiteException: duplicate column name: forwarded_folder (code 1): , while compiling: ALTER TABLE attachment ADD COLUMN forwarded_folder TEXT;
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[LOGCAT]
--------- beginning of main
04-22 09:59:27.858 I/        (23318): SS_ART_lib [I]: permission is absent: /data/app/com.flowcrypt.email-2/base.apk
04-22 09:59:27.858 I/        (23318): SS_ART_lib [I]: access to SS denied
04-22 09:59:34.018 I/SELinux (23964): SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.flowcrypt.email 
04-22 09:59:34.038 D/TimaKeyStoreProvider(23964): TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
04-22 09:59:34.083 I/ACRA    (23964): Migrating unsent ACRA reports to new file locations
04-22 09:59:34.086 I/ACRA    (23964): Migrated 0 unsent reports
04-22 09:59:34.087 I/ACRA    (23964): Converting unsent ACRA reports to json
04-22 09:59:34.090 I/ACRA    (23964): Converted 0 unsent reports
04-22 09:59:34.090 I/ACRA    (23964): ACRA is enabled for com.flowcrypt.email, initializing...
04-22 09:59:34.600 E/SQLiteLog(23964): (1) duplicate column name: forwarded_folder
04-22 09:59:34.609 W/System.err(23964): android.database.sqlite.SQLiteException: duplicate column name: forwarded_folder (code 1): , while compiling: ALTER TABLE attachment ADD COLUMN forwarded_folder TEXT;
04-22 09:59:34.609 W/System.err(23964): #################################################################
04-22 09:59:34.609 W/System.err(23964): Error Code : 1 (SQLITE_ERROR)
04-22 09:59:34.609 W/System.err(23964): Caused By : SQL(query) error or missing database.
04-22 09:59:34.609 W/System.err(23964):         (duplicate column name: forwarded_folder (code 1): , while compiling: ALTER TABLE attachment ADD COLUMN forwarded_folder TEXT;)
04-22 09:59:34.609 W/System.err(23964): #################################################################
04-22 09:59:34.611 W/System.err(23964):         at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
04-22 09:59:34.611 W/System.err(23964):         at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1008)
04-22 09:59:34.611 W/System.err(23964):         at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:573)
04-22 09:59:34.611 W/System.err(23964):         at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
04-22 09:59:34.611 W/System.err(23964):         at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
04-22 09:59:34.611 W/System.err(23964):         at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
04-22 09:59:34.611 W/System.err(23964):         at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2069)
04-22 09:59:34.611 W/System.err(23964):         at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2000)
04-22 09:59:34.612 W/System.err(23964):         at com.flowcrypt.email.database.FlowCryptSQLiteOpenHelper.upgradeDatabaseFrom10To11Version(FlowCryptSQLiteOpenHelper.java:2)
04-22 09:59:34.612 W/System.err(23964):         at com.flowcrypt.email.database.FlowCryptSQLiteOpenHelper.onUpgrade(FlowCryptSQLiteOpenHelper.java:64)
04-22 09:59:34.612 W/System.err(23964):         at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
04-22 09:59:34.612 W/System.err(23964):         at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
04-22 09:59:34.612 W/System.err(23964):         at com.flowcrypt.email.database.provider.SecurityContentProvider.query(SecurityContentProvider.java:1)
04-22 09:59:34.612 W/System.err(23964):         at android.content.ContentProvider.query(ContentProvider.java:1028)
04-22 09:59:34.612 W/System.err(23964):         at android.content.ContentProvider$Transport.query(ContentProvider.java:243)
04-22 09:59:34.612 W/System.err(23964):         at android.content.ContentResolver.query(ContentResolver.java:536)
04-22 09:59:34.612 W/System.err(23964):         at android.content.ContentResolver.query(ContentResolver.java:478)
04-22 09:59:34.612 W/System.err(23964):         at androidx.transition.ViewGroupUtilsApi14.getPrivateKeysInfo(ViewGroupUtilsApi14.java:2)
04-22 09:59:34.612 W/System.err(23964):         at com.flowcrypt.email.security.KeysStorageImpl.setup(KeysStorageImpl.java:4)
04-22 09:59:34.612 W/System.err(23964):         at com.flowcrypt.email.security.KeysStorageImpl.<init>(KeysStorageImpl.java:3)
04-22 09:59:34.612 W/System.err(23964):         at com.flowcrypt.email.security.KeysStorageImpl.getInstance(KeysStorageImpl.java:4)
04-22 09:59:34.612 W/System.err(23964):         at com.flowcrypt.email.BaseApplication.onCreate(BaseApplication.java:3)
04-22 09:59:34.612 W/System.err(23964):         at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
04-22 09:59:34.612 W/System.err(23964):         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5974)
04-22 09:59:34.612 W/System.err(23964):         at android.app.ActivityThread.-wrap3(ActivityThread.java)
04-22 09:59:34.612 W/System.err(23964):         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1707)
04-22 09:59:34.612 W/System.err(23964):         at android.os.Handler.dispatchMessage(Handler.java:102)
04-22 09:59:34.612 W/System.err(23964):         at android.os.Looper.loop(Looper.java:154)
04-22 09:59:34.612 W/System.err(23964):         at android.app.ActivityThread.main(ActivityThread.java:6780)
04-22 09:59:34.612 W/System.err(23964):         at java.lang.reflect.Method.invoke(Native Method)
04-22 09:59:34.612 W/System.err(23964):         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
04-22 09:59:34.612 W/System.err(23964):         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

```

ref https://mail.google.com/mail/u/0/#search/label%3Awork-flowcrypt-crashes+%22ADD+COLUMN+forwarded_folder%22

**Comment by DenBond7** [comment]
After optimizations which were made by R8 I see a wrong stacktrace. I'm moving it to later. Maybe next releases with disabled R8 will show full info.
