### ISSUE TITLE
Exception: Session key decryption failed.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#543]
```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
java.lang.Exception: Session key decryption failed.

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:28)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.java:582)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.Exception: Session key decryption failed.
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.getDecryptedFileResult(AttachmentDownloadManagerService.java:716)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.decryptFileIfNeeded(AttachmentDownloadManagerService.java:668)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.java:564)
        ... 5 more
java.lang.Exception: Session key decryption failed.
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.getDecryptedFileResult(AttachmentDownloadManagerService.java:716)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.decryptFileIfNeeded(AttachmentDownloadManagerService.java:668)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.java:564)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#search/%22Session+key+decryption+failed%22

**Comment by DenBond7** [comment]
@tomholub It happened when a user was trying to decrypt an attachment. It looks like

![image](https://user-images.githubusercontent.com/2863246/56847225-1160d600-68e1-11e9-9a53-bfe19d1b57aa.png)

**Comment by tomholub** [comment]
When does this happen? This looks like something that would be thrown in JavaScript, but I don't see any JS stack.

**Comment by DenBond7** [comment]
@tomholub 
> When does this happen?

When a user was trying to download an encrypted attachment. Node.js threw such error

https://github.com/FlowCrypt/flowcrypt-android/blob/686ad9c046f62152de17c83dde1bcd0a6973be5a/FlowCrypt/src/main/java/com/flowcrypt/email/service/attachment/AttachmentDownloadManagerService.java#L716

**Comment by tomholub** [comment]
Ah, it would be good to have a whole stack trace available (I thought Node will share the stack trace?).

Were you able to reproduce this reliably? It seems maybe it's encrypted for a wrong key?

**Comment by DenBond7** [comment]
> Were you able to reproduce this reliably? It seems maybe it's encrypted for a wrong key?

I can't reproduce it as is. I've added a screen as an example of what a user sees. (I've thrown a simple error with text _"Session key decryption failed"_ manually)

**Comment by DenBond7** [comment]
@tomholub 
> it would be good to have a whole stack trace available

I'll add it. If too hard understand what is wrong without a stack trace I propose to add the stack trace to the error info and move it to later. Such error is not very widespread

**Comment by DenBond7** [comment]
@tomholub I've added a stack trace to logs for all errors from Node.js

**Comment by tomholub** [comment]
Sounds good, you can close this issue and when we encounter it again, we'll create another one.
