### ISSUE TITLE
FileNotFoundException in AttachmentDownloadManagerService

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#544]
```
[SUMMARY]
java.io.FileNotFoundException: /storage/emulated/0/Download/New_Recording_6.m4a.pgp (No such file or directory)
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:28)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.java:582)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Download/New_Recording_6.m4a.pgp (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.decryptFileIfNeeded(AttachmentDownloadManagerService.java:667)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.java:564)
        ... 5 more
java.io.FileNotFoundException: /storage/emulated/0/Download/New_Recording_6.m4a.pgp (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.decryptFileIfNeeded(AttachmentDownloadManagerService.java:667)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.java:564)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#label/Work%2FFlowCrypt%2FCrashes/FMfcgxwCgLzKWzrKMpCkDSCtsVfDJnNx

**Comment by DenBond7** [comment]
I'm closing it as too old. I don't see any new reports for a long time.
