### ISSUE TITLE
EncryptPrivateKeysIfNeededAction: An error occurred during the key parsing| 1

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#551]
```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
java.lang.IllegalArgumentException: An error occurred during the key parsing| 1

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:24)
        at com.flowcrypt.email.service.actionqueue.actions.EncryptPrivateKeysIfNeededAction.run(EncryptPrivateKeysIfNeededAction.java:23)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.java:9)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:3)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: An error occurred during the key parsing| 1
        ... 8 more
java.lang.IllegalArgumentException: An error occurred during the key parsing| 1
        at com.flowcrypt.email.service.actionqueue.actions.EncryptPrivateKeysIfNeededAction.run(EncryptPrivateKeysIfNeededAction.java:23)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.java:9)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:3)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```

ref https://mail.google.com/mail/u/0/#search/%22An+error+occurred+during+the+key+parsing%22

**Comment by DenBond7** [comment]
deprecated
