### ISSUE TITLE
API error: code = 500, message = could not encrypt a welcome message for this key

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#560]
**SendWelcomeTestEmailAction**

```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
com.flowcrypt.email.util.exception.ApiException: API error: code = 500, message = could not encrypt a welcome message for this key

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil.handleError(ExceptionUtil.java:28)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.java:100)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: com.flowcrypt.email.util.exception.ApiException: API error: code = 500, message = could not encrypt a welcome message for this key
        at com.flowcrypt.email.service.actionqueue.actions.SendWelcomeTestEmailAction.run(SendWelcomeTestEmailAction.java:66)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.java:94)
        ... 7 more
com.flowcrypt.email.util.exception.ApiException: API error: code = 500, message = could not encrypt a welcome message for this key
        at com.flowcrypt.email.service.actionqueue.actions.SendWelcomeTestEmailAction.run(SendWelcomeTestEmailAction.java:66)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.java:94)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

ref https://mail.google.com/mail/u/0/#search/%22API+error%3A+code+%3D+500%22

**Comment by tomholub** [comment]
Hello, you can ignore error 500 for this particular call (welcome message), and let the setup proceed anyway (only for this call).

I'm seeing the errors on the backend too, and it only affects the welcome message. Eventually I'll fix it.

**Comment by DenBond7** [comment]
@tomholub 
Got it

**Comment by DenBond7** [comment]
deprecated
