### ISSUE TITLE
Trust anchor for certification path not found

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#579]
```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
javax.mail.MessagingException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.;

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_prodRelease(EmailSyncManager.kt:532)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.kt:614)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: javax.mail.MessagingException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:718)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:68)
        at javax.mail.Service.connect(Service.java:342)
        at javax.mail.Service.connect(Service.java:222)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openAndConnectToGimapsStore(OpenStoreHelper.kt:77)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openStore(OpenStoreHelper.kt:166)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnToStore$FlowCrypt_prodRelease(EmailSyncManager.kt:485)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_prodRelease(EmailSyncManager.kt:505)
        ... 6 more
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):43)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:110)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:107)
        at com.sun.mail.gimap.protocol.GmailProtocol.<init>(GmailProtocol.java:83)
        at com.sun.mail.gimap.GmailStore.newIMAPProtocol(GmailStore.java:74)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:674)
        ... 13 more
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):1)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@17785037@17.7.85 (100400-253824076):12)
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):7)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):14)
        ... 21 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        ... 34 more
javax.mail.MessagingException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.;
  nested exception is:
        javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:718)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:68)
        at javax.mail.Service.connect(Service.java:342)
        at javax.mail.Service.connect(Service.java:222)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openAndConnectToGimapsStore(OpenStoreHelper.kt:77)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openStore(OpenStoreHelper.kt:166)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnToStore$FlowCrypt_prodRelease(EmailSyncManager.kt:485)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_prodRelease(EmailSyncManager.kt:505)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.kt:614)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):43)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:110)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:107)
        at com.sun.mail.gimap.protocol.GmailProtocol.<init>(GmailProtocol.java:83)
        at com.sun.mail.gimap.GmailStore.newIMAPProtocol(GmailStore.java:74)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:674)
        ... 13 more
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):1)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@17785037@17.7.85 (100400-253824076):12)
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):7)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):14)
        ... 21 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        ... 34 more
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):43)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:110)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:107)
        at com.sun.mail.gimap.protocol.GmailProtocol.<init>(GmailProtocol.java:83)
        at com.sun.mail.gimap.GmailStore.newIMAPProtocol(GmailStore.java:74)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:674)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:68)
        at javax.mail.Service.connect(Service.java:342)
        at javax.mail.Service.connect(Service.java:222)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openAndConnectToGimapsStore(OpenStoreHelper.kt:77)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openStore(OpenStoreHelper.kt:166)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnToStore$FlowCrypt_prodRelease(EmailSyncManager.kt:485)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_prodRelease(EmailSyncManager.kt:505)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.kt:614)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):1)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@17785037@17.7.85 (100400-253824076):12)
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):7)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):14)
        ... 21 more
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        ... 34 more
java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):1)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@17785037@17.7.85 (100400-253824076):12)
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):7)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):14)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:110)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:107)
        at com.sun.mail.gimap.protocol.GmailProtocol.<init>(GmailProtocol.java:83)
        at com.sun.mail.gimap.GmailStore.newIMAPProtocol(GmailStore.java:74)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:674)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:68)
        at javax.mail.Service.connect(Service.java:342)
        at javax.mail.Service.connect(Service.java:222)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openAndConnectToGimapsStore(OpenStoreHelper.kt:77)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openStore(OpenStoreHelper.kt:166)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnToStore$FlowCrypt_prodRelease(EmailSyncManager.kt:485)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_prodRelease(EmailSyncManager.kt:505)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.kt:614)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        ... 34 more
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:646)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:495)
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:418)
        at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:339)
        at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
        at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):2)
        at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@17785037@17.7.85 (100400-253824076):1)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@17785037@17.7.85 (100400-253824076):12)
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):7)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@17785037@17.7.85 (100400-253824076):14)
        at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:602)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:376)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:214)
        at com.sun.mail.iap.Protocol.<init>(Protocol.java:110)
        at com.sun.mail.imap.protocol.IMAPProtocol.<init>(IMAPProtocol.java:107)
        at com.sun.mail.gimap.protocol.GmailProtocol.<init>(GmailProtocol.java:83)
        at com.sun.mail.gimap.GmailStore.newIMAPProtocol(GmailStore.java:74)
        at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:674)
        at com.sun.mail.gimap.GmailStore.protocolConnect(GmailStore.java:68)
        at javax.mail.Service.connect(Service.java:342)
        at javax.mail.Service.connect(Service.java:222)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openAndConnectToGimapsStore(OpenStoreHelper.kt:77)
        at com.flowcrypt.email.api.email.protocol.OpenStoreHelper$Companion.openStore(OpenStoreHelper.kt:166)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.openConnToStore$FlowCrypt_prodRelease(EmailSyncManager.kt:485)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_prodRelease(EmailSyncManager.kt:505)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.kt:614)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by DenBond7** [comment]
As Bill Shannon described [here](https://stackoverflow.com/questions/26470491/android-javamail-application-certpathvalidatorexception-trust-anchor-for-cert) there might be a firewall or anti-virus or proxy program problem. Just for info

**Comment by DenBond7** [comment]
duplicate of #857
