### ISSUE TITLE
add name into gey gen

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#590]
Currently it's sending

`{"passphrase":"...","userIds":[{"email":"aaa@gmail.com"}],"variant":"curve25519"}`

should be

`{"passphrase":"...","userIds":[{"email":"aaa@gmail.com", "name": "My Name"}],"variant":"curve25519"}`

**Comment by tomholub** [comment]
Maybe a problem on particular account

**Comment by tomholub** [comment]
to investigate further in #591

**Comment by tomholub** [comment]
here was the issue
```
[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.ui.loader.CreatePrivateKeyAsyncTaskLoader.loadInBackground(CreatePrivateKeyAsyncTaskLoader.kt:99)
        at com.flowcrypt.email.ui.loader.CreatePrivateKeyAsyncTaskLoader.loadInBackground(CreatePrivateKeyAsyncTaskLoader.kt:44)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: com.flowcrypt.email.util.exception.NodeException: Error :Error: Wrong request structure for NodeRequest.generateKey
Stack :Error: Wrong request structure for NodeRequest.generateKey
    at Function.module.exports.Validate.generateKey.v [as generateKey] ([eval]:71968:9)
    at Endpoints.generateKey ([eval]:71582:31)
    at delegateReqToEndpoint ([eval]:68811:12)
    at handleReq ([eval]:68851:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Type :null
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.checkResult(NodeCallsExecutor.kt:189)
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.genKey(NodeCallsExecutor.kt:156)
        at com.flowcrypt.email.ui.loader.CreatePrivateKeyAsyncTaskLoader.loadInBackground(CreatePrivateKeyAsyncTaskLoader.kt:67)
        ... 9 more
com.flowcrypt.email.util.exception.NodeException: Error :Error: Wrong request structure for NodeRequest.generateKey
Stack :Error: Wrong request structure for NodeRequest.generateKey
    at Function.module.exports.Validate.generateKey.v [as generateKey] ([eval]:71968:9)
    at Endpoints.generateKey ([eval]:71582:31)
    at delegateReqToEndpoint ([eval]:68811:12)
    at handleReq ([eval]:68851:36)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Type :null
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.checkResult(NodeCallsExecutor.kt:189)
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.genKey(NodeCallsExecutor.kt:156)
        at com.flowcrypt.email.ui.loader.CreatePrivateKeyAsyncTaskLoader.loadInBackground(CreatePrivateKeyAsyncTaskLoader.kt:67)
        at com.flowcrypt.email.ui.loader.CreatePrivateKeyAsyncTaskLoader.loadInBackground(CreatePrivateKeyAsyncTaskLoader.kt:44)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```
