### ISSUE TITLE
highlighting (long-press) recipient crashes app

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#598]
![Screenshot_20190629-215701](https://user-images.githubusercontent.com/6306961/60433735-0b46e880-9bf5-11e9-9655-75461e5871bb.png)

**Comment by tomholub** [comment]
```
V/FragmentManager: moveto RESUMED: EmailListFragment{165def3 #0 id=0x7f090086}
V/FragmentManager: moveto RESUMED: zzc{f0a7f65 #1 SupportLifecycleFragmentImpl}
V/FragmentManager: moveto RESUMED: SupportRequestManagerFragment{8189ef4 #2 com.bumptech.glide.manager}{parent=null}
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
I/chatty: uid=10079(u0_a79) com.flowcrypt.email.debug identical 4 lines
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
V/FragmentManager: movefrom STARTED: MessageDetailsFragment{534e4de #0 id=0x7f090128}
D/MessageDetailsActivity: onStop
V/FragmentManager: movefrom ACTIVITY_CREATED: MessageDetailsFragment{534e4de #0 id=0x7f090128}
V/FragmentManager: movefrom CREATED: MessageDetailsFragment{534e4de #0 id=0x7f090128}
V/FragmentManager: Freeing fragment index MessageDetailsFragment{534e4de #0 id=0x7f090128}
D/MessageDetailsActivity: onDestroy
D/MessageDetailsActivity: unbind from EmailSyncService
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
I/chatty: uid=10079(u0_a79) com.flowcrypt.email.debug identical 1 line
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
V/FragmentManager: movefrom RESUMED: EmailListFragment{165def3 #0 id=0x7f090086}
V/FragmentManager: movefrom RESUMED: zzc{f0a7f65 #1 SupportLifecycleFragmentImpl}
    movefrom RESUMED: SupportRequestManagerFragment{8189ef4 #2 com.bumptech.glide.manager}{parent=null}
D/CreateMessageActivity: onCreate
V/FragmentManager: onCreateView: id=0x7f09005e fname=com.flowcrypt.email.ui.activity.fragment.base.CreateMessageFragment existing=null
V/FragmentManager: add: CreateMessageFragment{97d9bb1 id=0x7f09005e}
V/FragmentManager: Allocated fragment index CreateMessageFragment{97d9bb1 #0 id=0x7f09005e}
    moveto CREATED: CreateMessageFragment{97d9bb1 #0 id=0x7f09005e}
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
I/chatty: uid=10079(u0_a79) com.flowcrypt.email.debug identical 2 lines
I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
D/CreateMessageActivity: bind to EmailSyncService
V/FragmentManager: moveto ACTIVITY_CREATED: CreateMessageFragment{97d9bb1 #0 id=0x7f09005e}
V/FragmentManager: moveto STARTED: CreateMessageFragment{97d9bb1 #0 id=0x7f09005e}
D/CreateMessageActivity: onStart
D/CreateMessageActivity: onResume
V/FragmentManager: moveto RESUMED: CreateMessageFragment{97d9bb1 #0 id=0x7f09005e}
D/CreateMessageActivity: Activity connected to com.flowcrypt.email.service.EmailSyncService
D/OpenGLRenderer: endAllActiveAnimators on 0x61bdd080 (RippleDrawable) with handle 0x8cca9c20
V/FragmentManager: Saved state of EmailListFragment{165def3 #0 id=0x7f090086}: Bundle[{android:view_state={2131296390=android.view.AbsSavedState$1@27f14ce, 2131296391=android.view.AbsSavedState$1@27f14ce, 2131296450=android.view.AbsSavedState$1@27f14ce, 2131296510=AbsListView.SavedState{b420ee5 selectedId=-9223372036854775808 firstId=-1 viewTop=0 position=0 height=1536 filter=null checkState=null}, 2131296579=android.widget.ProgressBar$SavedState@5c84dba, 2131296683=android.view.AbsSavedState$1@27f14ce, 2131296717=android.view.AbsSavedState$1@27f14ce, 2131296804=android.widget.ProgressBar$SavedState@5d3f46b, 2131296805=android.view.AbsSavedState$1@27f14ce, 2131296806=android.view.AbsSavedState$1@27f14ce}}]
V/FragmentManager: Saved state of zzc{f0a7f65 #1 SupportLifecycleFragmentImpl}: Bundle[{AutoManageHelper=Bundle[{}]}]
    Saved state of SupportRequestManagerFragment{8189ef4 #2 com.bumptech.glide.manager}{parent=null}: null
    saveAllState: adding fragment #0: EmailListFragment{165def3 #0 id=0x7f090086}
    saveAllState: adding fragment #1: zzc{f0a7f65 #1 SupportLifecycleFragmentImpl}
V/FragmentManager: saveAllState: adding fragment #2: SupportRequestManagerFragment{8189ef4 #2 com.bumptech.glide.manager}{parent=null}
V/FragmentManager: movefrom STARTED: EmailListFragment{165def3 #0 id=0x7f090086}
V/FragmentManager: movefrom STARTED: zzc{f0a7f65 #1 SupportLifecycleFragmentImpl}
    movefrom STARTED: SupportRequestManagerFragment{8189ef4 #2 com.bumptech.glide.manager}{parent=null}
D/EmailManagerActivity: onStop
I/txtClsf: memory-image-reader.h:129: Unable to parse the trimmed proto
I/chatty: uid=10079(u0_a79) AsyncTask #13 identical 4 lines
I/txtClsf: memory-image-reader.h:129: Unable to parse the trimmed proto
D/TextClassifierImpl: Got bad indices for input text. Ignoring result.
I/txtClsf: memory-image-reader.h:129: Unable to parse the trimmed proto
I/txtClsf: memory-image-reader.h:129: Unable to parse the trimmed proto
I/txtClsf: memory-image-reader.h:129: Unable to parse the trimmed proto
D/TextClassifierImpl: Got bad indices for input text. Ignoring result.
I/txtClsf: memory-image-reader.h:129: Unable to parse the trimmed proto
D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flowcrypt.email.debug, PID: 17948
    java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.android.internal.view.menu.MenuBuilder.getItem(MenuBuilder.java:682)
        at com.flowcrypt.email.ui.widget.PgpContactsNachoTextView$CustomActionModeCallback.onPrepareActionMode(PgpContactsNachoTextView.kt:195)
        at android.widget.Editor$TextActionModeCallback.onPrepareActionMode(Editor.java:3879)
        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onPrepareActionMode(DecorView.java:2425)
        at com.android.internal.view.FloatingActionMode.invalidate(FloatingActionMode.java:143)
        at com.android.internal.policy.DecorView.setHandledFloatingActionMode(DecorView.java:1834)
        at com.android.internal.policy.DecorView.setHandledActionMode(DecorView.java:1674)
        at com.android.internal.policy.DecorView.startActionMode(DecorView.java:895)
        at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:850)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:916)
        at android.view.View.startActionMode(View.java:6455)
        at android.widget.Editor.startSelectionActionModeInternal(Editor.java:2095)
        at android.widget.SelectionActionModeHelper.startActionMode(SelectionActionModeHelper.java:155)
        at android.widget.SelectionActionModeHelper.-android_widget_SelectionActionModeHelper-mthref-2(SelectionActionModeHelper.java:84)
        at android.widget.-$Lambda$tTszxdFZ0V9nXhnBpPsqeBMO0fw$2.$m$0(Unknown Source:6)
        at android.widget.-$Lambda$tTszxdFZ0V9nXhnBpPsqeBMO0fw$2.accept(Unknown Source:0)
        at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:367)
        at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:363)
        at android.os.AsyncTask.finish(AsyncTask.java:695)
        at android.os.AsyncTask.-wrap1(Unknown Source:0)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6567)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by tomholub** [comment]
Another from ACRA
```
java.lang.IndexOutOfBoundsException: Index: 4, Size: 3
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.android.internal.view.menu.MenuBuilder.getItem(MenuBuilder.java:698)
        at com.flowcrypt.email.ui.widget.PgpContactsNachoTextView$CustomActionModeCallback.onPrepareActionMode(PgpContactsNachoTextView.kt:195)
        at android.widget.Editor$TextActionModeCallback.onPrepareActionMode(Editor.java:4026)
        at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onPrepareActionMode(DecorView.java:2388)
        at com.android.internal.view.FloatingActionMode.invalidate(FloatingActionMode.java:145)
        at com.android.internal.policy.DecorView.setHandledFloatingActionMode(DecorView.java:1811)
        at com.android.internal.policy.DecorView.setHandledActionMode(DecorView.java:1651)
        at com.android.internal.policy.DecorView.startActionMode(DecorView.java:888)
        at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:843)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:985)
        at android.view.View.startActionMode(View.java:6796)
        at android.widget.Editor.startActionModeInternal(Editor.java:2222)
        at android.widget.SelectionActionModeHelper.startActionMode(SelectionActionModeHelper.java:261)
        at android.widget.SelectionActionModeHelper.startSelectionActionMode(SelectionActionModeHelper.java:242)
        at android.widget.SelectionActionModeHelper.lambda$startSelectionActionModeWithSmartSelectAnimation$0(SelectionActionModeHelper.java:296)
        at android.widget.-$$Lambda$SelectionActionModeHelper$xdBRwQcbRdz8duQr0RBo4YKAnOA.run(Unknown Source:4)
        at android.widget.SelectionActionModeHelper.startSelectionActionModeWithSmartSelectAnimation(SelectionActionModeHelper.java:304)
        at android.widget.SelectionActionModeHelper.lambda$l1f1_V5lw6noQxI_3u11qF753Iw(Unknown Source:0)
        at android.widget.-$$Lambda$SelectionActionModeHelper$l1f1_V5lw6noQxI_3u11qF753Iw.accept(Unknown Source:4)
        at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:910)
        at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onTimeOut(SelectionActionModeHelper.java:915)
        at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.lambda$D5tkmK-caFBtl9ux2L0aUfUee4E(Unknown Source:0)
        at android.widget.-$$Lambda$SelectionActionModeHelper$TextClassificationAsyncTask$D5tkmK-caFBtl9ux2L0aUfUee4E.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
