### ISSUE TITLE
Binder TransactionTooLargeException when opening email

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#609]
```
V/FragmentManager: Saved state of zzc{9b09a04 #1 SupportLifecycleFragmentImpl}: Bundle[{AutoManageHelper=Bundle[{}]}]
    Saved state of SupportRequestManagerFragment{e5d5ab8 #2 com.bumptech.glide.manager}{parent=null}: null
V/FragmentManager: saveAllState: adding fragment #0: EmailListFragment{788266c #0 id=0x7f090086}
V/FragmentManager: saveAllState: adding fragment #1: zzc{9b09a04 #1 SupportLifecycleFragmentImpl}
    saveAllState: adding fragment #2: SupportRequestManagerFragment{e5d5ab8 #2 com.bumptech.glide.manager}{parent=null}
V/FragmentManager: movefrom STARTED: EmailListFragment{788266c #0 id=0x7f090086}
V/FragmentManager: movefrom STARTED: zzc{9b09a04 #1 SupportLifecycleFragmentImpl}
V/FragmentManager: movefrom STARTED: SupportRequestManagerFragment{e5d5ab8 #2 com.bumptech.glide.manager}{parent=null}
D/EmailManagerActivity: onStop
V/FragmentManager: movefrom RESUMED: MessageDetailsFragment{7602de8 #0 id=0x7f090128}
V/FragmentManager: moveto STARTED: EmailListFragment{788266c #0 id=0x7f090086}
V/FragmentManager: moveto STARTED: zzc{9b09a04 #1 SupportLifecycleFragmentImpl}
D/AutoManageHelper: onStart true {0=com.google.android.gms.common.api.internal.zaj$zaa@9a78cf4}
V/FragmentManager: moveto STARTED: SupportRequestManagerFragment{e5d5ab8 #2 com.bumptech.glide.manager}{parent=null}
D/EmailManagerActivity: onStart
D/EmailManagerActivity: onResume
V/FragmentManager: moveto RESUMED: EmailListFragment{788266c #0 id=0x7f090086}
V/FragmentManager: moveto RESUMED: zzc{9b09a04 #1 SupportLifecycleFragmentImpl}
V/FragmentManager: moveto RESUMED: SupportRequestManagerFragment{e5d5ab8 #2 com.bumptech.glide.manager}{parent=null}
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
I/chatty: uid=10079(u0_a79) com.flowcrypt.email.debug identical 3 lines
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
V/FragmentManager: movefrom STARTED: MessageDetailsFragment{7602de8 #0 id=0x7f090128}
D/MessageDetailsActivity: onStop
V/FragmentManager: movefrom ACTIVITY_CREATED: MessageDetailsFragment{7602de8 #0 id=0x7f090128}
V/FragmentManager: movefrom CREATED: MessageDetailsFragment{7602de8 #0 id=0x7f090128}
V/FragmentManager: Freeing fragment index MessageDetailsFragment{7602de8 #0 id=0x7f090128}
D/MessageDetailsActivity: onDestroy
D/MessageDetailsActivity: unbind from EmailSyncService
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1791180)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flowcrypt.email.debug, PID: 26502
    java.lang.RuntimeException: Failure from system
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1617)
        at android.app.Activity.startActivityForResult(Activity.java:4473)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:886)
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:995)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1103)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1092)
        at com.flowcrypt.email.ui.activity.fragment.EmailListFragment.onItemClick(EmailListFragment.kt:215)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1167)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
        at android.widget.AbsListView$3.run(AbsListView.java:4051)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6567)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1791180 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:748)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4364)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
        at android.app.Activity.startActivityForResult(Activity.java:4473) 
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767) 
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234) 
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:886) 
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:995) 
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1103) 
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1092) 
        at com.flowcrypt.email.ui.activity.fragment.EmailListFragment.onItemClick(EmailListFragment.kt:215) 
        at android.widget.AdapterView.performItemClick(AdapterView.java:318) 
        at android.widget.AbsListView.performItemClick(AbsListView.java:1167) 
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136) 
        at android.widget.AbsListView$3.run(AbsListView.java:4051) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6567) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
I/System.out: DEBUG GIMAPS: IMAPStore cleanup, force false
I/System.out: E3 LOGOUT
I/System.out: * BYE LOGOUT Requested
    E3 OK 73 good day (Success)
I/System.out: DEBUG GIMAPS: IMAPStore cleanup done
D/PassiveSyncTaskRunnable: Disconnected. Wait new tasks.
I/System.out: DEBUG GIMAPS: IMAPStore cleanup, not connected
```

**Comment by tomholub** [comment]
I was opening messages one after another in from email list.

https://stackoverflow.com/questions/41821480/fatal-exception-java-lang-runtimeexception-failure-from-system

**Comment by tomholub** [comment]
Most likely related to me recently changing message fetch size from 200kb to 1000kb.
```js
list.writeString("BODY[]<0.1024000>")
```
There seems to be a hard-coded limit 1MB in Binder.

I'll lower it to 450kb for now. Very soon we should see if there is a way around that - eg chunk it up and send over binder in smaller chunks, or use a file, etc.

**Comment by tomholub** [comment]
Actually does not seem pull size related. Crashes either way.

**Comment by tomholub** [comment]
Keeps showing `(parcel size = 1791180)` regardless what size I select.

**Comment by tomholub** [comment]
Another message https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/WhctKJTrWNFtCxXXWRKkdrcSrfJrjGcmCLtvNgTqtkGgssRfhhTgqNnVpCXJpKXwVVWwgpG

Now I'm thinking it may be related to me returning back the attachments. Maybe the android app cannot take the big ones yet.

```
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 2049968)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flowcrypt.email.debug, PID: 31549
    java.lang.RuntimeException: Failure from system
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1617)
        at android.app.Activity.startActivityForResult(Activity.java:4473)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:886)
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:995)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1103)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1092)
        at com.flowcrypt.email.ui.activity.fragment.EmailListFragment.onItemClick(EmailListFragment.kt:215)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1167)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
        at android.widget.AbsListView$3.run(AbsListView.java:4051)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6567)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.os.TransactionTooLargeException: data parcel size 2049968 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:748)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4364)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
        at android.app.Activity.startActivityForResult(Activity.java:4473) 
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767) 
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234) 
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:886) 
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:995) 
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1103) 
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1092) 
        at com.flowcrypt.email.ui.activity.fragment.EmailListFragment.onItemClick(EmailListFragment.kt:215) 
        at android.widget.AdapterView.performItemClick(AdapterView.java:318) 
        at android.widget.AbsListView.performItemClick(AbsListView.java:1167) 
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136) 
        at android.widget.AbsListView$3.run(AbsListView.java:4051) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6567) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by tomholub** [comment]
another

https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/WhctKHTCFgHQqPvzmZcFkgPVzFJkzqfZRzVSXNTsQlZjpQMkgnrtTNkBHgjClgNrJqJtLnv

```
W/StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 2049968)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.flowcrypt.email.debug, PID: 31549
    java.lang.RuntimeException: Failure from system
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1617)
        at android.app.Activity.startActivityForResult(Activity.java:4473)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:886)
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:995)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1103)
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1092)
        at com.flowcrypt.email.ui.activity.fragment.EmailListFragment.onItemClick(EmailListFragment.kt:215)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1167)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
        at android.widget.AbsListView$3.run(AbsListView.java:4051)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6567)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: android.os.TransactionTooLargeException: data parcel size 2049968 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:748)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4364)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
        at android.app.Activity.startActivityForResult(Activity.java:4473) 
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767) 
        at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234) 
        at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:886) 
        at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:995) 
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1103) 
        at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1092) 
        at com.flowcrypt.email.ui.activity.fragment.EmailListFragment.onItemClick(EmailListFragment.kt:215) 
        at android.widget.AdapterView.performItemClick(AdapterView.java:318) 
        at android.widget.AbsListView.performItemClick(AbsListView.java:1167) 
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136) 
        at android.widget.AbsListView$3.run(AbsListView.java:4051) 
        at android.os.Handler.handleCallback(Handler.java:789) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6567) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
Application terminated.
```

**Comment by tomholub** [comment]
Inner attachments are not the problem, this happens before mobile-core gets the msg.

**Comment by tomholub** [comment]
the rest is in #610

**Comment by tomholub** [comment]
Some of these cannot be caught it seems (or don't know how to catch them), have to check message size in advance.
