### ISSUE TITLE
error ocurred during receiving the message details

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#628]
https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#search/compatibility+issue+public+key/WhctKJTrSJkJWfxbckhpLSRcXrnqCxmnwdXXQrbHmWwLFflmKMRlfKBCQhVRqzdwqbBTKZQ

This pubkey has also some issue on chrome, but it looks like the app gives up before even sending it to mobile-core.

```
D/ActiveSyncTaskRunnable: Start a new task = LoadMessageDetailsSyncTask for store gimaps://flowcrypt.compatibility%40gmail.com@imap.gmail.com
D/EmailSyncService: onActionProgress: accountAccountDao(email=flowcrypt.compatibility@gmail.com, accountType=com.google, displayName=FlowCrypt Compatibility, givenName=FlowCrypt, familyName=Compatibility, photoUrl=https://www.google.com/s2/photos/private/AIbEiAIAAABECIqJoOyM3fej1AEiC3ZjYXJkX3Bob3RvKig5MzhkNTBhNjQwNGM3YzViNmQ2ZmU0MjM0N2NjNjdkMDc5N2FiMGI5MAFByEbkIwRf4-NHV9NfvQKAAbT2JQ, areContactsLoaded=true, authCreds=AuthCredentials(email=flowcrypt.compatibility@gmail.com, username=flowcrypt.compatibility@gmail.com, password=, imapServer=imap.gmail.com, imapPort=993, imapOpt=SSL_TLS, smtpServer=smtp.gmail.com, smtpPort=465, smtpOpt=SSL_TLS, hasCustomSignInForSmtp=false, smtpSigInUsername=null, smtpSignInPassword=null))| ownerKey =MessageDetailsActivity_153318746| requestCode =2131296693
I/System.out: DEBUG GIMAPS: connection available -- size: 1
    I10 SELECT tests/pubkey
I/System.out: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing)
    * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $NotPhishing $Phishing \*)] Flags permitted.
    * OK [UIDVALIDITY 17] UIDs valid.
I/System.out: * 18 EXISTS
    * 0 RECENT
    * OK [UIDNEXT 20] Predicted next UID.
    * OK [HIGHESTMODSEQ 981338]
    I10 OK [READ-WRITE] tests/pubkey selected. (Success)
I/System.out: I11 UID FETCH 13 (RFC822.SIZE BODY[]<0.1024000>)
I/System.out: I11 OK Success
W/System.err: java.lang.IllegalStateException: An error occurred during receiving the message details
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessageDetailsSyncTask.runIMAPAction(LoadMessageDetailsSyncTask.kt:74)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_devDebug(EmailSyncManager.kt:519)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.kt:614)
W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
E/EmailSyncService: onError: errorType2| e =java.lang.IllegalStateException: An error occurred during receiving the message details
D/ActiveSyncTaskRunnable: ActiveSyncTaskBlockingQueue size = 0
```

**Comment by tomholub** [comment]
and from acra

```
[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_prodRelease(EmailSyncManager.kt:532)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.kt:614)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: An error occurred during receiving the message details
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessageDetailsSyncTask.runIMAPAction(LoadMessageDetailsSyncTask.kt:74)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_prodRelease(EmailSyncManager.kt:519)
        ... 6 more
java.lang.IllegalStateException: An error occurred during receiving the message details
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessageDetailsSyncTask.runIMAPAction(LoadMessageDetailsSyncTask.kt:74)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$BaseSyncRunnable.runSyncTask$FlowCrypt_prodRelease(EmailSyncManager.kt:519)
        at com.flowcrypt.email.api.email.sync.EmailSyncManager$ActiveSyncTaskRunnable.run(EmailSyncManager.kt:614)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#search/%22An+error+occurred+during+receiving+the+message+details%22

**Comment by DenBond7** [comment]
@tomholub 
> This pubkey has also some issue on chrome, but it looks like the app gives up before even sending it to mobile-core.

I think there is no relation between the current issue and that email. This issue happens when we don't receive `OK` response type from a server (maybe the server returned one of the errors. [There are a lot of variants](https://tools.ietf.org/html/rfc5530)). In that case, we show the following warning

![image](https://user-images.githubusercontent.com/2863246/61030773-d0983980-a3c6-11e9-9f43-c1b9ef4bff60.png)

I'm going to add some debug code to identify what the server exactly sent. Fortunately, it's not a widespread error. We have only a few.

**Comment by DenBond7** [comment]
Issue #585 should resolve this one
