### ISSUE TITLE
could not determine pgpType

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#633]
```
[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.kt:73)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.kt:30)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: com.flowcrypt.email.util.exception.NodeException: Error :Cannot parse key: could not determine pgpType
Stack :null
Type :null
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.checkResult(NodeCallsExecutor.kt:189)
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.parseKeys(NodeCallsExecutor.kt:53)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.kt:68)
        ... 9 more
com.flowcrypt.email.util.exception.NodeException: Error :Cannot parse key: could not determine pgpType
Stack :null
Type :null
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.checkResult(NodeCallsExecutor.kt:189)
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.parseKeys(NodeCallsExecutor.kt:53)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.kt:68)
        at com.flowcrypt.email.ui.loader.ParseKeysFromResourceAsyncTaskLoader.loadInBackground(ParseKeysFromResourceAsyncTaskLoader.kt:30)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by tomholub** [comment]
@DenBond7 This happens when supplied key to `parseKeys` is not a valid key.

```js
{ format: "unknown", keyDetails: [], error: { message: "Cannot parse key: could not determine pgpType" } }
```

I could skip the error and just return an empty result set:
```js
{ format: "unknown", keyDetails: [] }
```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#search/%22could+not+determine+pgpType%22

**Comment by DenBond7** [comment]
@tomholub 
> I could skip the error and just return an empty result set:

I think It'll be the best option. Then the app will show info: `The content of your file does not look like a valid PGP %1$s Key.` (%1$s = `Private` or `Public`). We had this logic before

**Comment by tomholub** [comment]
Ok I'll to that.

**Comment by tomholub** [comment]
See if this works better

**Comment by DenBond7** [comment]
I'm closing it. It works well
