### ISSUE TITLE
KotlinNullPointerException in EmailSyncService.onBind

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#639]
```
[SUMMARY]
java.lang.RuntimeException: Unable to bind to service com.flowcrypt.email.service.EmailSyncService@dc982d2 with Intent { cmp=com.flowcrypt.email/.service.EmailSyncService }: kotlin.KotlinNullPointerException
kotlin.KotlinNullPointerException

[STACK_TRACE]
java.lang.RuntimeException: Unable to bind to service com.flowcrypt.email.service.EmailSyncService@dc982d2 with Intent { cmp=com.flowcrypt.email/.service.EmailSyncService }: kotlin.KotlinNullPointerException
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3792)
        at android.app.ActivityThread.access$1500(ActivityThread.java:236)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1805)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
Caused by: kotlin.KotlinNullPointerException
        at com.flowcrypt.email.service.EmailSyncService.onBind(EmailSyncService.kt:166)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3776)
        ... 8 more
kotlin.KotlinNullPointerException
        at com.flowcrypt.email.service.EmailSyncService.onBind(EmailSyncService.kt:166)
        at android.app.ActivityThread.handleBindService(ActivityThread.java:3776)
        at android.app.ActivityThread.access$1500(ActivityThread.java:236)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1805)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7032)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

ref https://mail.google.com/mail/u/0/#search/%22EmailSyncService.onBind(EmailSyncService.kt%3A166)%22

**Comment by DenBond7** [comment]
It happens when a user is trying to use the app for sharing action, but the app didn't setup before
