### ISSUE TITLE
NumberFormatException in AddNewAccountManuallyActivity when a user uses autofill

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#640]
```
[SUMMARY]
java.lang.NumberFormatException: For input string: "mikex"

[STACK_TRACE]
java.lang.NumberFormatException: For input string: "mikex"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at com.flowcrypt.email.ui.activity.AddNewAccountManuallyActivity.generateAuthCreds(AddNewAccountManuallyActivity.kt:534)
        at com.flowcrypt.email.ui.activity.AddNewAccountManuallyActivity.onClick(AddNewAccountManuallyActivity.kt:262)
        at android.view.View.performClick(View.java:6648)
        at android.view.View.performClickInternal(View.java:6620)
        at android.view.View.access$3100(View.java:787)
        at android.view.View$PerformClick.run(View.java:26167)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7539)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

```

ref https://mail.google.com/mail/u/0/#search/%22AddNewAccountManuallyActivity.generateAuthCreds%22

**Comment by DenBond7** [comment]
It happens on Android 8 and high
