### ISSUE TITLE
handle keys without valid email address userId

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#641]
```
[SUMMARY]
kotlin.KotlinNullPointerException
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.parseKeys(PreviewImportPgpContactFragment.kt:226)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.doInBackground(PreviewImportPgpContactFragment.kt:188)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.doInBackground(PreviewImportPgpContactFragment.kt:168)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: kotlin.KotlinNullPointerException
        at com.flowcrypt.email.api.retrofit.response.model.node.NodeKeyDetails.determinePrimaryPgpContact(NodeKeyDetails.kt:94)
        at com.flowcrypt.email.api.retrofit.response.model.node.NodeKeyDetails.getPrimaryPgpContact(NodeKeyDetails.kt:35)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.getPublicKeyInfo(PreviewImportPgpContactFragment.kt:264)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.parsePublicKeysInfo(PreviewImportPgpContactFragment.kt:242)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.parseKeys(PreviewImportPgpContactFragment.kt:212)
        ... 8 more
kotlin.KotlinNullPointerException
        at com.flowcrypt.email.api.retrofit.response.model.node.NodeKeyDetails.determinePrimaryPgpContact(NodeKeyDetails.kt:94)
        at com.flowcrypt.email.api.retrofit.response.model.node.NodeKeyDetails.getPrimaryPgpContact(NodeKeyDetails.kt:35)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.getPublicKeyInfo(PreviewImportPgpContactFragment.kt:264)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.parsePublicKeysInfo(PreviewImportPgpContactFragment.kt:242)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.parseKeys(PreviewImportPgpContactFragment.kt:212)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.doInBackground(PreviewImportPgpContactFragment.kt:188)
        at com.flowcrypt.email.ui.activity.fragment.PreviewImportPgpContactFragment$PublicKeysParserAsyncTask.doInBackground(PreviewImportPgpContactFragment.kt:168)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#search/%22determinePrimaryPgpContact%22

**Comment by DenBond7** [comment]
@tomholub 
It happens when a user is trying to use a key which has primary user ID without a mail address. I've created an example of such a key:

[pubkey.txt](https://github.com/FlowCrypt/flowcrypt-android/files/3411050/pubkey.txt)

Steps to reproduce:
1) Settings
2) Contacts
3) Add a new one
4) Import from a file

I think it'll be better to throw an exception on the Node side. Because such keys are not applicable to the app (we should know at least one email to create an association `email <-> pubkey `)

**Comment by tomholub** [comment]
Sure. Where should the exception be thrown? In which call?

**Comment by DenBond7** [comment]
@tomholub 
>Where should the exception be thrown? In which call?

parseKeys

**Comment by tomholub** [comment]
I think maybe we need a smarter mechanism for this. It's complex.

For example, in browser, we allow users to import such keys for other people contacts (public keys) and assign their own email address to it.

There are more reasons the key may be not good. Maybe it's expired, or maybe has a weird structure, or unsupported algorithm.

I can verify this for each key. It's a bit expensive, because signatures have to be verified and so on. But I could give you a key status that would be something like:
```
"status": "valid" | "expired" | "badUser" | "invalid"
```
This scenario would be `badUser`. If this is a private key for import, we would have to fix the key before importing (add appropriate user). If this is public key, we leave key as is and import under a user-chosen email address.

As you see it's probably more work than we should be doing this release.

**Comment by DenBond7** [comment]
@tomholub 
> As you see it's probably more work than we should be doing this release.

Agree. Then I propose to move it to later. it's not a widespread error.

**Comment by tomholub** [comment]
All of this is easy to do in node, but I imagine the user interactions will be more work.

**Comment by DenBond7** [comment]
> All of this is easy to do in node, but I imagine the user interactions will be more work.

You are correct. Totally agree

**Comment by tomholub** [comment]
superseded by #976
