### ISSUE TITLE
"Use message password" when decrypt attachments

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#661]
```
[SUMMARY]
java.lang.Exception: Use message password
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.kt:485)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.Exception: Use message password
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.getDecryptedFileResult(AttachmentDownloadManagerService.kt:617)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.decryptFileIfNeeded(AttachmentDownloadManagerService.kt:581)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.kt:466)
        ... 5 more
java.lang.Exception: Use message password
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.getDecryptedFileResult(AttachmentDownloadManagerService.kt:617)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.decryptFileIfNeeded(AttachmentDownloadManagerService.kt:581)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.kt:466)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

ref https://mail.google.com/mail/u/0/#search/%22Use+message+password%22

**Comment by DenBond7** [comment]
@tomholub 
![image](https://user-images.githubusercontent.com/2863246/61536177-b1d81980-aa3c-11e9-9f8f-9f5eb07bfb41.png)

**Comment by tomholub** [comment]
@DenBond7 for now please make it render `Opening password encrypted messages not implemented yet`
