### ISSUE TITLE
https://flowcrypt.com/attester/lookup results with "null" values

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#662]
```
[SUMMARY]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.retrofit.response.model.LookUpPublicKeyInfo.getPubKey()' on a null object reference

[STACK_TRACE]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.flowcrypt.email.api.retrofit.response.model.LookUpPublicKeyInfo.getPubKey()' on a null object reference
        at com.flowcrypt.email.ui.activity.ImportPgpContactActivity.handleLookupResponse(ImportPgpContactActivity.kt:196)
        at com.flowcrypt.email.ui.activity.ImportPgpContactActivity.onSuccess(ImportPgpContactActivity.kt:136)
        at com.flowcrypt.email.ui.activity.base.BaseActivity.handleLoaderResult(BaseActivity.kt:190)
        at com.flowcrypt.email.ui.activity.base.BaseImportKeyActivity.onLoadFinished(BaseImportKeyActivity.kt:247)
        at com.flowcrypt.email.ui.activity.base.BaseImportKeyActivity.onLoadFinished(BaseImportKeyActivity.kt:51)
        at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:113)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:131)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:289)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
        at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
        at androidx.loader.content.Loader.deliverResult(Loader.java:132)
        at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
        at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
        at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7045)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

ref https://mail.google.com/mail/u/0/#search/%22LookUpPublicKeyInfo.getPubKey()%22

**Comment by DenBond7** [comment]
it happens when a server returns a response like

https://flowcrypt.com/attester/lookup/denbond7

``` json
{
   "query":"denbond7",
   "results":[
      null
   ]
}
```
then in the code, we have a null value in a list.

**Comment by DenBond7** [comment]
@tomholub 

Could we have a response like below if no results?

``` json
{
   "query":"denbond7",
   "results":[
   ]
}
```

**Comment by tomholub** [comment]
Best would be to switch to the new api

https://flowcrypt.com/attester/pub/human@flowcrypt.com
https://flowcrypt.com/attester/pub/unknown@flowcrypt.com
https://flowcrypt.com/attester/pub/0C9C2E6A4D273C6F

404 means not found. Else if 200 -> you get pubkey as text.

**Comment by tomholub** [comment]
Use http GET for the api above

**Comment by tomholub** [comment]
I want to deprecate this older Attester api one day.

**Comment by tomholub** [comment]
The original design was for pulling several pubkeys, a, b, c. Then you get `[pubkeyA, null, pubkeyB]` for example, positionally arranged with the nulls when pubkey not found.

If you don't want to change that now, you could run `.filter not null` on the array for the time being.

**Comment by DenBond7** [comment]
> If you don't want to change that now, you could run .filter not null on the array for the time being.

I will choose that option. We will create a separate issue for a migration
