### ISSUE TITLE
catch errors when processing keys

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#740]
it relates to #441 

`email 0.8.7 (under 5 errs) Handled manually: > Cannot read property 'length' of null`

```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
com.flowcrypt.email.util.exception.NodeException: Error :TypeError: Cannot read property 'length' of null
```

```
[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.ui.loader.EncryptAndSavePrivateKeysAsyncTaskLoader.loadInBackground(EncryptAndSavePrivateKeysAsyncTaskLoader.kt:104)
        at com.flowcrypt.email.ui.loader.EncryptAndSavePrivateKeysAsyncTaskLoader.loadInBackground(EncryptAndSavePrivateKeysAsyncTaskLoader.kt:41)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: com.flowcrypt.email.util.exception.NodeException: Error :TypeError: Cannot read property 'length' of null
Stack :TypeError: Cannot read property 'length' of null
    at MPI.toUint8Array ([eval]:72998:32)
    at MPI.write ([eval]:72985:48)
    at write_cleartext_params ([eval]:70310:24)
    at SecretKey.write ([eval]:70438:31)
    at List.write ([eval]:69481:33)
    at Key.armor ([eval]:64435:59)
    at Endpoints.decryptKey ([eval]:86887:29)
    at process._tickCallback (example.file:68:7)
Type :null
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.checkResult(NodeCallsExecutor.kt:189)
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.decryptKey(NodeCallsExecutor.kt:112)
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.decryptKey(NodeCallsExecutor.kt:92)
        at com.flowcrypt.email.ui.loader.EncryptAndSavePrivateKeysAsyncTaskLoader.loadInBackground(EncryptAndSavePrivateKeysAsyncTaskLoader.kt:68)
        ... 9 more
com.flowcrypt.email.util.exception.NodeException: Error :TypeError: Cannot read property 'length' of null
Stack :TypeError: Cannot read property 'length' of null
    at MPI.toUint8Array ([eval]:72998:32)
    at MPI.write ([eval]:72985:48)
    at write_cleartext_params ([eval]:70310:24)
    at SecretKey.write ([eval]:70438:31)
    at List.write ([eval]:69481:33)
    at Key.armor ([eval]:64435:59)
    at Endpoints.decryptKey ([eval]:86887:29)
    at process._tickCallback (example.file:68:7)
Type :null
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.checkResult(NodeCallsExecutor.kt:189)
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.decryptKey(NodeCallsExecutor.kt:112)
        at com.flowcrypt.email.api.retrofit.node.NodeCallsExecutor$Companion.decryptKey(NodeCallsExecutor.kt:92)
        at com.flowcrypt.email.ui.loader.EncryptAndSavePrivateKeysAsyncTaskLoader.loadInBackground(EncryptAndSavePrivateKeysAsyncTaskLoader.kt:68)
        at com.flowcrypt.email.ui.loader.EncryptAndSavePrivateKeysAsyncTaskLoader.loadInBackground(EncryptAndSavePrivateKeysAsyncTaskLoader.kt:41)
        at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by DenBond7** [comment]
ref https://mail.google.com/mail/u/0/#search/Cannot+read+property+'length'+of+null

**Comment by tomholub** [comment]
You cannot reproduce this yourself, right?

**Comment by tomholub** [comment]
I assume you CAN reproduce it with key from https://github.com/FlowCrypt/flowcrypt-android/issues/441#issuecomment-465048325

What happens when you import this key into browser extension?

**Comment by DenBond7** [comment]
> You cannot reproduce this yourself, right?

Yes, you are right. I've just found this one in the recent ACRA reports

**Comment by DenBond7** [comment]
@tomholub 
> What happens when you import this key into browser extension?

I can import that key in both apps

![image](https://user-images.githubusercontent.com/2863246/66195784-008e6a80-e6a0-11e9-871e-12fb3361301c.png)

**Comment by tomholub** [comment]
How about when you enter the key into FlowCrypt Settings -> Additional Settings -> Experimental -> Test OpenPGP Compatibility

**Comment by DenBond7** [comment]
output

```
(1) Primary keys found: 1  
(2) ----- Testing key 0 -----  
(3) PK 0 > Is Private? [-] true  
(4) PK 0 > User id 0: [-] FlowCrypt_C <default@denbond7.com>  
(5) PK 0 > Primary User: [-] FlowCrypt_C <default@denbond7.com>  
(6) PK 0 > Fingerprint: [-] 752D E3F8 ADF3 3FDB 2258 FB6A E0D5 29C5 E882 C038  
(7) PK 0 > Subkeys: [-] 1  
(8) PK 0 > Primary key algo: [-] rsa_encrypt_sign  
(9) PK 0 > key decrypt: [-] true  
(10) PK 0 > isFullyDecrypted: [-] true  
(11) PK 0 > isFullyEncrypted: [-] false  
(12) PK 0 > Primary key verify: [-] 3: expired  
(13) PK 0 > Primary key creation? [-] 1550594595 or 2019-02-19T16:43:15.000Z  
(14) PK 0 > Primary key expiration? [-] -  
(15) PK 0 > Encrypt/Decrypt test: Encryption with key was successful  
(16) PK 0 > Encrypt/Decrypt test: Decryption with key succeeded  
(17) PK 0 > Sign/Verify test: [-] sign msg ok|verify ok  
(18) PK 0 > SK 0 > LongId: [-] 5CA7D93B2524132B  
(19) PK 0 > SK 0 > Created: [-] 1550594601 or 2019-02-19T16:43:21.000Z  
(20) PK 0 > SK 0 > Algo: [-] rsa_encrypt_sign  
(21) PK 0 > SK 0 > Verify: [-] 3: expired  
(22) PK 0 > SK 0 > Subkey tag: [-] 7  
(23) PK 0 > SK 0 > Subkey getBitSize: [-] 2048  
(24) PK 0 > SK 0 > Subkey decrypted: [-] true  
(25) PK 0 > SK 0 > Binding signature length: [-] 1  
(26) PK 0 > SK 0 > SIG 0 > Key flags: [-] 12  
(27) PK 0 > SK 0 > SIG 0 > Tag: [-] 2  
(28) PK 0 > SK 0 > SIG 0 > Version: [-] 4  
(29) PK 0 > SK 0 > SIG 0 > Public key algorithm: [-] 1  
(30) PK 0 > SK 0 > SIG 0 > Sig creation time: [-] 1550594603 or 2019-02-19T16:43:23.000Z  
(31) PK 0 > SK 0 > SIG 0 > Sig expiration time: [-] -  
(32) PK 0 > SK 0 > SIG 0 > Verified: [-] true  
(33) PK 0 > internal dateBeforeExpiration: [-] undefined  
(34) PK 0 > internal usableButExpired: [-] false  
```

**Comment by tomholub** [comment]
Ok. So maybe the user is using some key that's broken in a different way.. unsure. Was that during key import? Or other action?

**Comment by DenBond7** [comment]
> Was that during key import? Or other action?

That can be during account setup or key import from the Settings

**Comment by tomholub** [comment]
Ok. I can look into catching this error in JS, so that the app will show compatibility error.

**Comment by tomholub** [comment]
superseded by #976
