### ISSUE TITLE
Could not find valid key packet for encryption

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#781]
It happens when a user is sending an encrypted message. Maybe it relates to #480 

```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
com.flowcrypt.email.util.exception.NodeEncryptException: Error :Error: Error encrypting message: Could not find valid key packet for encryption in key f6f27857d8c061cf

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.kt:152)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
Caused by: com.flowcrypt.email.util.exception.NodeEncryptException: Error :Error: Error encrypting message: Could not find valid key packet for encryption in key f6f27857d8c061cf
Stack :Error: Error encrypting message: Could not find valid key packet for encryption in key f6f27857d8c061cf
    at [eval]:66708:15
Type :null
        at com.flowcrypt.email.api.email.EmailUtil$Companion.genRawMsgWithoutAtts(EmailUtil.kt:681)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.kt:116)
        ... 7 more
com.flowcrypt.email.util.exception.NodeEncryptException: Error :Error: Error encrypting message: Could not find valid key packet for encryption in key f6f27857d8c061cf
Stack :Error: Error encrypting message: Could not find valid key packet for encryption in key f6f27857d8c061cf
    at [eval]:66708:15
Type :null
        at com.flowcrypt.email.api.email.EmailUtil$Companion.genRawMsgWithoutAtts(EmailUtil.kt:681)
        at com.flowcrypt.email.service.PrepareOutgoingMessagesJobIntentService.onHandleWork(PrepareOutgoingMessagesJobIntentService.kt:116)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

ref https://mail.google.com/mail/u/0/#search/%22Could+not+find+valid+key+packet+for+encryption%22

**Comment by tomholub** [comment]
For now, please make sure that the error is properly reported to the user.

**Comment by tomholub** [comment]
superseded by #976
