### ISSUE TITLE
SQLiteConstraintException: UNIQUE constraint failed in LoadGmailAliasesAction

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#807]
```
[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.database.provider.SecurityContentProvider.bulkInsert(SecurityContentProvider.kt:137)
        at android.content.ContentProvider$Transport.bulkInsert(ContentProvider.java:285)
        at android.content.ContentResolver.bulkInsert(ContentResolver.java:1610)
        at com.flowcrypt.email.database.dao.source.AccountAliasesDaoSource.addRows(AccountAliasesDaoSource.kt:61)
        at com.flowcrypt.email.service.actionqueue.actions.LoadGmailAliasesAction.run(LoadGmailAliasesAction.kt:65)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.kt:53)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: accounts_aliases.email, accounts_aliases.account_type, accounts_aliases.send_as_email (code 2067)
#################################################################
Error Code : 2067 (SQLITE_CONSTRAINT_UNIQUE)
Caused By : Abort due to constraint violation.
        (UNIQUE constraint failed: accounts_aliases.email, accounts_aliases.account_type, accounts_aliases.send_as_email (code 2067))
#################################################################
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:953)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1904)
        at androidx.example.file.framework.FrameworkSQLiteDatabase.insert(FrameworkSQLiteDatabase.java:188)
        at com.flowcrypt.email.database.provider.SecurityContentProvider.bulkInsert(SecurityContentProvider.kt:122)
        ... 12 more
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: accounts_aliases.email, accounts_aliases.account_type, accounts_aliases.send_as_email (code 2067)
#################################################################
Error Code : 2067 (SQLITE_CONSTRAINT_UNIQUE)
Caused By : Abort due to constraint violation.
        (UNIQUE constraint failed: accounts_aliases.email, accounts_aliases.account_type, accounts_aliases.send_as_email (code 2067))
#################################################################
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:953)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1904)
        at androidx.example.file.framework.FrameworkSQLiteDatabase.insert(FrameworkSQLiteDatabase.java:188)
        at com.flowcrypt.email.database.provider.SecurityContentProvider.bulkInsert(SecurityContentProvider.kt:122)
        at android.content.ContentProvider$Transport.bulkInsert(ContentProvider.java:285)
        at android.content.ContentResolver.bulkInsert(ContentResolver.java:1610)
        at com.flowcrypt.email.database.dao.source.AccountAliasesDaoSource.addRows(AccountAliasesDaoSource.kt:61)
        at com.flowcrypt.email.service.actionqueue.actions.LoadGmailAliasesAction.run(LoadGmailAliasesAction.kt:65)
        at com.flowcrypt.email.service.actionqueue.ActionQueueIntentService.onHandleWork(ActionQueueIntentService.kt:53)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
        at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

ref https://mail.google.com/mail/u/0/#search/%22AccountAliasesDaoSource.addRows(AccountAliasesDaoSource.kt%3A61)%22

**Comment by DenBond7** [comment]
fixed by #810
