### ISSUE TITLE
Fix download attachments issue on Android Q(10)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#814]
```
[SUMMARY]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
java.io.IOException: File '/storage/emulated/0/Download' exists but is a directory

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.kt:479)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.IOException: File '/storage/emulated/0/Download' exists but is a directory
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:352)
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:324)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.downloadFile(AttachmentDownloadManagerService.kt:492)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.kt:456)
        ... 5 more
java.io.IOException: File '/storage/emulated/0/Download' exists but is a directory
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:352)
        at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:324)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.downloadFile(AttachmentDownloadManagerService.kt:492)
        at com.flowcrypt.email.service.attachment.AttachmentDownloadManagerService$AttDownloadRunnable.run(AttachmentDownloadManagerService.kt:456)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by DenBond7** [comment]
https://commonsware.com/blog/2019/06/07/death-external-storage-end-saga.html

**Comment by DenBond7** [comment]
https://developer.android.com/training/data-storage
