### ISSUE TITLE
UNIQUE constraint failed: attachment.email, attachment.uid, attachment.folder, attachment.path

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#842]
```
[SUMMARY]
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: attachment.email, attachment.uid, attachment.folder, attachment.path (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.database.provider.SecurityContentProvider.bulkInsert(SecurityContentProvider.kt:130)
        at android.content.ContentProvider$Transport.bulkInsert(ContentProvider.java:281)
        at android.content.ContentResolver.bulkInsert(ContentResolver.java:1659)
        at com.flowcrypt.email.database.dao.source.imap.AttachmentDaoSource.addRows(AttachmentDaoSource.kt:105)
        at com.flowcrypt.email.database.dao.source.imap.AttachmentDaoSource.updateAttsTable(AttachmentDaoSource.kt:212)
        at com.flowcrypt.email.service.EmailSyncService.onMsgsReceived(EmailSyncService.kt:270)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessagesToCacheSyncTask.runIMAPAction(LoadMessagesToCacheSyncTask.kt:95)
        at com.flowcrypt.email.api.email.sync.SyncTaskRunnable.runTask(SyncTaskRunnable.kt:44)
        at com.flowcrypt.email.api.email.sync.SyncTaskRunnable.run(SyncTaskRunnable.kt:30)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: attachment.email, attachment.uid, attachment.folder, attachment.path (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:1015)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:2021)
        at androidx.example.file.framework.FrameworkSQLiteDatabase.insert(FrameworkSQLiteDatabase.java:188)
        at com.flowcrypt.email.database.provider.SecurityContentProvider.bulkInsert(SecurityContentProvider.kt:115)
        ... 13 more
android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: attachment.email, attachment.uid, attachment.folder, attachment.path (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067])
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:1015)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:2021)
        at androidx.example.file.framework.FrameworkSQLiteDatabase.insert(FrameworkSQLiteDatabase.java:188)
        at com.flowcrypt.email.database.provider.SecurityContentProvider.bulkInsert(SecurityContentProvider.kt:115)
        at android.content.ContentProvider$Transport.bulkInsert(ContentProvider.java:281)
        at android.content.ContentResolver.bulkInsert(ContentResolver.java:1659)
        at com.flowcrypt.email.database.dao.source.imap.AttachmentDaoSource.addRows(AttachmentDaoSource.kt:105)
        at com.flowcrypt.email.database.dao.source.imap.AttachmentDaoSource.updateAttsTable(AttachmentDaoSource.kt:212)
        at com.flowcrypt.email.service.EmailSyncService.onMsgsReceived(EmailSyncService.kt:270)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessagesToCacheSyncTask.runIMAPAction(LoadMessagesToCacheSyncTask.kt:95)
        at com.flowcrypt.email.api.email.sync.SyncTaskRunnable.runTask(SyncTaskRunnable.kt:44)
        at com.flowcrypt.email.api.email.sync.SyncTaskRunnable.run(SyncTaskRunnable.kt:30)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

```

ref https://mail.google.com/mail/u/1/#search/%22attachment.email%2C+attachment.uid%2C+attachment.folder%2C+attachment.path%22

**Comment by DenBond7** [comment]
fixed via #843
