### ISSUE TITLE
UnsupportedDataTypeException: no object DCH for MIME type

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#850]
```
[SUMMARY]
javax.activation.UnsupportedDataTypeException: no object DCH for MIME type application/ms-tnef; example.file
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:


[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.api.email.sync.SyncTaskRunnable.runTask(SyncTaskRunnable.kt:59)
        at com.flowcrypt.email.api.email.sync.SyncTaskRunnable.run(SyncTaskRunnable.kt:30)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
Caused by: javax.activation.UnsupportedDataTypeException: no object DCH for MIME type application/ms-tnef; example.file
        at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:878)
        at javax.activation.DataHandler.writeTo(DataHandler.java:300)
        at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1670)
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1880)
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1854)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessageDetailsSyncTask.storeMsg(LoadMessageDetailsSyncTask.kt:220)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessageDetailsSyncTask.runIMAPAction(LoadMessageDetailsSyncTask.kt:107)
        at com.flowcrypt.email.api.email.sync.SyncTaskRunnable.runTask(SyncTaskRunnable.kt:44)
        ... 7 more
javax.activation.UnsupportedDataTypeException: no object DCH for MIME type application/ms-tnef; example.file
        at javax.activation.ObjectDataContentHandler.writeTo(DataHandler.java:878)
        at javax.activation.DataHandler.writeTo(DataHandler.java:300)
        at javax.mail.internet.MimeBodyPart.writeTo(MimeBodyPart.java:1670)
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1880)
        at javax.mail.internet.MimeMessage.writeTo(MimeMessage.java:1854)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessageDetailsSyncTask.storeMsg(LoadMessageDetailsSyncTask.kt:220)
        at com.flowcrypt.email.api.email.sync.tasks.LoadMessageDetailsSyncTask.runIMAPAction(LoadMessageDetailsSyncTask.kt:107)
        at com.flowcrypt.email.api.email.sync.SyncTaskRunnable.runTask(SyncTaskRunnable.kt:44)
        at com.flowcrypt.email.api.email.sync.SyncTaskRunnable.run(SyncTaskRunnable.kt:30)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
```

**Comment by DenBond7** [comment]
https://community.oracle.com/thread/1589678

**Comment by DenBond7** [comment]
Duplicate of #785
