### ISSUE TITLE
node initializing error

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#876]
![image](https://user-images.githubusercontent.com/6306961/80573736-11ae1880-89f0-11ea-9e3f-8f394f1b3fdb.png)

have you seen this, received any ACRA about it?

**Comment by DenBond7** [comment]
@tomholub Yes, I've already seen that. We fixed this issue here https://github.com/FlowCrypt/flowcrypt-android/commit/8deb483ce96663f05a547b22728ee3a93a5ddfbf (v1.0.0). Are we able to ask a user about a version which he uses?

**Comment by tomholub** [comment]
This is on 1.0.1:

![image](https://user-images.githubusercontent.com/6306961/80829996-b8084280-8bd7-11ea-8931-bf359546d273.png)

**Comment by DenBond7** [comment]
Thanks for details. I will try to clarify the error message. Maybe it's a problem with decrypting certs for https connection to Node. I have to improve some moments.

**Comment by tomholub** [comment]
Another user, said he just downloaded it:

> Last one. I just downloaded it: 1.0.1

**Comment by DenBond7** [comment]
Hmm... It's strange. I thought I had fixed that issue. Ok. Got it. Let me investigate this issue in details.

**Comment by DenBond7** [comment]
For history. Example of errors

ref https://mail.google.com/mail/u/1/#search/%22Node.kt%3A67%22/FMfcgxwHMjjpzQkcJncWTRQbQRRvSptC

java.lang.IllegalArgumentException: invalid date string: Unparseable date: "b``d`dbc`ca`GMT+00:00"

[STACK_TRACE]
com.flowcrypt.email.util.exception.ManualHandledException: Handled manually:
        at com.flowcrypt.email.util.exception.ExceptionUtil$Companion.handleError(ExceptionUtil.kt:30)
        at com.flowcrypt.email.node.Node$init$1.run(Node.kt:67)
        at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalArgumentException: invalid date string: Unparseable date: "òððôòòñóôùõøGMT+00:00"
        at org.spongycastle.asn1.ASN1UTCTime.<init>(ASN1UTCTime.java:115)
        at org.spongycastle.asn1.DERUTCTime.<init>(DERUTCTime.java:23)
        at org.spongycastle.asn1.x509.Time.<init>(Time.java:67)
        at org.spongycastle.cert.X509v3CertificateBuilder.<init>(X509v3CertificateBuilder.java:40)
        at com.flowcrypt.email.node.NodeSecret.newSignedCrt(NodeSecret.kt:199)
        at com.flowcrypt.email.node.NodeSecret.genCerts(NodeSecret.kt:164)
        at com.flowcrypt.email.node.NodeSecret.initCerts(NodeSecret.kt:102)
        at com.flowcrypt.email.node.NodeSecret.<init>(NodeSecret.kt:88)
        at com.flowcrypt.email.node.NodeSecret.<init>(NodeSecret.kt:51)
        at com.flowcrypt.email.node.Node$init$1.run(Node.kt:53)
        ... 1 more
java.lang.IllegalArgumentException: invalid date string: Unparseable date: "òððôòòñóôùõøGMT+00:00"
        at org.spongycastle.asn1.ASN1UTCTime.<init>(ASN1UTCTime.java:115)
        at org.spongycastle.asn1.DERUTCTime.<init>(DERUTCTime.java:23)
        at org.spongycastle.asn1.x509.Time.<init>(Time.java:67)
        at org.spongycastle.cert.X509v3CertificateBuilder.<init>(X509v3CertificateBuilder.java:40)
        at com.flowcrypt.email.node.NodeSecret.newSignedCrt(NodeSecret.kt:199)
        at com.flowcrypt.email.node.NodeSecret.genCerts(NodeSecret.kt:164)
        at com.flowcrypt.email.node.NodeSecret.initCerts(NodeSecret.kt:102)
        at com.flowcrypt.email.node.NodeSecret.<init>(NodeSecret.kt:88)
        at com.flowcrypt.email.node.NodeSecret.<init>(NodeSecret.kt:51)
        at com.flowcrypt.email.node.Node$init$1.run(Node.kt:53)
        at java.lang.Thread.run(Thread.java:764)
